objects/Billing_Schedule__c/Billing_Schedule__c.object-meta.xml
<CustomObject>
    <description>Used to store billing information rolled up from the Opportunity Products</description>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{0000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Schedule__c/fields/Billing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billing_Amount__c</fullName>
    <description>Billing Amount</description>
    <inlineHelpText>Gross amount we are invoicing customers</inlineHelpText>
    <label>Billing Amount (Gross)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Billing_Schedule__c/fields/Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Date__c</fullName>
    <description>Billing Date</description>
    <label>Estimated Invoice Date</label>
    <type>Date</type>
</CustomField>

objects/Billing_Schedule__c/fields/ELV_Quote__c.field-meta.xml
<CustomField>
    <fullName>ELV_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Legacy Quote record.</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>ELV_Billing_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Schedule__c/fields/isReverseBilling__c.field-meta.xml
<CustomField>
    <fullName>isReverseBilling__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>if reverse billing was used for billing amount calculations</inlineHelpText>
    <label>is Reverse Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/Billing_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>Billing_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/BillingByQuoteLine__c.object-meta.xml
<CustomObject>
    <label>Billing by Quote Line</label>
    <nameField>
        <displayFormat>BQL-{0000}</displayFormat>
        <label>Billing by Quote Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings by Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BillingByQuoteLine__c/fields/BillAmount__c.field-meta.xml
<CustomField>
    <fullName>BillAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bill Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/BillDate__c.field-meta.xml
<CustomField>
    <fullName>BillDate__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/BillingSchedule__c.field-meta.xml
<CustomField>
    <fullName>BillingSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Schedule</label>
    <referenceTo>Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billings by Quote Lines</relationshipLabel>
    <relationshipName>BillingsByQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/BillingScheduleOrder__c.field-meta.xml
<CustomField>
    <fullName>BillingScheduleOrder__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Billing Schedule Order</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/ELV_Quote__c.field-meta.xml
<CustomField>
    <fullName>ELV_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote attached to the billing</description>
    <inlineHelpText>Quote attached to the billing</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Billing By Quote Lines</relationshipLabel>
    <relationshipName>ELV_BillingByQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/ELV_QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>ELV_QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Billing By Quote Lines</relationshipLabel>
    <relationshipName>ELV_BillingByQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/isReverseBilling__c.field-meta.xml
<CustomField>
    <fullName>isReverseBilling__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If Reverse Billing was used</inlineHelpText>
    <label>is Reverse Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity attached to the billing</description>
    <inlineHelpText>Opportunity attached to the billing</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billings by Quote Lines</relationshipLabel>
    <relationshipName>BillingsByQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>How the customer plans to pay Tanium</description>
    <inlineHelpText>How the customer plans to pay Tanium</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentType</valueSetName>
    </valueSet>
</CustomField>

objects/Product2/fields/A_la_carte_Required_SKUs__c.field-meta.xml
<CustomField>
    <fullName>A_la_carte_Required_SKUs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This SKU is Required for a-la-carte purchases.  Must be included in Quote or have an active subscription(s).
Twin Field from Product &gt; Quote Line &gt; Subscription.</description>
    <label>A-la-carte Required SKUs</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/Bundle_Component__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Component__c</fullName>
    <label>Bundle Components</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/Bundle_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Bundle_List_Price__c</fullName>
    <label>Bundle List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>License Term</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Support - Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Prorate_Billing__c.field-meta.xml
<CustomField>
    <fullName>Prorate_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prorate Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/Ruby__ProductRecordType__c.field-meta.xml
<CustomField>
    <fullName>Ruby__ProductRecordType__c</fullName>
    <label>Nue Product Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ruby__ProductRecordType</valueSetName>
    </valueSet>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
    <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/ELV_First_Billing_Override__c.field-meta.xml
<CustomField>
    <fullName>ELV_First_Billing_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Billing Override</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_isReverseBilling__c.field-meta.xml
<CustomField>
    <fullName>ELV_isReverseBilling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReverseBilling</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_PaymentTypeNew__c.field-meta.xml
<CustomField>
    <fullName>ELV_PaymentTypeNew__c</fullName>
    <label>Billing Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Upfront</fullName>
            </value>
            <value>
                <fullName>Annual Installment</fullName>
            </value>
            <value>
                <fullName>Quarterly Installment</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/Ruby__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Ruby__SubscriptionEndDate__c</fullName>
    <description>The Subscription End Date, which is defaulted to the Subscription Start Date plus the Term (in Month).</description>
    <inlineHelpText>The Subscription End Date, which is defaulted to the Subscription Start Date plus the Term (in Month).  It is typically calculated automatically from Start Date and Subscription Term.  In the Co-Term scenario, the Subscription Term is automatically calculated when the End Date is changed.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Quote/fields/Ruby__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>Ruby__SubscriptionStartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The Subscription Start Date, which is defaulted to the Quote Start Date, but can be updated for individual quote lines.</description>
    <inlineHelpText>The Subscription Start Date, which is defaulted to the Quote Start Date, but can be updated for individual quote lines.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/Quote/fields/Ruby__TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>Ruby__TotalAmount__c</fullName>
    <description>Total Amount summarized from the total price of all line items that are not summary line items.  Total Amount of each line item is equal to Total Price plus Tax Amount.</description>
    <inlineHelpText>Total Amount summarized from the total price of all line items that are not summary line items.  Total Amount of each line item is equal to Total Price plus Tax Amount.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/Quote/fields/Ruby__TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>Ruby__TotalPrice__c</fullName>
    <description>Total Price summarized from the total price of all line items that are not summary line items.</description>
    <inlineHelpText>Total Price summarized from the total price of all line items that are not summary line items.  When the Total Price is edited, the Discount Amount and Total Amount will be recalculated, and the change will be propagated to line items.</inlineHelpText>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_Bundle__c.field-meta.xml
<CustomField>
    <fullName>ELV_Bundle__c</fullName>
    <description>Indicates whether this line item represents a package; meaning, it includes other line items in this quote.</description>
    <formula>IF( ISPICKVAL(Product2.Ruby__ProductRecordType__c, &quot;Bundle&quot;), TRUE, FALSE )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package</label>
    <type>Checkbox</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_Bundled_Product__c.field-meta.xml
<CustomField>
    <fullName>ELV_Bundled_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bundled Product</label>
    <type>Checkbox</type>
</CustomField>

objects/QuoteLineItem/fields/Ruby__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Ruby__SubscriptionEndDate__c</fullName>
    <description>The Subscription End Date, which is defaulted to the Subscription Start Date plus the Term (in Month).</description>
    <inlineHelpText>The Subscription End Date, which is defaulted to the Subscription Start Date plus the Term (in Month).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/QuoteLineItem/fields/Ruby__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>Ruby__SubscriptionStartDate__c</fullName>
    <description>The Service Start Date, which is defaulted to the Quote Start Date, but can be updated for different quote lines.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/QuoteLineItem/fields/Ruby__TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>Ruby__TotalAmount__c</fullName>
    <description>The total amount of the line item, calculated as Total Price + Tax Amount.</description>
    <inlineHelpText>The total amount of the line item, calculated as Total Price + Tax Amount.</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

objects/QuoteLineItem/fields/Ruby__TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>Ruby__TotalPrice__c</fullName>
    <description>The total price of the line item, calculated as List Total - System Discount Amount - Discount Amount.</description>
    <inlineHelpText>The total price of the line item, calculated as List Total - System Discount Amount - Discount Amount.</inlineHelpText>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

classes/BillingScheduleServiceTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for BillingScheduleService
 * @Date: UNKNOWN
 * @Author: Tanium Dev Team
 * RequestId    ModifiedDate    Description
 * SS-13619     2026-08-18      Migrated to standard Quote/QuoteLineItem and reduced duplication
 */
@isTest
private class BillingScheduleServiceTest {
	private static User adminUser;
	public static final String FLAT_SKU_PRODUCT = 'Flat SKU Product';
	public static final String FLAT_SKU_PRODUCT_CUSTOM_BILLING = 'Flat SKU Product for Custom Billing';
	public static final String BUNDLE_PARENT_PRODUCT = 'Bundle Parent Hardware';
	public static final String UPFRONT_PAYMENT_TYPE = BillingScheduleConfiguratorController.UPFRONT_PAYMENT_TYPE;
	public static final String ANNUAL_PAYMENT_TYPE = BillingScheduleConfiguratorController.ANNUAL_PAYMENT_TYPE;
	public static final String CUSTOM_PAYMENT_TYPE = BillingScheduleConfiguratorController.CUSTOM_PAYMENT_TYPE;
	public static final String QUARTERLY_PAYMENT_TYPE = BillingScheduleConfiguratorController.QUARTERLY_PAYMENT_TYPE;
	@TestSetup
	static void makeData() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'OpportunityLineItemTriggerHandler',
				'QuoteCPQTriggerHandler',
				'QuoteLineTriggerHandler'
			}
		);
		System.runAs(getAdminUser()) {
			TestFactory.seedRubySettings();

			Account account = TestFactory.buildAccount('Test Account 1');
			insert new List<Account>{ account };

			Opportunity opportunity = TestFactory.buildOpportunity(
				'Test Opportunity 1',
				Date.today() + 30,
				'Prospecting',
				account.Id
			);
			opportunity.CloseDate = Date.today() + 60;
			opportunity.BillingScheduleTotalAmountNew__c = 10;

			insert new List<Opportunity>{ opportunity };

			Quote quote = TestFactory.buildQuote(
				'Test Quote 1',
				opportunity.Id,
				Date.today().addMonths(2),
				Date.today().addMonths(2).addYears(3).addMonths(3)
			);
			quote.ELV_isReverseBilling__c = true;
			quote.ELV_PaymentTypeNew__c = UPFRONT_PAYMENT_TYPE;

			insert new List<Quote>{ quote };

			Product2 flatSKUProduct = new Product2(
				IsActive = true,
				Name = FLAT_SKU_PRODUCT,
				Description = 'test description',
				Product_Category__c = 'Hardware',
				Prorate_Billing__c = false,
				SBQQ__SubscriptionPricing__c = 'One-time'
			);

			Product2 bundleParentHardware = new Product2(
				IsActive = true,
				Name = BUNDLE_PARENT_PRODUCT,
				A_la_carte_Required_SKUs__c = true,
				Description = 'bundle parent description',
				Product_Category__c = 'Hardware',
				Prorate_Billing__c = true,
				Bundle_Component__c = 'myBundleComponentHardware',
				Bundle_List_Price__c = 4000,
				Ruby__ProductRecordType__c = 'Bundle'
			);

			Product2 myBundleComponentHardware = new Product2(
				IsActive = true,
				Name = 'myBundleComponentHardware',
				Description = 'bundle component description',
				Product_Category__c = 'Hardware',
				Prorate_Billing__c = true,
				Bundle_List_Price__c = 4000
			);

			Product2 flatSKUProductForCustomBilling = new Product2(
				IsActive = true,
				Name = FLAT_SKU_PRODUCT_CUSTOM_BILLING,
				Description = 'test description for custom billing',
				Product_Category__c = 'Hardware',
				Prorate_Billing__c = true,
				SBQQ__SubscriptionPricing__c = 'Fixed Price'
			);

			insert new List<Product2>{
				flatSKUProduct,
				bundleParentHardware,
				myBundleComponentHardware,
				flatSKUProductForCustomBilling
			};

			List<PricebookEntry> pricebookEntries = new List<PricebookEntry>{
				TestFactory.buildPricebookEntry(flatSKUProduct.Id, 6000, Test.getStandardPricebookId()),
				TestFactory.buildPricebookEntry(bundleParentHardware.Id, 4000, Test.getStandardPricebookId()),
				TestFactory.buildPricebookEntry(
					myBundleComponentHardware.Id,
					4000,
					Test.getStandardPricebookId()
				),
				TestFactory.buildPricebookEntry(
					flatSKUProductForCustomBilling.Id,
					0,
					Test.getStandardPricebookId()
				)
			};
			insert pricebookEntries;
			PricebookEntry flatSKUProductPBE = pricebookEntries[0];
			PricebookEntry bundleParentHardwarePBE = pricebookEntries[1];
			PricebookEntry myBundleComponentHardwarePBE = pricebookEntries[2];

			QuoteLineItem quoteLineFlatSKU = TestFactory.buildQuoteLineItem(
				quote.Id,
				1,
				6000,
				flatSKUProductPBE.Id
			);
			quoteLineFlatSKU.ELV_Bundled_Product__c = false;
			quoteLineFlatSKU.Ruby__SubscriptionStartDate__c = Date.today().addMonths(2);
			quoteLineFlatSKU.Ruby__SubscriptionEndDate__c = Date.today()
				.addMonths(2)
				.addYears(3)
				.addMonths(3)
				.addDays(29);
			quoteLineFlatSKU.Ruby__TotalAmount__c = 6000;

			QuoteLineItem quoteLineFlatSKUZeroNet = TestFactory.buildQuoteLineItem(
				quote.Id,
				1,
				0,
				flatSKUProductPBE.Id
			);
			quoteLineFlatSKUZeroNet.ELV_Bundled_Product__c = false;
			quoteLineFlatSKUZeroNet.Ruby__SubscriptionStartDate__c = Date.today().addMonths(2);
			quoteLineFlatSKUZeroNet.Ruby__SubscriptionEndDate__c = Date.today()
				.addMonths(2)
				.addYears(3)
				.addMonths(3);
			quoteLineFlatSKUZeroNet.Ruby__TotalAmount__c = 0;

			QuoteLineItem quoteLineParentBundleHardware = TestFactory.buildQuoteLineItem(
				quote.Id,
				1,
				4000,
				bundleParentHardwarePBE.Id
			);
			quoteLineParentBundleHardware.ELV_Bundled_Product__c = false;
			quoteLineParentBundleHardware.Ruby__SubscriptionStartDate__c = Date.today().addMonths(2);
			quoteLineParentBundleHardware.Ruby__SubscriptionEndDate__c = Date.today()
				.addMonths(2)
				.addYears(3)
				.addMonths(3)
				.addDays(30);
			quoteLineParentBundleHardware.Ruby__TotalAmount__c = 4000;
			quoteLineParentBundleHardware.Ruby__TotalPrice__c = 4000;

			QuoteLineItem quoteLineBundleComponentHardware = TestFactory.buildQuoteLineItem(
				quote.Id,
				1,
				4000,
				myBundleComponentHardwarePBE.Id
			);
			quoteLineBundleComponentHardware.ELV_Bundled_Product__c = true;
			quoteLineBundleComponentHardware.Ruby__SubscriptionStartDate__c = Date.today().addMonths(2);
			quoteLineBundleComponentHardware.Ruby__SubscriptionEndDate__c = Date.today()
				.addMonths(2)
				.addYears(3)
				.addMonths(3);
			quoteLineBundleComponentHardware.Ruby__TotalAmount__c = 4000;

			insert new List<QuoteLineItem>{
				quoteLineFlatSKU,
				quoteLineFlatSKUZeroNet,
				quoteLineParentBundleHardware,
				quoteLineBundleComponentHardware
			};

			Billing_Schedule__c billingSchedule = new Billing_Schedule__c(
				isReverseBilling__c = false,
				PaymentType__c = BillingScheduleService.UPFRONT_PAYMENT_TYPE
			);
			billingSchedule.Billing_Date__c = opportunity.CloseDate;
			billingSchedule.Billing_Amount__c = 10;
			billingSchedule.Opportunity__c = opportunity.Id;
			billingSchedule.ELV_Quote__c = quote.Id;
			insert billingSchedule;

			BillingByQuoteLine__c billingFlatSKU = new BillingByQuoteLine__c(
				BillAmount__c = 5,
				BillingScheduleOrder__c = '1',
				IsReverseBilling__c = false,
				PaymentType__c = BillingScheduleService.UPFRONT_PAYMENT_TYPE
			);
			billingFlatSKU.BillingSchedule__c = billingSchedule.Id;
			billingFlatSKU.Opportunity__c = opportunity.Id;
			billingFlatSKU.ELV_Quote__c = quote.Id;
			billingFlatSKU.ELV_QuoteLine__c = quoteLineFlatSKU.Id;
			billingFlatSKU.BillDate__c = opportunity.CloseDate;

			BillingByQuoteLine__c billingHardwareBundle = new BillingByQuoteLine__c(
				BillAmount__c = 5,
				BillingScheduleOrder__c = '1',
				IsReverseBilling__c = false,
				PaymentType__c = BillingScheduleService.UPFRONT_PAYMENT_TYPE
			);
			billingHardwareBundle.BillingSchedule__c = billingSchedule.Id;
			billingHardwareBundle.Opportunity__c = opportunity.Id;
			billingHardwareBundle.ELV_Quote__c = quote.Id;
			billingHardwareBundle.ELV_QuoteLine__c = quoteLineParentBundleHardware.Id;
			billingHardwareBundle.BillDate__c = opportunity.CloseDate;

			insert new List<BillingByQuoteLine__c>{ billingFlatSKU, billingHardwareBundle };
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenNoExistingBillingsByQuoteLines_ReturnsUpfrontBillingByQuoteLines() {
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		List<Billing_Schedule__c> existingBillings = [SELECT Id FROM Billing_Schedule__c];
		delete existingBillings;
		List<BillingByQuoteLine__c> billingLines = [SELECT Id FROM BillingByQuoteLine__c];
		System.assertEquals(0, billingLines.size());
		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		Integer validQuoteLinesCount = [
			SELECT COUNT()
			FROM QuoteLineItem
			WHERE ELV_Bundled_Product__c = FALSE AND (Ruby__TotalAmount__c != 0 OR ELV_Bundle__c = TRUE)
		];
		System.assertEquals(
			validQuoteLinesCount,
			billingByQuoteLines.size(),
			'Ignoring Quotelines that are bundled and that have net total of zero'
		);
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.UPFRONT_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c
			);
			System.assertEquals(false, billingByQuoteLine.isReverseBilling__c);
			System.assertEquals(opportunity.CloseDate, billingByQuoteLine.BillDate__c);
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenOpportunityProvided_ReturnsUpfrontBillingByQuoteLines() {
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		Integer validQuoteLinesCount = [
			SELECT COUNT()
			FROM QuoteLineItem
			WHERE ELV_Bundled_Product__c = FALSE AND (Ruby__TotalAmount__c != 0 OR ELV_Bundle__c = TRUE)
		];
		System.assertEquals(
			validQuoteLinesCount,
			billingByQuoteLines.size(),
			'Ignoring Quotelines that are bundled and that have net total of zero'
		);
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.UPFRONT_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c
			);
			System.assertEquals(false, billingByQuoteLine.isReverseBilling__c);
			System.assertEquals(opportunity.CloseDate, billingByQuoteLine.BillDate__c);
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenExistingBillingsPaymentTypeIsCustom_DoesNotReturnBillingByQuoteLines() {
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		List<BillingByQuoteLine__c> existingBillings = [
			SELECT PaymentType__c
			FROM BillingByQuoteLine__c
			WHERE Opportunity__c = :opportunity.Id
		];
		for (BillingByQuoteLine__c eachBilling : existingBillings) {
			eachBilling.PaymentType__c = BillingScheduleService.CUSTOM_PAYMENT_TYPE;
		}
		update existingBillings;

		SBQQ.TriggerControl.disable();
		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();

		System.assertEquals(
			0,
			billingByQuoteLines.size(),
			'No billingByQuoteLines returned due to Custom payment type - restricted from automation'
		);
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenQuotePaymentTypeIsCustom_DoesNotReturnBillingByQuoteLines() {
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		System.assertEquals(0, [SELECT Id FROM BillingByQuoteLine__c].size());

		SBQQ.TriggerControl.disable();
		List<QuoteLineItem> quoteLines = new List<QuoteLineItem>();
		for (Quote quote : [
			SELECT ELV_PaymentTypeNew__c
			FROM Quote
			WHERE OpportunityId = :opportunity.Id
		]) {
			quote.ELV_PaymentTypeNew__c = BillingScheduleConfiguratorController.CUSTOM_PAYMENT_TYPE;
			update quote;
		}
		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();

		System.assertEquals(
			0,
			billingByQuoteLines.size(),
			'No billingByQuoteLines returned due to Custom payment type - restricted from automation'
		);
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenQuoteFirstBillingOverrideIsTrue_ReturnsBillingByQuoteLines() {
		SBQQ.TriggerControl.disable();
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		System.assertEquals(0, [SELECT Id FROM BillingByQuoteLine__c].size());

		for (Quote quote : [
			SELECT ELV_First_Billing_Override__c
			FROM Quote
			WHERE OpportunityId = :opportunity.Id
		]) {
			quote.ELV_First_Billing_Override__c = true;
			update quote;
		}

		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();

		System.assertEquals(
			2,
			billingByQuoteLines.size(),
			'No billingByQuoteLines returned due to First Billing Override being true on quote'
		);
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenOpportunityProvided_ReturnsAnnualNonReverseBillingByQuoteLines() {
		SBQQ.TriggerControl.disable();
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		updateQuotePaymentType(opportunity.Id, 'Annual Installment', false);

		QuoteLineItem quoteLineFlatSKU = getFlatSKUQuoteLine(opportunity.Id);
		QuoteLineItem quoteLineBundleParent = getBundleParentQuoteLine();

		Decimal noOfMonths = BillingScheduleService.getQuoteLineTermComputed(quoteLineBundleParent);
		System.assertEquals(true, noOfMonths > 39);

		Decimal installmentPerMonth = quoteLineBundleParent.ELV_PackageTotal__c / noOfMonths;
		Decimal annualPayment = (12 * installmentPerMonth).setScale(2);
		Decimal residuePayment = quoteLineBundleParent.ELV_PackageTotal__c - (annualPayment * 3);
		System.assertEquals(4000 - (annualPayment * 3), residuePayment);

		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.ANNUAL_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c,
				'Annual Installment shows accurately'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.isReverseBilling__c,
				'Reverse billing is false on QuoteLine'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundled_Product__c,
				'Bundled products cannot have billings'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.Ruby__TotalAmount__c == 0 &&
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundle__c == false,
				'Flat SKUs with NetTotal zero cannot have billings'
			);
			System.assertEquals(
				true,
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 0,
				'Orders are shown accurately'
			);

			if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineFlatSKU.Id) {
				System.assertEquals(
					6000,
					billingByQuoteLine.BillAmount__c,
					'Non-Prorated product billed upfront'
				);
				System.assertEquals(
					quoteLineFlatSKU.Ruby__SubscriptionStartDate__c,
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				(billingByQuoteLine.BillingScheduleOrder__c == '1' ||
				billingByQuoteLine.BillingScheduleOrder__c == '2' ||
				billingByQuoteLine.BillingScheduleOrder__c == '3')
			) {
				System.assertEquals(annualPayment, billingByQuoteLine.BillAmount__c, 'Billed annually');
				if (billingByQuoteLine.BillingScheduleOrder__c == '1') {
					System.assertEquals(
						BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent)
							.addYears(Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) - 1),
						billingByQuoteLine.BillDate__c,
						'Bill Date aligned with Start Date'
					);
				} else {
					System.assertEquals(
						BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent)
							.addYears(Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) - 1),
						billingByQuoteLine.BillDate__c,
						'Bill Date aligned with Start Date'
					);
				}
			} else if (billingByQuoteLine.BillingScheduleOrder__c == '4') {
				System.assertEquals(residuePayment, billingByQuoteLine.BillAmount__c, 'Residue payment');
				System.assertEquals(
					BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent)
						.addYears(Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) - 1),
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			}
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenOpportunityProvided_ReturnsAnnualNotReverseBillingByQuoteLines() {
		SBQQ.TriggerControl.disable();
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		Quote quote = updateQuotePaymentType(opportunity.Id, ANNUAL_PAYMENT_TYPE, false);

		QuoteLineItem quoteLineFlatSKU = getFlatSKUQuoteLine(opportunity.Id);
		QuoteLineItem quoteLineBundleParent = getBundleParentQuoteLine();
		Decimal noOfMonths = BillingScheduleService.getQuoteLineTermComputed(quoteLineBundleParent);
		System.assertEquals(true, noOfMonths > 39);

		Decimal installmentPerMonth = quoteLineBundleParent.ELV_PackageTotal__c / noOfMonths;
		Decimal annualPayment = (12 * installmentPerMonth).setScale(2);
		Decimal residuePayment = quoteLineBundleParent.ELV_PackageTotal__c - (annualPayment * 3);
		System.assertEquals(4000 - (annualPayment * 3), residuePayment);

		Product2 flatSKUProduct2 = new Product2(
			IsActive = true,
			Name = 'Flat SKU Product 2',
			Description = 'test description 2',
			Product_Category__c = 'Hardware',
			Prorate_Billing__c = true
		);
		insert flatSKUProduct2;
		PricebookEntry flatSKUProduct2PBE = TestFactory.buildPricebookEntry(
			flatSKUProduct2.Id,
			3100,
			Test.getStandardPricebookId()
		);
		insert flatSKUProduct2PBE;
		QuoteLineItem quoteLineFlatSKU2 = TestFactory.buildQuoteLineItem(
			quote.Id,
			1,
			3100,
			flatSKUProduct2PBE.Id
		);
		quoteLineFlatSKU2.ELV_Bundled_Product__c = false;
		quoteLineFlatSKU2.Ruby__SubscriptionStartDate__c = Date.newInstance(Date.today().year(), 7, 15);
		quoteLineFlatSKU2.Ruby__SubscriptionEndDate__c = Date.newInstance(Date.today().year() + 3, 2, 14);
		quoteLineFlatSKU2.Ruby__TotalAmount__c = 3100;
		insert quoteLineFlatSKU2;
		quoteLineFlatSKU2 = [
			SELECT
				ELV_End_Date__c,
				ELV_Bundle__c,
				Ruby__SubscriptionStartDate__c,
				Ruby__SubscriptionEndDate__c,
				Quote.Ruby__SubscriptionStartDate__c,
				Ruby__TotalAmount__c,
				ELV_PackageTotal__c,
				ELV_Term_Computed__c
			FROM QuoteLineItem
			WHERE Product2.Name = 'Flat SKU Product 2'
		];

		Decimal noOfMonthsForFlatSKU2 = BillingScheduleService.getQuoteLineTermComputed(quoteLineFlatSKU2);
		System.assertEquals(31, noOfMonthsForFlatSKU2);
		Decimal installmentPerMonthForFlatSKU2 =
			quoteLineFlatSKU2.Ruby__TotalAmount__c / noOfMonthsForFlatSKU2;
		System.assertEquals(100, installmentPerMonthForFlatSKU2);

		Decimal annualPaymentForFlatSKU2 = 12 * installmentPerMonthForFlatSKU2;
		System.assertEquals(1200, annualPaymentForFlatSKU2);
		Decimal residuePaymentForFlatSKU2 =
			quoteLineFlatSKU2.Ruby__TotalAmount__c - (12 * installmentPerMonthForFlatSKU2 * 2);
		System.assertEquals(700, residuePaymentForFlatSKU2);
		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.ANNUAL_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c,
				'Annual Installment shows accurately'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.isReverseBilling__c,
				'Reverse billing is false on QuoteLine'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundled_Product__c,
				'Bundled products cannot have billings'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.Ruby__TotalAmount__c == 0 &&
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundle__c == false,
				'Flat SKUs with NetTotal zero cannot have billings'
			);
			System.assertEquals(
				true,
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 0,
				'Orders are shown accurately'
			);

			if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineFlatSKU.Id) {
				System.assertEquals(
					6000,
					billingByQuoteLine.BillAmount__c,
					'Non-Prorated product billed upfront'
				);
			} else if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id) {
				switch on billingByQuoteLine.BillingScheduleOrder__c {
					when '1' {
						Date billdate = Date.newInstance(
							BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent).year(),
							BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent).month(),
							BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent).day()
						);
						System.assertEquals(billdate, billingByQuoteLine.BillDate__c, 'Billed annually');

						System.assertEquals(
							(installmentPerMonth * 12).setScale(2),
							billingByQuoteLine.BillAmount__c,
							'Bill date aligned with end date'
						);
					}
					when '2' {
						System.assertEquals(
							(installmentPerMonth * 12).setScale(2),
							billingByQuoteLine.BillAmount__c,
							'Billed annually'
						);
						System.assertEquals(
							BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent).addYears(1),
							billingByQuoteLine.BillDate__c,
							'Bill date aligned with end date'
						);
					}
					when '3' {
						System.assertEquals(
							(installmentPerMonth * 12).setScale(2),
							billingByQuoteLine.BillAmount__c,
							'Billed annually'
						);
						System.assertEquals(
							BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent).addYears(2),
							billingByQuoteLine.BillDate__c,
							'Bill date aligned with end date'
						);
					}
					when '4' {
						System.assertEquals(
							residuePayment,
							billingByQuoteLine.BillAmount__c,
							'Billed for 4 months'
						);
						System.assertEquals(
							BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent).addYears(3),
							billingByQuoteLine.BillDate__c,
							'Bill date aligned with start date'
						);
					}
				}
			} else if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineFlatSKU2.Id) {
				switch on billingByQuoteLine.BillingScheduleOrder__c {
					when '1' {
						System.assertEquals(
							installmentPerMonthForFlatSKU2 * 12,
							billingByQuoteLine.BillAmount__c,
							'Billed annually'
						);
						System.assertEquals(
							true,
							BillingScheduleService.getQuoteLineEndDate(quoteLineFlatSKU2).month() <
							BillingScheduleService.getQuoteLineStartDate(quoteLineFlatSKU2).month(),
							'End month is less'
						);
						System.assertEquals(
							BillingScheduleService.getQuoteLineStartDate(quoteLineFlatSKU2),
							billingByQuoteLine.BillDate__c,
							'Bill date aligned with start date'
						);
					}
					when '2' {
						System.assertEquals(
							installmentPerMonthForFlatSKU2 * 12,
							billingByQuoteLine.BillAmount__c,
							'Billed annually'
						);
						System.assertEquals(
							BillingScheduleService.getQuoteLineStartDate(quoteLineFlatSKU2).addYears(1),
							billingByQuoteLine.BillDate__c,
							'Bill date aligned with end date'
						);
					}
					when '3' {
						System.assertEquals(
							installmentPerMonthForFlatSKU2 * 7,
							billingByQuoteLine.BillAmount__c,
							'Billed for 7 months'
						);
						System.assertEquals(
							BillingScheduleService.getQuoteLineStartDate(quoteLineFlatSKU2).addYears(2),
							billingByQuoteLine.BillDate__c,
							'Bill date aligned with end date'
						);
					}
				}
			}
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenOpportunityProvided_ReturnsAnnualReverseBillingByQuoteLines() {
		SBQQ.TriggerControl.disable();
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		updateQuotePaymentType(opportunity.Id, 'Annual Installment', true);

		QuoteLineItem quoteLineFlatSKU = getFlatSKUQuoteLine(opportunity.Id);
		QuoteLineItem quoteLineBundleParent = getBundleParentQuoteLine();

		Decimal noOfMonths = BillingScheduleService.getQuoteLineTermComputed(quoteLineBundleParent);
		System.assertEquals(true, noOfMonths > 39);

		Decimal installmentPerMonth = quoteLineBundleParent.ELV_PackageTotal__c / noOfMonths;
		Decimal annualPayment = (12 * installmentPerMonth).setScale(2);
		Decimal residuePayment = quoteLineBundleParent.ELV_PackageTotal__c - (annualPayment * 3);
		System.assertEquals(4000 - (annualPayment * 3), residuePayment);

		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.ANNUAL_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c,
				'Annual Installment shows accurately'
			);
			System.assertEquals(
				true,
				billingByQuoteLine.isReverseBilling__c,
				'Reverse billing is true on QuoteLine'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundled_Product__c,
				'Bundled products cannot have billings'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.Ruby__TotalAmount__c == 0 &&
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundle__c == false,
				'Flat SKUs with NetTotal zero cannot have billings'
			);
			System.assertEquals(
				true,
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 0,
				'Orders are shown accurately'
			);

			if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineFlatSKU.Id) {
				System.assertEquals(
					6000,
					billingByQuoteLine.BillAmount__c,
					'Non-Prorated product billed upfront'
				);
				System.assertEquals(
					quoteLineFlatSKU.Ruby__SubscriptionStartDate__c,
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				(billingByQuoteLine.BillingScheduleOrder__c == '2' ||
				billingByQuoteLine.BillingScheduleOrder__c == '3' ||
				billingByQuoteLine.BillingScheduleOrder__c == '4')
			) {
				System.assertEquals(
					Integer.valueOf(annualPayment),
					Integer.valueOf(billingByQuoteLine.BillAmount__c),
					'Billed annually'
				);
			} else if (billingByQuoteLine.BillingScheduleOrder__c == '1') {
				System.assertEquals(residuePayment, billingByQuoteLine.BillAmount__c, 'Residue payment');
				Date billDate = BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent);
				System.assertEquals(
					billDate,
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			}
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_whenReverseBilling_returnsEmptyList() {
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'OpportunityLineItemTriggerHandler',
				'QuoteCPQTriggerHandler',
				'QuoteLineTriggerHandler'
			}
		);
		List<PermissionSetAssignment> psa = [
			SELECT Id
			FROM PermissionSetAssignment
			WHERE AssigneeId = :UserInfo.getUserId() AND PermissionSet.Name = 'DisableFlows'
		];
		if (psa.isEmpty()) {
			TestingUtility.assignPermissionSet(UserInfo.getUserId(), 'DisableFlows');
		}
		System.runAs(new User(Id = UserInfo.getUserId())) {
			List<Billing_Schedule__c> existingBillingSchedules = [SELECT Id FROM Billing_Schedule__c];
			delete existingBillingSchedules;
			Quote quote = [
				SELECT Id, ELV_PaymentTypeNew__c, OpportunityId
				FROM Quote
				WHERE Ruby__IsPrimaryQuote__c = TRUE
				LIMIT 1
			];
			quote.ELV_PaymentTypeNew__c = null;
			update quote;
			Product2 product = [SELECT Id FROM Product2 WHERE Name = :FLAT_SKU_PRODUCT_CUSTOM_BILLING];
			PricebookEntry productPBE = [
				SELECT Id
				FROM PricebookEntry
				WHERE Product2Id = :product.Id AND Pricebook2Id = :Test.getStandardPricebookId()
			];
			QuoteLineItem quoteLineFlatSKU = TestFactory.buildQuoteLineItem(
				quote.Id,
				1,
				10000,
				productPBE.Id
			);
			quoteLineFlatSKU.ELV_Bundled_Product__c = false;
			quoteLineFlatSKU.Ruby__SubscriptionStartDate__c = Date.today().addMonths(2);
			quoteLineFlatSKU.Ruby__SubscriptionEndDate__c = Date.today().addMonths(2).addYears(3).addMonths(3);
			quoteLineFlatSKU.Ruby__TotalAmount__c = 10000;
			insert quoteLineFlatSKU;
			Boolean exceptionThrown = false;
			TriggerHandler.clearAllBypasses();
			Test.startTest();
			try {
				BillingScheduleService.getPrimaryQuoteLinesData(quote.OpportunityId, 'Opportunity');
			} catch (Exception e) {
				exceptionThrown = true;
			}
			Test.stopTest();
			System.assertEquals(false, exceptionThrown, 'Exception should not be thrown');
			List<Billing_Schedule__c> billings = [
				SELECT Id
				FROM Billing_Schedule__c
				WHERE ELV_Quote__c = :quote.Id
			];
			System.assertEquals(
				0,
				billings.size(),
				'No billings should be created since Custom Billing is true on one of the line items'
			);
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenNoQuoteLines_ErrorShouldNotOccur() {
		Opportunity opp = [SELECT Id, AccountId FROM Opportunity WHERE Name = 'Test Opportunity 1'];

		Quote quote = TestFactory.buildQuote(
			'Test Quote No Lines',
			opp.Id,
			Date.today().addMonths(2),
			Date.today().addMonths(2).addYears(3).addMonths(3)
		);
		quote.ELV_PaymentTypeNew__c = UPFRONT_PAYMENT_TYPE;

		insert quote;

		Boolean exceptionThrown = false;

		Test.startTest();
		try {
			BillingScheduleService.getPrimaryQuoteLinesData(opp.Id, 'Opportunity');
		} catch (Exception e) {
			exceptionThrown = true;
		}
		Test.stopTest();

		System.assertEquals(false, exceptionThrown, 'Exception should not be thrown');
	}

	@IsTest
	static void getPrimaryQuoteLinesData_whenZeroNetAmountAndBillingsExsts_returnsEmptyList() {
		Quote quote = [SELECT Id, OpportunityId FROM Quote LIMIT 1];
		List<QuoteLineItem> quoteLines = [
			SELECT Id, Ruby__NetSalesPrice__c
			FROM QuoteLineItem
			WHERE QuoteId = :quote.Id
		];
		for (QuoteLineItem quoteLine : quoteLines) {
			quoteLine.Ruby__NetSalesPrice__c = 0;
		}
		update quoteLines;

		quote.Ruby__SellerTotalAmount__c = 0;
		update quote;

		List<Billing_Schedule__c> existingbillings = [
			SELECT Id, ELV_Quote__r.Ruby__SellerTotalAmount__c
			FROM Billing_Schedule__c
			WHERE ELV_Quote__c = :quote.Id
		];
		Assert.isFalse(existingbillings.isEmpty(), 'Billing Schedules should exists');
		Assert.isTrue(
			existingbillings[0].ELV_Quote__r.Ruby__SellerTotalAmount__c == 0,
			'Quote Net Amount should be 0'
		);

		Test.startTest();
		List<BillingByQuoteLine__c> billings = BillingScheduleService.getPrimaryQuoteLinesData(
			quote.OpportunityId,
			'Opportunity'
		);

		Test.stopTest();

		List<Billing_Schedule__c> billingsAfter = [
			SELECT Id, ELV_Quote__r.Ruby__SellerTotalAmount__c
			FROM Billing_Schedule__c
			WHERE ELV_Quote__c = :quote.Id
		];
		Assert.isTrue(billingsAfter.isEmpty(), 'Billing Schedules should be deleted.');
		Assert.isTrue(billings.isEmpty(), 'Should return empty list.');
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenOpportunityProvided_ReturnsQuarterlyNonReverseBillingByQuoteLines() {
		SBQQ.TriggerControl.disable();
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		updateQuotePaymentType(opportunity.Id, 'Quarterly Installment', false);

		QuoteLineItem quoteLineFlatSKU = getFlatSKUQuoteLine(opportunity.Id);
		QuoteLineItem quoteLineBundleParent = getBundleParentQuoteLine();

		Decimal monthsBetweenQuoteStartEndDate = BillingScheduleService.getQuoteLineTermComputed(
			quoteLineBundleParent
		);
		System.assertEquals(true, monthsBetweenQuoteStartEndDate.intValue() == 40);

		Integer noOfInstallmentsWithoutResidual = Math.floor(monthsBetweenQuoteStartEndDate / 3)
			.intValue();
		System.assertEquals(13, noOfInstallmentsWithoutResidual);
		Integer noOfInstallmentsWithResidual = 0;
		if (Math.mod(noOfInstallmentsWithoutResidual, 3) > 0) {
			noOfInstallmentsWithResidual = noOfInstallmentsWithoutResidual + 1;
		}
		System.assertEquals(14, noOfInstallmentsWithResidual);

		Decimal installmentPerMonth =
			quoteLineBundleParent.ELV_PackageTotal__c / monthsBetweenQuoteStartEndDate;
		Decimal quarterlyPayment = (3 * installmentPerMonth).setScale(2);
		Decimal residuePayment = ((installmentPerMonth * monthsBetweenQuoteStartEndDate) -
			(quarterlyPayment * noOfInstallmentsWithoutResidual))
			.setScale(2);
		System.assertEquals(true, residuePayment > 0 && residuePayment < quarterlyPayment);

		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.QUARTERLY_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c,
				'Quarterly Installment shows accurately'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.isReverseBilling__c,
				'Reverse billing is false on QuoteLine'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundled_Product__c,
				'Bundled products cannot have billings'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.Ruby__TotalAmount__c == 0 &&
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundle__c == false,
				'Flat SKUs with NetTotal zero cannot have billings'
			);
			System.assertEquals(
				true,
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 0,
				'Orders are shown accurately'
			);

			if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineFlatSKU.Id) {
				System.assertEquals(
					6000,
					billingByQuoteLine.BillAmount__c,
					'Non-Prorated product billed upfront'
				);
				System.assertEquals(
					quoteLineFlatSKU.Ruby__SubscriptionStartDate__c,
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) == 1
			) {
				System.assertEquals(quarterlyPayment, billingByQuoteLine.BillAmount__c, 'Billed quarterly');
				System.assertEquals(
					BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent),
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				(Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 1 &&
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) < 14)
			) {
				System.assertEquals(quarterlyPayment, billingByQuoteLine.BillAmount__c, 'Billed quarterly');
				System.assertEquals(
					BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent)
						.addMonths((Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) - 1) * 3),
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Quarterly Start Date'
				);
			} else if (billingByQuoteLine.BillingScheduleOrder__c == '14') {
				System.assertEquals(residuePayment, billingByQuoteLine.BillAmount__c, 'Residue payment');
				System.assertEquals(
					BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent)
						.addMonths((Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) - 1) * 3),
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Quarterly Start Date'
				);
			}
		}
	}

	@isTest
	static void getPrimaryQuoteLinesData_WhenOpportunityProvided_ReturnsQuarterlyReverseBillingByQuoteLines() {
		SBQQ.TriggerControl.disable();
		Opportunity opportunity = [SELECT Id, CloseDate FROM Opportunity LIMIT 1];
		deleteExistingBillingSchedules(opportunity.Id);
		Quote quote = [
			SELECT ELV_First_Billing_Override__c, ELV_isReverseBilling__c, ELV_PaymentTypeNew__c
			FROM Quote
			WHERE OpportunityId = :opportunity.Id
		];
		quote.ELV_PaymentTypeNew__c = QUARTERLY_PAYMENT_TYPE;
		quote.ELV_First_Billing_Override__c = true;
		quote.ELV_isReverseBilling__c = true;
		update quote;

		QuoteLineItem quoteLineFlatSKU = getFlatSKUQuoteLine(opportunity.Id);
		QuoteLineItem quoteLineBundleParent = getBundleParentQuoteLine();

		Decimal monthsBetweenQuoteStartEndDate = BillingScheduleService.getQuoteLineTermComputed(
			quoteLineBundleParent
		);
		System.assertEquals(true, monthsBetweenQuoteStartEndDate.intValue() == 40);

		Integer noOfInstallmentsWithoutResidual = Math.floor(monthsBetweenQuoteStartEndDate / 3)
			.intValue();
		System.assertEquals(13, noOfInstallmentsWithoutResidual);
		Integer noOfInstallmentsWithResidual = 0;
		if (Math.mod(noOfInstallmentsWithoutResidual, 3) > 0) {
			noOfInstallmentsWithResidual = noOfInstallmentsWithoutResidual + 1;
		}
		System.assertEquals(14, noOfInstallmentsWithResidual);

		Decimal installmentPerMonth =
			quoteLineBundleParent.ELV_PackageTotal__c / monthsBetweenQuoteStartEndDate;
		Decimal quarterlyPayment = (3 * installmentPerMonth).setScale(2);
		Decimal residuePayment = ((installmentPerMonth * monthsBetweenQuoteStartEndDate) -
			(quarterlyPayment * noOfInstallmentsWithoutResidual))
			.setScale(2);
		System.assertEquals(true, residuePayment > 0 && residuePayment < quarterlyPayment);

		Test.startTest();
		List<BillingByQuoteLine__c> billingByQuoteLines = BillingScheduleService.getPrimaryQuoteLinesData(
			opportunity.Id,
			'Opportunity'
		);
		Test.stopTest();
		BillingByQuoteLine__c priorBilling;
		for (BillingByQuoteLine__c billingByQuoteLine : billingByQuoteLines) {
			System.assertEquals(
				BillingScheduleService.QUARTERLY_PAYMENT_TYPE,
				billingByQuoteLine.PaymentType__c,
				'Quarterly Installment shows accurately'
			);
			System.assertEquals(
				true,
				billingByQuoteLine.isReverseBilling__c,
				'Reverse billing is false on QuoteLine'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundled_Product__c,
				'Bundled products cannot have billings'
			);
			System.assertEquals(
				false,
				billingByQuoteLine.ELV_QuoteLine__r.Ruby__TotalAmount__c == 0 &&
				billingByQuoteLine.ELV_QuoteLine__r.ELV_Bundle__c == false,
				'Flat SKUs with NetTotal zero cannot have billings'
			);
			System.assertEquals(
				true,
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 0,
				'Orders are shown accurately'
			);

			if (billingByQuoteLine.ELV_QuoteLine__c == quoteLineFlatSKU.Id) {
				System.assertEquals(
					6000,
					billingByQuoteLine.BillAmount__c,
					'Non-Prorated product billed upfront'
				);
				System.assertEquals(
					quoteLineFlatSKU.Ruby__SubscriptionStartDate__c,
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) == 1
			) {
				System.assertEquals(residuePayment, billingByQuoteLine.BillAmount__c, 'Residue payment');
				System.assertEquals(
					BillingScheduleService.getQuoteLineStartDate(quoteLineBundleParent),
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with Start Date'
				);
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				(Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) == 2)
			) {
				Date billDate = Date.newInstance(
					quoteLineBundleParent.Ruby__SubscriptionStartDate__c.year(),
					quoteLineBundleParent.Ruby__SubscriptionEndDate__c.month(),
					quoteLineBundleParent.Ruby__SubscriptionEndDate__c.day()
				);
				Integer diff = quoteLineBundleParent.Ruby__SubscriptionStartDate__c.monthsBetween(billDate);
				if (diff < 0) {
					billDate = Date.newInstance(
						quoteLineBundleParent.Ruby__SubscriptionStartDate__c.year() + 1,
						quoteLineBundleParent.Ruby__SubscriptionEndDate__c.month(),
						quoteLineBundleParent.Ruby__SubscriptionEndDate__c.day()
					);
					diff = quoteLineBundleParent.Ruby__SubscriptionStartDate__c.monthsBetween(billDate);
				}
				diff++;

				if (diff > 0 && diff <= 3) {
					billDate = quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff);
					System.assertEquals(
						quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff),
						billingByQuoteLine.BillDate__c,
						'Billed with difference'
					);
					System.assertEquals(
						diff * installmentPerMonth,
						billingByQuoteLine.BillAmount__c,
						'quarterly payment'
					);
				} else if (diff > 3 && diff <= 6) {
					billDate = quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff - 3);
					System.assertEquals(
						quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff - 3),
						billingByQuoteLine.BillDate__c,
						'Billed with difference'
					);
					System.assertEquals(
						quarterlyPayment,
						billingByQuoteLine.BillAmount__c,
						'quarterly payment'
					);
				} else if (diff > 6 && diff <= 9) {
					billDate = quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff - 6);
					System.assertEquals(
						quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff - 6),
						billingByQuoteLine.BillDate__c,
						'Billed with difference'
					);
					System.assertEquals(
						quarterlyPayment,
						billingByQuoteLine.BillAmount__c,
						'quarterly payment'
					);
				} else if (diff > 9) {
					billDate = quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff - 9);
					System.assertEquals(
						quoteLineBundleParent.Ruby__SubscriptionStartDate__c.addMonths(diff - 9),
						billingByQuoteLine.BillDate__c,
						'Billed with difference'
					);
					System.assertEquals(
						quarterlyPayment,
						billingByQuoteLine.BillAmount__c,
						'quarterly payment'
					);
				}
			} else if (
				billingByQuoteLine.ELV_QuoteLine__c == quoteLineBundleParent.Id &&
				(Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) > 2 &&
				Integer.valueOf(billingByQuoteLine.BillingScheduleOrder__c) < 14)
			) {
				System.assertEquals(quarterlyPayment, billingByQuoteLine.BillAmount__c, 'Billed quarterly');
				System.assertEquals(
					priorBilling.BillDate__c.addMonths(3),
					billingByQuoteLine.BillDate__c,
					'Bill Date aligned with prior bill Date'
				);
			}
			priorBilling = billingByQuoteLine;
		}
	}

	static void deleteExistingBillingSchedules(Id opportunityId) {
		delete [SELECT Id FROM Billing_Schedule__c WHERE Opportunity__c = :opportunityId];
	}

	static Quote updateQuotePaymentType(
		Id opportunityId,
		String paymentType,
		Boolean isReverseBilling
	) {
		Quote quote = [
			SELECT ELV_isReverseBilling__c, ELV_PaymentTypeNew__c
			FROM Quote
			WHERE OpportunityId = :opportunityId
		];
		quote.ELV_PaymentTypeNew__c = paymentType;
		quote.ELV_isReverseBilling__c = isReverseBilling;
		update quote;
		return quote;
	}

	static QuoteLineItem getFlatSKUQuoteLine(Id opportunityId) {
		return [
			SELECT
				ELV_End_Date__c,
				ELV_Bundle__c,
				Ruby__SubscriptionStartDate__c,
				Ruby__SubscriptionEndDate__c,
				Quote.Ruby__SubscriptionStartDate__c,
				Ruby__TotalAmount__c,
				ELV_PackageTotal__c,
				ELV_Term_Computed__c
			FROM QuoteLineItem
			WHERE
				Product2.Name = :FLAT_SKU_PRODUCT
				AND Ruby__TotalAmount__c > 0
				AND Quote.OpportunityId = :opportunityId
		];
	}

	static QuoteLineItem getBundleParentQuoteLine() {
		return [
			SELECT
				ELV_End_Date__c,
				ELV_Bundle__c,
				Ruby__SubscriptionStartDate__c,
				Ruby__SubscriptionEndDate__c,
				Quote.Ruby__SubscriptionStartDate__c,
				Ruby__TotalAmount__c,
				ELV_PackageTotal__c,
				ELV_Term_Computed__c
			FROM QuoteLineItem
			WHERE Product2.Name = :BUNDLE_PARENT_PRODUCT
		];
	}

	static User getAdminUser() {
		if (adminUser == null) {
			List<User> testUsers = [
				SELECT Id
				FROM User
				WHERE LastName = :TestUserFactory.TANIUM_ADMIN_USER
			];
			if (testUsers.isEmpty()) {
				adminUser = TestUserFactory.createTaniumAdminUser(true);
				TestingUtility.assignPermissionSet(adminUser.Id, 'DisableFlows');
				TestingUtility.assignPermissionSet(adminUser.Id, 'DisableValidationRules');
				TestingUtility.assignPermissionSet(adminUser.Id, 'BillingScheduleConfigurator');
			} else {
				adminUser = testUsers[0];
			}
		}
		return adminUser;
	}
}