objects/Instance_Setting__mdt/Instance_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Instance Setting</description>
    <label>Instance Setting</label>
    <pluralLabel>Instance Settings</pluralLabel>
</CustomObject>

objects/Instance_Setting__mdt/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <description>Instance (prod, UAT, Build, etc)</description>
    <label>Instance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
                <default>true</default>
                <label>Production</label>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Instance_Setting__mdt/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>IsSandbox</description>
    <label>IsSandbox</label>
    <type>Checkbox</type>
</CustomField>

objects/Instance_Setting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BaseUrlClassic</fullName>
            </value>
            <value>
                <fullName>BaseUrlCustomerPortal</fullName>
            </value>
            <value>
                <fullName>BaseUrlLightning</fullName>
            </value>
            <value>
                <fullName>BaseUrlZoomIn</fullName>
                <isActive>false</isActive>
                <label>BaseUrlZoomIn</label>
            </value>
            <value>
                <fullName>CommunitiesSelfRegCaptchaKey</fullName>
            </value>
            <value>
                <fullName>CustAuthSelfRegCaptchaKey</fullName>
            </value>
            <value>
                <fullName>CustAuthSelfRegCaptchaSecretKey</fullName>
            </value>
            <value>
                <fullName>PartnerInquiryCaptchaKey</fullName>
            </value>
            <value>
                <fullName>PrivateKeyTestClass</fullName>
                <isActive>false</isActive>
                <label>PrivateKeyTestClass</label>
            </value>
            <value>
                <fullName>ServiceNowIntegrationKey</fullName>
            </value>
            <value>
                <fullName>ServiceNowIntegrationUrl</fullName>
            </value>
            <value>
                <fullName>TestClass</fullName>
                <isActive>false</isActive>
                <label>TestClass</label>
            </value>
            <value>
                <fullName>TestClassKey</fullName>
            </value>
            <value>
                <fullName>UserVoiceIntegration</fullName>
                <isActive>false</isActive>
                <label>UserVoiceIntegration</label>
            </value>
            <value>
                <fullName>UserVoiceIntegrationKey</fullName>
            </value>
            <value>
                <fullName>UserVoiceIntegrationUrl</fullName>
            </value>
            <value>
                <fullName>ZoomInBaseUrl</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Instance_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Partner_Inquiry__c/Partner_Inquiry__c.object-meta.xml
<CustomObject>
    <description>Partner Portal 2020-02-12:  A form will be accessible from new WebI Portal for potential new partners to submit their contact and interest.  Partner Inquiry object will receive the form data.</description>
    <label>Partner Inquiry</label>
    <nameField>
        <displayFormat>PI-{00000}</displayFormat>
        <label>Partner Inquiry Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Inquiry__c/fields/Company_director_has_gov_relation__c.field-meta.xml
<CustomField>
    <fullName>Company_director_has_gov_relation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Company director(s) has gov relation</description>
    <inlineHelpText>Does any current or former director or executive officer of your company, or any employee of your company who will be involved with Tanium business, have a have a family relationship or other close relationship with a Government Official?</inlineHelpText>
    <label>Company director(s) has gov relation</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Director_Bribery_Fraud_Corrupt__c.field-meta.xml
<CustomField>
    <fullName>Director_Bribery_Fraud_Corrupt__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Director/company bribery/fraud/corrupt</description>
    <inlineHelpText>Within the past ten years has your business, or any director or executive officer of your business, been the subject of any investigations, claims, demands or proceedings involving bribery, fraud, or corruption issues?</inlineHelpText>
    <label>Director/company bribery/fraud/corrupt</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Director_Convicted_of_Crime__c.field-meta.xml
<CustomField>
    <fullName>Director_Convicted_of_Crime__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Director(s) convicted/guilty of crime</description>
    <inlineHelpText>Has your business, or any directors or executive officers of your business, been found guilty or convicted of a violation of any criminal laws?</inlineHelpText>
    <label>Director(s) convicted/guilty of crime</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Director_Disciplined_for_Misconduct__c.field-meta.xml
<CustomField>
    <fullName>Director_Disciplined_for_Misconduct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Company director discipline/misconduct</description>
    <inlineHelpText>In the past ten years has your bus., or any dir. or exec. off. of your bus., been suspended/disqualified/debarred from doing bus. with any comp. or gov. ent., been under the review of a monitor/been determined to not be a responsible or qualified bidder?</inlineHelpText>
    <label>Company director discipline/misconduct</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Government_Ties_Director__c.field-meta.xml
<CustomField>
    <fullName>Government_Ties_Director__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Company director(s) has government role</description>
    <inlineHelpText>Does any current or former director or executive officer of your company, or any employee of your company who will be involved with Tanium business, have a role as a Government Official?</inlineHelpText>
    <label>Company director(s) has government role</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Partner_Plans_To_Outsource__c.field-meta.xml
<CustomField>
    <fullName>Partner_Plans_To_Outsource__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Partner requests/plans to outsource</description>
    <inlineHelpText>Do you plan to request permission for any subsidiaries, affiliates or other group companies to provide any part of the services under the proposed partnership with Tanium?</inlineHelpText>
    <label>Partner requests/plans to outsource</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Partner_Primary_Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Primary_Point_of_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Partner Primary Point of Contact</description>
    <label>Partner Primary Point of Contact?</label>
    <type>Checkbox</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_1__c</fullName>
    <label>Street Address 1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Street_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_2__c</fullName>
    <label>Street Address 2</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

objects/Partner_Inquiry__c/fields/Street_Address_3__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_3__c</fullName>
    <label>Street Address 3</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

classes/PartnerInquiryController.cls
/**
 * @Business: Controller class for the PartnerInquiry page
 * @Authors: Cumulus Vision, Tanium Dev team
 * RequestId  	ModifiedDate   	Description
 * TAN-855   	2020-03-17     	Initial development
 * SS-7043		2024-02-08		Added method setCaptchaKeyValue
 * SS-9959   	2025-01-11     	Added validation on First Name, Last Name and Address fields
 */
public class PartnerInquiryController {
	public Partner_Inquiry__c newPartnerInquiry { get; set; }
	public Boolean isRecordCreated { get; private set; }
	public String isPrimaryPartnerContact { get; set; }
	public Boolean showPrimaryContactInfo { get; set; }
	public String isOutSourcing { get; set; }
	public Boolean showOutSourcingInfo { get; set; }
	public String isGovTiesDirector { get; set; }
	public Boolean showGovTiesDirector { get; set; }
	public String isGovRelationDirector { get; set; }
	public Boolean showGovRelationDirector { get; set; }
	public String isDisciplinedDirector { get; set; }
	public Boolean showDisciplinedDirector { get; set; }
	public String isCorruptDirector { get; set; }
	public Boolean showCorruptDirector { get; set; }
	public String isConvictedDirector { get; set; }
	public Boolean showConvictedDirector { get; set; }
	public String captchaKeyValue { get; set; }

	public List<SelectOption> yesNoNoneList { get; set; }

	public PartnerInquiryController() {
		isRecordCreated = false;
		showPrimaryContactInfo = false;
		showOutSourcingInfo = false;
		showGovTiesDirector = false;
		showGovRelationDirector = false;
		showDisciplinedDirector = false;
		showCorruptDirector = false;
		showConvictedDirector = false;
		newPartnerInquiry = new Partner_Inquiry__c();
		yesNoNoneList = new List<SelectOption>();
		yesNoNoneList.add(new SelectOption('', '--None--'));
		yesNoNoneList.add(new SelectOption('Yes', 'Yes'));
		yesNoNoneList.add(new SelectOption('No', 'No'));
		setCaptchaKeyValue();
	}

	public PageReference savePartnerInquiry() {
		newPartnerInquiry.Partner_Primary_Point_of_Contact__c = isPrimaryPartnerContact == 'Yes'
			? true
			: false;
		newPartnerInquiry.Partner_Plans_To_Outsource__c = isOutSourcing == 'Yes' ? true : false;
		newPartnerInquiry.Government_Ties_Director__c = isGovTiesDirector == 'Yes' ? true : false;
		newPartnerInquiry.Company_director_has_gov_relation__c = isGovRelationDirector == 'Yes'
			? true
			: false;
		newPartnerInquiry.Director_Disciplined_for_Misconduct__c = isDisciplinedDirector == 'Yes'
			? true
			: false;
		newPartnerInquiry.Director_Bribery_Fraud_Corrupt__c = isCorruptDirector == 'Yes' ? true : false;
		newPartnerInquiry.Director_Convicted_of_Crime__c = isConvictedDirector == 'Yes' ? true : false;
		try {
			if (isNameAndAdressValuesValid(newPartnerInquiry)) {
				insert newPartnerInquiry;
				isRecordCreated = true;
			} else {
				ApexPages.addMessage(
					new ApexPages.Message(
						ApexPages.Severity.Error,
						'The following fields should only contain alphanumeric, comma and period characters: First Name, Last Name, Street Address 1, Street Address 2, Street Address 3, City and State/Province'
					)
				);
			}
		} catch (Exception ex) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage()));
		}
		return null;
	}

	public PageReference showEmailValidationError() {
		ApexPages.addMessage(new ApexPages.Message(Apexpages.Severity.ERROR, 'Email is not valid'));
		return null;
	}

	public PageReference renderPrimaryContactInfo() {
		showPrimaryContactInfo = (isPrimaryPartnerContact == 'No') ? true : false;
		return null;
	}

	public PageReference renderOutSourcingInfo() {
		showOutSourcingInfo = (isOutSourcing == 'Yes') ? true : false;
		return null;
	}

	public PageReference renderGovTiesDirectorInfo() {
		showGovTiesDirector = (isGovTiesDirector == 'Yes') ? true : false;
		return null;
	}

	public PageReference renderGovRelationDirectorInfo() {
		showGovRelationDirector = (isGovRelationDirector == 'Yes') ? true : false;
		return null;
	}

	public PageReference renderDisciplinedDirectorInfo() {
		showDisciplinedDirector = (isDisciplinedDirector == 'Yes') ? true : false;
		return null;
	}

	public PageReference renderCorruptDirectorInfo() {
		showCorruptDirector = (isCorruptDirector == 'Yes') ? true : false;
		return null;
	}

	public PageReference renderConvictedDirectorInfo() {
		showConvictedDirector = (isConvictedDirector == 'Yes') ? true : false;
		return null;
	}

	public void setCaptchaKeyValue() {
		Boolean isSandbox = Utility.isSandbox();
		String instance = Utility.getInstance(Url.getOrgDomainURL());
		String captchaKeyValue;

		for (Instance_Setting__mdt instanceSetting : Instance_Setting__mdt.getAll().values()) {
			if (
				instanceSetting.IsActive__c &&
				instanceSetting.Instance__c == instance &&
				instanceSetting.Type__c == 'PartnerInquiryCaptchaKey' &&
				instanceSetting.IsSandbox__c == isSandbox
			) {
				this.captchaKeyValue = instanceSetting.Value__c;
			}
		}
	}

	public static Boolean isNameAndAdressValuesValid(Partner_Inquiry__c partnerInquiry) {
		Boolean isValid = true;
		String alphanumericAndSpecialChars = '^[a-zA-Z0-9., ]+$';
		String urlPattern = '^(https?:\\/\\/|www\\.)[	\\w.-]+';

		if (
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.First_Name__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.First_Name__c)) ||
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.Last_Name__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.Last_Name__c)) ||
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.Street_Address_1__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.Street_Address_1__c)) ||
			(partnerInquiry.Street_Address_2__c != null &&
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.Street_Address_2__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.Street_Address_2__c))) ||
			(partnerInquiry.Street_Address_3__c != null &&
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.Street_Address_3__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.Street_Address_3__c))) ||
			(partnerInquiry.Province__c != null &&
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.Province__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.Province__c))) ||
			(!Pattern.matches(alphanumericAndSpecialChars, partnerInquiry?.City__c) ||
			Pattern.matches(urlPattern, partnerInquiry?.City__c))
		) {
			isValid = false;
		}
		return isValid;
	}
}