objects/Product2/fields/Bypass_Recalc_Batch_Job__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Recalc_Batch_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Exclude products from the being recalculated via SBQQ_QuoteRenewal_Async</description>
    <label>Bypass Recalc Batch Job</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>License Term</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Support - Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Prorate_Billing__c.field-meta.xml
<CustomField>
    <fullName>Prorate_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prorate Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
    <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c/fields/Geo__c.field-meta.xml
<CustomField>
    <fullName>Geo__c</fullName>
    <description>Used in CPQ rules and search filters.</description>
    <formula>TEXT(SBQQ__Account__r.Geo__c)</formula>
    <label>Geo</label>
    <type>Text</type>
</CustomField>

objects/SBQQ__Quote__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used in CPQ rules and search filters.</description>
    <formula>TEXT(SBQQ__Account__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Payment Terms for this Quote. If available, the Partner/Account Payment Terms will automatically populate. Otherwise, this will default to Net 30.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 40</fullName>
            </value>
            <value>
                <fullName>Net 42</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 50</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 70</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 85</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 105</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
            <value>
                <fullName>Net 130</fullName>
            </value>
            <value>
                <fullName>Cash with Order (CWO)</fullName>
            </value>
            <value>
                <fullName>See Additional Terms</fullName>
            </value>
            <value>
                <fullName>See Applicable Marketplace Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Check as Primary if opportunity NACV should be calculated off of this quote (each opportunity has one primary quote and it should reflect the most likely scenario).</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CEO/Finance Approval</fullName>
            </value>
            <value>
                <fullName>COE Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Lead Approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>RVP Approval</fullName>
            </value>
            <value>
                <fullName>Upper Management Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Length of the deal, in whole months</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/Total_Addressable_Seats__c.field-meta.xml
<CustomField>
    <fullName>Total_Addressable_Seats__c</fullName>
    <description>Value sourced from related Account.  This field is used in CPQ Product Rule.</description>
    <formula>SBQQ__Account__r.Total_Addressable_Seats__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Addressable Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/fields/Bundled_Product__c.field-meta.xml
<CustomField>
    <fullName>Bundled_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom bundle tracker.  Twin Field from Product Option. Bundled Product is used for Billing Schedule Configurator and necessary to identify if a product is a bundle. This field will allow value to copy from Quote Line to Renewal Quote Line to ensure Billing Schedule for Renewals are correct.</description>
    <inlineHelpText>CPQ TwinField feature will copy the field value from QuoteLine to Subscription and Subscription to Renewal QuoteLine.</inlineHelpText>
    <label>Bundled Product</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Bypass_Recalc_Batch_Job__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Recalc_Batch_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Exclude products from the being recalculated via SBQQ_QuoteRenewal_Async.  Twin Field from Product.</description>
    <label>Bypass Recalc Batch Job</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Uplift_Output__c.field-meta.xml
<CustomField>
    <fullName>Uplift_Output__c</fullName>
    <description>The calculation is now managed by a price rule.  Target field is Suggested_Uplift_Output__c.  This field is kept to make it read only while on the QLE.</description>
    <formula>Suggested_Uplift_Output__c 

/*IF( 
 OR(
 IF( Contains( SBQQ__RenewedSubscription__r.Product_Code__c, &quot;CONVERSION&quot;), true, false),
     SBQQ__Quote__r.Business_Motion_Oppty__c == &quot;MSP&quot;,
     ISPICKVAL(SBQQ__OptionType__c, &quot;Component&quot;),
     ISPICKVAL(SBQQ__OptionType__c, &quot;Accessory&quot;),
     ISBLANK( SBQQ__RenewedSubscription__c )),0,
 IF( SBQQ__Bundle__c,
     1-( Suggested_Uplift_Goal__c /(( SBQQ__Product__r.Bundle_List_Price__c * SBQQ__SubscriptionTerm__c / 12)*(1-Volume_Discount__c )*(1- 
     Term_Discount__c )*(1- SBQQ__PartnerDiscount__c )*(1- Distributor_Discount__c ))),

     1-(Uplift_Goal__c/(( SBQQ__ListPrice__c * SBQQ__SubscriptionTerm__c / 12)*(1-Volume_Discount__c )*(1- Term_Discount__c )*(1- 
     SBQQ__PartnerDiscount__c )*(1- Distributor_Discount__c )))
 )
)


backup - 07.24.24
IF(  
 OR(
   ISPICKVAL(SBQQ__OptionType__c, &quot;Component&quot;), 
    ISPICKVAL(SBQQ__OptionType__c, &quot;Accessory&quot;), 
     ISBLANK( SBQQ__RenewedSubscription__c )),0,

IF( SBQQ__Bundle__c,  
1-( Suggested_Uplift_Goal__c /(( SBQQ__Product__r.Bundle_List_Price__c * SBQQ__SubscriptionTerm__c / 12)*(1-Volume_Discount__c )*(1- Term_Discount__c )*(1- SBQQ__PartnerDiscount__c )*(1- Distributor_Discount__c ))),

1-(Uplift_Goal__c/(( SBQQ__ListPrice__c * SBQQ__SubscriptionTerm__c / 12)*(1-Volume_Discount__c )*(1- Term_Discount__c )*(1- SBQQ__PartnerDiscount__c )*(1- Distributor_Discount__c )))
))
*/</formula>
    <label>Uplift Output</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

classes/SBQQ_QuoteRenewalAsyncTest.cls
/**
 * Copyright (c) 2026 Tanium, Inc. All rights reserved.
 *
 * @Business:	Testclass for SBQQ_QuoteRenewalAsync
 * @Author:    	Tanium Dev team
 * Modified    	ModifiedDate    Description
 * SS-6987	   	2024-01-04	   	Created the test class
 * SS-12364	   	2026-01-22	   	Added testmethod testIdentifyNewModules_WhenNewModules_ReturnNewModules
 * SS-13086	   	2026-05-19	   	Drop Level_3_Sub_Area__c from SOQL; seed Geo__c/Region__c for federal-quote detection
 * SS-13176    2026-05-27    Removed Level_3__c reference
 */
@IsTest
private class SBQQ_QuoteRenewalAsyncTest {
	@TestSetup
	static void makeData() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'OpportunityLineItemTriggerHandler',
				'QuoteCPQTriggerHandler',
				'QuoteLineTriggerHandler',
				'SubscriptionTriggerHandler',
				'UserTriggerHandler'
			}
		);
		User fedAdminUser = TestUserFactory.getAdminUser();
		update fedAdminUser;

		System.runAs(fedAdminUser) {
			Pricebook2 globalPriceBook = new Pricebook2(
				Name = 'Global Pricebook',
				Description = 'Global Pricebook description.',
				IsActive = true
			);
			insert globalPriceBook;
			List<Account> accounts = new List<Account>();
			accounts.add(TestFactory.buildAccount('Test Account 1'));
			accounts[0].Seats_Purchased1__c = 26000;
			accounts[0].Total_Addressable_Seats__c = 5000;
			accounts[0].Geo__c = 'USPS Federal';
			accounts[0].Region__c = 'US Federal';
			accounts.add(TestFactory.buildAccount('Test Account 2'));
			accounts[1].Seats_Purchased1__c = 26000;
			accounts[1].Total_Addressable_Seats__c = 5000;
			insert accounts;

			List<Opportunity> opps = new List<Opportunity>();
			opps.add(
				TestFactory.buildOpportunity(
					'Test Opportunity 1',
					Date.today() + 30,
					'Prospecting',
					accounts[0].Id
				)
			);
			opps[0].Type = 'New Customer';
			opps.add(
				TestFactory.buildOpportunity(
					'Test Opportunity 2',
					Date.today() + 30,
					'Prospecting',
					accounts[1].Id
				)
			);
			opps[1].Type = 'New Customer';
			insert opps;

			List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
			quotes.add(
				new SBQQ__Quote__c(
					SBQQ__Account__c = accounts[0].Id,
					SBQQ__EndDate__c = Date.today().addDays(30),
					SBQQ__Opportunity2__c = opps[0].Id,
					SBQQ__PaymentTerms__c = 'Net 30',
					SBQQ__PriceBook__c = Test.getStandardPricebookId(),
					SBQQ__Primary__c = true,
					SBQQ__StartDate__c = Date.today(),
					SBQQ__Status__c = 'Accepted',
					SBQQ__SubscriptionTerm__c = 30,
					SBQQ__Type__c = 'Quote'
				)
			);
			quotes.add(
				new SBQQ__Quote__c(
					SBQQ__Account__c = accounts[1].Id,
					SBQQ__EndDate__c = Date.today().addDays(30),
					SBQQ__Opportunity2__c = opps[1].Id,
					SBQQ__PaymentTerms__c = 'Net 30',
					SBQQ__PriceBook__c = Test.getStandardPricebookId(),
					SBQQ__Primary__c = true,
					SBQQ__StartDate__c = Date.today(),
					SBQQ__Status__c = 'Accepted',
					SBQQ__SubscriptionTerm__c = 30,
					SBQQ__Type__c = 'Quote'
				)
			);
			insert quotes;

			List<Product2> products = new List<Product2>();
			products.add(
				new Product2(
					IsActive = true,
					Name = 'FLAT_SKU_PRODUCT',
					Description = 'Flat SKU Product',
					Product_Category__c = 'Hardware',
					Prorate_Billing__c = false,
					SBQQ__SubscriptionPricing__c = 'One-time'
				)
			);
			products.add(
				new Product2(
					IsActive = true,
					Name = 'PRODUCT_TO_EXCLUDE',
					Description = 'Product To Exclude',
					Product_Category__c = 'Hardware',
					Prorate_Billing__c = false,
					SBQQ__SubscriptionPricing__c = 'One-time',
					Bypass_Recalc_Batch_Job__c = true
				)
			);
			insert products;

			SBQQ__Subscription__c subscription = buildSubscription(
				accounts[0].Id,
				1,
				products[0].Id,
				1000,
				Date.today() + 100
			);
			insert subscription;
			subscription.SBQQ__AdditionalDiscountAmount__c = 5;
			update subscription;

			List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
			quoteLines.add(
				new SBQQ__QuoteLine__c(
					SBQQ__Bundle__c = false,
					Bundled_Product__c = false,
					SBQQ__StartDate__c = Date.today() + 100,
					SBQQ__Quantity__c = 1,
					SBQQ__Quote__c = quotes[0].Id,
					SBQQ__Product__c = products[0].Id,
					SBQQ__SubscriptionTerm__c = 40,
					SBQQ__NetPrice__c = 1000,
					SBQQ__RenewedSubscription__c = subscription.Id
				)
			);
			quoteLines.add(
				new SBQQ__QuoteLine__c(
					SBQQ__Bundle__c = false,
					Bundled_Product__c = false,
					SBQQ__StartDate__c = Date.today() + 100,
					SBQQ__Quantity__c = 1,
					SBQQ__Quote__c = quotes[1].Id,
					SBQQ__Product__c = products[1].Id,
					SBQQ__SubscriptionTerm__c = 40,
					SBQQ__NetPrice__c = 1000,
					SBQQ__Discount__c = 1
				)
			);
			insert quoteLines;
		}
	}

	@IsTest
	static void testQueueableJob_WhenEmptyListOfQuotes_DoNothing() {
		List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
		SBQQ_QuoteRenewalAsync async = new SBQQ_QuoteRenewalAsync(quotes);

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			async.execute(null);
			Test.stopTest();
		}

		SBQQ__QuoteLine__c[] recalcQuoteLines = [
			SELECT Id, SBQQ__Discount__c, Uplift_Output__c
			FROM SBQQ__QuoteLine__c
		];
		Assert.isTrue(recalcQuoteLines[1].SBQQ__Discount__c != recalcQuoteLines[1].Uplift_Output__c);
	}

	@IsTest
	static void testExecute_WhenOneQuoteFirstIteration_SetSubmitSecondIterationToTrueInTestContext() {
		SBQQ__Quote__c[] quotes = [
			SELECT Id, SBQQ__Account__c
			FROM SBQQ__Quote__c
			LIMIT 1
		];
		SBQQ_QuoteRenewalAsync async = new SBQQ_QuoteRenewalAsync(quotes);
		async.doChainJob = false;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			async.execute(null);
			Test.stopTest();
		}

		Assert.isTrue(async.submitSecondIteration);
	}

	@IsTest
	static void testExecute_WhenMultipleQuotesSecondIteration_SetSubmitSecondIterationToFalseInTestContext() {
		SBQQ__Quote__c[] quotes = [
			SELECT Id, SBQQ__Account__c
			FROM SBQQ__Quote__c
		];
		SBQQ_QuoteRenewalAsync async = new SBQQ_QuoteRenewalAsync(quotes, false);
		async.doChainJob = false;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			async.execute(null);
			Test.stopTest();
		}

		Assert.isFalse(async.submitSecondIteration);
	}

	@IsTest
	static void testRecalculateQuote_WhenNonFederalQuote_ReturnDiscountEqualsUplift() {
		Account account = [SELECT Id FROM Account WHERE Name = 'Test Account 1' LIMIT 1];
		SBQQ__Quote__c quote = [
			SELECT Id
			FROM SBQQ__Quote__c
			WHERE SBQQ__Account__c = :account.Id
			LIMIT 1
		];
		Boolean isFederalQuote = false;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			SBQQ_QuoteRenewalAsync.recalculateQuote1stIteration(
				quote.Id,
				isFederalQuote,
				new Set<Id>()
			);
			SBQQ_QuoteRenewalAsync.recalculateQuote2ndIteration(quote.Id);
			Test.stopTest();
		}

		SBQQ__QuoteLine__c[] recalcQuoteLines = [
			SELECT Id, SBQQ__Discount__c, Uplift_Output__c
			FROM SBQQ__QuoteLine__c
			WHERE SBQQ__Quote__c = :quote.Id
		];
		Assert.isTrue(recalcQuoteLines[0].SBQQ__Discount__c == recalcQuoteLines[0].Uplift_Output__c);
	}

	@IsTest
	static void testRecalculateQuote_WhenFederalQuote_ReturnAdditionalDiscountAmountEquals() {
		TriggerHandler.bypass(new List<String>{ 'UserTriggerHandler' });
		Account account = [SELECT Id, OwnerId FROM Account WHERE Name = 'Test Account 1' LIMIT 1];
		SBQQ__Quote__c quote = [
			SELECT Id
			FROM SBQQ__Quote__c
			WHERE SBQQ__Account__c = :account.Id
			LIMIT 1
		];
		Boolean isFederalQuote = true;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			SBQQ_QuoteRenewalAsync.recalculateQuote1stIteration(
				quote.Id,
				isFederalQuote,
				new Set<Id>()
			);
			SBQQ_QuoteRenewalAsync.recalculateQuote2ndIteration(quote.Id);
			Test.stopTest();
		}

		SBQQ__QuoteLine__c[] recalcQuoteLines = [
			SELECT
				Id,
				SBQQ__Discount__c,
				SBQQ__RenewedSubscription__r.SBQQ__AdditionalDiscountAmount__c,
				SBQQ__AdditionalDiscountAmount__c
			FROM SBQQ__QuoteLine__c
			WHERE SBQQ__Quote__c = :quote.Id
		];
		Assert.isTrue(
			recalcQuoteLines[0].SBQQ__AdditionalDiscountAmount__c ==
			recalcQuoteLines[0].SBQQ__RenewedSubscription__r.SBQQ__AdditionalDiscountAmount__c
		);
	}

	@IsTest
	static void testRecalculateQuote_WhenOnlyExcludedProducts_DoNothing() {
		TriggerHandler.bypass(new List<String>{ 'UserTriggerHandler' });
		Account account = [SELECT Id, OwnerId FROM Account WHERE Name = 'Test Account 2' LIMIT 1];
		SBQQ__Quote__c quote = [
			SELECT Id
			FROM SBQQ__Quote__c
			WHERE SBQQ__Account__c = :account.Id
			LIMIT 1
		];
		Map<Id, Product2> productsToExcludeMap = new Map<Id, Product2>(
			[SELECT Id FROM Product2 WHERE Bypass_Recalc_Batch_Job__c = TRUE]
		);
		Boolean isFederalQuote = false;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			SBQQ_QuoteRenewalAsync.recalculateQuote1stIteration(
				quote.Id,
				isFederalQuote,
				productsToExcludeMap.keySet()
			);
			SBQQ_QuoteRenewalAsync.recalculateQuote2ndIteration(quote.Id);
			Test.stopTest();
		}

		SBQQ__QuoteLine__c[] recalcQuoteLines = [
			SELECT Id, SBQQ__Discount__c, Uplift_Output__c
			FROM SBQQ__QuoteLine__c
		];
		Assert.isTrue(recalcQuoteLines[1].SBQQ__Discount__c != recalcQuoteLines[1].Uplift_Output__c);
	}

	static SBQQ__Subscription__c buildSubscription(
		Id accountId,
		Integer qty,
		Id productId,
		Decimal netPrice,
		Date startDate
	) {
		return new SBQQ__Subscription__c(
			SBQQ__Account__c = accountId,
			SBQQ__Quantity__c = qty,
			SBQQ__Product__c = productId,
			SBQQ__NetPrice__c = netPrice,
			SBQQ__SubscriptionStartDate__c = startDate
		);
	}
}