objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Twin Field.  Value pushed to quote line field &apos;Product Grouping&apos;</description>
    <label>Partner Discount Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Group</valueSetName>
    </valueSet>
</CustomField>

objects/Product2/fields/Ruby__OriginalProduct__c.field-meta.xml
<CustomField>
    <fullName>Ruby__OriginalProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The original product that the product is copied from, only for multi attributes record type products.</description>
    <label>Original Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Original Product)</relationshipLabel>
    <relationshipName>multiAttributesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>ELV_Product_Group__c</fullName>
    <label>Partner Discount Product Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/ELV_ProductGroupStampBackfillBatch.cls
/**
 * Copyright (c) 2026 Tanium, Inc. All rights reserved.
 *
 * @Business: One-time backfill for the QuoteLineItem.ELV_Product_Group__c formula-to-text
 *            migration. Future saves are handled by ELV_QuoteLineTriggerUtility and future
 *            Product2 changes are handled by ELV_ProductGroupStampService.
 */
public with sharing class ELV_ProductGroupStampBackfillBatch implements Database.Batchable<SObject>, Database.Stateful {
	@TestVisible
	private Integer recordsProcessed = 0;
	@TestVisible
	private Integer recordsUpdated = 0;

	public Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator(
			[
				SELECT
					Id,
					ELV_Product_Group__c,
					Product2.Product_Group__c,
					Product2.Ruby__OriginalProduct__c,
					Product2.Ruby__OriginalProduct__r.Product_Group__c
				FROM QuoteLineItem
			]
		);
	}

	public void execute(Database.BatchableContext context, List<SObject> scope) {
		this.recordsProcessed += scope.size();

		List<QuoteLineItem> linesToUpdate = new List<QuoteLineItem>();
		for (QuoteLineItem line : (List<QuoteLineItem>) scope) {
			String target = ELV_QuoteLineTriggerUtility.resolveProductGroupStamp(
				line.Product2
			);
			if (line.ELV_Product_Group__c == target) {
				continue;
			}

			linesToUpdate.add(
				new QuoteLineItem(Id = line.Id, ELV_Product_Group__c = target)
			);
		}

		if (!linesToUpdate.isEmpty()) {
			update linesToUpdate;
		}

		this.recordsUpdated += linesToUpdate.size();
	}

	public void finish(Database.BatchableContext context) {
		System.debug(
			LoggingLevel.INFO,
			'ELV_ProductGroupStampBackfillBatch finished. recordsProcessed=' +
				this.recordsProcessed +
				', recordsUpdated=' +
				this.recordsUpdated
		);
	}
}