objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Twin Field.  Value pushed to quote line field &apos;Product Grouping&apos;</description>
    <label>Partner Discount Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Group</valueSetName>
    </valueSet>
</CustomField>

objects/Product2/fields/Ruby__OriginalProduct__c.field-meta.xml
<CustomField>
    <fullName>Ruby__OriginalProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The original product that the product is copied from, only for multi attributes record type products.</description>
    <label>Original Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Original Product)</relationshipLabel>
    <relationshipName>multiAttributesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>ELV_Product_Group__c</fullName>
    <label>Partner Discount Product Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/ELV_QuoteLineProductGroupStampTest.cls
@IsTest
private class ELV_QuoteLineProductGroupStampTest {
	@IsTest
	static void stampProductGroupUsesLineProductGroupWhenOriginalProductIsBlank() {
		Product2 product = createProduct('Software', null);
		QuoteLineItem line = new QuoteLineItem(
			Product2Id = product.Id,
			ELV_Product_Group__c = 'Previous'
		);

		ELV_QuoteLineTriggerUtility.stampProductGroup(
			new List<QuoteLineItem>{ line },
			null
		);

		Assert.areEqual('Software', line.ELV_Product_Group__c);
	}

	@IsTest
	static void stampProductGroupUsesOriginalProductGroupWhenOriginalProductIsPopulated() {
		Product2 originalProduct = createProduct('ESR', null);
		Product2 configuredProduct = createProduct('Software', originalProduct.Id);
		QuoteLineItem line = new QuoteLineItem(Product2Id = configuredProduct.Id);

		ELV_QuoteLineTriggerUtility.stampProductGroup(
			new List<QuoteLineItem>{ line },
			null
		);

		Assert.areEqual('ESR', line.ELV_Product_Group__c);
	}

	@IsTest
	static void stampProductGroupClearsValueWhenProductIsBlank() {
		QuoteLineItem line = new QuoteLineItem(ELV_Product_Group__c = 'Software');

		ELV_QuoteLineTriggerUtility.stampProductGroup(
			new List<QuoteLineItem>{ line },
			null
		);

		Assert.areEqual(null, line.ELV_Product_Group__c);
	}

	@IsTest
	static void productChangeDetectionIncludesFormulaInputsOnly() {
		Product2 unchangedProduct = createProduct('Software', null);
		Product2 groupChangedProduct = createProduct('Software', null);
		Product2 originalProduct = createProduct('ESR', null);
		Product2 originalChangedProduct = createProduct('Software', null);

		Map<Id, Product2> oldMap = new Map<Id, Product2>{
			unchangedProduct.Id => unchangedProduct.clone(true, false, false, false),
			groupChangedProduct.Id => groupChangedProduct.clone(true, false, false, false),
			originalChangedProduct.Id => originalChangedProduct.clone(
				true,
				false,
				false,
				false
			)
		};

		groupChangedProduct.Product_Group__c = 'ESR';
		originalChangedProduct.Ruby__OriginalProduct__c = originalProduct.Id;

		Set<Id> changedProductIds = ELV_ProductGroupStampService.getProductsWithChangedFormulaInputs(
			new List<Product2>{
				unchangedProduct,
				groupChangedProduct,
				originalChangedProduct
			},
			oldMap
		);

		Assert.isFalse(changedProductIds.contains(unchangedProduct.Id));
		Assert.isTrue(changedProductIds.contains(groupChangedProduct.Id));
		Assert.isTrue(changedProductIds.contains(originalChangedProduct.Id));
	}

	private static Product2 createProduct(String productGroup, Id originalProductId) {
		Product2 product = new Product2(
			Name = 'Product ' + productGroup + ' ' + String.valueOf(Crypto.getRandomInteger()),
			Family = 'None',
			IsActive = true,
			Product_Group__c = productGroup,
			Ruby__OriginalProduct__c = originalProductId
		);
		insert product;
		return product;
	}
}