objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>License Term</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Support - Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Prorate_Billing__c.field-meta.xml
<CustomField>
    <fullName>Prorate_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prorate Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
    <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Payment Terms for this Quote. If available, the Partner/Account Payment Terms will automatically populate. Otherwise, this will default to Net 30.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 40</fullName>
            </value>
            <value>
                <fullName>Net 42</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 50</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 70</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 85</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 105</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
            <value>
                <fullName>Net 130</fullName>
            </value>
            <value>
                <fullName>Cash with Order (CWO)</fullName>
            </value>
            <value>
                <fullName>See Additional Terms</fullName>
            </value>
            <value>
                <fullName>See Applicable Marketplace Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Check as Primary if opportunity NACV should be calculated off of this quote (each opportunity has one primary quote and it should reflect the most likely scenario).</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CEO/Finance Approval</fullName>
            </value>
            <value>
                <fullName>COE Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Lead Approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>RVP Approval</fullName>
            </value>
            <value>
                <fullName>Upper Management Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Length of the deal, in whole months</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/Total_Addressable_Seats__c.field-meta.xml
<CustomField>
    <fullName>Total_Addressable_Seats__c</fullName>
    <description>Value sourced from related Account.  This field is used in CPQ Product Rule.</description>
    <formula>SBQQ__Account__r.Total_Addressable_Seats__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Addressable Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/fields/Bundled_Product__c.field-meta.xml
<CustomField>
    <fullName>Bundled_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom bundle tracker.  Twin Field from Product Option. Bundled Product is used for Billing Schedule Configurator and necessary to identify if a product is a bundle. This field will allow value to copy from Quote Line to Renewal Quote Line to ensure Billing Schedule for Renewals are correct.</description>
    <inlineHelpText>CPQ TwinField feature will copy the field value from QuoteLine to Subscription and Subscription to Renewal QuoteLine.</inlineHelpText>
    <label>Bundled Product</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

classes/SBQQ_QuoteCalculatorTest.cls
/**
 * @Business: Testclass for SBQQ_QuoteCalculator
 * @Authors:  Tanium Dev team
 * RequestId  ModifiedDate  Description
 * SS-6987    2024-01-04    Created the class
 */
@IsTest
private class SBQQ_QuoteCalculatorTest {
	@TestSetup
	static void makeData() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'OpportunityLineItemTriggerHandler',
				'QuoteCPQTriggerHandler',
				'QuoteLineTriggerHandler'
			}
		);

		System.runAs(TestUserFactory.getAdminUser()) {
			Pricebook2 globalPriceBook = new Pricebook2(
				Name = 'Global Pricebook',
				Description = 'Global Pricebook description.',
				IsActive = true
			);
			insert globalPriceBook;
			Account account = TestFactory.buildAccount('Test Account');
			account.Seats_Purchased1__c = 26000;
			account.Total_Addressable_Seats__c = 5000;
			insert account;

			Opportunity opp = TestFactory.buildOpportunity(
				'Test Opportunity',
				Date.today() + 30,
				'Prospecting',
				account.Id
			);
			opp.Type = 'New Customer';
			insert opp;

			SBQQ__Quote__c quote = new SBQQ__Quote__c(
				SBQQ__Account__c = account.Id,
				SBQQ__EndDate__c = Date.today().addDays(30),
				SBQQ__Opportunity2__c = opp.Id,
				SBQQ__PaymentTerms__c = 'Net 30',
				SBQQ__PriceBook__c = Test.getStandardPricebookId(),
				SBQQ__Primary__c = true,
				SBQQ__StartDate__c = Date.today(),
				SBQQ__Status__c = 'Accepted',
				SBQQ__SubscriptionTerm__c = 30,
				SBQQ__Type__c = 'Quote'
			);
			insert quote;

			Product2 product = new Product2(
				IsActive = true,
				Name = 'FLAT_SKU_PRODUCT',
				Description = 'Flat SKU Product',
				Product_Category__c = 'Hardware',
				Prorate_Billing__c = false,
				SBQQ__SubscriptionPricing__c = 'One-time'
			);
			insert product;

			SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
				SBQQ__Bundle__c = false,
				Bundled_Product__c = false,
				SBQQ__StartDate__c = Date.today() + 100,
				SBQQ__Quantity__c = 1,
				SBQQ__Quote__c = quote.Id,
				SBQQ__Product__c = product.Id,
				SBQQ__SubscriptionTerm__c = 40,
				SBQQ__NetPrice__c = 1000
			);
			insert quoteLine;
		}
	}

	@IsTest
	static void testSBQQ_QuoteCalculator() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'OpportunityLineItemTriggerHandler',
				'QuoteCPQTriggerHandler',
				'QuoteLineTriggerHandler'
			}
		);
		SBQQ_ApiDataModels.QuoteModel quoteModel;
		SBQQ_QuoteCalculator calculator = new SBQQ_QuoteCalculator();
		SBQQ_QuoteReader reader = new SBQQ_QuoteReader();
		SBQQ__Quote__c[] quotes = [SELECT Id FROM SBQQ__Quote__c];

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			quoteModel = reader.read(String.valueOf(quotes[0].Id));
			quoteModel.lineItems[0].record.SBQQ__Quantity__c = 2;
			calculator.calculate(quoteModel, 'SBQQ_CalculateCallback');
			Test.stopTest();
		}
	}
}