objects/rosco_escalation_rbac__c/rosco_escalation_rbac__c.object-meta.xml
<CustomObject>
    <label>rosco_escalation_rbac</label>
    <nameField>
        <label>level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>rosco_escalation_rbac</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/rosco_escalation_rbac__c/fields/authorized__c.field-meta.xml
<CustomField>
    <fullName>authorized__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>authorized</label>
    <referenceTo>User</referenceTo>
    <relationshipName>usermap</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/rosco_people__c/rosco_people__c.object-meta.xml
<CustomObject>
    <label>rosco_people</label>
    <nameField>
        <label>slackname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>rosco_peoples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/rosco_people__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>rosco_peoples</relationshipLabel>
    <relationshipName>rosco_peoples</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/rosco_people__c/fields/pod__c.field-meta.xml
<CustomField>
    <fullName>pod__c</fullName>
    <label>pod</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product SME</fullName>
            </value>
            <value>
                <fullName>Northeast and Canada</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Federal-Civ</fullName>
            </value>
            <value>
                <fullName>EMEA South</fullName>
            </value>
            <value>
                <fullName>EMEA North</fullName>
            </value>
            <value>
                <fullName>Asia North</fullName>
            </value>
            <value>
                <fullName>Asia South</fullName>
            </value>
            <value>
                <fullName>Product Engineering</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>TAM &amp; CS Leadership</fullName>
            </value>
            <value>
                <fullName>CSM</fullName>
            </value>
            <value>
                <fullName>ESO</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Partner Pod</fullName>
            </value>
            <value>
                <fullName>CSM-Central</fullName>
            </value>
            <value>
                <fullName>Order Ops</fullName>
            </value>
            <value>
                <fullName>CSM-East</fullName>
            </value>
            <value>
                <fullName>CSM-Intl</fullName>
            </value>
            <value>
                <fullName>CSM-West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/rosco_people__c/fields/psme__c.field-meta.xml
<CustomField>
    <fullName>psme__c</fullName>
    <label>psme</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SME-Infrastructure</fullName>
            </value>
            <value>
                <fullName>SME-Asset</fullName>
            </value>
            <value>
                <fullName>SME-Comply</fullName>
            </value>
            <value>
                <fullName>SME-Connect</fullName>
            </value>
            <value>
                <fullName>SME-Deploy</fullName>
            </value>
            <value>
                <fullName>SME-Discover</fullName>
            </value>
            <value>
                <fullName>SME-Incident Response</fullName>
            </value>
            <value>
                <fullName>SME-Index</fullName>
            </value>
            <value>
                <fullName>SME-Integrity Monitor</fullName>
            </value>
            <value>
                <fullName>SME-Console / Interact</fullName>
            </value>
            <value>
                <fullName>SME-Patch</fullName>
            </value>
            <value>
                <fullName>SME-Protect</fullName>
            </value>
            <value>
                <fullName>SME-Trends</fullName>
            </value>
            <value>
                <fullName>SME-Platform</fullName>
            </value>
            <value>
                <fullName>SME-Threat Response</fullName>
            </value>
            <value>
                <fullName>SME-Map</fullName>
            </value>
            <value>
                <fullName>SME-Reveal</fullName>
            </value>
            <value>
                <fullName>SME-Health Check</fullName>
            </value>
            <value>
                <fullName>SME-Performance</fullName>
            </value>
            <value>
                <fullName>SME-Other</fullName>
            </value>
            <value>
                <fullName>SME-Tanium Index</fullName>
            </value>
            <value>
                <fullName>EDR</fullName>
            </value>
            <value>
                <fullName>SME-Tanium Client Management (TCM)</fullName>
            </value>
            <value>
                <fullName>SME-Client Management</fullName>
            </value>
            <value>
                <fullName>SME-Network Quarantine Service</fullName>
            </value>
            <value>
                <fullName>SME-Enforce</fullName>
            </value>
            <value>
                <fullName>SME-Direct Connect (DEC)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/rosco_people__c/fields/ssme__c.field-meta.xml
<CustomField>
    <fullName>ssme__c</fullName>
    <label>ssme</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SME-Infrastructure</fullName>
            </value>
            <value>
                <fullName>SME-Asset</fullName>
            </value>
            <value>
                <fullName>SME-Comply</fullName>
            </value>
            <value>
                <fullName>SME-Connect</fullName>
            </value>
            <value>
                <fullName>SME-Deploy</fullName>
            </value>
            <value>
                <fullName>SME-Discover</fullName>
            </value>
            <value>
                <fullName>SME-Incident Response</fullName>
            </value>
            <value>
                <fullName>SME-Tanium Index</fullName>
            </value>
            <value>
                <fullName>SME-Integrity Monitor</fullName>
            </value>
            <value>
                <fullName>SME-Console / Interact</fullName>
            </value>
            <value>
                <fullName>SME-Patch</fullName>
            </value>
            <value>
                <fullName>SME-Protect</fullName>
            </value>
            <value>
                <fullName>SME-Trends</fullName>
            </value>
            <value>
                <fullName>SME-Platform</fullName>
            </value>
            <value>
                <fullName>SME-Threat Response</fullName>
            </value>
            <value>
                <fullName>SME-Map</fullName>
            </value>
            <value>
                <fullName>SME-Reveal</fullName>
            </value>
            <value>
                <fullName>SME-Health Check</fullName>
            </value>
            <value>
                <fullName>SME-Performance</fullName>
            </value>
            <value>
                <fullName>EDR</fullName>
            </value>
            <value>
                <fullName>SME-Tanium Client Management (TCM)</fullName>
            </value>
            <value>
                <fullName>SME-Client Management</fullName>
            </value>
            <value>
                <fullName>SME-Network Quarantine Service</fullName>
            </value>
            <value>
                <fullName>SME-Enforce</fullName>
            </value>
            <value>
                <fullName>SME-Direct Connect (DEC)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/rosco_people__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>user</label>
    <referenceTo>User</referenceTo>
    <relationshipName>rosco_peoples</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TAM_Team__c/TAM_Team__c.object-meta.xml
<CustomObject>
    <label>TAM Team</label>
    <nameField>
        <label>TAM Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAM Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TAM_Team__c/fields/Slack_Ticket_Channel_ID__c.field-meta.xml
<CustomField>
    <fullName>Slack_Ticket_Channel_ID__c</fullName>
    <description>The ticketing slack channel (Some SMEs have a separate channel .. otherwise we use the private one)</description>
    <label>Slack Ticket Channel ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

objects/TAM_Team__c/fields/SME_Component_Name__c.field-meta.xml
<CustomField>
    <fullName>SME_Component_Name__c</fullName>
    <description>This is the SME Component Name as reflected in the Case Object</description>
    <label>SME Component Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

classes/RoscoTriageTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for RoscoTriage
 * @Date:
 * @Author: Cumulus Vision
 * @Request:
 * RequestId  ModifiedDate  Description
 * TAN-832	  2019-18-11    Test methods updated..
 * SS-11173   2025-07-10    Changed field from Severity__c to Severity_Community__c
 * SS-10294   2026-02-12    Remove TAM_Assigned_GS__c reference	from the test class
 */
@isTest
public with sharing class RoscoTriageTest {
	static void CreateRecords() {
		TriggerHandler.bypass(new List<String>{ 'ContactTriggerHandler', 'AccountTriggerHandler' });
	}

	@isTest(SeeAllData=false)
	static void TestIt() {
		CreateRecords();
		Test.setMock(HttpCalloutMock.class, new mockCallout());

		Id profileId = [SELECT Id FROM Profile WHERE Name = 'Tanium System Administrator'].Id;

		User userObj = TestFactory.buildUser(
			'ApexUser',
			'roscoapextest@roscolab.com',
			'roscoapextest@roscolab.com',
			profileId
		);
		userObj.Email = 'roscoapextest@roscolab.com';
		userObj.FirstName = 'Test';
		userObj.LastName = 'ApexUser';
		userObj.Username = 'roscoapextest@roscolab.com';
		userObj.Alias = 'afdsa';
		userObj.CommunityNickname = 'asfdasf';
		userObj.TimeZoneSidKey = 'America/Los_Angeles';
		userObj.LocaleSidKey = 'en_US';
		userObj.EmailEncodingKey = 'ISO-8859-1';
		userObj.ProfileId = profileId;
		userObj.LanguageLocaleKey = 'en_US';
		insert userObj;

		System.runAs(TestUserFactory.getAdminUser()) {
			Account accountObj = TestFactory.buildAccount('roscoapextestingd');
			accountObj.slack_channel_id__c = 'TESTCASE';
			insert accountObj;
			Contact contactObj = new Contact(
				Email = 'roscoapextest@roscolab.com',
				FirstName = 'Test',
				LastName = 'Apex',
				AccountId = null
			);
			insert contactObj;
			Contact contactObj2 = new Contact(
				Email = 'roscoapextest@tanium.com',
				FirstName = 'Test2',
				LastName = 'Apex',
				AccountId = null
			);
			insert contactObj2;

			String recordTypeId = RoscoUtility.getRecordTypeIdByAPIName('Case', 'Support');

			Case caseObj = new Case(
				ContactId = contactObj.id,
				accountid = accountObj.id,
				ownerid = userObj.id,
				subject = 'ROSCOTESTCASE',
				Severity_Community__c = '3',
				type = 'Incident',
				Reason = 'New problem',
				Origin = 'Email',
				suppliedEmail = '99@outlook.com',
				LatestPublicCommentHTML__c = '<html>hello</html>',
				Component__c = 'Other',
				RecordTypeId = recordTypeId,
				status = 'On Hold'
			);
			insert caseObj;

			rosco_people__c peep = new rosco_people__c(
				Name = 'roscoapextestingd',
				contact__c = contactObj.Id,
				user__c = userObj.Id,
				pod__c = 'Central',
				psme__c = 'SME-Patch',
				ssme__c = 'SME-Map'
			);
			insert peep;

			rosco_escalation_rbac__c rbac = new rosco_escalation_rbac__c(
				Name = '4',
				authorized__c = userObj.Id
			);
			insert rbac;

			rosco_people__c sme = new rosco_people__c(
				Name = 'slack.name',
				contact__c = contactObj.Id,
				user__c = userObj.Id,
				pod__c = 'Central',
				psme__c = 'SME-Patch',
				ssme__c = 'SME-Map'
			);
			insert sme;

			TAM_Team__c team = new TAM_Team__c(
				Name = 'Patch',
				SME_Component_Name__c = 'Workbench-Patch',
				Slack_Ticket_Channel_ID__c = 'CCC66LTRT'
			);
			insert team;

			Case casecreated = RoscoUtility.getCaseDetails(caseObj.Id);
			List<Case> cases = new List<Case>();
			cases.add(casecreated);

			RoscoTriage.getCaseContactLookup('foo', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseContactLookup('', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseContactLookup('rosco', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseOwnerLookup('foo', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseOwnerLookup('', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseOwnerLookup('newcaseinit', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseAccountLookup('foo', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseAccountLookup('', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseAccountLookupSales('foo', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseAccountLookupSales('', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseInfo(caseObj.Id);
			RoscoTriage.getCaseInfo('newcase');
			RoscoTriage.getCaseInfoTSE(caseObj.Id);
			RoscoTriage.getCaseInfoTSE('newcase');
			RoscoTriage.getPicklistValuesCaseComponent();
			RoscoTriage.getPods();
			RoscoTriage.getCasePreferredTAMLookup(
				'',
				String.valueOf(caseObj.Id),
				String.valueOf(accountObj.Id),
				''
			);
			RoscoTriage.getCasePreferredTAMLookup(
				'foo',
				String.valueOf(caseObj.Id),
				String.valueOf(accountObj.Id),
				''
			);
			RoscoTriage.getCaseOppLookup('', caseObj.Id, accountObj.Id);
			RoscoTriage.getCaseOppLookup('foo', caseObj.Id, accountObj.Id);
			RoscoTriage.getSalesCaseContactId();

			Map<String, Object> caseinfo = new Map<String, Object>();
			caseinfo.put('caseId', caseObj.Id);
			caseinfo.put('accountId', accountObj.Id);
			caseinfo.put('componentversion', '123');
			caseinfo.put('case_component', 'Other');
			caseinfo.put('contactId', contactObj.Id);
			caseinfo.put('jira', '1');
			caseinfo.put('ownerId', userObj.Id);
			caseinfo.put('severity', '3');
			caseinfo.put('status', 'On Hold');
			caseinfo.put('status_details', '');
			caseinfo.put('subject', 'Subject123');
			caseinfo.put('tags', 'tag1');
			caseinfo.put('case_type', 'Incident');
			caseinfo.put('richtext', 'blah');

			caseinfo.put('ccrstring', 'rosco1@tanium.com;rosco2@tanium.com');
			RoscoTriage.saveCase(caseinfo);
			RoscoTriage.saveCaseTSE2(caseinfo);
		}
	}

	@isTest(SeeAllData=true)
	static void test_Unit_createCase() {
		List<Map<String, String>> result = RoscoTriage.getCaseOppLookup('', '', '');
		System.debug('result:' + result);
	}

	public class mockCallout implements HttpCalloutMock {
		public HttpResponse respond(HttpRequest request) {
			HttpResponse res = new HttpResponse();
			res.setBody('{"text":"value"}');
			res.setStatusCode(200);
			return res;
		}
	}
}