objects/Tool_Displacement__c/Tool_Displacement__c.object-meta.xml
<CustomObject>
    <label>Tool Displacement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Displacement Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tool Displacements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tool_Displacement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tool Displacements</relationshipLabel>
    <relationshipName>Vendors</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Tool_Displacement__c/fields/Displacement_Stage__c.field-meta.xml
<CustomField>
    <fullName>Displacement_Stage__c</fullName>
    <label>Displacement Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Evaluating</fullName>
            </value>
            <value>
                <fullName>Implementing</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Not Displacing Anymore</fullName>
                <label>Displacement Failed</label>
            </value>
            <value>
                <fullName>Not Exploring Displacement</fullName>
                <isActive>false</isActive>
                <label>Not Exploring Displacement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ToolDisplacementTriggerTest.cls
/**
 * @Business: Test class of Trigger on Tool Displacement i.e.ToolDisplacementTrigger
 * @Date: 2019-10-16
 * @Author: Cumulus Vision
 * @Request: TAN-820
 * Modified  ModifiedDate   Description
 * TAN-820   2019-10-21     Initial Development
 */

@isTest
private class ToolDisplacementTriggerTest {
	@TestSetup
	static void makeData() {
		List<Account> accList = new List<Account>();
		accList.add(TestFactory.buildAccount('Test1'));
		accList.add(TestFactory.buildAccount('Test2'));
		insert accList;
	}

	@isTest
	private static void integration_WhenToolDisplacementInsert_UpdateAccountStage() {
		List<Account> accList = [SELECT Id FROM Account];
		Tool_Displacement__c tdRec1 = new Tool_Displacement__c(
			Account__c = accList[0].Id,
			Displacement_Stage__c = 'Evaluating'
		);
		Tool_Displacement__c tdRec2 = new Tool_Displacement__c(
			Account__c = accList[0].Id,
			Displacement_Stage__c = 'Evaluating'
		);

		Test.startTest();
		insert new List<Tool_Displacement__c>{ tdRec1, tdRec2 };
		Test.stopTest();

		Account acc1 = [
			SELECT Tool_Displacement_Stage__c
			FROM Account
			WHERE Id = :tdRec1.Account__c
			LIMIT 1
		];
		System.assertEquals('2 Evaluating.', acc1.Tool_Displacement_Stage__c);
	}

	@isTest
	private static void integration_WhenToolDisplacementUpdate_UpdateAccountStage() {
		List<Account> accList = [SELECT Id FROM Account];

		Tool_Displacement__c tdRec1 = new Tool_Displacement__c(
			Account__c = accList[0].Id,
			Displacement_Stage__c = 'Evaluating'
		);
		insert tdRec1;

		TriggerHandler.resetRecursionLimits();

		Test.startTest();
		tdRec1.Displacement_Stage__c = 'Implementing';
		update tdRec1;
		Test.stopTest();

		Account acc1 = [
			SELECT Tool_Displacement_Stage__c
			FROM Account
			WHERE Id = :tdRec1.Account__c
			LIMIT 1
		];
		System.assertEquals('1 Implementing.', acc1.Tool_Displacement_Stage__c);
	}

	@isTest
	private static void integration_WhenToolDisplacementDeleted_UpdateAccountStage() {
		List<Account> accList = [SELECT Id FROM Account];

		Tool_Displacement__c tdRec1 = new Tool_Displacement__c(
			Account__c = accList[0].Id,
			Displacement_Stage__c = 'Evaluating'
		);
		insert tdRec1;

		TriggerHandler.resetRecursionLimits();

		Test.startTest();
		delete tdRec1;
		Test.stopTest();

		Account acc1 = [
			SELECT Tool_Displacement_Stage__c
			FROM Account
			WHERE Id = :tdRec1.Account__c
			LIMIT 1
		];
		System.assertEquals(null, acc1.Tool_Displacement_Stage__c);
	}

	@isTest
	private static void integration_WhenToolDisplacementUndeleted_UpdateAccountStage() {
		List<Account> accList = [SELECT Id FROM Account];

		Tool_Displacement__c tdRec1 = new Tool_Displacement__c(
			Account__c = accList[0].Id,
			Displacement_Stage__c = 'Evaluating'
		);
		insert tdRec1;

		TriggerHandler.resetRecursionLimits();

		delete tdRec1;

		TriggerHandler.resetRecursionLimits();

		Test.startTest();
		undelete tdRec1;
		Test.stopTest();

		Account acc1 = [
			SELECT Tool_Displacement_Stage__c
			FROM Account
			WHERE Id = :tdRec1.Account__c
			LIMIT 1
		];
		System.assertEquals('1 Evaluating.', acc1.Tool_Displacement_Stage__c);
	}
}