objects/Rosco_Account__c/Rosco_Account__c.object-meta.xml
<CustomObject>
    <label>rosco_account</label>
    <nameField>
        <label>slack_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>rosco_accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rosco_Account__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>rosco_accounts</relationshipLabel>
    <relationshipName>rosco_accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Rosco_Account__c/fields/case_flash__c.field-meta.xml
<CustomField>
    <fullName>case_flash__c</fullName>
    <label>case_flash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Rosco_Account__c/fields/Case_Flash_Persist__c.field-meta.xml
<CustomField>
    <fullName>Case_Flash_Persist__c</fullName>
    <label>Case Flash Persist</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/CaseRoscoAccountFlashMsgController.cls
/*
 * @BUSINESS: Controller class for LWC - caseRoscoAccountFlashMessage
 * @DATE: 2024-01-29
 * @AUTHOR: Tanium Dev Team
 * @REQUEST:
 * RequestId  ModifiedDate  Comment
 * SS-9787    2024-01-29    Initial creation
 */
public class CaseRoscoAccountFlashMsgController {
	@AuraEnabled(cacheable=true)
	public static String getRoscoAccountDetails(String accountId, String caseStatus) {
		String flashMessage = '';

		List<Rosco_Account__c> roscoAccounts = [
			SELECT Name, case_flash__c, Case_Flash_Persist__c
			FROM Rosco_Account__c
			WHERE account__c = :accountId
		];

		if (!roscoAccounts.isEmpty()) {
			flashMessage = (caseStatus == 'New')
				? roscoAccounts[0].case_flash__c
				: roscoAccounts[0].Case_Flash_Persist__c;
		}

		return flashMessage;
	}
}