objects/Account_Support_Request__c/Account_Support_Request__c.object-meta.xml
<CustomObject>
    <description>Internal Support Requests</description>
    <label>Internal Support Request</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Internal Support Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Support_Request__c/fields/Country_Exception_Approved__c.field-meta.xml
<CustomField>
    <fullName>Country_Exception_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Country Exception Approved</label>
    <type>Checkbox</type>
</CustomField>

objects/Country_For_Export__c/Country_For_Export__c.object-meta.xml
<CustomObject>
    <label>Country For Export</label>
    <nameField>
        <label>Country For Export Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries For Export</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country_For_Export__c/fields/Country_Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Country_Restrictions__c</fullName>
    <formula>IF(NOT(Business_Allowed__c) &amp;&amp; Partner_Permitted__c, &quot;Partner Permitted&quot;,
IF(NOT(Business_Allowed__c) &amp;&amp; NOT(Partner_Permitted__c),&quot;Restricted&quot;,
IF(Business_Allowed__c,&quot;Direct Sales Permitted&quot;,
&quot;Embargo or DNS&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field will indicate how business is allowed to be conducted within this country</inlineHelpText>
    <label>Country Restrictions</label>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/POC_Request__c.object-meta.xml
<CustomObject>
    <description>Custom Object to request and trigger POC process</description>
    <label>POC Request</label>
    <nameField>
        <label>POC Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POC_Request__c/fields/Deployment_Country__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Country__c</fullName>
    <description>02.06.2026 Added Korea, Republic Of and deactivated South Korea</description>
    <label>Server Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/POC_Request__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <inlineHelpText>-Production: intended for live environment, does not allow unsigned content
-Lab: testing license, includes labs content and allows unsigned content
-QA: testing license that mirrors prod, no labs content and no unsigned content, Limited use</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tanium_Infrastructure__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
                <default>true</default>
                <label>Lab</label>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/POC_Request__c/fields/POC_Type__c.field-meta.xml
<CustomField>
    <fullName>POC_Type__c</fullName>
    <label>POC Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Modify an existing/active POC license</fullName>
            </value>
            <value>
                <fullName>Partner IR/Assessment</fullName>
                <isActive>false</isActive>
                <label>Partner IR/Assessment</label>
            </value>
            <value>
                <fullName>QA</fullName>
                <isActive>false</isActive>
                <label>QA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/POC_Request__c/fields/TAN_220_DEV_Copper_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_220_DEV_Copper_Quantity__c</fullName>
    <label>TAN-DEV-220-CP: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_220_DEV_Fiber_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_220_DEV_Fiber_Quantity__c</fullName>
    <label>TAN-DEV-225-FB : Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_320_S_Copper_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_320_S_Copper_Quantity__c</fullName>
    <label>TAN-320-S-Copper : Quantity</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_320_S_Fiber_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_320_S_Fiber_Quantity__c</fullName>
    <label>TAN-325-S-Fiber: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_420_M_Copper_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_420_M_Copper_Quantity__c</fullName>
    <label>TAN-420-M-Copper : Quantity</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_420_M_Fiber_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_420_M_Fiber_Quantity__c</fullName>
    <label>TAN-425-M-Fiber: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_720_L_Copper_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_720_L_Copper_Quantity__c</fullName>
    <label>TAN-720-L-Copper: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_720_L_Fiber_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_720_L_Fiber_Quantity__c</fullName>
    <label>TAN-725-L-Fiber: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_920_XL_Copper_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_920_XL_Copper_Quantity__c</fullName>
    <label>TAN-920-XL-Copper: Quantity</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_920_XL_Fiber_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_920_XL_Fiber_Quantity__c</fullName>
    <label>TAN-925-XL-Fiber: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_CLOUD_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_CLOUD_Quantity__c</fullName>
    <label>TAN-CLOUD : Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_L_730_CP_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_L_730_CP_Quantity__c</fullName>
    <label>TAN-L-730-CP: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_L_735_FB_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_L_735_FB_Quantity__c</fullName>
    <label>TAN-L-735-FB: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_M_430_CP_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_M_430_CP_Quantity__c</fullName>
    <label>TAN-M-430-CP: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_M_435_FB_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_M_435_FB_Quantity__c</fullName>
    <label>TAN-M-435-FB: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_S_330_CP_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_S_330_CP_Quantity__c</fullName>
    <label>TAN-S-330-CP: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_S_335_FB_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_S_335_FB_Quantity__c</fullName>
    <label>TAN-S-335-FB: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_VIRTUAL_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_VIRTUAL_Quantity__c</fullName>
    <label>TAN-VIRTUAL : Quantity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_XL_930_CP_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_XL_930_CP_Quantity__c</fullName>
    <label>TAN-XL-930-CP: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/TAN_XL_935_FB_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TAN_XL_935_FB_Quantity__c</fullName>
    <label>TAN-XL-935-FB: Quantity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Non-Perpetual</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>TaaS</fullName>
            </value>
            <value>
                <fullName>Term</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/POCRequestTriggerHandlerTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for POCRequestTriggerHandler
 * @Date: 2018-03-15
 * @Author: Cumulus Vision
 * @Request: TAN-487
 * Modified  ModifiedDate   Description
 * TAN-551   2018-04-26     Updated test class to trigger process builder and avoid failure
 * TAN-588   2018-05-22     Updated test class to trigger process builder and avoid failure
 * TAN-621   2018-07-20     Updated test method to support for addition of "OpportunitLineItem" record.
 * TAN-890   2020-07-15     Fixed test class issue due to update in the POC_Request's License_Type__c field's definition
 * TAN-1190  2021-04-13     Updated to increase coverage and avoid failure
 * TAN-1318  2021-10-01     Added new method createNewPOCOppRequirement for New changes
 * SS-7583	 2024-03-21     Removing BoomiRestService code references
 * SS-12077  2025-11-13     Updated test class with best practices for trigger framework
 * SS-10294  2026-02-12     Remove TAM_Assigned_GS__c reference	from the test class
 */
@IsTest
private class POCRequestTriggerHandlerTest {
	static final String RESTRICTED_COUNTRY = 'France';
	static final String COUNTRY_CODE = 'FR';
	static final String NON_RESTRICTED_COUNTRY = 'United States';
	static final String APPROVED_ISR_COUNTRY = 'India';

	@TestSetup
	static void makeData() {
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'ContactTriggerHandler',
				'LeadTriggerHandler',
				'QuoteCPQTriggerHandler',
				'OpportunityTeamMemberTriggerHandler',
				'OpportunityPartnerTriggerHandler'
			}
		);
		System.runAs(TestUserFactory.getAdminUser()) {
			Account acc = TestFactory.buildAccount('Test Account');
			acc.Type = 'Partner';
			acc.Country_Exception_Approved__c = true;
			acc.Country_Restrictions__c = 'Unrestricted';
			insert acc;

			Id pricebookId = Test.getStandardPricebookId();

			Opportunity opp = TestFactory.buildOpportunity(
				'Test Opp1',
				Date.today() + 30,
				Utility.PROSPECTING,
				acc.Id
			);
			opp.Pricebook2Id = pricebookId;
			opp.Seats__c = 1000;
			opp.Amount = 1000;
			insert opp;

			Country_For_Export__c countryExport = TestFactory.buildCountryForExport('France', 'FR');
			insert countryExport;

			List<String> pocSKUs = new List<String>();
			pocSKUs.addAll(POCRequestOpportunityUtility.POC_SKUS);
			List<Product2> products = new List<Product2>();
			List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
			for (Integer i = 0; i < pocSKUs.size(); i++) {
				Product2 prod = TestFactory.buildProduct(
					'Tanium ' + pocSKUs + ' - Subscription',
					pocSKUs[i]
				);
				products.add(prod);
			}
			insert products;
			for (Product2 eachProduct : [SELECT Id FROM Product2 WHERE ID IN :products]) {
				PricebookEntry priceBookEntry1 = TestFactory.buildPricebookEntry(
					eachProduct.Id,
					10000,
					pricebookId
				);
				PricebookEntry priceBookEntry2 = TestFactory.buildPricebookEntry(
					eachProduct.Id,
					12000,
					System.Label.POC_PriceBookId
				);
				pricebookEntries.add(priceBookEntry1);
				pricebookEntries.add(priceBookEntry2);
			}
			insert pricebookEntries;

			POC_Request__c pocRequest = TestFactory.buildPOCRequest(opp);
			pocRequest.Approved__c = true;
			pocRequest.Deployment_Country__c = 'Canada';
			insert pocRequest;
			Account_Support_Request__c accountSupportRequest = TestFactory.buildAccountSupportRequest(
				acc.Id
			);
			insert accountSupportRequest;
		}
	}

	@IsTest
	static void testCreateNewPOCOppRequirement() {
		System.runAs(TestUserFactory.getAdminUser()) {
			Opportunity opp = [
				SELECT Id, Name, CloseDate, StageName, AccountId, Amount, Seats__c, Pricebook2Id
				FROM Opportunity
				LIMIT 1
			];
			POC_Request__c pocr1 = TestFactory.buildPOCRequest(opp);
			POC_Request__c pocr2 = TestFactory.buildPOCRequest(opp);
			pocr2.POC_Type__c = 'Extension';
			POC_Request__c poc3 = TestFactory.buildPOCRequest(opp);
			poc3.TAN_320_S_Copper_Quantity__c = '0';
			poc3.TAN_320_S_Fiber_Quantity__c = '0';
			poc3.TAN_420_M_Fiber_Quantity__c = '0';
			poc3.TAN_420_M_Copper_Quantity__c = '0';
			poc3.TAN_220_DEV_Copper_Quantity__c = '0';
			poc3.TAN_220_DEV_Fiber_Quantity__c = '0';
			poc3.TAN_720_L_Fiber_Quantity__c = '0';
			poc3.TAN_720_L_Copper_Quantity__c = '0';
			poc3.TAN_920_XL_Copper_Quantity__c = '0';
			poc3.TAN_920_XL_Fiber_Quantity__c = '0';
			poc3.TAN_VIRTUAL_Quantity__c = '0';
			poc3.TAN_CLOUD_Quantity__c = '0';
			poc3.TAN_L_730_CP_Quantity__c = '0';
			poc3.TAN_L_735_FB_Quantity__c = '0';
			poc3.TAN_M_430_CP_Quantity__c = '0';
			poc3.TAN_M_435_FB_Quantity__c = '0';
			poc3.TAN_S_330_CP_Quantity__c = '0';
			poc3.TAN_S_335_FB_Quantity__c = '0';
			poc3.TAN_XL_930_CP_Quantity__c = '0';
			poc3.TAN_XL_935_FB_Quantity__c = '0';

			List<POC_Request__c> pocList = new List<POC_Request__c>{ pocr1, pocr2, poc3 };
			insert pocList;

			TriggerHandler.resetRecursionLimits();

			Test.startTest();
			for (POC_Request__c poc : pocList) {
				poc.Approved__c = true;
			}
			update pocList;
			Test.stopTest();

			List<Opportunity> pocOpps = [
				SELECT ID, Parent_Opportunity__c
				FROM Opportunity
				WHERE AccountID = :opp.AccountId AND StageName = :Utility.POC AND Type = 'POC'
			];
			Assert.areEqual(
				1,
				pocOpps.size(),
				'Opportunity is not created for pocr2 and pocr3 POC Request, because in pocr2 POC_Type__c is Extension(not New) and in pocr3 All Quantities are zero value.'
			);
		}
	}

	@IsTest
	static void testOnCreateUpdatePOC_WhenApprovedISRRecordNotExistOnAccount_ShowErrorMessage() {
		String actualErrorMessage = '';

		System.runAs(TestUserFactory.getAdminUser()) {
			POC_Request__c pocRequest = [SELECT Deployment_Country__c FROM POC_Request__c LIMIT 1];

			Test.startTest();
			try {
				pocRequest.Deployment_Country__c = RESTRICTED_COUNTRY;
				update pocRequest;
			} catch (Exception ex) {
				actualErrorMessage = ex.getMessage();
			}
			Test.stopTest();
		}

		Assert.isTrue(
			actualErrorMessage.containsIgnoreCase(label.POC_Request_Restricted_Country_Validation_Msg)
		);
	}

	@IsTest
	static void testOnCreateUpdatePOC_WhenApprovedISRRecordExistOnAccount_DontShowErrorMessage() {
		String actualErrorMessage = 'NoError';
		POC_Request__c pocRequest = [SELECT Deployment_Country__c FROM POC_Request__c LIMIT 1];
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			try {
				pocRequest.Deployment_Country__c = NON_RESTRICTED_COUNTRY;
				update pocRequest;
			} catch (Exception ex) {
				actualErrorMessage = ex.getMessage();
			}
			Test.stopTest();
			Assert.areEqual('NoError', actualErrorMessage);
		}
	}

	@IsTest
	static void testOnCreateUpdatePOC_WhenApprovedISRRecordExistOnAccountButNotForPOCsCountry_ShowErrorMessage() {
		String actualErrorMessage = '';

		System.runAs(TestUserFactory.getAdminUser()) {
			Opportunity opp = [
				SELECT AccountId, Amount, Closedate, Seats__c, StageName
				FROM Opportunity
				LIMIT 1
			];
			Account_Support_Request__c accountSupportRequest = TestFactory.buildAccountSupportRequest(
				opp.AccountID
			);
			accountSupportRequest.Status__c = 'Approved';
			accountSupportRequest.Exception_Country__c = APPROVED_ISR_COUNTRY;
			insert accountSupportRequest;

			POC_Request__c pocRequest = TestFactory.buildPOCRequest(opp);
			pocRequest.Deployment_Country__c = APPROVED_ISR_COUNTRY;
			insert pocRequest;

			TriggerHandler.resetRecursionLimits();

			Test.startTest();
			try {
				pocRequest.Deployment_Country__c = RESTRICTED_COUNTRY;
				update pocRequest;
			} catch (Exception ex) {
				actualErrorMessage = ex.getMessage();
			}
			Test.stopTest();
		}

		Assert.isTrue(
			actualErrorMessage.containsIgnoreCase(label.POC_Request_Restricted_Country_Validation_Msg)
		);
	}
}