objects/Account_Support_Request__c/Account_Support_Request__c.object-meta.xml
<CustomObject>
    <description>Internal Support Requests</description>
    <label>Internal Support Request</label>
    <nameField>
        <displayFormat>ISR-{000000}</displayFormat>
        <label>Internal Support Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Support Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Support_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please enter the end user/customer for this Opportunity</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internal Support Requests (Account)</relationshipLabel>
    <relationshipName>Account_Support_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Support_Request__c/fields/AVP__c.field-meta.xml
<CustomField>
    <fullName>AVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Support_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Support_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Formulates Region value from related Account.</description>
    <formula>Text(Account__r.Region__c)</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

objects/Account_Support_Request__c/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Support_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Support_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Please do not reorder the Status Values. This can cause misalignment in Path Value used by different ISRs
This should be Read Only for Sales Profiles</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Training Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Assignment</fullName>
            </value>
            <value>
                <fullName>Resources Assigned</fullName>
            </value>
            <value>
                <fullName>Submitted and Under Review</fullName>
            </value>
            <value>
                <fullName>Approved and Under Review</fullName>
            </value>
            <value>
                <fullName>Sent to Sr. Advisor/E-Staff</fullName>
            </value>
            <value>
                <fullName>Request sent to contact</fullName>
            </value>
            <value>
                <fullName>Acknowledged by Contact</fullName>
            </value>
            <value>
                <fullName>Call or Meeting Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Request Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assigned to Deal Desk</fullName>
            </value>
            <value>
                <fullName>Call or Meeting Completed - No Current Interest</fullName>
            </value>
            <value>
                <fullName>Entered</fullName>
            </value>
            <value>
                <fullName>ESO Draft</fullName>
            </value>
            <value>
                <fullName>ESO Submitted and Under Review</fullName>
            </value>
            <value>
                <fullName>ESO Approved</fullName>
            </value>
            <value>
                <fullName>ESO Approved Partner</fullName>
            </value>
            <value>
                <fullName>ESE Active</fullName>
                <label>ESO Active</label>
            </value>
            <value>
                <fullName>ESO Closed</fullName>
            </value>
            <value>
                <fullName>ESO Recalled</fullName>
            </value>
            <value>
                <fullName>ESO Failed</fullName>
            </value>
            <value>
                <fullName>ESO Approved for Quote</fullName>
                <label>ESO Approved OTAM Quote</label>
            </value>
            <value>
                <fullName>Executives Engaged - Active Opportunity</fullName>
            </value>
            <value>
                <fullName>Executives Engaged - No immediate interest</fullName>
            </value>
            <value>
                <fullName>Executives not Engaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountInternalSupportRequestAsyncTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for AccountInternalSupportRequestAsync
 * @Date: UNKNOWN
 * @Author: Tanium Dev Team
 * @Request:
 * RequestId  ModifiedDate  Description
 * SS-13176   2026-05-27    Replaced Level_4__c with Region__c for LATAM RVP detection
 */
@IsTest
private class AccountInternalSupportRequestAsyncTest {
	@TestSetup
	static void makeData() {
		TriggerHandler.bypass('AccountTriggerHandler');
		TriggerHandler.bypass('UserTriggerHandler');
		Id currentUserId = UserInfo.getUserId();

		User adminUser = TestUserFactory.getAdminUser();
		adminUser.Area_VP__c = currentUserId;
		update adminUser;

		System.runAs(adminUser) {
			List<Account> accounts = new List<Account>();
			Account account;
			for (Integer i = 0; i < 2; i++) {
				account = TestFactory.buildAccount('Test Account' + i);
				account.OwnerId = currentUserId;
				account.Area_VP__c = adminUser.Id;
				accounts.add(account);
			}
			insert accounts;

			List<Account_Support_Request__c> requests = new List<Account_Support_Request__c>();
			Account_Support_Request__c request;
			for (Integer i = 0; i < 2; i++) {
				request = new Account_Support_Request__c();
				request.Account__c = accounts[0].Id;
				request.OwnerId = (i == 0) ? adminUser.Id : currentUserId;
				request.AVP__c = (i == 0) ? adminUser.Id : currentUserId;
				request.RVP__c = (i == 0) ? adminUser.Id : currentUserId;
				request.Status__c = 'Draft';
				requests.add(request);
			}
			insert requests;
		}
	}

	@IsTest
	static void testAccountInternalSupportRequestAsync() {
		TriggerHandler.bypass('AccountSupportRequestTriggerHandler');
		List<Account> accounts = [SELECT Id, OwnerId, Area_VP__c, RVP__c, Region__c FROM Account];
		List<Account_Support_Request__c> requests;
		Set<Id> userIds = new Set<Id>();

		for (Account_Support_Request__c request : [
			SELECT Id, OwnerId
			FROM Account_Support_Request__c
		]) {
			userIds.add(request.OwnerId);
		}

		Id accountRvpUserId;
		Id currentUserId = UserInfo.getUserId();
		Map<Id, User> usersMap = new Map<Id, User>(
			[
				SELECT Id, Area_VP__c, Full_Name__c, Manager.Id, Manager.Full_Name__c
				FROM User
				WHERE Id IN :userIds
			]
		);

		AccountInternalSupportRequestAsync async1 = new AccountInternalSupportRequestAsync(
			accounts,
			true
		);
		AccountInternalSupportRequestAsync async2 = new AccountInternalSupportRequestAsync(
			new List<Account>(),
			false
		);

		Test.startTest();

		Id jobId1 = System.enqueueJob(async1);
		Id jobId2 = System.enqueueJob(async2);

		accountRvpUserId = async2.getAccountRvpUserId(null, null, usersMap);
		accountRvpUserId = async2.getAccountRvpUserId(currentUserId, null, usersMap);
		requests = async1.getSupportRequestsToSync();
		async1.syncSupportRequests(requests);

		Test.stopTest();

		Assert.isTrue(requests.size() > 0);
		Assert.isTrue(requests[0].OwnerId == currentUserId);
	}
}