objects/BillingByQuoteLine__c/BillingByQuoteLine__c.object-meta.xml
<CustomObject>
    <label>Billing by Quote Line</label>
    <nameField>
        <displayFormat>BQL-{0000}</displayFormat>
        <label>Billing by Quote Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings by Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BillingByQuoteLine__c/fields/BillAmount__c.field-meta.xml
<CustomField>
    <fullName>BillAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bill Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/BillDate__c.field-meta.xml
<CustomField>
    <fullName>BillDate__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/BillingScheduleOrder__c.field-meta.xml
<CustomField>
    <fullName>BillingScheduleOrder__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <label>Billing Schedule Order</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/ELV_Quote__c.field-meta.xml
<CustomField>
    <fullName>ELV_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote attached to the billing</description>
    <inlineHelpText>Quote attached to the billing</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Billing By Quote Lines</relationshipLabel>
    <relationshipName>ELV_BillingByQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/isReverseBilling__c.field-meta.xml
<CustomField>
    <fullName>isReverseBilling__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If Reverse Billing was used</inlineHelpText>
    <label>is Reverse Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity attached to the billing</description>
    <inlineHelpText>Opportunity attached to the billing</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billings by Quote Lines</relationshipLabel>
    <relationshipName>BillingsByQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/BillingByQuoteLine__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>How the customer plans to pay Tanium</description>
    <inlineHelpText>How the customer plans to pay Tanium</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentType</valueSetName>
    </valueSet>
</CustomField>

objects/Quote/fields/ELV_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ELV_ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/ELV_First_Billing_Override__c.field-meta.xml
<CustomField>
    <fullName>ELV_First_Billing_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Billing Override</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_QteNetTotQLBillDiscrep__c.field-meta.xml
<CustomField>
    <fullName>ELV_QteNetTotQLBillDiscrep__c</fullName>
    <formula>Ruby__SellerTotalAmount__c - ELV_Billing_Schedule_Total_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Net Total Billing Discrepancy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote/fields/Ruby__IsPrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>Ruby__IsPrimaryQuote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this quote is a primary quote.  The primary quote can be synchronized with the opportunity.</description>
    <inlineHelpText>By selecting this option, the quote will be set as the primary quote of this opportunity.  A primary quote&apos;s line items will be synchronized with the opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <type>Checkbox</type>
</CustomField>

classes/BatchCreateBillingScheduleRecords.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Batch class that creates Billing Schedule records for Opportunities whose billing amount has drifted from their primary quote's net amount.
 * @Date: UNKNOWN
 * @Author: Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-13619   2026-08-17    Migrated to standard Quote fields
 */
public class BatchCreateBillingScheduleRecords implements Database.Batchable<sObject>, Schedulable {
	private static final integer BATCH_SIZE_LIMIT = 1;

	private String queryString =
		'SELECT ' +
		'Id, ' +
		'CloseDate, ' +
		'( ' +
		'SELECT ' +
		'Id, ' +
		'Name, ' +
		'BillAmount__c, ' +
		'BillDate__c, ' +
		'BillingScheduleOrder__c, ' +
		'IsReverseBilling__c, ' +
		'Opportunity__c, ' +
		'PaymentType__c, ' +
		'ELV_Quote__c ' +
		'FROM BillingsByQuoteLines__r ' +
		'WHERE ELV_Quote__r.Ruby__IsPrimaryQuote__c = TRUE ' +
		'ORDER BY BillingScheduleOrder__c, BillDate__c ' +
		') ' +
		'FROM  Opportunity ' +
		'WHERE isClosed = false ' +
		'AND (Ruby__PrimaryQuote__r.ELV_QteNetTotQLBillDiscrep__c >= 1 OR Ruby__PrimaryQuote__r.ELV_QteNetTotQLBillDiscrep__c <= -1) ' +
		'AND RecordType.DeveloperName IN (\'Open\') ' +
		'AND Ruby__PrimaryQuote__c != null ' +
		'AND ' +
		'( ' +
		'Ruby__PrimaryQuote__r.ELV_ApprovalStatus__c = null ' +
		'OR ' +
		'Ruby__PrimaryQuote__r.ELV_ApprovalStatus__c IN (\'Recalled\',\'Rejected\') ' +
		') ';

	public static void executeBatch(String customQuery) {
		Database.executeBatch(new BatchCreateBillingScheduleRecords(customQuery), BATCH_SIZE_LIMIT);
	}

	@InvocableMethod
	public static void executeBatch() {
		Database.executeBatch(new BatchCreateBillingScheduleRecords(), BATCH_SIZE_LIMIT);
	}

	public void execute(SchedulableContext sc) {
		Database.executeBatch(new BatchCreateBillingScheduleRecords(), BATCH_SIZE_LIMIT);
	}

	@TestVisible
	private BatchCreateBillingScheduleRecords() {
	}

	private BatchCreateBillingScheduleRecords(String customQuery) {
		if (!String.isBlank(customQuery)) {
			this.queryString = customQuery;
		}
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(this.queryString);
	}

	public void execute(Database.BatchableContext BC, List<Opportunity> opportunitiesToUpdate) {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'QuoteCPQTriggerHandler'
			}
		);

		try {
			List<Opportunity> oppsToUpdate = [
				SELECT Id, Name, CloseDate
				FROM Opportunity
				WHERE Id IN :opportunitiesToUpdate
				FOR UPDATE
			];
			List<BillingByQuoteLine__c> billingsToInsert = BillingScheduleService.getPrimaryQuoteLinesData(
				oppsToUpdate[0].Id,
				'Opportunity'
			);
			if (!billingsToInsert.isEmpty()) {
				BillingScheduleConfiguratorController.createBillingScheduleAndRelatedRecords(
					billingsToInsert,
					oppsToUpdate[0].CloseDate,
					billingsToInsert[0].ELV_Quote__r.ELV_First_Billing_Override__c
				);
			}
		} catch (Exception e) {
			Logger.error('BatchCreateBillingScheduleRecords Errors', e)
				.addTag('apex')
				.addTag('batch');
			Logger.saveLog();
		}
	}

	public void finish(Database.BatchableContext BC) {
		AsyncApexJob job = [
			SELECT
				Id,
				Status,
				NumberOfErrors,
				JobItemsProcessed,
				TotalJobItems,
				CreatedBy.Email,
				ExtendedStatus
			FROM AsyncApexJob
			WHERE Id = :BC.getJobId()
		];

		if (job.Status == 'Completed' && job.NumberOfErrors > 0 || Test.isRunningTest()) {
			String results =
				'NumberOfErrors: ' +
				job.NumberOfErrors +
				'.' +
				' BatchCreateBillingScheduleRecords processed ' +
				job.TotalJobItems +
				' batches with ' +
				job.NumberOfErrors;
			if (job.ExtendedStatus != null) {
				results = results + ' failures.ExtendedStatus: ' + job.ExtendedStatus;
			}
			Logger.error('BatchCreateBillingScheduleRecords FAILURE STATISTICS:' + results);
			Logger.saveLog();
		}
	}
}