objects/rosco_people__c/rosco_people__c.object-meta.xml
<CustomObject>
    <label>rosco_people</label>
    <nameField>
        <label>slackname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>rosco_peoples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/rosco_people__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>rosco_peoples</relationshipLabel>
    <relationshipName>rosco_peoples</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/rosco_people__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>user</label>
    <referenceTo>User</referenceTo>
    <relationshipName>rosco_peoples</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Server_Deployment__c/Server_Deployment__c.object-meta.xml
<CustomObject>
    <description>The Server Deployment Object tracks important technical characteristics about a Production, Test, QA, or Evaluation deployment to provide the support team background information when responding to requests for assistance as well as to gather metrics for Product Management to understand typical configuration and usage.  The object includes two additional Objects--the Client and Zone Server.

2014 | JR</description>
    <label>Server Deployment</label>
    <nameField>
        <label>Instance/Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Server_Deployment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Server Deployments</relationshipLabel>
    <relationshipName>Server_Deployments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Server_Deployment__c/fields/Cloud_Provider__c.field-meta.xml
<CustomField>
    <fullName>Cloud_Provider__c</fullName>
    <description>SS-4495 - Field to capture the cloud provider.
ITSC-00291940 - Field to default to blank and only OrderOps (use Deal Desk profile) can update it.</description>
    <inlineHelpText>This field should be blank - it can only be updated by Order Ops for initial tenant builds. It&apos;s only editable by order ops and it overrides the cloud provider that Provisioner defaults to (via license file), for when deals come through a given cloud marketplace.</inlineHelpText>
    <label>Cloud Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Server_Deployment__c/fields/Server_Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Server_Device_Type__c</fullName>
    <description>2014-10-14 | JR
2020-08-26 Case 54755 Sophie Xu requested label and help text change</description>
    <inlineHelpText>Indicate whether the application server is installed to a physical or virtual device, for license key purpose.</inlineHelpText>
    <label>Infrastructure-License Key Purpose</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On-Prem</fullName>
            </value>
            <value>
                <fullName>Tanium Cloud for U.S. Government</fullName>
            </value>
            <value>
                <fullName>Tanium as a Service</fullName>
                <label>Tanium Cloud</label>
            </value>
            <value>
                <fullName>? object:null ?</fullName>
                <isActive>false</isActive>
                <label>? object:null ?</label>
            </value>
            <value>
                <fullName>Appliance</fullName>
                <isActive>false</isActive>
                <label>Appliance</label>
            </value>
            <value>
                <fullName>Chronical</fullName>
                <isActive>false</isActive>
                <label>Chronical</label>
            </value>
            <value>
                <fullName>Chronicle</fullName>
                <isActive>false</isActive>
                <label>Chronicle</label>
            </value>
            <value>
                <fullName>Cloud</fullName>
                <isActive>false</isActive>
                <label>Cloud</label>
            </value>
            <value>
                <fullName>Customer  - Physical</fullName>
                <isActive>false</isActive>
                <label>Customer - Physical</label>
            </value>
            <value>
                <fullName>Customer - Physical</fullName>
                <isActive>false</isActive>
                <label>Customer - Physical</label>
            </value>
            <value>
                <fullName>Customer - Virtual</fullName>
                <isActive>false</isActive>
                <label>Customer - Virtual</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer Provided</label>
            </value>
            <value>
                <fullName>Customer Provided</fullName>
                <isActive>false</isActive>
                <label>Customer Provided</label>
            </value>
            <value>
                <fullName>Customer Provided - Physical</fullName>
                <isActive>false</isActive>
                <label>Customer Provided - Physical</label>
            </value>
            <value>
                <fullName>Customer Provided - Virtual</fullName>
                <isActive>false</isActive>
                <label>Customer Provided - Virtual</label>
            </value>
            <value>
                <fullName>Physical</fullName>
                <isActive>false</isActive>
                <label>Physical</label>
            </value>
            <value>
                <fullName>Tanium - Cloud</fullName>
                <isActive>false</isActive>
                <label>Tanium - Cloud</label>
            </value>
            <value>
                <fullName>Tanium - Cloud Appliance</fullName>
                <isActive>false</isActive>
                <label>Tanium - Cloud Appliance</label>
            </value>
            <value>
                <fullName>Tanium - Physical</fullName>
                <isActive>false</isActive>
                <label>Tanium - Physical</label>
            </value>
            <value>
                <fullName>Tanium - Physical Appliance</fullName>
                <isActive>false</isActive>
                <label>Tanium - Physical Appliance</label>
            </value>
            <value>
                <fullName>Tanium - Virtual</fullName>
                <isActive>false</isActive>
                <label>Tanium - Virtual</label>
            </value>
            <value>
                <fullName>Tanium - Virtual Appliance</fullName>
                <isActive>false</isActive>
                <label>Tanium - Virtual Appliance</label>
            </value>
            <value>
                <fullName>Tanium - Virtual Appliance (OVA)</fullName>
                <isActive>false</isActive>
                <label>Tanium - Virtual Appliance (OVA)</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
                <isActive>false</isActive>
                <label>Virtual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Server_Deployment__c/recordTypes/TaaS.recordType-meta.xml
<RecordType>
    <fullName>TaaS</fullName>
    <active>true</active>
    <label>Tanium Cloud</label>
</RecordType>

objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Customer Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c/fields/Case_1_Recommend__c.field-meta.xml
<CustomField>
    <fullName>Case_1_Recommend__c</fullName>
    <label>Transactional NPS Factor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Survey__c/fields/Case_2_Overall_Support__c.field-meta.xml
<CustomField>
    <fullName>Case_2_Overall_Support__c</fullName>
    <label>Overall Satisfaction Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extremely satisfied</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat satisfied</fullName>
            </value>
            <value>
                <fullName>Not so satisfied</fullName>
            </value>
            <value>
                <fullName>Not at all satisfied</fullName>
            </value>
            <value>
                <fullName>非常に満足</fullName>
            </value>
            <value>
                <fullName>やや満足</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
            <value>
                <fullName>やや不満</fullName>
            </value>
            <value>
                <fullName>非常に不満</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_2_Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Case_2_Satisfaction__c</fullName>
    <label>Overall Satisfaction</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Survey__c/fields/Case_3_Speed_of_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Case_3_Speed_of_Resolution__c</fullName>
    <label>Speed of Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extremely satisfied</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat satisfied</fullName>
            </value>
            <value>
                <fullName>Not so satisfied</fullName>
            </value>
            <value>
                <fullName>Not at all satisfied</fullName>
            </value>
            <value>
                <fullName>非常に満足</fullName>
            </value>
            <value>
                <fullName>やや満足</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
            <value>
                <fullName>やや不満</fullName>
            </value>
            <value>
                <fullName>非常に不満</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_4_Technical_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Case_4_Technical_Knowledge__c</fullName>
    <label>Technical Knowledge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extremely satisfied</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat satisfied</fullName>
            </value>
            <value>
                <fullName>Not so satisfied</fullName>
            </value>
            <value>
                <fullName>Not at all satisfied</fullName>
            </value>
            <value>
                <fullName>非常に満足</fullName>
            </value>
            <value>
                <fullName>やや満足</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
            <value>
                <fullName>やや不満</fullName>
            </value>
            <value>
                <fullName>非常に不満</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_5_Issue_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Case_5_Issue_Resolved__c</fullName>
    <label>Issue Resolved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>はい</fullName>
            </value>
            <value>
                <fullName>いいえ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_6_Comment__c.field-meta.xml
<CustomField>
    <fullName>Case_6_Comment__c</fullName>
    <label>CSAT Survey Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Survey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Survey__c/fields/SurveyCreateDate__c.field-meta.xml
<CustomField>
    <fullName>SurveyCreateDate__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

objects/TAM_Team__c/TAM_Team__c.object-meta.xml
<CustomObject>
    <label>TAM Team</label>
    <nameField>
        <label>TAM Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAM Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TAM_Team__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAM Teams</relationshipLabel>
    <relationshipName>TAM_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/RoscoInfoTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for RoscoInfo
 * @Date:
 * @Author: Cumulus Vision
 * @Request:
 * Modified  ModifiedDate   Description
 * TAN-832	  2019-18-11    Test methods updated.
 * SS-9852    2025-01-24    Added test method
 * SS-11173   2025-07-10    Changed field from Severity__c to Severity_Community__c
 * SS-10294   2026-02-12    Remove TAM_Assigned_GS__c reference	from the test class
 */
@IsTest
private class RoscoInfoTest {
	@TestSetup
	static void makeData() {
		Id taniumCloudRecTypeId = Utility.getRecordTypeIdByAPIName('Server_Deployment__c', 'TaaS');
		String recordTypeId = RoscoUtility.getRecordTypeIdByAPIName('Case', 'Support');

		System.runAs(TestUserFactory.getAdminUser()) {
			Account account = TestFactory.buildAccount('Test Account');
			account.Type = 'Prospect';
			insert account;

			Contact contact = TestFactory.buildContact(account.Id);
			insert contact;

			List<Server_Deployment__c> serverDeployments = new List<Server_Deployment__c>();
			serverDeployments.add(
				new Server_Deployment__c(
					Account__c = account.Id,
					RecordTypeId = taniumCloudRecTypeId,
					Server_Device_Type__c = 'Tanium as a Service',
					Cloud_Provider__c = 'AWS'
				)
			);

			insert serverDeployments;

			Case caseObj = new Case(
				ContactId = contact.id,
				accountid = account.id,
				subject = 'ROSCOTESTCASE',
				Severity_Community__c = '3',
				type = 'Incident',
				Reason = 'New problem',
				Origin = 'Email',
				suppliedEmail = '99@outlook.com',
				LatestPublicCommentHTML__c = '<html>hello</html>',
				Component__c = 'Other',
				RecordTypeId = recordTypeId,
				status = 'On Hold'
			);
			insert caseObj;
		}
	}

	@IsTest
	static void testGetInitInfo_WhenCaseRecordIsExisting_GetCaseDetails() {
		TriggerHandler.bypass(new List<String>{ 'AccountTriggerHandler', 'ContactTriggerHandler' });
		Test.setMock(HttpCalloutMock.class, new mockCallout());

		Id profileId = [SELECT Id FROM Profile WHERE Name = 'Tanium System Administrator'].Id;

		User userObj = new User(
			Email = 'roscoapextest@roscolab.com',
			FirstName = 'Test',
			LastName = 'ApexUser',
			Username = 'roscoapextest@roscolab.com',
			Alias = 'testals',
			CommunityNickname = 'testcommnickname',
			TimeZoneSidKey = 'America/Los_Angeles',
			LocaleSidKey = 'en_US',
			EmailEncodingKey = 'ISO-8859-1',
			ProfileId = profileId,
			LanguageLocaleKey = 'en_US'
		);

		insert userObj;

		Account accountObj = TestFactory.buildAccount('ROSCOTESTCASE');
		accountObj.slack_channel_id__c = 'TESTCASE';

		insert accountObj;
		Contact contactObj = new Contact(
			Email = 'roscoapextest@roscolab.com',
			FirstName = 'Test',
			LastName = 'Apex',
			AccountId = null
		);
		insert contactObj;
		Contact contactObj2 = new Contact(
			Email = 'roscoapextest@tanium.com',
			FirstName = 'Test2',
			LastName = 'Apex',
			AccountId = null
		);
		insert contactObj2;

		String recordTypeId = RoscoUtility.getRecordTypeIdByAPIName('Case', 'Support');

		Case caseObj = new Case(
			ContactId = contactObj.id,
			accountid = accountObj.id,
			ownerid = userObj.id,
			subject = 'ROSCOTESTCASE',
			Severity_Community__c = '3',
			type = 'Incident',
			Reason = 'New problem',
			Origin = 'Email',
			suppliedEmail = '99@outlook.com',
			LatestPublicCommentHTML__c = '<html>hello</html>',
			Component__c = 'Other',
			RecordTypeId = recordTypeId,
			status = 'On Hold'
		);
		insert caseObj;

		Survey__c s = new Survey__c();
		//s.Account__c = '00160000018u4tdAAA'
		s.Case_1_Recommend__c = '10';
		s.Case_2_Overall_Support__c = 'Very Satisfied';
		s.Case_2_Satisfaction__c = '100';
		s.Case_3_Speed_of_Resolution__c = 'Very Satisfied';
		s.Case_4_Technical_Knowledge__c = 'Very Satisfied';
		s.Case_5_Issue_Resolved__c = 'Yes';
		s.Case_6_Comment__c = 'Comment1';
		s.Name = 'Support Center CSAT';
		s.SurveyCreateDate__c = System.Datetime.now();
		s.Case__c = String.valueOf(caseObj.Id);
		insert s;

		rosco_people__c peep = new rosco_people__c(
			Name = 'roscoapextestingd',
			contact__c = contactObj.Id,
			user__c = userObj.Id,
			pod__c = 'Central',
			psme__c = 'SME-Patch',
			ssme__c = 'SME-Map'
		);
		insert peep;

		rosco_escalation_rbac__c rbac = new rosco_escalation_rbac__c(
			Name = '4',
			authorized__c = userObj.Id
		);
		insert rbac;

		rosco_people__c sme = new rosco_people__c(
			Name = 'slack.name',
			contact__c = contactObj.Id,
			user__c = userObj.Id,
			pod__c = 'Central',
			psme__c = 'SME-Patch',
			ssme__c = 'SME-Map'
		);
		insert sme;

		TAM_Team__c team = new TAM_Team__c(
			Name = 'Patch',
			SME_Component_Name__c = 'Workbench-Patch',
			Slack_Ticket_Channel_ID__c = 'CCC66LTRT'
		);
		insert team;

		Case casecreated = RoscoUtility.getCaseDetails(caseObj.Id);
		List<Case> cases = new List<Case>();
		cases.add(casecreated);

		RoscoInfo.getInitInfo(caseObj.Id);
		RoscoInfo.nullOrEmpty(caseObj.Id);
	}

	public class mockCallout implements HttpCalloutMock {
		public HttpResponse respond(HttpRequest request) {
			HttpResponse res = new HttpResponse();
			res.setBody('{"text":"value"}');
			res.setStatusCode(200);
			return res;
		}
	}

	@IsTest
	static void testGetSDR_WhenThereAreServerDeploymentRecords_ReturnResult() {
		List<Map<String, String>> result = new List<Map<String, String>>();
		Case caseRec = [SELECT Id FROM Case LIMIT 1];

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			result = RoscoInfo.getSDR(caseRec.Id);
			Test.stopTest();
		}

		Assert.isTrue(result != null);
	}
}