objects/Account_Entitlements__c/Account_Entitlements__c.object-meta.xml
<CustomObject>
    <description>Consolidates all of a customer’s entitlements in a single object. Populated from Subscriptions and POC Requests. Jira ticket SS-10388</description>
    <label>Account Entitlements</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Entitlements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Entitlements__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links this entitlement to the customer&apos;s account record.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the customer&apos;s account record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The End Date of the Entitlement.  Jira ticket SS-10388</description>
    <inlineHelpText>The End Date of the Entitlement.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Account_Entitlements__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this entitlement to the Product Module related to the POC or Subscription.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the Product Module related to the POC or Subscription.</inlineHelpText>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Quantity_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Allocated__c</fullName>
    <defaultValue>(0)</defaultValue>
    <description>The amount of modules that have been licensed to the customer.  Jira ticket SS-10388</description>
    <inlineHelpText>The amount of modules that have been licensed to the customer.</inlineHelpText>
    <label>Quantity Allocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account_Entitlements__c/fields/Quantity_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Purchased__c</fullName>
    <description>The amount of modules that have been purchased or given to the customer.  Jira ticket SS-10388</description>
    <inlineHelpText>The amount of modules that have been purchased or given to the customer. If the product is sold by credits, then this will represent the number of credits that will be issued to the customer.</inlineHelpText>
    <label>Quantity Purchased</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account_Entitlements__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Start Date of the Entitlement.  Jira ticket SS-10388</description>
    <inlineHelpText>The Start Date of the Entitlement.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/Account_Entitlements__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of record  that created this record.  Jira ticket SS-10388</description>
    <inlineHelpText>The type of record  that created this record.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Feature</fullName>
            </value>
            <value>
                <fullName>NFR</fullName>
            </value>
            <value>
                <fullName>POC Request</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Object that will store the data pertaining to Product Modules. This data should match the Module list that is used by the Provisioner team to entitle customers to Tanium Modules.</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Module__c/fields/Module_Description__c.field-meta.xml
<CustomField>
    <fullName>Module_Description__c</fullName>
    <label>Module Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/NFR__c/NFR__c.object-meta.xml
<CustomObject>
    <label>NFR</label>
    <nameField>
        <displayFormat>NFR-{00000}</displayFormat>
        <label>NFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NFR__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NFRs</relationshipLabel>
    <relationshipName>NFRs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/NFR__c/fields/NFR_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>NFR_Expiration_Date__c</fullName>
    <label>NFR Expiration Date</label>
    <type>Date</type>
</CustomField>

objects/NFR__c/fields/NFR_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>NFR_Issued_Date__c</fullName>
    <label>NFR Issued Date</label>
    <type>Date</type>
</CustomField>

objects/NFR__c/fields/Number_of_Endpoints__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Endpoints__c</fullName>
    <label>Number of Endpoints</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/NFR__c/fields/Select_Tanium_Product__c.field-meta.xml
<CustomField>
    <fullName>Select_Tanium_Product__c</fullName>
    <label>Select Tanium Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Asset</fullName>
                <isActive>false</isActive>
                <label>Asset</label>
            </value>
            <value>
                <fullName>Automate</fullName>
                <isActive>false</isActive>
                <label>Automate</label>
            </value>
            <value>
                <fullName>Certificate Manager</fullName>
            </value>
            <value>
                <fullName>Comply</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Detect</fullName>
                <isActive>false</isActive>
                <label>Detect</label>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Enforce</fullName>
            </value>
            <value>
                <fullName>Enforce macOS Device Enrollment</fullName>
                <isActive>false</isActive>
                <label>Enforce macOS Device Enrollment</label>
            </value>
            <value>
                <fullName>Engage</fullName>
            </value>
            <value>
                <fullName>Impact</fullName>
            </value>
            <value>
                <fullName>Integrity Monitor</fullName>
            </value>
            <value>
                <fullName>Intune</fullName>
            </value>
            <value>
                <fullName>Investigate</fullName>
            </value>
            <value>
                <fullName>IR</fullName>
                <isActive>false</isActive>
                <label>IR</label>
            </value>
            <value>
                <fullName>Jump Gate</fullName>
            </value>
            <value>
                <fullName>Map</fullName>
                <isActive>false</isActive>
                <label>Map</label>
            </value>
            <value>
                <fullName>Patch</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Protect</fullName>
                <isActive>false</isActive>
                <label>Protect</label>
            </value>
            <value>
                <fullName>Provision</fullName>
            </value>
            <value>
                <fullName>Reveal</fullName>
            </value>
            <value>
                <fullName>Risk</fullName>
            </value>
            <value>
                <fullName>SBOM</fullName>
            </value>
            <value>
                <fullName>Threat Response</fullName>
            </value>
            <value>
                <fullName>Trace</fullName>
                <isActive>false</isActive>
                <label>Trace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/NFR__c/fields/Server_Deployment_Links_From_Account__c.field-meta.xml
<CustomField>
    <fullName>Server_Deployment_Links_From_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>INC0124516</description>
    <label>Server Deployment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Server_Deployment__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Server_Deployment__c</referenceTo>
    <relationshipLabel>Server Deployments</relationshipLabel>
    <relationshipName>NFRServDep</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/NFR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Server_Deployment__c/Server_Deployment__c.object-meta.xml
<CustomObject>
    <description>The Server Deployment Object tracks important technical characteristics about a Production, Test, QA, or Evaluation deployment to provide the support team background information when responding to requests for assistance as well as to gather metrics for Product Management to understand typical configuration and usage.  The object includes two additional Objects--the Client and Zone Server.

2014 | JR</description>
    <label>Server Deployment</label>
    <nameField>
        <label>Instance/Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Server_Deployment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Server Deployments</relationshipLabel>
    <relationshipName>Server_Deployments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Server_Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status (active vs inactive) of this server deployment.
2020-09-01 Duyen added help text to indicate field is required.</description>
    <inlineHelpText>Status is a required field: Indicates the status (active vs inactive) of this server deployment. 
When Status is &quot;Active&quot;, License Delivery Email, Server Version, Server OS, and Tanium Infrastructure are required.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Server_Deployment_Subscriptions__c/Server_Deployment_Subscriptions__c.object-meta.xml
<CustomObject>
    <description>Records the relationship between Server Deployments and Subscriptions. Used in the licensing process by the Automated Management Platform (AMP) maintained by the Tech Tools team</description>
    <label>Server Deployment Subscriptions</label>
    <nameField>
        <displayFormat>SDS-{000000}</displayFormat>
        <label>Server Deployment Subscriptions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Server Deployment Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Server_Deployment_Subscriptions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Server Deployment Subscriptions</relationshipLabel>
    <relationshipName>Server_Deployment_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Server_Deployment_Subscriptions__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Formula that retrieves the Module from the Related Account Entitlement.</description>
    <formula>Account_Entitlement__r.Module__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Module</label>
    <type>Text</type>
</CustomField>

objects/Server_Deployment_Subscriptions__c/fields/Server_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Server_Deployment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Server Deployment</label>
    <referenceTo>Server_Deployment__c</referenceTo>
    <relationshipLabel>Server Deployment Subscriptions</relationshipLabel>
    <relationshipName>Server_Deployment_Subscriptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

classes/NFRTriggerUtilityTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class forNFR Trigger Utility, part of Trigger Framework
 * @Date: 2026-01-12
 * @Author: Tanium Dev Team
 * RequestId    ModifiedDate    Description
 * SS-12077     2026-01-12      Initial development
 */
@IsTest
private class NFRTriggerUtilityTest {
	@TestSetup
	static void makeData() {
		TriggerHandler.bypass(new List<String>{ 'AccountTriggerHandler', 'UserTriggerHandler' });

		System.runAs(TestUserFactory.getAdminUser()) {
			List<Module__c> modules = new List<Module__c>();
			modules.add(new Module__c(Name = 'Comply', Module_Description__c = 'Comply Product'));
			modules.add(new Module__c(Name = 'Core', Module_Description__c = 'Core Product'));
			modules.add(new Module__c(Name = 'Deploy', Module_Description__c = 'Deploy Product'));
			modules.add(new Module__c(Name = 'Discover', Module_Description__c = 'Discover Product'));
			insert modules;

			Account acc = TestFactory.buildAccount('Test Account');
			insert acc;

			List<Server_Deployment__c> serverDeployments = new List<Server_Deployment__c>();
			serverDeployments.add(TestFactory.buildServerDeployment('Test Server Deployment', acc.Id));
			insert serverDeployments;

			List<NFR__c> nfrs = new List<NFR__c>();
			nfrs.add(TestFactory.buildNFR(acc.Id, 'Comply;Core;Deploy;Discover'));
			nfrs[0].Server_Deployment_Links_From_Account__c = serverDeployments[0].Id;
			insert nfrs;
			update nfrs;
		}
	}

	@IsTest
	static void testHandleApprovedNFRs_WhenApproved_CreateAccEntAndServerDeploymentSubscriptions() {
		List<NFR__c> nfrs = [
			SELECT
				Id,
				Name,
				Select_Tanium_Product__c,
				NFR_Expiration_Date__c,
				NFR_Issued_Date__c,
				Status__c,
				Account__c,
				Number_of_Endpoints__c,
				Server_Deployment_Links_From_Account__c
			FROM NFR__c
		];
		Map<Id, NFR__c> oldMap = new Map<Id, NFR__c>(nfrs.deepClone(true, true, true));

		for (NFR__c nfr : nfrs) {
			nfr.Status__c = 'Approved';
		}

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			NFRTriggerUtility.handleApprovedNFRs(nfrs, oldMap);
			Test.stopTest();
		}

		List<Account_Entitlements__c> accountEntitlements = [SELECT Id FROM Account_Entitlements__c];
		List<Server_Deployment_Subscriptions__c> serverDeploymentSubscriptions = [
			SELECT Id
			FROM Server_Deployment_Subscriptions__c
		];

		Assert.areEqual(
			4,
			accountEntitlements.size(),
			'4 Account Entitlements should be created for each module'
		);
		Assert.areEqual(
			4,
			serverDeploymentSubscriptions.size(),
			'4 Server Deployment Subscriptions should be created for each module'
		);

		Account_Entitlements__c accountEntitlement = [
			SELECT
				Id,
				Account__c,
				Start_Date__c,
				End_Date__c,
				Quantity_Purchased__c,
				Quantity_Allocated__c,
				Type__c,
				Source_NFR__c
			FROM Account_Entitlements__c
			LIMIT 1
		];
		NFR__c nfr = [
			SELECT Id, Account__c, NFR_Issued_Date__c, NFR_Expiration_Date__c, Number_of_Endpoints__c
			FROM NFR__c
			LIMIT 1
		];
		Assert.areEqual(nfr.Account__c, accountEntitlement.Account__c);
		Assert.areEqual(nfr.NFR_Issued_Date__c, accountEntitlement.Start_Date__c);
		Assert.areEqual(nfr.NFR_Expiration_Date__c, accountEntitlement.End_Date__c);
		Assert.areEqual(nfr.Number_of_Endpoints__c, accountEntitlement.Quantity_Purchased__c);
		Assert.areEqual(nfr.Number_of_Endpoints__c, accountEntitlement.Quantity_Allocated__c);
		Assert.areEqual('NFR', accountEntitlement.Type__c);
		Assert.areEqual(nfr.Id, accountEntitlement.Source_NFR__c);

		Server_Deployment__c serverDeployment = [SELECT Id FROM Server_Deployment__c LIMIT 1];
		Server_Deployment_Subscriptions__c serverDeploymentSubscription = [
			SELECT
				Id,
				Account__c,
				Server_Deployment__c,
				Subscription_Quantity__c,
				Subscription__c,
				Account_Entitlement__c
			FROM Server_Deployment_Subscriptions__c
			LIMIT 1
		];
		Assert.areEqual(accountEntitlement.Account__c, serverDeploymentSubscription.Account__c);
		Assert.areEqual(serverDeployment.Id, serverDeploymentSubscription.Server_Deployment__c);
		Assert.areEqual(
			accountEntitlement.Quantity_Purchased__c,
			serverDeploymentSubscription.Subscription_Quantity__c
		);
		Assert.areEqual(null, serverDeploymentSubscription.Subscription__c);
		Assert.areEqual(accountEntitlement.Id, serverDeploymentSubscription.Account_Entitlement__c);
	}

	@IsTest
	static void testHandleApprovedNFRs_WhenNotApproved_DoNotCreateAccEntAndServerDeploymentSubscriptions() {
		List<NFR__c> nfrs = [
			SELECT
				Id,
				Name,
				Select_Tanium_Product__c,
				NFR_Expiration_Date__c,
				NFR_Issued_Date__c,
				Status__c,
				Account__c,
				Number_of_Endpoints__c,
				Server_Deployment_Links_From_Account__c
			FROM NFR__c
		];
		Map<Id, NFR__c> oldMap = new Map<Id, NFR__c>(nfrs.deepClone(true, true, true));

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			NFRTriggerUtility.handleApprovedNFRs(nfrs, oldMap);
			Test.stopTest();
		}

		List<Account_Entitlements__c> accountEntitlements = [SELECT Id FROM Account_Entitlements__c];
		List<Server_Deployment_Subscriptions__c> serverDeploymentSubscriptions = [
			SELECT Id
			FROM Server_Deployment_Subscriptions__c
		];

		Assert.areEqual(0, accountEntitlements.size(), 'No Account Entitlements should be created');
		Assert.areEqual(
			0,
			serverDeploymentSubscriptions.size(),
			'No Server Deployment Subscriptions should be created'
		);
	}
}