objects/Account_Entitlements__c/Account_Entitlements__c.object-meta.xml
<CustomObject>
    <description>Consolidates all of a customer’s entitlements in a single object. Populated from Subscriptions and POC Requests. Jira ticket SS-10388</description>
    <label>Account Entitlements</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Entitlements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Entitlements__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links this entitlement to the customer&apos;s account record.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the customer&apos;s account record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>AND(
   TODAY() &gt;= Start_Date__c,
   TODAY() &lt;= End_Date__c,
   Quantity_Purchased__c &gt; 0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

objects/Account_Entitlements__c/fields/Module_Name__c.field-meta.xml
<CustomField>
    <fullName>Module_Name__c</fullName>
    <formula>Module__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Module Name</label>
    <type>Text</type>
</CustomField>

objects/AI_Credit_Tier__c/AI_Credit_Tier__c.object-meta.xml
<CustomObject>
    <label>AI Credit Tier</label>
    <nameField>
        <label>AI Credit Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Credit Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AI_Credit_Tier__c/fields/Full_Amount__c.field-meta.xml
<CustomField>
    <fullName>Full_Amount__c</fullName>
    <description>Full Amount</description>
    <formula>Upper_Band__c -  Lower_Band__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Full Tier Amount, i.e. Upper Band - Lower Band</inlineHelpText>
    <label>Full Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Full_Credits__c.field-meta.xml
<CustomField>
    <fullName>Full_Credits__c</fullName>
    <description>Full Credits</description>
    <formula>( Full_Amount__c /  Tanium_Cost_Per_Credit__c ) *  Marginal_Rate_Percent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Full Credits for the Tier</inlineHelpText>
    <label>Full Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Lower_Band__c.field-meta.xml
<CustomField>
    <fullName>Lower_Band__c</fullName>
    <description>Total Customer Software Spend</description>
    <label>Lower Band</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Marginal_Rate_Percent__c.field-meta.xml
<CustomField>
    <fullName>Marginal_Rate_Percent__c</fullName>
    <label>Marginal Rate Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Tanium_Cost_Per_Credit__c.field-meta.xml
<CustomField>
    <fullName>Tanium_Cost_Per_Credit__c</fullName>
    <label>Tanium Cost Per Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Upper_Band__c.field-meta.xml
<CustomField>
    <fullName>Upper_Band__c</fullName>
    <description>Total Customer Software Spend</description>
    <label>Upper Band</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Billing_Schedule__c/Billing_Schedule__c.object-meta.xml
<CustomObject>
    <description>Used to store billing information rolled up from the Opportunity Products</description>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{0000}</displayFormat>
        <label>Billing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Schedule__c/fields/ELV_Quote__c.field-meta.xml
<CustomField>
    <fullName>ELV_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Legacy Quote record.</description>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>ELV_Billing_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Billing_Schedule__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>Billing_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order/fields/Ruby__PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>Ruby__PaymentTerm__c</fullName>
    <description>The order payment term.</description>
    <inlineHelpText>The order payment term.</inlineHelpText>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ruby__PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

objects/Quote/fields/Calculated_AI_Credits__c.field-meta.xml
<CustomField>
    <fullName>Calculated_AI_Credits__c</fullName>
    <label>Calculated AI Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Quote/fields/Calculated_Annualized_Software_Spend__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Annualized_Software_Spend__c</fullName>
    <label>Calculated Annualized Software Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote/fields/ELV_Billing_Schedule_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>ELV_Billing_Schedule_Total_Amount__c</fullName>
    <label>Billing Schedule Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Quote/fields/ELV_Deployment_Exception_Granted__c.field-meta.xml
<CustomField>
    <fullName>ELV_Deployment_Exception_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deployment Exception Granted</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_Deployment_Partner__c.field-meta.xml
<CustomField>
    <fullName>ELV_Deployment_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Deployment Provider)</relationshipLabel>
    <relationshipName>ELV_Deployment_Partner_Q</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote/fields/ELV_Do_Not_Show_Dates__c.field-meta.xml
<CustomField>
    <fullName>ELV_Do_Not_Show_Dates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lock in Dates &amp; Display on Quote</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_First_Billing_Override__c.field-meta.xml
<CustomField>
    <fullName>ELV_First_Billing_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Billing Override</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_L1_L2_Support_Exception_Granted__c.field-meta.xml
<CustomField>
    <fullName>ELV_L1_L2_Support_Exception_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>L1/L2 Support Exception Granted</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/ELV_L1_L2_Support_Partner__c.field-meta.xml
<CustomField>
    <fullName>ELV_L1_L2_Support_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L1/L2 Support Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (L1/L2 Support Provider)</relationshipLabel>
    <relationshipName>ELV_L1_L2_Support_Partner_Q</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote/fields/ELV_LastCalculatedOn__c.field-meta.xml
<CustomField>
    <fullName>ELV_LastCalculatedOn__c</fullName>
    <label>Last Calculated On</label>
    <type>DateTime</type>
</CustomField>

objects/Quote/fields/ELV_Newly_Quoted_Modules__c.field-meta.xml
<CustomField>
    <fullName>ELV_Newly_Quoted_Modules__c</fullName>
    <label>Newly Quoted Modules</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Quote/fields/ELV_Partner_Accreditation__c.field-meta.xml
<CustomField>
    <fullName>ELV_Partner_Accreditation__c</fullName>
    <label>Partner Accreditation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/Quote/fields/Ruby__IsPrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>Ruby__IsPrimaryQuote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this quote is a primary quote.  The primary quote can be synchronized with the opportunity.</description>
    <inlineHelpText>By selecting this option, the quote will be set as the primary quote of this opportunity.  A primary quote&apos;s line items will be synchronized with the opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote/fields/Ruby__PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>Ruby__PaymentTerm__c</fullName>
    <description>The payment term applied for this quote.</description>
    <inlineHelpText>The payment term applied for this quote.</inlineHelpText>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Upon Receipt</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Net 40</label>
            </value>
            <value>
                <fullName>42</fullName>
                <label>Net 42</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Net 50</label>
            </value>
            <value>
                <fullName>65</fullName>
                <label>Net 65</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Net 70</label>
            </value>
            <value>
                <fullName>75</fullName>
                <label>Net 75</label>
            </value>
            <value>
                <fullName>85</fullName>
                <label>Net 85</label>
            </value>
            <value>
                <fullName>90</fullName>
                <label>Net 90</label>
            </value>
            <value>
                <fullName>105</fullName>
                <label>Net 105</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>Net 120</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>Net 130</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Custom Account Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/QuoteLineItem/fields/Ruby__PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>Ruby__PaymentTerm__c</fullName>
    <description>Quote line item payment term</description>
    <inlineHelpText>Payment term used for this item</inlineHelpText>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ruby__PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

classes/QuoteTriggerUtility.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Utility for QuoteTriggerHandler (standard Quote, Nue)
 * @Description: Ports SS-13958's Quote-object behaviors: partner accreditation, AI credits, billing-quote-terms sync, billing-total zeroing, billing schedule re-linking, newly-quoted-modules diffing, and cascade delete; see QuoteTriggerHandler for what's excluded and why.
 * @Date: 2026-09-09
 * @Author: Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-13958   2026-09-15    Added AI credits calc, billing quote terms sync
 */
public with sharing class QuoteTriggerUtility {
	public static void setPartnerAccreditationValues(List<Quote> newQuotes, Map<Id, Quote> oldMap) {
		Set<String> partnerAccredMap = new Set<String>();
		for (Quote eachQuote : newQuotes) {
			if (
				(eachQuote.ELV_Deployment_Partner__c != null) &&
				(eachQuote.ELV_L1_L2_Support_Partner__c != null)
			) {
				partnerAccredMap.add(eachQuote.ELV_L1_L2_Support_Partner__c);
				partnerAccredMap.add(eachQuote.ELV_Deployment_Partner__c);
			} else {
				if (
					oldMap != null &&
					(eachQuote.ELV_Deployment_Partner__c != null &&
					eachQuote.ELV_Deployment_Partner__c !=
					oldMap.get(eachQuote.Id).ELV_Deployment_Partner__c ||
					(eachQuote.ELV_L1_L2_Support_Partner__c != null &&
					oldMap.get(eachQuote.Id).ELV_L1_L2_Support_Partner__c != null &&
					eachQuote.ELV_L1_L2_Support_Partner__c !=
					oldMap.get(eachQuote.Id).ELV_L1_L2_Support_Partner__c))
				) {
					partnerAccredMap.add(eachQuote.ELV_Deployment_Partner__c);
					partnerAccredMap.add(eachQuote.ELV_L1_L2_Support_Partner__c);
				} else if (
					oldMap != null &&
					((eachQuote.ELV_Deployment_Partner__c !=
					oldMap.get(eachQuote.Id).ELV_Deployment_Partner__c &&
					eachQuote.ELV_Deployment_Partner__c == null) ||
					(eachQuote.ELV_L1_L2_Support_Partner__c !=
					oldMap.get(eachQuote.Id).ELV_L1_L2_Support_Partner__c &&
					eachQuote.ELV_L1_L2_Support_Partner__c == null))
				) {
					if (
						eachQuote.ELV_Deployment_Partner__c == null &&
						eachQuote.ELV_Partner_Accreditation__c != null &&
						eachQuote.ELV_Partner_Accreditation__c.contains('Deployment')
					) {
						String clearString = eachQuote.ELV_Partner_Accreditation__c.replace(
							'Deployment',
							''
						);
						eachQuote.ELV_Partner_Accreditation__c = clearString.trim();
					}
					if (
						eachQuote.ELV_L1_L2_Support_Partner__c == null &&
						eachQuote.ELV_Partner_Accreditation__c != null &&
						eachQuote.ELV_Partner_Accreditation__c.contains('Support')
					) {
						String clearString = eachQuote.ELV_Partner_Accreditation__c.replace(
							'Support',
							''
						);
						eachQuote.ELV_Partner_Accreditation__c = clearString.trim();
					}
				} else if (
					oldMap != null &&
					eachQuote.ELV_Deployment_Exception_Granted__c !=
					oldMap.get(eachQuote.Id).ELV_Deployment_Exception_Granted__c
				) {
					if (
						eachQuote.ELV_Deployment_Exception_Granted__c &&
						eachQuote.ELV_Partner_Accreditation__c != null &&
						eachQuote.ELV_Partner_Accreditation__c.contains('Deployment')
					) {
						String clearString = eachQuote.ELV_Partner_Accreditation__c.replace(
							'Deployment',
							''
						);
						eachQuote.ELV_Partner_Accreditation__c = clearString.trim();
					} else {
						partnerAccredMap.add(eachQuote.ELV_Deployment_Partner__c);
					}
				} else if (
					oldMap != null &&
					eachQuote.ELV_L1_L2_Support_Exception_Granted__c !=
					oldMap.get(eachQuote.Id).ELV_L1_L2_Support_Exception_Granted__c
				) {
					if (
						eachQuote.ELV_L1_L2_Support_Exception_Granted__c &&
						eachQuote.ELV_Partner_Accreditation__c != null &&
						eachQuote.ELV_Partner_Accreditation__c.contains('Support')
					) {
						String clearString = eachQuote.ELV_Partner_Accreditation__c.replace(
							'Support',
							''
						);
						eachQuote.ELV_Partner_Accreditation__c = clearString.trim();
					} else {
						partnerAccredMap.add(eachQuote.ELV_L1_L2_Support_Partner__c);
					}
				}
			}
		}
		if (!partnerAccredMap.isEmpty()) {
			QuoteTriggerUtility.handleDefaultPartnerAccreditation(newQuotes, partnerAccredMap);
		}
	}

	public static void setBillingRelatedFieldsOnQuote(List<Quote> newQuotes) {
		for (Quote eachQuote : newQuotes) {
			eachQuote.ELV_Billing_Schedule_Total_Amount__c = 0;
		}
	}

	public static void setAICredits(List<Quote> quotes, Map<Id, Quote> oldMap) {
		List<Quote> eligibleQuotes = new List<Quote>();
		for (Quote quote : quotes) {
			if (
				quote.Calculated_Annualized_Software_Spend__c !=
				oldMap.get(quote.Id).Calculated_Annualized_Software_Spend__c
			) {
				eligibleQuotes.add(quote);
			}
		}
		if (!eligibleQuotes.isEmpty()) {
			List<AI_Credit_Tier__c> tiers = getAICreditTiers();

			for (Quote eligibleQuote : eligibleQuotes) {
				Decimal annualizedSoftwareSpend =
					eligibleQuote.Calculated_Annualized_Software_Spend__c ?? 0;
				Decimal totalAICredits = 0;
				for (AI_Credit_Tier__c tier : tiers) {
					if (annualizedSoftwareSpend >= tier.Lower_Band__c) {
						if (annualizedSoftwareSpend >= tier.Upper_Band__c) {
							totalAICredits += tier.Full_Credits__c;
						}
						if (annualizedSoftwareSpend < tier.Upper_Band__c) {
							totalAICredits +=
								((annualizedSoftwareSpend - tier.Lower_Band__c) / tier.Full_Amount__c) *
								tier.Full_Credits__c;
						}
					}
				}
				eligibleQuote.Calculated_AI_Credits__c = getMonthlyAICredits(totalAICredits);
			}
		}
	}

	public static void processBillingScheduleOnOpportunity(
		List<Quote> newQuotes,
		Map<Id, Quote> oldQuotes
	) {
		Set<Id> oppIdsForBillingUpdates = new Set<Id>();
		for (Quote eachQuote : newQuotes) {
			if (eachQuote.Ruby__IsPrimaryQuote__c != oldQuotes.get(eachQuote.Id).Ruby__IsPrimaryQuote__c) {
				oppIdsForBillingUpdates.add(eachQuote.OpportunityId);
			}
		}
		if (!oppIdsForBillingUpdates.isEmpty()) {
			updateBillingScheduleFuture(oppIdsForBillingUpdates);
		}
	}

	public static void updateBillingSchedules(Set<Id> oppIdsForBillingUpdates) {
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'QuoteTriggerHandler'
			}
		);
		try {
			List<Billing_Schedule__c> billingsToUpdate = new List<Billing_Schedule__c>();
			List<Billing_Schedule__c> billingsSelected = [
				SELECT Id, Opportunity__c, ELV_Quote__r.Ruby__IsPrimaryQuote__c, ELV_Quote__r.OpportunityId
				FROM Billing_Schedule__c
				WHERE ELV_Quote__r.OpportunityId IN :oppIdsForBillingUpdates
			];
			for (Billing_Schedule__c eachBilling : billingsSelected) {
				if (eachBilling.ELV_Quote__r.Ruby__IsPrimaryQuote__c == true) {
					eachBilling.Opportunity__c = eachBilling.ELV_Quote__r.OpportunityId;
				} else {
					eachBilling.Opportunity__c = null;
				}
				billingsToUpdate.add(eachBilling);
			}
			List<Database.SaveResult> saveResults = Database.update(billingsToUpdate, false);
			Logger.logDatabaseErrors(
					LoggingLevel.ERROR,
					'QuoteTriggerUtility.updateBillingSchedules ERRORS',
					saveResults
				)
				.addTag('apex');
		} catch (Exception e) {
			Logger.error('QuoteTriggerUtility.updateBillingSchedules ERRORS', e);
		}
		Logger.saveLog();
	}

	public static void updateBillingQuoteTerms(List<Quote> newQuotes, Map<Id, Quote> oldMap) {
		for (Quote eachQuote : newQuotes) {
			if (
				oldMap != null &&
				(eachQuote.ELV_Do_Not_Show_Dates__c != oldMap.get(eachQuote.Id).ELV_Do_Not_Show_Dates__c ||
				(eachQuote.Ruby__PaymentTerm__c != null &&
				eachQuote.Ruby__PaymentTerm__c != oldMap.get(eachQuote.Id).Ruby__PaymentTerm__c))
			) {
				BillingScheduleConfiguratorController.updateBillingInformationOnQuote(
					eachQuote.Id,
					eachQuote.ELV_First_Billing_Override__c
				);
			}
		}
	}

	public static void processIdentifyNewModules(List<Quote> quotes, Map<Id, Quote> oldMap) {
		List<Quote> quotesToIdentifyNewModules = new List<Quote>();
		for (Quote quote : quotes) {
			if (quote.ELV_LastCalculatedOn__c != oldMap.get(quote.Id).ELV_LastCalculatedOn__c) {
				quotesToIdentifyNewModules.add(quote);
			}
		}
		if (!quotesToIdentifyNewModules.isEmpty()) {
			identifyNewModules(quotesToIdentifyNewModules);
		}
	}

	public static void identifyNewModules(List<Quote> quotes) {
		List<Quote> quotesToUpdate = new List<Quote>();
		Map<Id, Id> quoteIdToAccountId = new Map<Id, Id>();
		for (Quote quote : quotes) {
			quoteIdToAccountId.put(quote.Id, quote.AccountId);
		}

		Map<Id, Set<String>> accountIdToEntitlementModuleNames = getAccountIdToEntitlementModuleNames(
			new Set<Id>(quoteIdToAccountId.values())
		);

		Set<Id> productIds = new Set<Id>();
		List<QuoteLineItem> quoteLines = [
			SELECT Id, PricebookEntry.Product2Id, QuoteId
			FROM QuoteLineItem
			WHERE QuoteId IN :quoteIdToAccountId.keySet()
		];
		for (QuoteLineItem quoteLine : quoteLines) {
			productIds.add(quoteLine.PricebookEntry.Product2Id);
		}

		Map<Id, Set<String>> productIdToProductModuleNames = ProductUtility.getProductIdToProductModuleNames(
			productIds
		);

		Map<Id, Set<String>> quoteIdToProductModuleNames = new Map<Id, Set<String>>();
		for (QuoteLineItem quoteLine : quoteLines) {
			if (!quoteIdToProductModuleNames.containsKey(quoteLine.QuoteId)) {
				quoteIdToProductModuleNames.put(quoteLine.QuoteId, new Set<String>());
			}
			if (productIdToProductModuleNames.containsKey(quoteLine.PricebookEntry.Product2Id)) {
				quoteIdToProductModuleNames.get(quoteLine.QuoteId)
					?.addAll(productIdToProductModuleNames.get(quoteLine.PricebookEntry.Product2Id));
			}
		}

		for (Quote quote : quotes) {
			if (quoteIdToProductModuleNames.get(quote.Id) != null) {
				Set<String> productModuleDifference = quoteIdToProductModuleNames.get(quote.Id)?.clone();

				if (accountIdToEntitlementModuleNames.get(quoteIdToAccountId.get(quote.Id)) != null) {
					productModuleDifference.removeAll(
						accountIdToEntitlementModuleNames.get(quoteIdToAccountId.get(quote.Id))
					);
				}

				quotesToUpdate.add(
					new Quote(
						Id = quote.Id,
						ELV_Newly_Quoted_Modules__c = String.join(productModuleDifference, ', ')
					)
				);
			}
		}

		List<Database.SaveResult> saveResults = Database.update(quotesToUpdate, false);
		Logger.logDatabaseErrors(
			LoggingLevel.ERROR,
			'QuoteTriggerUtility.identifyNewModules Errors',
			saveResults
		);
		Logger.saveLog();
	}

	public static void handleDeletedQuotes(List<Quote> oldQuotes) {
		Map<Id, Billing_Schedule__c> billingMap = new Map<Id, Billing_Schedule__c>(
			[SELECT Id FROM Billing_Schedule__c WHERE ELV_Quote__c IN :oldQuotes]
		);
		if (!billingMap.isEmpty()) {
			QuoteTriggerUtility.deleteBillingSchedulesFuture(billingMap.keySet());
		}
	}

	public static void deleteBillingSchedulesFuture(Set<Id> billingIdsToDelete) {
		deleteBillingSchedules(billingIdsToDelete);
	}

	public static void deleteBillingSchedules(Set<Id> billingIdsToDelete) {
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityTriggerHandler',
				'QuoteTriggerHandler'
			}
		);
		try {
			List<Billing_Schedule__c> billingsToDelete = [
				SELECT Id
				FROM Billing_Schedule__c
				WHERE Id IN :billingIdsToDelete
			];
			List<Database.DeleteResult> deleteResults = Database.delete(billingsToDelete, false);
			Logger.logDatabaseErrors(
					LoggingLevel.ERROR,
					'QuoteTriggerUtility.deleteBillingSchedules ERRORS',
					deleteResults
				)
				.addTag('apex');
		} catch (Exception e) {
			Logger.error('QuoteTriggerUtility.deleteBillingSchedules ERRORS', e);
		}
		Logger.saveLog();
	}

	@future
	private static void updateBillingScheduleFuture(Set<Id> oppIdsForBillingUpdates) {
		updateBillingSchedules(oppIdsForBillingUpdates);
	}

	private static void handleDefaultPartnerAccreditation(List<Quote> newQuotes, Set<String> partnerSet) {
		Map<Id, Account> mapAccount = new Map<Id, Account>(
			[SELECT Id, Partner_Accreditations__c, Business_Motion__c FROM Account WHERE Id IN :partnerSet]
		);
		for (Quote eachQuote : newQuotes) {
			String partnerAccreditation = '';
			if (mapAccount.get(eachQuote.ELV_L1_L2_Support_Partner__c) != null) {
				Account supportPartner = mapAccount.get(eachQuote.ELV_L1_L2_Support_Partner__c);
				if (!eachQuote.ELV_L1_L2_Support_Exception_Granted__c) {
					if (
						supportPartner.Business_Motion__c != null &&
						!supportPartner.Business_Motion__c.contains('Support') &&
						supportPartner.Partner_Accreditations__c == null
					) {
						partnerAccreditation += 'Support';
					} else if (
						supportPartner.Partner_Accreditations__c == null &&
						supportPartner.Business_Motion__c == null
					) {
						partnerAccreditation += 'Support';
					} else if (
						supportPartner.Partner_Accreditations__c != null &&
						!supportPartner.Partner_Accreditations__c.contains('Support')
					) {
						partnerAccreditation += 'Support';
					}
				}
			}
			if (mapAccount.get(eachQuote.ELV_Deployment_Partner__c) != null) {
				Account deploymentPartner = mapAccount.get(eachQuote.ELV_Deployment_Partner__c);
				if (!eachQuote.ELV_Deployment_Exception_Granted__c) {
					if (
						deploymentPartner.Business_Motion__c != null &&
						!deploymentPartner.Business_Motion__c.contains('Support') &&
						deploymentPartner.Partner_Accreditations__c == null
					) {
						partnerAccreditation += ' Deployment';
					} else if (
						deploymentPartner.Partner_Accreditations__c == null &&
						deploymentPartner.Business_Motion__c == null
					) {
						partnerAccreditation += ' Deployment';
					} else if (
						deploymentPartner.Partner_Accreditations__c != null &&
						!deploymentPartner.Partner_Accreditations__c.contains('Deployment')
					) {
						partnerAccreditation += ' Deployment';
					}
				}
			}

			eachQuote.ELV_Partner_Accreditation__c = partnerAccreditation.trim();
		}
	}

	@TestVisible
	private static List<AI_Credit_Tier__c> getAICreditTiers() {
		return [
			SELECT
				Id,
				Tier__c,
				Lower_Band__c,
				Upper_Band__c,
				Full_Amount__c,
				Marginal_Rate_Percent__c,
				Tanium_Cost_Per_Credit__c,
				Full_Credits__c
			FROM AI_Credit_Tier__c
			ORDER BY Tier__c ASC
		];
	}

	@TestVisible
	private static Integer getMonthlyAICredits(Decimal totalAICredits) {
		Integer roundedMonthlyAICredits = Integer.valueOf(
			((totalAICredits / 12) / 500).round(System.RoundingMode.HALF_UP) * 500
		);
		return roundedMonthlyAICredits < 10000 ? 10000 : roundedMonthlyAICredits;
	}

	@TestVisible
	private static Map<Id, Set<String>> getAccountIdToEntitlementModuleNames(Set<Id> accountIds) {
		Map<Id, Set<String>> accountIdToEntitlementModules = new Map<Id, Set<String>>();

		for (Account_Entitlements__c accountEntitlement : [
			SELECT Id, Module_Name__c, Account__c
			FROM Account_Entitlements__c
			WHERE Account__c IN :accountIds AND Active__c = TRUE
			ORDER BY Account__c
		]) {
			if (!accountIdToEntitlementModules.containsKey(accountEntitlement.Account__c)) {
				accountIdToEntitlementModules.put(accountEntitlement.Account__c, new Set<String>());
			}
			accountIdToEntitlementModules.get(accountEntitlement.Account__c)
				.add(accountEntitlement.Module_Name__c);
		}
		return accountIdToEntitlementModules;
	}
}