objects/Account_Entitlements__c/Account_Entitlements__c.object-meta.xml
<CustomObject>
    <description>Consolidates all of a customer’s entitlements in a single object. Populated from Subscriptions and POC Requests. Jira ticket SS-10388</description>
    <label>Account Entitlements</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Account Entitlements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Entitlements__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links this entitlement to the customer&apos;s account record.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the customer&apos;s account record.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The End Date of the Entitlement.  Jira ticket SS-10388</description>
    <inlineHelpText>The End Date of the Entitlement.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/Account_Entitlements__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this entitlement to the Product Module related to the POC or Subscription.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the Product Module related to the POC or Subscription.</inlineHelpText>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this entitlement to the Product record. Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the Product record.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Quantity_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Allocated__c</fullName>
    <defaultValue>(0)</defaultValue>
    <description>The amount of modules that have been licensed to the customer.  Jira ticket SS-10388</description>
    <inlineHelpText>The amount of modules that have been licensed to the customer.</inlineHelpText>
    <label>Quantity Allocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account_Entitlements__c/fields/Quantity_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Purchased__c</fullName>
    <description>The amount of modules that have been purchased or given to the customer.  Jira ticket SS-10388</description>
    <inlineHelpText>The amount of modules that have been purchased or given to the customer. If the product is sold by credits, then this will represent the number of credits that will be issued to the customer.</inlineHelpText>
    <label>Quantity Purchased</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Account_Entitlements__c/fields/Source_NFR__c.field-meta.xml
<CustomField>
    <fullName>Source_NFR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this entitlement to the customer&apos;s NFR record.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the customer&apos;s NFR record.</inlineHelpText>
    <label>Source (NFR)</label>
    <referenceTo>NFR__c</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Source_POC_Request__c.field-meta.xml
<CustomField>
    <fullName>Source_POC_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this entitlement to the customer&apos;s POC Request record.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the customer&apos;s POC Request record.</inlineHelpText>
    <label>Source (POC Request)</label>
    <referenceTo>POC_Request__c</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Source_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Source_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this entitlement to the customer&apos;s Subscription record.  Jira ticket SS-10388</description>
    <inlineHelpText>Links this entitlement to the customer&apos;s Subscription record.</inlineHelpText>
    <label>CPQ Source (Subscription)</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Account Entitlements</relationshipLabel>
    <relationshipName>Account_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Entitlements__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Start Date of the Entitlement.  Jira ticket SS-10388</description>
    <inlineHelpText>The Start Date of the Entitlement.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/Account_Entitlements__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of record  that created this record.  Jira ticket SS-10388</description>
    <inlineHelpText>The type of record  that created this record.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Feature</fullName>
            </value>
            <value>
                <fullName>NFR</fullName>
            </value>
            <value>
                <fullName>POC Request</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Object that will store the data pertaining to Product Modules. This data should match the Module list that is used by the Provisioner team to entitle customers to Tanium Modules.</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NFR__c/NFR__c.object-meta.xml
<CustomObject>
    <label>NFR</label>
    <nameField>
        <displayFormat>NFR-{00000}</displayFormat>
        <label>NFR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NFR__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NFRs</relationshipLabel>
    <relationshipName>NFRs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/NFR__c/fields/NFR_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>NFR_Expiration_Date__c</fullName>
    <label>NFR Expiration Date</label>
    <type>Date</type>
</CustomField>

objects/NFR__c/fields/NFR_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>NFR_Issued_Date__c</fullName>
    <label>NFR Issued Date</label>
    <type>Date</type>
</CustomField>

objects/NFR__c/fields/Number_of_Endpoints__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Endpoints__c</fullName>
    <label>Number of Endpoints</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/POC_Request__c/POC_Request__c.object-meta.xml
<CustomObject>
    <description>Custom Object to request and trigger POC process</description>
    <label>POC Request</label>
    <nameField>
        <label>POC Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POC_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner: On-Prem, Partner: Tanium Cloud</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer: On-Prem, HFPOC, Customer: Tanium Cloud</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POC Requests</relationshipLabel>
    <relationshipName>POC_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/POC_Request__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Start_Date__c + Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/POC_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>4/19/21: Change label from Number of End Points to Number of POC Endpoints</description>
    <inlineHelpText>Production: limited to maximum purchased seats. Lab: limited to
10% of purchased seats</inlineHelpText>
    <label>Number of POC Endpoints</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/POC_Request__c/fields/Server_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Server_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Server Deployment object (records)</description>
    <inlineHelpText>Lookup field to the Server Deployment object (records).</inlineHelpText>
    <label>Server Deployment</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Server Deployment selected does not meet filter criteria. The Server Deployment must be active, be on the same Account as this POC and can not be in POC/Pilot</errorMessage>
        <filterItems>
            <field>Server_Deployment__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Server_Deployment__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Server_Deployment__c.Type__c</field>
            <operation>notEqual</operation>
            <value>POC/Pilot</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Server_Deployment__c</referenceTo>
    <relationshipLabel>POC Requests</relationshipLabel>
    <relationshipName>POC_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product_Module__c/Product_Module__c.object-meta.xml
<CustomObject>
    <description>Junction table to link Products and Modules.</description>
    <label>Product Module</label>
    <nameField>
        <displayFormat>PRDMD-{000000}</displayFormat>
        <label>Product Module</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Product Modules</relationshipLabel>
    <relationshipName>Product_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product_Module__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Modules</relationshipLabel>
    <relationshipName>Product_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Server_Deployment__c/Server_Deployment__c.object-meta.xml
<CustomObject>
    <description>The Server Deployment Object tracks important technical characteristics about a Production, Test, QA, or Evaluation deployment to provide the support team background information when responding to requests for assistance as well as to gather metrics for Product Management to understand typical configuration and usage.  The object includes two additional Objects--the Client and Zone Server.

2014 | JR</description>
    <label>Server Deployment</label>
    <nameField>
        <label>Instance/Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Server_Deployment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Server Deployments</relationshipLabel>
    <relationshipName>Server_Deployments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/Server_Deployment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Track the purpose of this server deployment within the organization&apos;s change management process.</description>
    <inlineHelpText>-Production: intended for live environment, does not allow unsigned content
-Lab: testing license, includes labs content and allows unsigned content
-QA: testing license that mirrors prod, no labs content and no unsigned content, Limited use</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>POC/Pilot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountEntitlementTriggerUtility.cls
/**
 * Copyright (c) 2025 Tanium
 *
 * @Business: Utility class for Account Entitlement trigger
 * @Date: 2025-11-13
 * @Author: Tanium Dev Team
 * RequestId    ModifiedDate    Description
 * SS-12077     2025-11-13      Initial development
 * SS-12494     2026-01-27      Update createAccountEntitlement methods with different key value pairs
 * SS-12651     2026-02-16      Update createAccountEntitlementsOneServDep with null check
 * SS-12914     2026-03-31      Update createAccountEntitlementsOneServDep to always create server deployment subscriptions for testing
 */
public class AccountEntitlementTriggerUtility {
	public static void createAccountEntitlementsManyServerDeps(
		Map<SBQQ__Subscription__c, Id> subscriptionToProductId
	) {
		List<Account_Entitlements__c> newAccountEntitlements = new List<Account_Entitlements__c>();
		Map<Id, List<Product_Module__c>> productIdToProductModules = getProductIdToProductModules(
			subscriptionToProductId.values()
		);

		for (SBQQ__Subscription__c subscription : subscriptionToProductId.keySet()) {
			if (productIdToProductModules.containsKey(subscriptionToProductId.get(subscription))) {
				for (
					Product_Module__c productModule : productIdToProductModules.get(
						subscriptionToProductId.get(subscription)
					)
				) {
					newAccountEntitlements.add(
						buildAccountEntitlementSubscription(subscription, productModule)
					);
				}
			}
		}

		Database.SaveResult[] saveResults = Database.insert(newAccountEntitlements, false);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'AccountEntitlementTriggerUtility.createAccountEntitlementsManyServerDeps ERRORS',
				saveResults
			)
			.addTag('apex');
		Logger.saveLog();
	}

	public static void createAccountEntitlementsOneServDep(
		Map<SBQQ__Subscription__c, Id> subscriptionToProductId,
		Map<Id, Server_Deployment__c> accountIdToServerDeployment
	) {
		List<Account_Entitlements__c> newAccountEntitlements = new List<Account_Entitlements__c>();
		Map<Id, List<Product_Module__c>> productIdToProductModules = getProductIdToProductModules(
			subscriptionToProductId.values()
		);

		for (SBQQ__Subscription__c subscription : subscriptionToProductId.keySet()) {
			if (productIdToProductModules.containsKey(subscriptionToProductId.get(subscription))) {
				for (
					Product_Module__c productModule : productIdToProductModules.get(
						subscriptionToProductId.get(subscription)
					)
				) {
					Account_Entitlements__c newAccountEntitlement = buildAccountEntitlementSubscription(
						subscription,
						productModule
					);
					newAccountEntitlement.Quantity_Allocated__c = subscription.SBQQ__Quantity__c;
					newAccountEntitlements.add(newAccountEntitlement);
				}
			}
		}

		Database.SaveResult[] saveResults = Database.insert(newAccountEntitlements, false);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'AccountEntitlementTriggerUtility.createAccountEntitlementsOneServDep ERRORS',
				saveResults
			)
			.addTag('apex');
		Logger.saveLog();

		if (System.Label.Trigger_CreateServDepSubsFlag == 'true' || Test.isRunningTest()) {
			ServerDeploymentSubTriggerUtility.createServerDeploymentSubscriptions(
				newAccountEntitlements,
				accountIdToServerDeployment,
				true
			);
		}
	}

	public static void createAccountEntitlementsNFR(
		Map<Id, NFR__c> nfrMap,
		Map<Id, List<Module__c>> nfrIdToModules,
		Map<Id, Server_Deployment__c> accountIdToServerDeployment
	) {
		List<Account_Entitlements__c> newAccountEntitlements = new List<Account_Entitlements__c>();

		for (Id nfrId : nfrIdToModules.keySet()) {
			for (Module__c module : nfrIdToModules.get(nfrId)) {
				newAccountEntitlements.add(buildAccountEntitlementNFR(nfrMap.get(nfrId), module));
			}
		}

		Database.SaveResult[] saveResults = Database.insert(newAccountEntitlements, false);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'AccountEntitlementTriggerUtility.createAccountEntitlementsNFR ERRORS',
				saveResults
			)
			.addTag('apex');
		Logger.saveLog();

		if (System.Label.Trigger_CreateServDepSubsFlag == 'true' || Test.isRunningTest()) {
			ServerDeploymentSubTriggerUtility.createServerDeploymentSubscriptions(
				newAccountEntitlements,
				accountIdToServerDeployment,
				false
			);
		}
	}

	public static void createAccountEntitlementsPOCRequestModules(
		Map<Id, POC_Request__c> pocRequestMap,
		Map<Id, List<Id>> pocRequestIdToModuleIds,
		Map<Id, Server_Deployment__c> accountIdToServerDeployment
	) {
		List<Account_Entitlements__c> newAccountEntitlements = new List<Account_Entitlements__c>();

		for (Id pocRequestId : pocRequestIdToModuleIds.keySet()) {
			for (Id moduleId : pocRequestIdToModuleIds.get(pocRequestId)) {
				newAccountEntitlements.add(
					buildAccountEntitlementPOCRequestModule(pocRequestMap.get(pocRequestId), moduleId)
				);
			}
		}

		Database.SaveResult[] saveResults = Database.insert(newAccountEntitlements, false);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'AccountEntitlementTriggerUtility.createAccountEntitlementsPOCRequestModules ERRORS',
				saveResults
			)
			.addTag('apex');
		Logger.saveLog();

		if (System.Label.Trigger_CreateServDepSubsFlag == 'true' || Test.isRunningTest()) {
			ServerDeploymentSubTriggerUtility.createServerDeploymentSubscriptions(
				newAccountEntitlements,
				accountIdToServerDeployment,
				false
			);
		}
	}

	public static void createAccountEntitlementsPOCRequestSolutions(
		Map<Id, POC_Request__c> productIdToPOCRequest,
		Map<Id, Server_Deployment__c> accountIdToServerDeployment
	) {
		List<Account_Entitlements__c> newAccountEntitlements = new List<Account_Entitlements__c>();
		Map<Id, Product_Module__c> productModuleMap = new Map<Id, Product_Module__c>(
			[
				SELECT Id, Module__c, Product__c
				FROM Product_Module__c
				WHERE Product__c IN :productIdToPOCRequest.keySet()
			]
		);

		for (Product_Module__c productModule : productModuleMap.values()) {
			newAccountEntitlements.add(
				buildAccountEntitlementPOCRequestSolution(
					productIdToPOCRequest.get(productModule.Product__c),
					productModule
				)
			);
		}

		Database.SaveResult[] saveResults = Database.insert(newAccountEntitlements, false);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'AccountEntitlementTriggerUtility.createAccountEntitlementsPOCRequestSolutions ERRORS',
				saveResults
			)
			.addTag('apex');
		Logger.saveLog();

		if (System.Label.Trigger_CreateServDepSubsFlag == 'true' || Test.isRunningTest()) {
			ServerDeploymentSubTriggerUtility.createServerDeploymentSubscriptions(
				newAccountEntitlements,
				accountIdToServerDeployment,
				true
			);
		}
	}

	private static Map<Id, List<Product_Module__c>> getProductIdToProductModules(
		List<Id> productIds
	) {
		Map<Id, List<Product_Module__c>> productIdToProductModules = new Map<Id, List<Product_Module__c>>();

		for (Product_Module__c productModule : [
			SELECT Id, Module__c, Product__c
			FROM Product_Module__c
			WHERE Product__c IN :productIds
		]) {
			if (!productIdToProductModules.containsKey(productModule.Product__c)) {
				productIdToProductModules.put(productModule.Product__c, new List<Product_Module__c>());
			}
			productIdToProductModules.get(productModule.Product__c).add(productModule);
		}
		return productIdToProductModules;
	}

	private static Account_Entitlements__c buildAccountEntitlementSubscription(
		SBQQ__Subscription__c subscription,
		Product_Module__c productModule
	) {
		return new Account_Entitlements__c(
			Account__c = subscription.SBQQ__Account__c,
			Module__c = productModule.Module__c,
			Product__c = productModule.Product__c,
			Start_Date__c = subscription.SBQQ__StartDate__c,
			End_Date__c = subscription.SBQQ__EndDate__c,
			Quantity_Purchased__c = subscription.SBQQ__Quantity__c,
			Type__c = 'Subscription',
			Source_Subscription__c = subscription.Id
		);
	}

	private static Account_Entitlements__c buildAccountEntitlementNFR(NFR__c nfr, Module__c module) {
		return new Account_Entitlements__c(
			Account__c = nfr.Account__c,
			Module__c = module.Id,
			Start_Date__c = nfr.NFR_Issued_Date__c,
			End_Date__c = nfr.NFR_Expiration_Date__c,
			Quantity_Purchased__c = nfr.Number_of_Endpoints__c,
			Quantity_Allocated__c = nfr.Number_of_Endpoints__c,
			Type__c = 'NFR',
			Source_NFR__c = nfr.Id
		);
	}

	private static Account_Entitlements__c buildAccountEntitlementPOCRequestModule(
		POC_Request__c pocRequest,
		Id moduleId
	) {
		return new Account_Entitlements__c(
			Account__c = pocRequest.Account__c,
			Module__c = moduleId,
			Start_Date__c = pocRequest.Start_Date__c,
			End_Date__c = pocRequest.End_Date__c,
			Quantity_Purchased__c = pocRequest.Quantity__c,
			Quantity_Allocated__c = pocRequest.Quantity__c,
			Type__c = 'POC Request',
			Source_POC_Request__c = pocRequest.Id
		);
	}

	private static Account_Entitlements__c buildAccountEntitlementPOCRequestSolution(
		POC_Request__c pocRequest,
		Product_Module__c productModule
	) {
		return new Account_Entitlements__c(
			Account__c = pocRequest.Account__c,
			Module__c = productModule.Module__c,
			Product__c = productModule.Product__c,
			Start_Date__c = pocRequest.Start_Date__c,
			End_Date__c = pocRequest.End_Date__c,
			Quantity_Purchased__c = pocRequest.Quantity__c,
			Quantity_Allocated__c = pocRequest.Quantity__c,
			Type__c = 'POC Request',
			Source_POC_Request__c = pocRequest.Id
		);
	}
}