objects/Case_Management__c/Case_Management__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Manage settings for case management.</description>
    <label>Case Management</label>
</CustomObject>

objects/Case_Management__c/fields/rosco_case_url_prefix__c.field-meta.xml
<CustomField>
    <fullName>rosco_case_url_prefix__c</fullName>
    <label>rosco_case_url_prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Case_Management__c/fields/rosco_sfdc_dom_l__c.field-meta.xml
<CustomField>
    <fullName>rosco_sfdc_dom_l__c</fullName>
    <label>rosco_sfdc_dom_l</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

objects/Rosco_Account__c/Rosco_Account__c.object-meta.xml
<CustomObject>
    <label>rosco_account</label>
    <nameField>
        <label>slack_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>rosco_accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rosco_Account__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>rosco_accounts</relationshipLabel>
    <relationshipName>rosco_accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Rosco_Account__c/fields/case_flash__c.field-meta.xml
<CustomField>
    <fullName>case_flash__c</fullName>
    <label>case_flash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/CaseSendToEscalationSlackTest.cls
@isTest
private class CaseSendToEscalationSlackTest {
	static void CreateRecords() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(new List<String>{ 'AccountTriggerHandler', 'ContactTriggerHandler' });
	}

	static testMethod void testEscalationSlackCall() {
		Case_Management__c cmSetting = new Case_Management__c();
		cmSetting.Name = '';
		cmSetting.rosco_case_url_prefix__c = 'foo';
		cmSetting.rosco_sfdc_dom_l__c = 'foo';
		insert cmSetting;

		CreateRecords();
		Test.setMock(HttpCalloutMock.class, new mockCallout());
		/*Account accountObj = new Account(name='testAccount',
		 slack_channel_id__c='C72LD4NN5');*/
		Account accountObj = TestFactory.buildAccount('testAccount');
		accountObj.slack_channel_id__c = 'CH87S4VUJ';

		insert accountObj;
		rosco_account__c ra = new rosco_account__c(
			Name = 'customer-foo',
			account__c = accountObj.Id,
			case_flash__c = 'caseflash1'
		);
		insert ra;
		Contact contactObj = new Contact(
			Email = 'matt+testapex@mindvault.com',
			FirstName = 'Test',
			LastName = 'Apex',
			AccountId = accountObj.id
		);
		insert contactObj;
		Case caseObj = new Case(
			ContactId = contactObj.id,
			accountid = accountObj.id,
			subject = 'IGNORE:testing:matt:20180313.1009',
			Severity_Community__c = '3',
			type = 'Incident',
			Reason = 'New problem',
			Origin = 'Email',
			suppliedEmail = 'matt+testapex@mindvault.com'
		);
		insert caseObj;
		List<Case> lis = new List<Case>();
		lis.add(caseObj);
		CaseSendToEscalationSlack.sendToEscalationSlack(lis);
	}

	static testMethod void testEscalationSlackCallWithNoContact() {
		CreateRecords();
		Test.setMock(HttpCalloutMock.class, new mockCallout());
		/*Account accountObj = new Account(name='testAccount',
		 slack_channel_id__c='C72LD4NN5');*/
		Account accountObj = TestFactory.buildAccount('testAccount');
		accountObj.slack_channel_id__c = 'CH87S4VUJ';
		insert accountObj;
		Case caseObj = new Case(
			accountid = accountObj.id,
			subject = 'IGNORE:testing:matt:20180313.1009',
			Severity_Community__c = '3',
			type = 'Incident',
			Reason = 'New problem',
			Origin = 'Email',
			suppliedEmail = 'matt+testapex@mindvault.com'
		);
		insert caseObj;
		List<Case> lis = new List<Case>();
		lis.add(caseObj);
		CaseSendToEscalationSlack.sendToEscalationSlack(lis);
	}

	public class mockCallout implements HttpCalloutMock {
		public HttpResponse respond(HttpRequest request) {
			HttpResponse res = new HttpResponse();
			res.setBody('{"text":"value"}');
			res.setStatusCode(200);
			return res;
		}
	}
}