objects/Case_Management__c/Case_Management__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Manage settings for case management.</description>
    <label>Case Management</label>
</CustomObject>

objects/Case_Management__c/fields/rosco_slack_triage_channel_poland__c.field-meta.xml
<CustomField>
    <fullName>rosco_slack_triage_channel_poland__c</fullName>
    <description>rosco_slack_triage_channel_poland</description>
    <label>rosco_slack_triage_channel_poland</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TAM_Team__c/TAM_Team__c.object-meta.xml
<CustomObject>
    <label>TAM Team</label>
    <nameField>
        <label>TAM Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAM Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TAM_Team__c/fields/L2_Slack_Channel_Ids__c.field-meta.xml
<CustomField>
    <fullName>L2_Slack_Channel_Ids__c</fullName>
    <description>Slack Channel(s) that should be notified on L2 escalations (comma separated)</description>
    <inlineHelpText>The L2 Slack Channel Id is used for Case Escalations.  For example, when a L2 Escalation for this team is raised this channel (or channels) will receive a slack message.  To specify a single channel, simply type in the Slack channel Id, i.e. GCEBYKZ24, or specify multiple channels via comma separated values, i.e. GCEBYKZ24,CCC66LTRT.  You can identify a Slack Channel Id by right clicking a Slack Channel in the Slack UI &gt; Copy Link &gt; and extracting the rightmost value.</inlineHelpText>
    <label>L2 Slack Channel Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/TAM_Team__c/fields/L3_Slack_Channel_Ids__c.field-meta.xml
<CustomField>
    <fullName>L3_Slack_Channel_Ids__c</fullName>
    <description>Slack Channel(s) that should be notified on L3 escalations (comma separated)</description>
    <inlineHelpText>The L3 Slack Channel Id is used for Case Escalations.  For example, when a L2 Escalation for this team is raised this channel (or channels) will receive a slack message.  To specify a single channel, simply type in the Slack channel Id, i.e. GCEBYKZ24, or specify multiple channels via comma separated values, i.e. GCEBYKZ24,CCC66LTRT.  You can identify a Slack Channel Id by right clicking a Slack Channel in the Slack UI &gt; Copy Link &gt; and extracting the rightmost value.</inlineHelpText>
    <label>L3 Slack Channel Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/PostRefreshTest.cls
/**
 * Copyright (c) 2026 Tanium, Inc. All rights reserved.
 *
 * @Business: Test class for PostRefresh
 * @Author: Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-12775   2026-03-24    Add best practice updates
 */
@IsTest
public class PostRefreshTest {
	@TestSetup
	static void makeData() {
		System.runAs(TestUserFactory.getAdminUser()) {
			Apttus__ComplySystemProperties__c complySystemProperties = new Apttus__ComplySystemProperties__c();
			complySystemProperties.Name = 'System Properties';
			insert complySystemProperties;

			Apttus_Approval__ApprovalsSystemProperties__c approvalsSystemProperties = new Apttus_Approval__ApprovalsSystemProperties__c();
			approvalsSystemProperties.Name = 'System Properties';
			insert approvalsSystemProperties;

			Case_Management__c caseManagement = new Case_Management__c();
			insert caseManagement;

			TAM_Team__c tamTeamL2 = TestFactory.buildTAMTeam(
				'Test TAM Team L2',
				'test-slack-channel-id'
			);
			tamTeamL2.L2_Slack_Channel_Ids__c = 'test-slack-channel-id';
			TAM_Team__c tamTeamL3 = TestFactory.buildTAMTeam(
				'Test TAM Team L3',
				'test-slack-channel-id-2'
			);
			tamTeamL3.L3_Slack_Channel_Ids__c = 'test-slack-channel-id-2';
			insert new List<TAM_Team__c>{ tamTeamL2, tamTeamL3 };
		}
	}

	@IsTest
	static void testRunApexClass_WhenSandboxRefreshed_AlwaysRunApex() {
		Test.startTest();
		PostRefresh apexClass = new PostRefresh();
		Test.testSandboxPostCopyScript(
			apexClass,
			UserInfo.getOrganizationId(),
			UserInfo.getOrganizationId(),
			'sandboxName'
		);
		Test.stopTest();

		Assert.isTrue(apexClass.isRunSuccessful, 'PostRefresh should have run successfully');
		Apttus__ComplySystemProperties__c complySystemProperties = Apttus__ComplySystemProperties__c.getInstance(
			'System Properties'
		);
		Assert.areEqual(
			URL.getOrgDomainURL().toExternalForm(),
			complySystemProperties.Apttus__InstanceUrl__c,
			'Comply System Properties should have been updated'
		);

		Apttus_Approval__ApprovalsSystemProperties__c approvalsSystemProperties = Apttus_Approval__ApprovalsSystemProperties__c.getInstance(
			'System Properties'
		);
		Assert.areEqual(
			URL.getOrgDomainURL().toExternalForm(),
			approvalsSystemProperties.Apttus_Approval__InstanceUrl__c,
			'Approvals System Properties should have been updated'
		);

		Case_Management__c caseManagement = Case_Management__c.getOrgDefaults();
		Assert.areEqual(
			PostRefresh.nonProdSlackChannelId,
			caseManagement.rosco_slack_triage_channel_poland__c,
			'Case Management slack channel ids should have been updated'
		);

		TAM_Team__c tamTeamL2 = [
			SELECT Id, L2_Slack_Channel_Ids__c
			FROM TAM_Team__c
			WHERE L2_Slack_Channel_Ids__c != NULL
		];
		Assert.areEqual(
			PostRefresh.nonProdSlackChannelId,
			tamTeamL2.L2_Slack_Channel_Ids__c,
			'TAM Team slack channel ids should have been updated'
		);

		TAM_Team__c tamTeamL3 = [
			SELECT Id, L3_Slack_Channel_Ids__c
			FROM TAM_Team__c
			WHERE L3_Slack_Channel_Ids__c != NULL
		];
		Assert.areEqual(
			PostRefresh.nonProdSlackChannelId,
			tamTeamL3.L3_Slack_Channel_Ids__c,
			'TAM Team slack channel ids should have been updated'
		);
	}
}