objects/QuoteLineItem/fields/ELV_Customer_Discount__c.field-meta.xml
<CustomField>
    <fullName>ELV_Customer_Discount__c</fullName>
    <label>ADDT&apos;L DISCOUNT (%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_DistributorDiscount__c.field-meta.xml
<CustomField>
    <fullName>ELV_DistributorDiscount__c</fullName>
    <label>Distributor Discount (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_PartnerDiscount__c.field-meta.xml
<CustomField>
    <fullName>ELV_PartnerDiscount__c</fullName>
    <label>Partner Discount (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/QuoteLineItem/fields/ELV_Pricing_Refresh_Required__c.field-meta.xml
<CustomField>
    <fullName>ELV_Pricing_Refresh_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set when partner or distributor discount enrichment changes after the Line Editor has loaded. The Line Editor clears the displayed indicator on its next pricing calculation.</description>
    <inlineHelpText>Selected when partner or distributor discounts were retrieved after the Line Editor loaded. Refresh pricing to apply them.</inlineHelpText>
    <label>Refresh Required</label>
    <type>Checkbox</type>
</CustomField>

objects/QuoteLineItem/fields/Ruby__Discount__c.field-meta.xml
<CustomField>
    <fullName>Ruby__Discount__c</fullName>
    <description>The discount (in percentage) that Sales Rep applies to the quote line item. You can enter a number with or without the percent symbol. You can use up to two decimal places.</description>
    <label>Discount %</label>
    <precision>12</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

objects/QuoteLineItem/fields/Ruby__LineType__c.field-meta.xml
<CustomField>
    <fullName>Ruby__LineType__c</fullName>
    <defaultValue>&apos;LineItem&apos;</defaultValue>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LineItem</fullName>
                <default>true</default>
                <label>Product</label>
            </value>
            <value>
                <fullName>RampItem</fullName>
                <label>Ramp Item</label>
            </value>
            <value>
                <fullName>SplitItem</fullName>
                <label>Split Line</label>
            </value>
            <value>
                <fullName>SummaryItem</fullName>
                <label>Summary Item</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/ELV_QuoteLinePricingRefreshTest.cls
@IsTest
private class ELV_QuoteLinePricingRefreshTest {
	@IsTest
	static void reconcilePricingRefreshRequiredClearsWhenDistributorDiscountIsNullButDiscountIsCurrent() {
		QuoteLineItem line = new QuoteLineItem(
			Ruby__LineType__c = 'LineItem',
			ELV_Customer_Discount__c = -50.4043127111376,
			ELV_PartnerDiscount__c = 60,
			ELV_DistributorDiscount__c = null,
			Ruby__Discount__c = 39.83827,
			ELV_Pricing_Refresh_Required__c = true
		);

		ELV_QuoteLineTriggerUtility.reconcilePricingRefreshRequired(
			new List<QuoteLineItem>{ line }
		);

		Assert.isFalse(line.ELV_Pricing_Refresh_Required__c);
	}

	@IsTest
	static void reconcilePricingRefreshRequiredSetsTrueWhenCompoundedDiscountIsStale() {
		QuoteLineItem line = new QuoteLineItem(
			Ruby__LineType__c = 'LineItem',
			ELV_Customer_Discount__c = -50.4043127111376,
			ELV_PartnerDiscount__c = 60,
			ELV_DistributorDiscount__c = null,
			Ruby__Discount__c = 60,
			ELV_Pricing_Refresh_Required__c = false
		);

		ELV_QuoteLineTriggerUtility.reconcilePricingRefreshRequired(
			new List<QuoteLineItem>{ line }
		);

		Assert.isTrue(line.ELV_Pricing_Refresh_Required__c);
	}

	@IsTest
	static void customCalculationClearTreatsNullDistributorDiscountAsSettledWhenDiscountIsCurrent() {
		QuoteLineItem line = new QuoteLineItem(
			ELV_Customer_Discount__c = -50.4043127111376,
			ELV_PartnerDiscount__c = 60,
			ELV_DistributorDiscount__c = null,
			Ruby__Discount__c = 39.83827
		);

		Assert.isFalse(ELV_CustomCalculationClearQueueable.isUnsettled(line));
	}

	@IsTest
	static void customCalculationClearTreatsStaleCompoundedDiscountAsUnsettled() {
		QuoteLineItem line = new QuoteLineItem(
			ELV_Customer_Discount__c = -50.4043127111376,
			ELV_PartnerDiscount__c = 60,
			ELV_DistributorDiscount__c = null,
			Ruby__Discount__c = 60
		);

		Assert.isTrue(ELV_CustomCalculationClearQueueable.isUnsettled(line));
	}
}