objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Registration__c/fields/or_Expiry_Date_Extension_Opp_Reg__c.field-meta.xml
<CustomField>
    <fullName>or_Expiry_Date_Extension_Opp_Reg__c</fullName>
    <description>Expiry Date for extensions</description>
    <inlineHelpText>Expiry Date for extensions</inlineHelpText>
    <label>Expiry Date - Extension</label>
    <type>Date</type>
</CustomField>

objects/Deal_Registration__c/fields/or_Expiry_Date_New_Opp_Reg__c.field-meta.xml
<CustomField>
    <fullName>or_Expiry_Date_New_Opp_Reg__c</fullName>
    <description>Expiry Date for new Opp Reg Approval.
INC0161411- FLS changed..</description>
    <inlineHelpText>Expiry Date for new Deal approval</inlineHelpText>
    <label>Expiry Date - New Deal Reg</label>
    <type>Date</type>
</CustomField>

objects/Deal_Registration__c/fields/or_Opp_Reg_Status__c.field-meta.xml
<CustomField>
    <fullName>or_Opp_Reg_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Extension Pending</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/BatchUpdateLeadExpiryDateTest.cls
/**
 * Test class for BatchUpdateLeadExpiryDate
 * Modified  ModifiedDate   Description
 * SS-9000   2024-09-23     Opp Reg to Deal Reg Migration
 */
@IsTest
private class BatchUpdateLeadExpiryDateTest {
	@TestSetup
	static void makeData() {
		TriggerHandler.bypass(
			new List<String>{ 'DealRegistrationTriggerHandler', 'UserTriggerHandler' }
		);
		System.runAs(TestUserFactory.getAdminUser()) {
			Deal_Registration__c deal1 = TestFactory.buildDealReg(
				'Test FName1',
				'TestLname1',
				'test1@test.com',
				'My Company1'
			);
			deal1.or_Opp_Reg_Status__c = 'Approved';
			deal1.or_Expiry_Date_Extension_Opp_Reg__c = System.today();
			deal1.or_Expiry_Date_New_Opp_Reg__c = System.today().addDays(-30);

			Deal_Registration__c deal2 = TestFactory.buildDealReg(
				'Test FName2',
				'TestLname2',
				'test2@test.com',
				'My Company2'
			);
			deal2.or_Opp_Reg_Status__c = 'Approved';
			deal2.or_Expiry_Date_Extension_Opp_Reg__c = System.today().addDays(10);
			deal2.or_Expiry_Date_New_Opp_Reg__c = System.today().addDays(10);
			insert new List<Deal_Registration__c>{ deal1, deal2 };
		}
	}

	@IsTest
	static void testBatchUpdate() {
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			Database.executeBatch(new BatchUpdateLeadExpiryDate());
			Test.stopTest();
			Deal_Registration__c deal = [
				SELECT Id, or_Opp_Reg_Status__c
				FROM Deal_Registration__c
				WHERE FirstName__c = 'Test FName1'
				LIMIT 1
			];
			System.assertEquals('Expired', deal.or_Opp_Reg_Status__c);
		}
	}

	@IsTest
	static void testBatchScheduler() {
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			BatchUpdateLeadExpiryDate sh1 = new BatchUpdateLeadExpiryDate();

			String sch = '0 0 23 * * ?';
			String jobid = System.schedule('Test BatchUpdateLeadExpiryDate', sch, sh1);
			sh1.execute(null);

			Test.stopTest();
			Deal_Registration__c deal = [
				SELECT Id, or_Opp_Reg_Status__c
				FROM Deal_Registration__c
				WHERE FirstName__c = 'Test FName1'
				LIMIT 1
			];
			System.assertEquals('Expired', deal.or_Opp_Reg_Status__c);
		}
	}
}