objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Registration__c/fields/Mapped_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Map an existing opportunity to this Deal, but first check to ensure the opportunity does not already have an active Deal</inlineHelpText>
    <label>Mapped Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Registration</relationshipLabel>
    <relationshipName>Opportunity_DealReg</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Deal_Registration__c/fields/or_Create_Opportunity_upon_Approval__c.field-meta.xml
<CustomField>
    <fullName>or_Create_Opportunity_upon_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If no opportunity exists, check this option to auto-create an opportunity upon Deal Approval</inlineHelpText>
    <label>Create Opportunity upon Approval?</label>
    <type>Checkbox</type>
</CustomField>

objects/Deal_Registration__c/fields/or_New_Opp_Reg__c.field-meta.xml
<CustomField>
    <fullName>or_New_Opp_Reg__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Value is selected at the time a new opp reg is created, and is updated to unselected when a new opp reg approval is approved or rejected.  System will use this flag in addition to other filters (extension count, opp reg status) to determine new or extension approval process when user submits approval.</description>
    <inlineHelpText>Value is selected at the time a new Deal is created, and is updated to unselected when a new Deal approval is approved or rejected.  System will use this flag in addition to other filters (extension count,status) to determine new or extension</inlineHelpText>
    <label>New Deal?</label>
    <type>Checkbox</type>
</CustomField>

objects/Deal_Registration__c/fields/or_Opp_Reg_Status__c.field-meta.xml
<CustomField>
    <fullName>or_Opp_Reg_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Extension Pending</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Deal_Registration__c/fields/or_Opportunity_Registration__c.field-meta.xml
<CustomField>
    <fullName>or_Opportunity_Registration__c</fullName>
    <description>Refer to the Opp Reg Policy Guide for further details on Opp Reg type requirements</description>
    <inlineHelpText>Refer to the Policy Guide for further details on Type requirements</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Registration</valueSetName>
    </valueSet>
</CustomField>

classes/DealRegistrationTriggerHandlerTest.cls
/**
 * @Business: Test class for the DealRegistrationTriggerHandler class
 * @Date: 2024-09-13
 * @Author: Tanium Dev Team
 * Modified  ModifiedDate   Description
 * SS-8999   2024-09-12     Initial development - Opp Reg to Deal Reg Migration
 */
@IsTest
private class DealRegistrationTriggerHandlerTest {
	@TestSetup
	static void makeData() {
		System.runAs(TestUserFactory.getAdminUser()) {
			Deal_Registration__c deal = TestFactory.buildDealReg(
				'First',
				'Last',
				'firstlast@test.com',
				'Test Company'
			);
			deal.Mapped_Opportunity__c = null;
			deal.or_New_Opp_Reg__c = true;
			deal.or_Create_Opportunity_upon_Approval__c = true;
			deal.or_Opportunity_Registration__c = 'Partner Sourced';
			deal.or_Opp_Reg_Status__c = 'Pending';
			insert deal;
		}
	}

	@IsTest
	static void testDealRegistrationHandler() {
		Deal_Registration__c[] deals = [SELECT Id FROM Deal_Registration__c];
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();

			update deals;
			delete deals;
			Test.stopTest();
		}
	}
}