objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Registration__c/fields/or_Opp_Reg_Status__c.field-meta.xml
<CustomField>
    <fullName>or_Opp_Reg_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Extension Pending</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Deal_Registration__c/fields/or_Opportunity_Registration_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>or_Opportunity_Registration_Expiry_Date__c</fullName>
    <formula>IF( NOT(ISNULL(or_Expiry_Date_New_Opp_Reg__c )) &amp;&amp; NOT(ISNULL(or_Expiry_Date_Extension_Opp_Reg__c)),
IF (or_Expiry_Date_Extension_Opp_Reg__c &lt; or_Expiry_Date_New_Opp_Reg__c, or_Expiry_Date_New_Opp_Reg__c, or_Expiry_Date_Extension_Opp_Reg__c
),
IF(NOT(ISNULL(or_Expiry_Date_New_Opp_Reg__c )),or_Expiry_Date_New_Opp_Reg__c ,
IF(NOT(ISNULL(or_Expiry_Date_Extension_Opp_Reg__c)),or_Expiry_Date_Extension_Opp_Reg__c,null)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

objects/Deal_Registration__c/fields/PreExpiry_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>PreExpiry_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>INC0119131 Field is set to TRUE upon pre-expiry (30 days), and reset to FALSE upon opp reg extension approval. For triggering pre-expiry email notification.</description>
    <inlineHelpText>Field is set to &quot;Selected&quot; upon pre-expiry (30 days), and deselected upon extension approval. For triggering pre-expiry email notification.</inlineHelpText>
    <label>PreExpiry Email Sent?</label>
    <type>Checkbox</type>
</CustomField>

classes/BatchUpdateLeadExpiryDate.cls
/**
 * @Business: "Opp Reg Status" updating to Expired upon expiration date.
 * @Date: 2021-02-25
 * @Author: Anurupa Busi
 * @Request: INC0119131
 * Modified    ModifiedDate   Description
 * INC0119131   2021-02-25     "Opp Reg Status" updating to Expired upon expiration date.
 * SS-9000      2024-09-23     Opp Reg to Deal Reg Migration
 */
public class BatchUpdateLeadExpiryDate implements Database.Batchable<sObject>, Schedulable {
	public Database.QueryLocator start(Database.BatchableContext bc) {
		Date dt = system.today().addDays(10);
		String query =
			'SELECT Id, ' +
			'or_Opportunity_Registration_Expiry_Date__c, ' +
			'PreExpiry_Email_Sent__c ' +
			'FROM Deal_Registration__c ' +
			'WHERE or_Opp_Reg_Status__c = \'Approved\' ' +
			'AND (or_Opportunity_Registration_Expiry_Date__c = :dt ' +
			'OR or_Opportunity_Registration_Expiry_Date__c = TODAY)';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext bc, List<Deal_Registration__c> deals) {
		for (Deal_Registration__c deal : deals) {
			if (System.today() == deal.or_Opportunity_Registration_Expiry_Date__c) {
				deal.or_Opp_Reg_Status__c = 'Expired';
			} else if (
				System.today().addDays(10) == deal.or_Opportunity_Registration_Expiry_Date__c &&
				deal.PreExpiry_Email_Sent__c != true
			) {
				deal.PreExpiry_Email_Sent__c = true;
			}
		}
		Database.SaveResult[] saveResults = Database.update(deals, false);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'BatchUpdateLeadExpiryDate.execute ERRORS',
				saveResults
			)
			.addTag('apex')
			.addTag('batch');
		Logger.saveLog();
	}

	public void finish(Database.BatchableContext bc) {
	}

	// Scheduler Execute Method
	public void execute(SchedulableContext ctx) {
		BatchUpdateLeadExpiryDate batch = new BatchUpdateLeadExpiryDate();
		Database.executeBatch(batch);
	}
}