objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Address__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Address__c/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <label>Attention</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire, Saint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Address__c/fields/Default_Billing__c.field-meta.xml
<CustomField>
    <fullName>Default_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Billing</label>
    <type>Checkbox</type>
</CustomField>

objects/Address__c/fields/Default_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Default_Shipping__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Shipping</label>
    <type>Checkbox</type>
</CustomField>

objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Armed Forces Americas</fullName>
            </value>
            <value>
                <fullName>Armed Forces Europe</fullName>
            </value>
            <value>
                <fullName>Armed Forces Pacific</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Deal_Registration__c/Deal_Registration__c.object-meta.xml
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deal_Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account is required to Submit for Approval</inlineHelpText>
    <label>End Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registration (Account)</relationshipLabel>
    <relationshipName>DealRegistration</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Deal_Registration__c/fields/Mapped_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Map an existing opportunity to this Deal, but first check to ensure the opportunity does not already have an active Deal</inlineHelpText>
    <label>Mapped Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Registration</relationshipLabel>
    <relationshipName>Opportunity_DealReg</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Deal_Registration__c/fields/or_Create_Opportunity_upon_Approval__c.field-meta.xml
<CustomField>
    <fullName>or_Create_Opportunity_upon_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If no opportunity exists, check this option to auto-create an opportunity upon Deal Approval</inlineHelpText>
    <label>Create Opportunity upon Approval?</label>
    <type>Checkbox</type>
</CustomField>

objects/Deal_Registration__c/fields/or_New_Opp_Reg__c.field-meta.xml
<CustomField>
    <fullName>or_New_Opp_Reg__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Value is selected at the time a new opp reg is created, and is updated to unselected when a new opp reg approval is approved or rejected.  System will use this flag in addition to other filters (extension count, opp reg status) to determine new or extension approval process when user submits approval.</description>
    <inlineHelpText>Value is selected at the time a new Deal is created, and is updated to unselected when a new Deal approval is approved or rejected.  System will use this flag in addition to other filters (extension count,status) to determine new or extension</inlineHelpText>
    <label>New Deal?</label>
    <type>Checkbox</type>
</CustomField>

objects/Deal_Registration__c/fields/or_Opp_Reg_Status__c.field-meta.xml
<CustomField>
    <fullName>or_Opp_Reg_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Extension Pending</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Deal_Registration__c/fields/or_Opportunity_Registration__c.field-meta.xml
<CustomField>
    <fullName>or_Opportunity_Registration__c</fullName>
    <description>Refer to the Opp Reg Policy Guide for further details on Opp Reg type requirements</description>
    <inlineHelpText>Refer to the Policy Guide for further details on Type requirements</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Registration</valueSetName>
    </valueSet>
</CustomField>

objects/Deal_Registration__c/fields/Zift_Lead_Partner__c.field-meta.xml
<CustomField>
    <fullName>Zift_Lead_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the Partner Account associated with the Deal. Created as a part of the Zift integration project. Jira ticket SS-8969</description>
    <inlineHelpText>Indicates the Partner Account associated with the Deal</inlineHelpText>
    <label>Zift Lead Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Registration (Zift Lead Partner)</relationshipLabel>
    <relationshipName>Deal_Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote_Request__c/Quote_Request__c.object-meta.xml
<CustomObject>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{000000}</displayFormat>
        <label>Quote Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Request__c/fields/Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Deal_Registration__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deal Registration for which this Quote Request was created. Jira ticket SS-11057.</description>
    <inlineHelpText>Select the Deal to which this Quote Request should be associated. Please note that the Deal must be approved and must have a mapped opportunity.</inlineHelpText>
    <label>Deal Registration</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Deal_Registration__c.Mapped_Opportunity__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Deal_Registration__c.or_Opp_Reg_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Deal_Registration__c</referenceTo>
    <relationshipLabel>Quote Requests</relationshipLabel>
    <relationshipName>Quote_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/Quote_Request__c/fields/Multi_Tier_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Multi_Tier_Transaction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multi-Tier Transaction?</label>
    <type>Checkbox</type>
</CustomField>

objects/Quote_Request__c/fields/Submitter_Role__c.field-meta.xml
<CustomField>
    <fullName>Submitter_Role__c</fullName>
    <label>Submitter Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote_Request__c/fields/Subscription_Term__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Term__c</fullName>
    <defaultValue>(12)</defaultValue>
    <description>The subscription term, in months, for this request. Jira ticket SS-11057.</description>
    <inlineHelpText>Please enter the subscrption term, in months, for this request.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/QuoteRequestControllerTest.cls
/**
 * @Business: Test class for QuoteRequestController
 * @Authors: Tanium Dev team
 * RequestId  ModifiedDate  Description
 * SS-11140   2025-07-10    Created the test class
 * SS-11835   2025-10-08    Removed test methods linked to methods getDistributorIds, getDistributorPicklistValues
 * SS-12279   2025-12-18    Added test method testGetDeploymentProviderPicklistValues_Always_ReturnDeploymentProviderPicklistValues
 */
@IsTest
private class QuoteRequestControllerTest {
	@TestSetup
	static void makeData() {
		TriggerHandler.bypass(
			new List<String>{ 'AccountTriggerHandler', 'DealRegistrationTriggerHandler' }
		);

		System.runAs(TestUserFactory.getAdminUser()) {
			Account distributorAccount = TestFactory.buildAccount('Distributor Account');
			distributorAccount.Type = 'Distributor';
			distributorAccount.RecordTypeId = Utility.getRecordTypeIdByAPIName('Account', 'Partner');
			distributorAccount.Cloud_Deployment_Verified__c = true;
			distributorAccount.On_Prem_Deployment_Verified__c = true;
			insert distributorAccount;

			Account resellerAccount = TestFactory.buildAccount('Reseller Account');
			resellerAccount.Type = 'Reseller';
			resellerAccount.RecordTypeId = Utility.getRecordTypeIdByAPIName('Account', 'Partner');
			insert resellerAccount;

			Address__c billToAddress = new Address__c(Account__c = resellerAccount.Id);
			billToAddress.Attention__c = 'Billing Dept';
			billToAddress.Address_1__c = '123 Street';
			billToAddress.City__c = 'Miami';
			billToAddress.State__c = 'Florida';
			billToAddress.Country__c = 'United States';
			billToAddress.Zip_Code__c = '33145';
			billToAddress.Default_Billing__c = true;
			insert billToAddress;

			Address__c shipToAddress = new Address__c(Account__c = resellerAccount.Id);
			shipToAddress.Attention__c = 'Shipping Dept';
			shipToAddress.Address_1__c = '123 Street';
			shipToAddress.City__c = 'Miami';
			shipToAddress.State__c = 'Florida';
			shipToAddress.Country__c = 'United States';
			shipToAddress.Zip_Code__c = '33145';
			shipToAddress.Default_Shipping__c = true;
			insert shipToAddress;

			Opportunity opp = TestFactory.buildOpportunity(
				'Reseller Opportunity',
				System.today().addDays(120),
				'New',
				resellerAccount.Id
			);
			insert opp;

			Deal_Registration__c dealRegistration = TestFactory.buildDealReg(
				'First',
				'Last',
				'first.last@testcompany.io',
				'Test Company'
			);
			dealRegistration.Mapped_Opportunity__c = opp.Id;
			dealRegistration.or_New_Opp_Reg__c = true;
			dealRegistration.or_Create_Opportunity_upon_Approval__c = true;
			dealRegistration.or_Opportunity_Registration__c = 'Partner Sourced';
			dealRegistration.or_Opp_Reg_Status__c = 'Approved';
			insert dealRegistration;

			Quote_Request__c quoteRequest = new Quote_Request__c();
			quoteRequest.Deal_Registration__c = dealRegistration.Id;
			quoteRequest.Submitter_Role__c = 'Distributor';
			quoteRequest.Multi_Tier_Transaction__c = false;
			quoteRequest.Subscription_Term__c = 12;
			quoteRequest.Partner_Email__c = 'partner@email.com';
			insert quoteRequest;
		}
	}

	@IsTest
	static void testIsValidDealRegId_WhenValidDealregId_ReturnsTrue() {
		Deal_Registration__c dealRegistration = [SELECT Id FROM Deal_Registration__c LIMIT 1];
		Boolean validDealRegId;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			validDealRegId = QuoteRequestController.isValidDealRegId(dealRegistration.Id);
			Test.stopTest();
		}

		Assert.isTrue(validDealRegId == true);
	}

	@IsTest
	static void testIsValidAccountId_WhenInvalidAccountId_ReturnsFalse() {
		Boolean validAccountId;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			validAccountId = QuoteRequestController.isValidAccountId(UserInfo.getUserId());
			Test.stopTest();
		}

		Assert.isTrue(validAccountId == false);
	}

	@IsTest
	static void testGetDealReg_WhenValidDealregId_ReturnDealRegistration() {
		Id dealRegistrationId = [SELECT Id FROM Deal_Registration__c LIMIT 1].Id;
		Deal_Registration__c dealRegistration = null;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			dealRegistration = QuoteRequestController.getDealReg(dealRegistrationId);
			Test.stopTest();
		}

		Assert.isTrue(dealRegistration != null);
	}

	@IsTest
	static void testGetUserAccountInfo_WhenValidAccountId_ReturnUserAccountInformation() {
		Account resellerAccount = [SELECT Id FROM Account WHERE Type = 'Reseller' LIMIT 1];
		QuoteRequestController.UserAccountInfo userAccountInfo = null;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			userAccountInfo = QuoteRequestController.getUserAccountInfo(resellerAccount.Id);
			Test.stopTest();
		}

		Assert.isTrue(userAccountInfo != null);
	}

	@IsTest
	static void testSubmitInsertQuoteRequestPlatformEvent_Always_ReturnSuccess() {
		Deal_Registration__c dealRegistration = [
			SELECT Id, Zift_Lead_Partner__c, Account__c
			FROM Deal_Registration__c
			LIMIT 1
		];
		EnhancedReturnType rt;
		QuoteRequestController.QuoteRequestWrapper quoteRequestWrapper = new QuoteRequestController.QuoteRequestWrapper();
		quoteRequestWrapper.dealRegId = dealRegistration.Id;
		quoteRequestWrapper.partnerId = dealRegistration.Zift_Lead_Partner__c;
		quoteRequestWrapper.customerId = dealRegistration.Account__c;
		quoteRequestWrapper.multiTierTransaction = true;
		quoteRequestWrapper.subscriptionTerm = 12;
		quoteRequestWrapper.partnerContactEmail = 'partner.contact@partnercorp.io';
		quoteRequestWrapper.distributorEmail = 'distruibutor@partnercorp.io';
		quoteRequestWrapper.billingStreet = '123 Billing St';
		quoteRequestWrapper.billingCity = 'Billing City';
		quoteRequestWrapper.billingProvince = 'Billing Province';
		quoteRequestWrapper.billingZipCode = '12345';
		quoteRequestWrapper.billingCountry = 'United States';
		quoteRequestWrapper.shippingStreet = '123 Shipping St';
		quoteRequestWrapper.shippingCity = 'Shipping City';
		quoteRequestWrapper.shippingProvince = 'Shipping Province';
		quoteRequestWrapper.shippingZipCode = '54321';
		quoteRequestWrapper.shippingCountry = 'United States';

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			rt = QuoteRequestController.submitInsertQuoteRequestPlatformEvent(
				JSON.serialize(quoteRequestWrapper)
			);
			Test.stopTest();
		}

		Assert.isTrue(rt.retResult);
	}

	@IsTest
	static void testSubmitUpdateQuoteRequestPlatformEvent_Always_ReturnSuccess() {
		Quote_Request__c quoteRequest = [SELECT Id FROM Quote_Request__c LIMIT 1];
		EnhancedReturnType rt;

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			rt = QuoteRequestController.submitUpdateQuoteRequestPlatformEvent(quoteRequest.Id);
			Test.stopTest();
		}

		Assert.isTrue(rt.retResult);
	}

	@IsTest
	static void testSubmitQuoteRequestProductPlatformEvent_Always_ReturnSuccess() {
		Deal_Registration__c dealRegistration = [
			SELECT Id, Zift_Lead_Partner__c, Account__c
			FROM Deal_Registration__c
			LIMIT 1
		];
		EnhancedReturnType rt;
		List<QuoteRequestController.QuoteRequestProductWrapper> quoteRequestProductsWrapper = new List<QuoteRequestController.QuoteRequestProductWrapper>();
		QuoteRequestController.QuoteRequestProductWrapper quoteRequestProductWrapper = new QuoteRequestController.QuoteRequestProductWrapper();
		quoteRequestProductWrapper.dealRegId = dealRegistration.Id;
		quoteRequestProductWrapper.productId = null;
		quoteRequestProductWrapper.quantity = 500;
		quoteRequestProductWrapper.subscriptionTerm = 12;
		quoteRequestProductsWrapper.add(quoteRequestProductWrapper);
		quoteRequestProductWrapper = new QuoteRequestController.QuoteRequestProductWrapper();
		quoteRequestProductWrapper.dealRegId = dealRegistration.Id;
		quoteRequestProductWrapper.productId = null;
		quoteRequestProductWrapper.quantity = 500;
		quoteRequestProductWrapper.subscriptionTerm = 12;
		quoteRequestProductsWrapper.add(quoteRequestProductWrapper);

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			rt = QuoteRequestController.submitQuoteRequestProductPlatformEvent(
				JSON.serialize(quoteRequestProductsWrapper)
			);
			Test.stopTest();
		}

		Assert.isTrue(rt.retResult);
	}

	@IsTest
	static void testGetQuoteRequestId_WhenInvalidDealRegId_ReturnNull() {
		Id quoteRequestId;
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			quoteRequestId = QuoteRequestController.getQuoteRequestId(UserInfo.getUserId());
			Test.stopTest();
		}
		Assert.isTrue(quoteRequestId == null);
	}

	@IsTest
	static void testGetQuoteRequestProductsCount_WhenNoProducts_ReturnZero() {
		Integer quoteRequestProductsCount;
		Quote_Request__c quoteRequest = [SELECT Id FROM Quote_Request__c LIMIT 1];
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			quoteRequestProductsCount = QuoteRequestController.getQuoteRequestProductsCount(
				quoteRequest.Id
			);
			Test.stopTest();
		}
		Assert.isTrue(quoteRequestProductsCount == 0);
	}

	@IsTest
	static void testGetExistingQuoteRequests_WhenOneExistingQuoteRequest_ReturnOneRecord() {
		Deal_Registration__c dealRegistration = [
			SELECT Id
			FROM Deal_Registration__c
			LIMIT 1
		];
		Quote_Request__c[] quoteRequests;
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			quoteRequests = QuoteRequestController.getExistingQuoteRequests(dealRegistration.Id);
			Test.stopTest();
		}
		Assert.isTrue(quoteRequests.size() == 1);
	}

	@IsTest
	static void testGetDeploymentProviderPicklistValues_Always_ReturnDeploymentProviderPicklistValues() {
		List<Map<String, String>> deploymentProviderPicklistValues;
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			deploymentProviderPicklistValues = QuoteRequestController.getDeploymentProviderPicklistValues();
			Test.stopTest();
		}
		Assert.isFalse(deploymentProviderPicklistValues.isEmpty());
	}
}