objects/TAM_Team__c/TAM_Team__c.object-meta.xml
<CustomObject>
    <label>TAM Team</label>
    <nameField>
        <label>TAM Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAM Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TAM_Team__c/fields/Specialty_Group__c.field-meta.xml
<CustomField>
    <fullName>Specialty_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Support Specialty Group is an umbrella group that contains individual SME teams.</description>
    <label>Specialty Group</label>
    <referenceTo>TAM_Team__c</referenceTo>
    <relationshipLabel>TAM Teams</relationshipLabel>
    <relationshipName>TAM_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TAM_Team__c/recordTypes/Escalation_SME.recordType-meta.xml
<RecordType>
    <fullName>Escalation_SME</fullName>
    <active>true</active>
    <label>Escalation SME</label>
</RecordType>

objects/TAM_Team_Member__c/TAM_Team_Member__c.object-meta.xml
<CustomObject>
    <label>TAM Team Member</label>
    <nameField>
        <label>TAM Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAM Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TAM_Team_Member__c/fields/Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Responsibility__c</fullName>
    <label>Responsibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TAM</fullName>
            </value>
            <value>
                <fullName>OTAM</fullName>
            </value>
            <value>
                <fullName>Primary TAM</fullName>
            </value>
            <value>
                <fullName>Secondary TAM</fullName>
            </value>
            <value>
                <fullName>TAM Architect</fullName>
            </value>
            <value>
                <fullName>CSM</fullName>
            </value>
            <value>
                <fullName>SME Lead</fullName>
            </value>
            <value>
                <fullName>SME Lead (Secondary)</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Pod Lead</fullName>
            </value>
            <value>
                <fullName>Support Enabled</fullName>
            </value>
            <value>
                <fullName>Support Candidate</fullName>
            </value>
            <value>
                <fullName>Escalation Engineer</fullName>
            </value>
            <value>
                <fullName>Principal Escalation Engineer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TAM_Team_Member__c/fields/Slack_Name__c.field-meta.xml
<CustomField>
    <fullName>Slack_Name__c</fullName>
    <label>Slack Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/TAM_Team_Member__c/fields/TAM__c.field-meta.xml
<CustomField>
    <fullName>TAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TAM_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TAM_Team_Member__c/fields/TAM_Team__c.field-meta.xml
<CustomField>
    <fullName>TAM_Team__c</fullName>
    <label>TAM Team</label>
    <referenceTo>TAM_Team__c</referenceTo>
    <relationshipLabel>TAM Team Members</relationshipLabel>
    <relationshipName>TAM_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/TAM_Team_Member__c/recordTypes/Escalation_SME.recordType-meta.xml
<RecordType>
    <fullName>Escalation_SME</fullName>
    <active>true</active>
    <label>Escalation SME</label>
</RecordType>

classes/TAMTeamMemberTriggerHandlerTest.cls
@isTest
public with sharing class TAMTeamMemberTriggerHandlerTest {
	@isTest(SeeAllData=false)
	static void test1() {
		Id profileId = [SELECT Id FROM Profile WHERE Name = 'Tanium System Administrator'].Id;

		User userObj = new User(
			Email = 'roscoapextest@roscolab.com',
			FirstName = 'Test',
			LastName = 'ApexUser',
			Username = 'roscoapextest@roscolab.com',
			Alias = 'xafds',
			CommunityNickname = 'asdfsaafd3',
			TimeZoneSidKey = 'America/Los_Angeles',
			LocaleSidKey = 'en_US',
			EmailEncodingKey = 'ISO-8859-1',
			ProfileId = profileId,
			LanguageLocaleKey = 'en_US'
		);
		insert userObj;

		String teamSMETypeId = Utility.getRecordTypeIdByAPIName('TAM_Team__c', 'Escalation_SME');
		TAM_Team__c smeTeam1 = new TAM_Team__c(
			Name = 'SME-Patch',
			recordTypeId = teamSMETypeId,
			Specialty_Group__c = null
		);
		insert smeTeam1;

		String memberSMETypeId = Utility.getRecordTypeIdByAPIName(
			'TAM_Team_Member__c',
			'Escalation_SME'
		);
		TAM_Team_Member__c smeMember = new TAM_Team_Member__c(
			recordTypeId = memberSMETypeId,
			Responsibility__c = 'Support Enabled',
			Slack_Name__c = 'foo.bar',
			TAM_Team__c = smeTeam1.Id,
			TAM__c = userObj.Id
		);
		insert smeMember;

		System.runAs(TestUserFactory.getAdminUser()) {
			Account accountObj = TestFactory.buildAccount('roscoapextestingd');
			accountObj.slack_channel_id__c = 'TESTCASE';
			insert accountObj;

			Contact contactObj = new Contact(
				Email = 'roscoapextest@tanium.com',
				FirstName = 'Test',
				LastName = 'Apex',
				AccountId = null
			);
			insert contactObj;

			String recordTypeId = RoscoUtility.getRecordTypeIdByAPIName('Case', 'Support');

			Case caseObj = new Case(
				ContactId = contactObj.id,
				accountid = accountObj.id,
				ownerid = userObj.id,
				subject = 'ROSCOTESTCASE',
				Severity_Community__c = '3',
				type = 'Incident',
				Reason = 'New problem',
				Origin = 'Email',
				suppliedEmail = '99@outlook.com',
				LatestPublicCommentHTML__c = '<html>hello</html>',
				Component__c = 'Other',
				RecordTypeId = recordTypeId,
				SME_OwnerId__c = userObj.Id,
				status = 'In Progress - Troubleshooting'
			);
			insert caseObj;

			TAM_Team_Member__c member = [SELECT Id FROM TAM_Team_Member__c WHERE Id = :smeMember.Id];
			delete member;
		}

	}
}