objects/Server_Deployment__c/Server_Deployment__c.object-meta.xml
<CustomObject>
    <description>The Server Deployment Object tracks important technical characteristics about a Production, Test, QA, or Evaluation deployment to provide the support team background information when responding to requests for assistance as well as to gather metrics for Product Management to understand typical configuration and usage.  The object includes two additional Objects--the Client and Zone Server.

2014 | JR</description>
    <label>Server Deployment</label>
    <nameField>
        <label>Instance/Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Server_Deployment__c/fields/First_Platform_Login__c.field-meta.xml
<CustomField>
    <fullName>First_Platform_Login__c</fullName>
    <description>DET-173 Telemetry fields. These values originate from the User Analytics platform, are ingested into Snowflake and pushed to Salesforce via Workato.</description>
    <inlineHelpText>The first time the customer logged into the Tanium Cloud platform as measured by the User Analytics tool for Tanium Cloud.</inlineHelpText>
    <label>First Platform Login</label>
    <type>Date</type>
</CustomField>

objects/Server_Deployment__c/fields/Last_Platform_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Platform_Login__c</fullName>
    <description>DET-173 Telemetry fields. These values originate from the User Analytics platform, are ingested into Snowflake and pushed to Salesforce via Workato.</description>
    <inlineHelpText>The last time the customer logged into the Tanium Cloud platform as measured by the User Analytics tool for Tanium Cloud.</inlineHelpText>
    <label>Last Platform Login</label>
    <type>Date</type>
</CustomField>

objects/Server_Deployment__c/fields/Last_Refresh_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Refresh_Date__c</fullName>
    <description>The date that the last usage data was pulled from the User Analytics platform for Tanium Cloud customers.</description>
    <inlineHelpText>The date that the last usage data was pulled from the User Analytics platform for Tanium Cloud customers.</inlineHelpText>
    <label>Last Refresh Date</label>
    <type>Date</type>
</CustomField>

objects/Server_Deployment__c/fields/Monthly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Active_Users__c</fullName>
    <description>DET-173 Telemetry fields. These values originate from the User Analytics platform, are ingested into Snowflake and pushed to Salesforce via Workato.</description>
    <inlineHelpText>The number of monthly active users logged into the Tanium Cloud platform as measured by the User Analytics tool for Tanium Cloud.</inlineHelpText>
    <label>Monthly Active Users</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Server_Deployment__c/fields/Seats_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Seats_Deployed__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Any time you interact with a customer, note the number of computers registered within the last 30 days as reported from the Console&apos;s &quot;Administration-&gt;System Status&quot; tab and enter that value in this field.</inlineHelpText>
    <label>Seats Deployed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Server_Deployment__c/fields/Staging_Record__c.field-meta.xml
<CustomField>
    <fullName>Staging_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is a link to the staging record that was used to create and/or update this Server Deployment. You can use this link to see the payload of the update record.</inlineHelpText>
    <label>Staging Record</label>
    <referenceTo>STG_Server_Deployment__c</referenceTo>
    <relationshipLabel>Server Deployments</relationshipLabel>
    <relationshipName>Server_Deployments</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Server_Deployment__c/fields/Weekly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Active_Users__c</fullName>
    <description>DET-173 Telemetry fields. These values originate from the User Analytics platform, are ingested into Snowflake and pushed to Salesforce via Workato.</description>
    <inlineHelpText>The number of weekly active users logged into the Tanium Cloud platform as measured by the User Analytics tool for Tanium Cloud.</inlineHelpText>
    <label>Weekly Active Users</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/STG_Server_Deployment__c/STG_Server_Deployment__c.object-meta.xml
<CustomObject>
    <description>This table will be used to stage SERVER DEPLOYMENT data that is migrated from Snowflake into Salesforce. The object will contain multiple fields. Flows or Apex batches will be used to pick the data up from the Staging table and update the relevant Salesforce data.</description>
    <label>STG Server Deployment</label>
    <nameField>
        <displayFormat>STGSD-{0000000000}</displayFormat>
        <label>STG SD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STG Server Deployment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/STG_Server_Deployment__c/fields/Data_as_of_Date__c.field-meta.xml
<CustomField>
    <fullName>Data_as_of_Date__c</fullName>
    <label>Data as of Date</label>
    <type>Date</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Data_Set_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Set_Type__c</fullName>
    <label>Data Set Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seats Deployed</fullName>
            </value>
            <value>
                <fullName>User Analytics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/STG_Server_Deployment__c/fields/Fault_Message__c.field-meta.xml
<CustomField>
    <fullName>Fault_Message__c</fullName>
    <label>Fault Message</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/First_Platform_Login__c.field-meta.xml
<CustomField>
    <fullName>First_Platform_Login__c</fullName>
    <label>First Platform Login</label>
    <type>Date</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Last_Platform_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Platform_Login__c</fullName>
    <label>Last Platform Login</label>
    <type>Date</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Last_Refresh_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Refresh_Date__c</fullName>
    <label>Last Refresh Date</label>
    <type>Date</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Monthly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Active_Users__c</fullName>
    <label>Monthly Active Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Processed_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Processed_DateTime__c</fullName>
    <label>Processed DateTime</label>
    <type>DateTime</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Seats_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Seats_Deployed__c</fullName>
    <label>Seats Deployed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Server_Deployment_ID__c.field-meta.xml
<CustomField>
    <fullName>Server_Deployment_ID__c</fullName>
    <externalId>true</externalId>
    <label>Server Deployment ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/STG_Server_Deployment__c/fields/Weekly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Active_Users__c</fullName>
    <label>Weekly Active Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/ServerDeploymentIntegrationAsync.cls
/*
 * @BUSINESS: Async class that populates ServerDeployment data based on StagingServerDeployment data
 * @DATE: 2022-05-02
 * @AUTHOR: Tanium Dev Team
 * @REQUEST:
 * RequestId  ModifiedDate  Comment
 * SS-8357    2024-06-03    Updated updateServerDeployments method, added Nebula Logger func.
 * SS-8551    2024-06-28    Updated Nebula Logger func., added filter on serverDeploymentId
 * SS-9202    2024-09-24    Updated updateServerDeployments method to get the correct fault message
 */
global class ServerDeploymentIntegrationAsync implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
	private static final Integer BATCH_SIZE = !Test.isRunningTest() ? 1 : 50;
	private Id serverDeploymentId;

	public ServerDeploymentIntegrationAsync() {
		this(null);
	}

	public ServerDeploymentIntegrationAsync(Id serverDeploymentId) {
		this.serverDeploymentId = serverDeploymentId;
	}

	global Database.QueryLocator start(Database.BatchableContext bc) {
		String query = 'SELECT Id ';
		query += 'FROM STG_Server_Deployment__c ';
		query += 'WHERE Data_Set_Type__c != null AND Server_Deployment_ID__c != null AND Processed_DateTime__c = null ';
		if (serverDeploymentId != null) {
			query += 'AND Server_Deployment_ID__c =\'' + serverDeploymentId + '\' ';
		}
		query += 'ORDER BY CreatedDate ASC';
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext bc, STG_Server_Deployment__c[] scope) {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'ContactTriggerHandler',
				'OpportunityTriggerHandler',
				'QuoteCPQTriggerHandler'
			}
		);

		STG_Server_Deployment__c[] stagingServerDeployments = [
			SELECT
				Id,
				Data_Set_Type__c,
				Seats_Deployed__c,
				First_Platform_Login__c,
				Last_Platform_Login__c,
				Last_Refresh_Date__c,
				Weekly_Active_Users__c,
				Monthly_Active_Users__c,
				Server_Deployment_ID__c,
				Data_as_of_Date__c
			FROM STG_Server_Deployment__c
			WHERE Id IN :scope
			FOR UPDATE
		];

		List<STG_Server_Deployment__c> stagingServerDeploymentsSeatsDeployed = new List<STG_Server_Deployment__c>();
		List<STG_Server_Deployment__c> stagingServerDeploymentsSeatsAnalytics = new List<STG_Server_Deployment__c>();

		for (STG_Server_Deployment__c stagingServerDeployment : stagingServerDeployments) {
			if (stagingServerDeployment.Data_Set_Type__c == 'Seats Deployed') {
				stagingServerDeploymentsSeatsDeployed.add(stagingServerDeployment);
			}
			if (stagingServerDeployment.Data_Set_Type__c == 'User Analytics') {
				stagingServerDeploymentsSeatsAnalytics.add(stagingServerDeployment);
			}
		}

		// it will be common to have two staging records for each serverDeployment record, one per Data_Set_Type
		updateServerDeployments(stagingServerDeploymentsSeatsDeployed);
		updateServerDeployments(stagingServerDeploymentsSeatsAnalytics);
	}

	@TestVisible
	private void updateServerDeployments(STG_Server_Deployment__c[] stagingServerDeployments) {
		Map<Id, String> serverDeploymentIdsFaultsMap = new Map<Id, String>();
		Map<Id, Server_Deployment__c> serverDeploymentsMap = new Map<Id, Server_Deployment__c>();
		Server_Deployment__c serverDeployment;
		Id serverDeploymentId;

		List<STG_Server_Deployment__c> stagingServerDeploymentsToUpdate = new List<STG_Server_Deployment__c>();
		STG_Server_Deployment__c stagingServerDeploymentToUpdate;

		for (STG_Server_Deployment__c stagingServerDeployment : stagingServerDeployments) {
			try {
				serverDeploymentId = Id.valueOf(stagingServerDeployment.Server_Deployment_ID__c); // ensure valid Id
			} catch (Exception e) {
				continue;
			}
			if (serverDeploymentsMap.containsKey(serverDeploymentId)) {
				continue; // we don't want two serverDeployment records with same Id in the same update
			}
			serverDeployment = new Server_Deployment__c(
				Id = serverDeploymentId,
				Staging_Record__c = stagingServerDeployment.Id,
				Last_Refresh_Date__c = stagingServerDeployment.Data_as_of_Date__c
			);

			if (stagingServerDeployment.Data_Set_Type__c == 'Seats Deployed') {
				serverDeployment.Seats_Deployed__c = stagingServerDeployment.Seats_Deployed__c;
			}

			if (stagingServerDeployment.Data_Set_Type__c == 'User Analytics') {
				serverDeployment.First_Platform_Login__c = stagingServerDeployment.First_Platform_Login__c;
				serverDeployment.Last_Platform_Login__c = stagingServerDeployment.Last_Platform_Login__c;
				serverDeployment.Weekly_Active_Users__c = stagingServerDeployment.Weekly_Active_Users__c;
				serverDeployment.Monthly_Active_Users__c = stagingServerDeployment.Monthly_Active_Users__c;
			}
			serverDeploymentsMap.put(serverDeploymentId, serverDeployment);
		}

		Database.SaveResult[] saveResults = Database.update(serverDeploymentsMap.values(), false);

		for (Database.SaveResult saveResult : saveResults) {
			if (!saveResult.isSuccess()) {
				serverDeploymentIdsFaultsMap.put(
					saveResult.getId(),
					saveResult.getErrors()[0].getMessage()
				);
			}
		}

		for (Server_Deployment__c serverDeploymentRecord : serverDeploymentsMap.values()) {
			stagingServerDeploymentToUpdate = new STG_Server_Deployment__c(
				Id = serverDeploymentRecord.Staging_Record__c
			);
			if (serverDeploymentIdsFaultsMap.containsKey(serverDeploymentRecord.Id)) {
				stagingServerDeploymentToUpdate.Fault_Message__c = serverDeploymentIdsFaultsMap.get(
					serverDeploymentRecord.Id
				);
			} else {
				stagingServerDeploymentToUpdate.Fault_Message__c = 'Processed without error';
				stagingServerDeploymentToUpdate.Processed_DateTime__c = System.now();
			}
			stagingServerDeploymentsToUpdate.add(stagingServerDeploymentToUpdate);
		}

		try {
			update stagingServerDeploymentsToUpdate;
		} catch (Exception e) {
			Logger.error('ServerDeploymentIntegrationAsync.updateServerDeployments Errors', e)
				.addTag('apex')
				.addTag('batch');
			Logger.saveLog();
		}
	}

	global void finish(Database.BatchableContext bc) {
	}

	// Scheduler execute method
	global void execute(SchedulableContext ctx) {
		ServerDeploymentIntegrationAsync async = new ServerDeploymentIntegrationAsync();
		Database.executeBatch(async, BATCH_SIZE);
	}
}