objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>Track and manage events for Tanium Customers and partners.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X7S_Event_RSVP__c/X7S_Event_RSVP__c.object-meta.xml
<CustomObject>
    <description>Object to support Event RSVP records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event RSVP</label>
    <nameField>
        <displayFormat>RSVP-{0000}</displayFormat>
        <label>Event RSVP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>7S Event RSVPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/X7S_Event_RSVP__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Will be populated automatically and set to read only if a authenticated user is the owner</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>X7S_Event__c</referenceTo>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Event_Segment__c.field-meta.xml
<CustomField>
    <fullName>Event_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>7S Event Segment</label>
    <referenceTo>X7S_Event_Segment__c</referenceTo>
    <relationshipLabel>7S Event RSVPs</relationshipLabel>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Will be populated automatically and set to read only if a authenticated user is the owner</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Will be populated automatically and set to read only if a authenticated user is the owner</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_Segment__c/X7S_Event_Segment__c.object-meta.xml
<CustomObject>
    <description>Object to support Event Segment records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event Segment</label>
    <nameField>
        <label>7S Event Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Event Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/X7S_Event_Segment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>X7S_Event__c</referenceTo>
    <relationshipLabel>7S Event Segments</relationshipLabel>
    <relationshipName>X7S_Event_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/X7S_Event_Segment__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-person</fullName>
                <default>true</default>
                <label>In-person</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Overall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/X7S_Event_Segment__c/fields/Track_capacity__c.field-meta.xml
<CustomField>
    <fullName>Track_capacity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track capacity</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Event_Segment__c/fields/Wait_list__c.field-meta.xml
<CustomField>
    <fullName>Wait_list__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wait list</label>
    <type>Checkbox</type>
</CustomField>

classes/x7sEventsRSVPTriggerHelper.cls
/*
 * Licensed Materials - Property of IBM
 * 6949-82P
 * © Copyright IBM Corp. 2022 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */
public with sharing class x7sEventsRSVPTriggerHelper {
	public static void handleEventsRSVPInsert(List<X7S_Event_RSVP__c> rsvpItems) {
		Set<Id> rsvpIds = new Set<Id>();
		Set<Id> eventIds = new Set<Id>();

		if (!rsvpItems.isEmpty()) {
			for (X7S_Event_RSVP__c rsvp : rsvpItems) {
				rsvpIds.add(rsvp.Event_Segment__c);
				eventIds.add(rsvp.Event__c);
			}
		}

		List<X7S_Event_Segment__c> segments = [
			SELECT Id, Capacity__c, Event__c, Track_capacity__c, Segment__c, Wait_list__c
			FROM X7S_Event_Segment__c
			WHERE Id = :rsvpIds AND Event__c = :eventIds
			WITH SECURITY_ENFORCED
		];

		if (!rsvpItems.isEmpty() && !segments.isEmpty()) {
			for (X7S_Event_RSVP__c rsvp : rsvpItems) {
				for (X7S_Event_Segment__c eventSegment : segments) {
					try {
						if (
							eventSegment.Track_capacity__c &&
							(eventSegment.Event__c == rsvp.Event__c) &&
							(eventSegment.Id == rsvp.Event_Segment__c)
						) {
							Integer count = x7sEventsRegistration.getExperienceCount(
								eventSegment.Event__c,
								eventSegment.Segment__c
							);

							if (count > eventSegment.Capacity__c) {
								if (eventSegment.Wait_list__c) {
									rsvp.addError(Label.x7sEventsCapacityFullWaitlist);
									WriteError(Label.x7sEventsCapacityFullWaitlist, rsvp);
								} else {
									rsvp.addError(Label.x7sEventsCapacityFull);
									WriteError(Label.x7sEventsCapacityFull, rsvp);
								}
							}
						}
					} catch (Exception e) {
						throw new EventRSVPTriggerException(e);
					}
				}
			}
		}
	}

	private static void WriteError(String message, X7S_Event_RSVP__c rsvp) {
		System.debug(
			message +
			' User: ' +
			rsvp.First_Name__c +
			' ' +
			rsvp.Last_Name__c +
			' Emai: ' +
			rsvp.Email__c
		);
	}

	public class EventRSVPTriggerException extends Exception {
	}
}