objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>TB-{00000}</displayFormat>
        <label>Budget #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Budget__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will auto populate based on Department &amp; Region combination</inlineHelpText>
    <label>Budget Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Finance_Approver__c.field-meta.xml
<CustomField>
    <fullName>Finance_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will auto populate based on Department &amp; Region combination</inlineHelpText>
    <label>Finance Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budgets2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Procurement_E_Staff_Approver__c.field-meta.xml
<CustomField>
    <fullName>Procurement_E_Staff_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will auto populate based on Department &amp; Region combination</inlineHelpText>
    <label>Procurement E Staff Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budgets1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Has_NS_Access__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Budgets4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <formula>TEXT(Business_Department__c)+&quot;.&quot;+TEXT(Business_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Identifier</label>
    <type>Text</type>
</CustomField>

objects/Budget__c/recordTypes/Budget.recordType-meta.xml
<RecordType>
    <fullName>Budget</fullName>
    <active>true</active>
    <label>Budget</label>
</RecordType>

objects/Budget_Approver__c/Budget_Approver__c.object-meta.xml
<CustomObject>
    <label>Budget Approver</label>
    <nameField>
        <displayFormat>BA-{000}</displayFormat>
        <label>Budget Approvers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget_Approver__c/fields/Budget_E_Staff__c.field-meta.xml
<CustomField>
    <fullName>Budget_E_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget E Staff</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Budget_Finance_Approver__c.field-meta.xml
<CustomField>
    <fullName>Budget_Finance_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Finance Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <formula>TEXT(Business_Department__c)+&quot;.&quot;+TEXT(Business_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Identifier</label>
    <type>Text</type>
</CustomField>

classes/BudgetApproverTriggerHandler.cls
/**
 * @Business: Handler class for Budget Approver Trigger
 * @Date: 2018-02-16
 * @Author: Cumulus Vision
 * @Request: TAN-480
 * Modified  ModifiedDate   Description
 * TAN-480   2018-02-16     Initial Development
 * TAN-664   2018-09-13     added Receiver to the process.
 */
public class BudgetApproverTriggerHandler extends TriggerHandler {
	private List<Budget_Approver__c> newBudgetApproverList;
	private Map<Id, Budget_Approver__c> oldBudgetApproverMap;

	public BudgetApproverTriggerHandler() {
		super('BudgetApproverTriggerHandler');
		this.newBudgetApproverList = (List<Budget_Approver__c>) Trigger.new;
		this.oldBudgetApproverMap = (Map<Id, Budget_Approver__c>) Trigger.oldMap;
	}

	public override void afterUpdate() {
		Set<String> uniqueIdentifiers = new Set<String>();
		Map<String, Id> ownerMap = new Map<String, Id>();
		Map<String, Id> eStaffMap = new Map<String, Id>();
		Map<String, Id> financeMap = new Map<String, Id>();
		Map<String, Id> receiverMap = new Map<String, Id>();

		for (Budget_Approver__c budgetApprover : newBudgetApproverList) {
			Budget_Approver__c oldBudgetApprover = oldBudgetApproverMap.get(budgetApprover.Id);

			if (
				(budgetApprover.Budget_Owner__c != null &&
				budgetApprover.Budget_Owner__c != oldBudgetApprover.Budget_Owner__c) ||
				(budgetApprover.Budget_E_Staff__c != null &&
				budgetApprover.Budget_E_Staff__c != oldBudgetApprover.Budget_E_Staff__c) ||
				(budgetApprover.Budget_Finance_Approver__c != null &&
				budgetApprover.Budget_Finance_Approver__c != oldBudgetApprover.Budget_Finance_Approver__c)
			) {
				uniqueIdentifiers.add(budgetApprover.Unique_Identifier__c);
				ownerMap.put(budgetApprover.Unique_Identifier__c + '.o', budgetApprover.Budget_Owner__c);
				eStaffMap.put(budgetApprover.Unique_Identifier__c + '.e', budgetApprover.Budget_E_Staff__c);
				financeMap.put(
					budgetApprover.Unique_Identifier__c + '.f',
					budgetApprover.Budget_Finance_Approver__c
				);
				receiverMap.put(budgetApprover.Unique_Identifier__c + '.a', budgetApprover.Receiver__c);
			}
		}

		if (!uniqueIdentifiers.isEmpty()) {
			updateOpenBudgets(uniqueIdentifiers, ownerMap, eStaffMap, financeMap);
		}
	}

	private static void updateOpenBudgets(
		Set<String> uniqueIdentifiers,
		Map<String, Id> ownerMap,
		Map<String, Id> eStaffMap,
		Map<String, Id> financeMap
	) {
		List<Budget__c> openBudgets = [
			SELECT
				Id,
				Unique_Identifier__c,
				Budget_Owner__c,
				Procurement_E_Staff_Approver__c,
				Status__c,
				Finance_Approver__c,
				Receiver__c
			FROM Budget__c
			WHERE Unique_Identifier__c IN :uniqueIdentifiers AND Status__c IN ('New', 'In Progess')
		];

		String owner;
		String eStaff;
		String finance;
		String receiver;

		List<Budget__c> updatedBudgets = new List<Budget__c>();

		for (Budget__c budget : openBudgets) {
			owner = budget.Unique_Identifier__c + '.o';
			eStaff = budget.Unique_Identifier__c + '.e';
			finance = budget.Unique_Identifier__c + '.f';
			receiver = budget.Unique_Identifier__c + '.r';

			if (budget.Budget_Owner__c != ownerMap.get(owner)) {
				budget.Budget_Owner__c = ownerMap.get(owner);
			}

			if (budget.Procurement_E_Staff_Approver__c != eStaffMap.get(eStaff)) {
				budget.Procurement_E_Staff_Approver__c = eStaffMap.get(eStaff);
			}

			if (budget.Finance_Approver__c != financeMap.get(finance)) {
				budget.Finance_Approver__c = financeMap.get(finance);
			}

			if (budget.Receiver__c != financeMap.get(receiver)) {
				budget.Receiver__c = financeMap.get(receiver);
			}

			updatedBudgets.add(budget);
		}

		update updatedBudgets;
	}
}