objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>TB-{00000}</displayFormat>
        <label>Budget #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Budget__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will auto populate based on Department &amp; Region combination</inlineHelpText>
    <label>Budget Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Business_Department__c.field-meta.xml
<CustomField>
    <fullName>Business_Department__c</fullName>
    <inlineHelpText>Department you are requesting for</inlineHelpText>
    <label>Business Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Hardware</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Software</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: TaaS</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Accounting</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Allocate</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Executives/Other</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Facilities</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Finance</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Global Enablement</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Human Resources</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Support</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Legal</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Office of the CEO</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Physical Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Strategy &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Talent Acquisition</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Tax &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Marketing: Brand &amp; Communication</fullName>
            </value>
            <value>
                <fullName>Marketing: Demand Generation</fullName>
            </value>
            <value>
                <fullName>Marketing: Events Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing_Fed</fullName>
            </value>
            <value>
                <fullName>Marketing: Marketing Leadership</fullName>
            </value>
            <value>
                <fullName>Marketing: Product Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget__c/fields/Business_Region__c.field-meta.xml
<CustomField>
    <fullName>Business_Region__c</fullName>
    <inlineHelpText>Region you are Requesting for</inlineHelpText>
    <label>Business Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>East/CA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>HQ</fullName>
            </value>
            <value>
                <fullName>HQ (Onsite Security)</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Munich</fullName>
            </value>
            <value>
                <fullName>N/E</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>North Asia</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>S/E</fullName>
            </value>
            <value>
                <fullName>South Asia</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Has_NS_Access__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Budgets4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget__c/recordTypes/Budget.recordType-meta.xml
<RecordType>
    <fullName>Budget</fullName>
    <active>true</active>
    <label>Budget</label>
</RecordType>

objects/Budget_Approver__c/Budget_Approver__c.object-meta.xml
<CustomObject>
    <label>Budget Approver</label>
    <nameField>
        <displayFormat>BA-{000}</displayFormat>
        <label>Budget Approvers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget_Approver__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Business_Department__c.field-meta.xml
<CustomField>
    <fullName>Business_Department__c</fullName>
    <label>Business Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : Hardware</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Software</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : TaaS</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Accounting</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Allocate</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Executives/Other</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Facilities</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Finance</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Global Enablement</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Human Resources</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Support</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Legal</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Office of the CEO</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Physical Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Strategy &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Talent Acquitision</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Tax &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Marketing: Brand &amp; Communication</fullName>
            </value>
            <value>
                <fullName>Marketing: Demand Generation</fullName>
            </value>
            <value>
                <fullName>Marketing: Events Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing_Fed</fullName>
            </value>
            <value>
                <fullName>Marketing: Marketing Leadership</fullName>
            </value>
            <value>
                <fullName>Marketing: Product Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Public Relations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget_Approver__c/fields/Business_Region__c.field-meta.xml
<CustomField>
    <fullName>Business_Region__c</fullName>
    <label>Business Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>HQ</fullName>
            </value>
            <value>
                <fullName>HQ (Onsite Security)</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Munich</fullName>
            </value>
            <value>
                <fullName>N/E</fullName>
            </value>
            <value>
                <fullName>Nagoya</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>S/E</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Asia</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget_Approver__c/fields/Receiver__c.field-meta.xml
<CustomField>
    <fullName>Receiver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers4</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/BudgetTriggerHandler.cls
/**
 * @Business: Handler class for Budget Trigger
 * @Date: 2018-02-16
 * @Author: Cumulus Vision
 * @Request: TAN-480
 * Modified  ModifiedDate   Description
 * TAN-480   2018-02-16     Initial Development
 * TAN-664   2018-09-14     Added logic to handle Receiver__c
 */
public class BudgetTriggerHandler extends TriggerHandler {
	private List<Budget__c> newBudgetList;
	private Map<Id, Budget__c> oldBudgetMap;

	public BudgetTriggerHandler() {
		super('BudgetTriggerHandler');
		this.newBudgetList = (List<Budget__c>) Trigger.new;
		this.oldBudgetMap = (Map<Id, Budget__c>) Trigger.oldMap;
	}

	public override void beforeInsert() {
		Set<String> uniqueIdentifiers = new Set<String>();

		for (Budget__c budget : newBudgetList) {
			if (budget.Business_Department__c != null && budget.Business_Region__c != null) {
				uniqueIdentifiers.add(budget.Business_Department__c + '.' + budget.Business_Region__c);
			}
		}

		if (!uniqueIdentifiers.isEmpty()) {
			findApprovers(newBudgetList, uniqueIdentifiers);
		}
	}

	public override void beforeUpdate() {
		Set<String> uniqueIdentifiers = new Set<String>();

		for (Budget__c budget : newBudgetList) {
			Budget__c oldBudget = oldBudgetMap.get(budget.Id);

			if (budget.Status__c == 'New' || budget.Status__c == 'In Progress') {
				if (
					(budget.Business_Department__c != null &&
					budget.Business_Department__c != oldBudget.Business_Department__c) ||
					(budget.Business_Region__c != null &&
					budget.Business_Region__c != oldBudget.Business_Region__c)
				) {
					uniqueIdentifiers.add(budget.Business_Department__c + '.' + budget.Business_Region__c);
				}
			}
		}

		if (!uniqueIdentifiers.isEmpty()) {
			findApprovers(newBudgetList, uniqueIdentifiers);
		}
	}

	private static void findApprovers(List<Budget__c> newBudgetList, Set<String> uniqueIdentifiers) {
		List<Budget_Approver__c> approvers = [
			SELECT
				Id,
				Budget_Owner__c,
				Budget_E_Staff__c,
				Unique_Identifier__c,
				Budget_Finance_Approver__c,
				Receiver__c
			FROM Budget_Approver__c
			WHERE Unique_Identifier__c IN :uniqueIdentifiers
		];

		Map<String, Id> ownerMap = new Map<String, Id>();
		Map<String, Id> eStaffMap = new Map<String, Id>();
		Map<String, Id> financeMap = new Map<String, Id>();
		Map<String, Id> receiverMap = new Map<String, Id>();

		for (Budget_Approver__c ba : approvers) {
			ownerMap.put(ba.Unique_Identifier__c, ba.Budget_Owner__c);
			eStaffMap.put(ba.Unique_Identifier__c, ba.Budget_E_Staff__c);
			financeMap.put(ba.Unique_Identifier__c, ba.Budget_Finance_Approver__c);
			receiverMap.put(ba.Unique_Identifier__c, ba.Receiver__c);
		}

		for (Budget__c budget : newBudgetList) {
			budget.Budget_Owner__c = ownerMap.get(budget.Unique_Identifier__c);
			budget.Procurement_E_Staff_Approver__c = eStaffMap.get(budget.Unique_Identifier__c);
			budget.Finance_Approver__c = financeMap.get(budget.Unique_Identifier__c);
			budget.Receiver__c = receiverMap.get(budget.Unique_Identifier__c);
		}
	}
}