objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>TB-{00000}</displayFormat>
        <label>Budget #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Budget__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will auto populate based on Department &amp; Region combination</inlineHelpText>
    <label>Budget Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Business_Department__c.field-meta.xml
<CustomField>
    <fullName>Business_Department__c</fullName>
    <inlineHelpText>Department you are requesting for</inlineHelpText>
    <label>Business Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Hardware</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Software</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: TaaS</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Accounting</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Allocate</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Executives/Other</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Facilities</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Finance</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Global Enablement</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Human Resources</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Support</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Legal</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Office of the CEO</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Physical Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Strategy &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Talent Acquisition</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Tax &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Marketing: Brand &amp; Communication</fullName>
            </value>
            <value>
                <fullName>Marketing: Demand Generation</fullName>
            </value>
            <value>
                <fullName>Marketing: Events Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing_Fed</fullName>
            </value>
            <value>
                <fullName>Marketing: Marketing Leadership</fullName>
            </value>
            <value>
                <fullName>Marketing: Product Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget__c/fields/Business_Region__c.field-meta.xml
<CustomField>
    <fullName>Business_Region__c</fullName>
    <inlineHelpText>Region you are Requesting for</inlineHelpText>
    <label>Business Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>East/CA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>HQ</fullName>
            </value>
            <value>
                <fullName>HQ (Onsite Security)</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Munich</fullName>
            </value>
            <value>
                <fullName>N/E</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>North Asia</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>S/E</fullName>
            </value>
            <value>
                <fullName>South Asia</fullName>
            </value>
            <value>
                <fullName>Southwest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget__c/fields/Finance_Approver__c.field-meta.xml
<CustomField>
    <fullName>Finance_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This will auto populate based on Department &amp; Region combination</inlineHelpText>
    <label>Finance Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budgets2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <inlineHelpText>Free text form - make it specific to your request</inlineHelpText>
    <label>Purchase Request Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Budget__c/recordTypes/Budget.recordType-meta.xml
<RecordType>
    <fullName>Budget</fullName>
    <active>true</active>
    <label>Budget</label>
</RecordType>

objects/Budget_Approver__c/Budget_Approver__c.object-meta.xml
<CustomObject>
    <label>Budget Approver</label>
    <nameField>
        <displayFormat>BA-{000}</displayFormat>
        <label>Budget Approvers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget_Approver__c/fields/Budget_E_Staff__c.field-meta.xml
<CustomField>
    <fullName>Budget_E_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget E Staff</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Budget_Finance_Approver__c.field-meta.xml
<CustomField>
    <fullName>Budget_Finance_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Finance Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Budget_Owner__c.field-meta.xml
<CustomField>
    <fullName>Budget_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Budget_Approvers1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Budget_Approver__c/fields/Business_Department__c.field-meta.xml
<CustomField>
    <fullName>Business_Department__c</fullName>
    <label>Business Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : Chronicle</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : Hardware</fullName>
            </value>
            <value>
                <fullName>Cost of Sales: Software</fullName>
            </value>
            <value>
                <fullName>Cost of Sales : TaaS</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Accounting</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Allocate</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Executives/Other</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Facilities</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Finance</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Global Enablement</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Human Resources</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: IT Support</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Legal</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Office of the CEO</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Physical Security</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Strategy &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Talent Acquitision</fullName>
            </value>
            <value>
                <fullName>G&amp;A: Tax &amp; Payroll</fullName>
            </value>
            <value>
                <fullName>Marketing: Brand &amp; Communication</fullName>
            </value>
            <value>
                <fullName>Marketing: Demand Generation</fullName>
            </value>
            <value>
                <fullName>Marketing: Events Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Field Marketing_Fed</fullName>
            </value>
            <value>
                <fullName>Marketing: Marketing Leadership</fullName>
            </value>
            <value>
                <fullName>Marketing: Product Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing: Public Relations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Budget_Approver__c/fields/Business_Region__c.field-meta.xml
<CustomField>
    <fullName>Business_Region__c</fullName>
    <label>Business Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>HQ</fullName>
            </value>
            <value>
                <fullName>HQ (Onsite Security)</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Munich</fullName>
            </value>
            <value>
                <fullName>N/E</fullName>
            </value>
            <value>
                <fullName>Nagoya</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>North Carolina</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>S/E</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Asia</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/BudgetTriggerHandlerTest.cls
/**
 * @Business: Test class for Budget Trigger Handler
 * @Date: 2018-02-16
 * @Author: Cumulus Vision
 * @Request: TAN-480
 * Modified  ModifiedDate   Description
 * TAN-480   2018-02-16     Initial Development
 * TAN-662   2018-09-07     Fixed issues in the test methods
 */
@isTest
private class BudgetTriggerHandlerTest {
	static testMethod void assignApproversTest() {
		//Get 4 users for approvers
		List<User> users = [SELECT Id, isActive FROM User WHERE isActive = TRUE LIMIT 4];

		//Insert the Budget Approver Record
		Budget_Approver__c ba = new Budget_Approver__c(
			Budget_Owner__c = users[1].Id,
			Budget_E_Staff__c = users[2].Id,
			Budget_Finance_Approver__c = users[3].Id,
			Business_Region__c = 'Global',
			Business_Department__c = 'Cost of Sales'
		);

		insert ba;

		//Insert the Budget Record
		Budget__c b = new Budget__c(
			Business_Region__c = 'Global',
			Business_Department__c = 'Cost of Sales',
			Program_Name__c = 'Test Budget',
			Status__c = 'New',
			Program_Description__c = 'Test',
			Program_Start_Date__c = system.today(),
			Requestor__c = users[0].Id,
			Budget_Amount__c = 100,
			Approximate_Amount_In_USD__c = 10
		);

		Test.startTest();

		insert b;

		Test.stopTest();

		Budget__c newB = [
			SELECT Id, Budget_Owner__c, Procurement_E_Staff_Approver__c, Finance_Approver__c
			FROM Budget__c
			WHERE Id = :b.Id
		];

		//check if the approvers from the budget approver record were added to the new budget record
		system.assertEquals(users[1].Id, newB.Budget_Owner__c);
		system.assertEquals(users[2].Id, newB.Procurement_E_Staff_Approver__c);
		system.assertEquals(users[3].Id, newB.Finance_Approver__c);
	}

	static testMethod void assignApproversUpdateTest() {
		//Get 8 users for approvers
		List<User> users = [SELECT Id, isActive FROM User WHERE isActive = TRUE LIMIT 8];

		//Insert the Budget Approver Records
		Budget_Approver__c ba = new Budget_Approver__c(
			Budget_Owner__c = users[1].Id,
			Budget_E_Staff__c = users[2].Id,
			Budget_Finance_Approver__c = users[3].Id,
			Business_Region__c = 'Global',
			Business_Department__c = 'Cost of Sales'
		);

		insert ba;

		Budget_Approver__c ba1 = new Budget_Approver__c(
			Budget_Owner__c = users[5].Id,
			Budget_E_Staff__c = users[6].Id,
			Budget_Finance_Approver__c = users[7].Id,
			Business_Region__c = 'HQ',
			Business_Department__c = 'Cost of Sales'
		);

		insert ba1;

		//Insert the Budget Record
		Budget__c b = new Budget__c(
			Business_Region__c = 'Global',
			Business_Department__c = 'Cost of Sales',
			Program_Name__c = 'Test Budget',
			Status__c = 'New',
			Program_Description__c = 'Test',
			Program_Start_Date__c = system.today(),
			Requestor__c = users[0].Id,
			Budget_Amount__c = 100,
			Approximate_Amount_In_USD__c = 10
		);
		insert b;

		Test.startTest();
		//Update the budget record to a new region
		b.Business_Region__c = 'HQ';
		update b;

		Test.stopTest();

		Budget__c newB = [
			SELECT Id, Budget_Owner__c, Procurement_E_Staff_Approver__c, Finance_Approver__c
			FROM Budget__c
			WHERE Id = :b.Id
		];

		//check if the approvers from the 2nd budget approver record were added to the udated budget record
		system.assertEquals(users[5].Id, newB.Budget_Owner__c);
		system.assertEquals(users[6].Id, newB.Procurement_E_Staff_Approver__c);
		system.assertEquals(users[7].Id, newB.Finance_Approver__c);
	}
}