objects/HiddenFeatures__mdt/HiddenFeatures__mdt.object-meta.xml
<CustomObject>
    <description>This is to prevent the code from running in production or sandboxes when needed</description>
    <label>HiddenFeature</label>
    <pluralLabel>HiddenFeatures</pluralLabel>
</CustomObject>

objects/HiddenFeatures__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>&apos;True&apos;</defaultValue>
    <inlineHelpText>If True, the hidden feature settings for the record will be honored.
If False, the hidden feature settings for the record will NOT be honored and the code will run for all records.</inlineHelpText>
    <label>isActive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
                <default>true</default>
                <label>True</label>
            </value>
            <value>
                <fullName>False</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c/fields/Deployment_Exception_Granted__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Exception_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deployment Exception Granted</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/Deployment_Partner__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Must be accredited for quoted software type (Cloud/OnPrem). See &apos;Partner Selection&apos; information in Helpful Links section for more details</inlineHelpText>
    <label>Deployment Provider</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND 4 AND 5) OR (6) OR (1 AND 2 AND 3 AND 7 AND (5 OR 6)) OR ( NOT (3) AND 7) OR ( NOT (3) AND (4 OR 6))</booleanFilter>
        <filterItems>
            <field>$Source.ApprovalStatus__c</field>
            <operation>notEqual</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>Integration</value>
        </filterItems>
        <filterItems>
            <field>$Source.Partner_Program_Bucket__c</field>
            <operation>equals</operation>
            <value>MSP</value>
        </filterItems>
        <filterItems>
            <field>Account.Cloud_Deployment_Verified__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Support_Verified__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.MSP_EM_RS_Accredited__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.On_Prem_Deployment_Verified__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Deployment Partner)</relationshipLabel>
    <relationshipName>Deployment_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SBQQ__Quote__c/fields/L1_L2_Support_Exception_Granted__c.field-meta.xml
<CustomField>
    <fullName>L1_L2_Support_Exception_Granted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>L1/L2 Support Exception Granted</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/L1_L2_Support_Partner__c.field-meta.xml
<CustomField>
    <fullName>L1_L2_Support_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous Filter Logic: (1 AND 2 AND (3 AND (4 OR 5) AND 6) OR ( NOT (3) AND 4)). 3: Quote: Partner Program Bucket = MSP
Added a filter to ensure that MSP-verified L1/L2 Support Provider could be selected. Also updated Lookup Filter #4 on the L1/L2 Support Provider Quote field to reference the Support Verified checkbox. SS-13460</description>
    <inlineHelpText>If partner, see list linked above in the “Helpful Links” right rail. If Tanium, select “Tanium Support Center”</inlineHelpText>
    <label>L1/L2 Support Provider</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 AND (4 OR 5) AND 6) OR ( NOT 3 AND (4 OR 5)) OR ((7 OR 8) AND 6))</booleanFilter>
        <filterItems>
            <field>$Source.ApprovalStatus__c</field>
            <operation>notEqual</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notContain</operation>
            <value>Integration</value>
        </filterItems>
        <filterItems>
            <field>$Source.Partner_Program_Bucket__c</field>
            <operation>equals</operation>
            <value>MSP</value>
        </filterItems>
        <filterItems>
            <field>Account.Support_Verified__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.MSP_EM_RS_Accredited__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>notEqual</operation>
            <value>Tanium Support Center</value>
        </filterItems>
        <filterItems>
            <field>Account.MSP_EM_Verified__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.MSP_RS_Verified__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (L1/L2 Support Partner)</relationshipLabel>
    <relationshipName>Support_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Partner__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary partner on this deal (if any). Defaulted to partner marked as primary in Partners related list on the opportunity.</description>
    <inlineHelpText>If applicable, enter the name of the Transacting Partner that will be receiving the quote. Please ensure the correct account is chosen. &quot;(Partner)&quot; is usually at the end of the name.</inlineHelpText>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Quotes</relationshipLabel>
    <relationshipName>PartnerQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__PricebookId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricebookId__c</fullName>
    <description>ID of the Price Book used by this quote.</description>
    <inlineHelpText>ID of the Price Book used by this quote.</inlineHelpText>
    <label>Pricebook ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Check as Primary if opportunity NACV should be calculated off of this quote (each opportunity has one primary quote and it should reflect the most likely scenario).</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/Total_Addressable_Seats__c.field-meta.xml
<CustomField>
    <fullName>Total_Addressable_Seats__c</fullName>
    <description>Value sourced from related Account.  This field is used in CPQ Product Rule.</description>
    <formula>SBQQ__Account__r.Total_Addressable_Seats__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Addressable Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verifications</label>
    <nameField>
        <displayFormat>VE-{00000}</displayFormat>
        <label>Verifications Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteCPQTriggerHandler_MidMarket_Test.cls
/**
 * @Business: Test class for QuoteCPQTriggerHandler
 * @Date: 2021-12-17
 * @Author: Cumulus Vision, Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-10736   2025-07-05    Use new Verification object and new Account fields
 */
@IsTest
private class QuoteCPQTriggerHandler_MidMarket_Test {
	@TestSetup
	static void makeData() {
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'OpportunityContractsProcess',
				'OpportunityTriggerHandler',
				'QuoteCPQTriggerHandler'
			}
		);
		System.runAs(TestUserFactory.getAdminUser()) {
			Pricebook2 globalPriceBook = new Pricebook2(
				Name = 'Global Pricebook',
				Description = 'Global Pricebook description.',
				IsActive = true
			);
			insert globalPriceBook;

			List<Account> accounts = new List<Account>();
			accounts.add(TestFactory.buildAccount('GenericPartnerAccount'));
			accounts[0].RecordTypeId = Utility.getRecordTypeIdByAPIName('Account', 'Partner');
			accounts[0]
				.Partner_Accreditations__c = 'Fully Verified - Support L1/L2;Proxy Approval - Cloud Deployment;';
			accounts[0].Support_Verified__c = true;
			accounts[0].Cloud_Deployment_Verified__c = true;
			accounts[0].On_Prem_Deployment_Verified__c = true;

			accounts.add(TestFactory.buildAccount('MidMarketAccount'));
			accounts[1].Segment__c = 'Enterprise';
			accounts[1].Total_Addressable_Seats__c = 5000;
			accounts[1].RecordTypeId = Utility.getRecordTypeIdByAPIName('Account', 'Prospect');
			insert accounts;

			List<Verification__c> verifications = new List<Verification__c>();
			verifications.addAll(
				TestFactory.buildVerifications(
					accounts[0].Id,
					new List<String>{ 'Cloud Deployment', 'Support L1/L2', 'On-Prem Deployment' },
					Date.today().addDays(30)
				)
			);
			insert verifications;

			Opportunity opp = TestFactory.buildOpportunity(
				'Test Opp',
				System.today().addDays(51),
				Utility.PROSPECTING,
				accounts[1].Id
			);
			opp.Type = 'New Customer';
			insert opp;

			SBQQ__Quote__c quote = TestFactory.buildSBQQ_Quote(
				opp.Id,
				accounts[1].Id,
				'Accepted',
				'Quote',
				System.today(),
				System.today().addDays(30),
				globalPriceBook.Id
			);
			quote.Deployment_Exception_Granted__c = false;
			quote.L1_L2_Support_Exception_Granted__c = false;
			quote.SBQQ__Partner__c = accounts[0].Id;
			quote.L1_L2_Support_Partner__c = accounts[0].Id;
			quote.Deployment_Partner__c = accounts[0].Id;
			quote.SBQQ__PricebookId__c = globalPriceBook.Id;
			quote.SBQQ__Primary__c = true;
			insert quote;

			SBQQ__Quote__c nonPrimaryQuote = TestFactory.buildSBQQ_Quote(
				opp.Id,
				accounts[1].Id,
				'Accepted',
				'Quote',
				System.today(),
				System.today().addDays(30),
				globalPriceBook.Id
			);
			nonPrimaryQuote.Deployment_Exception_Granted__c = false;
			nonPrimaryQuote.L1_L2_Support_Exception_Granted__c = false;
			nonPrimaryQuote.SBQQ__Partner__c = accounts[0].Id;
			nonPrimaryQuote.L1_L2_Support_Partner__c = accounts[0].Id;
			nonPrimaryQuote.Deployment_Partner__c = accounts[0].Id;
			nonPrimaryQuote.SBQQ__PricebookId__c = globalPriceBook.Id;
			nonPrimaryQuote.SBQQ__Primary__c = false;
			insert nonPrimaryQuote;
		}
	}

	@IsTest
	static void testPartnerValidation_whenSupportPartnerEmptiedOnPrimaryQuote_returnException() {
		TriggerHandler.resetRecursionLimits();
		HiddenFeatures__mdt hiddenFeatureL1L2SupportProvVR = Utility.getHiddenFeaturesByDeveloperName(
			'QuoteCPQTriggerUtility_L1L2SupportProvVR'
		);
		hiddenFeatureL1L2SupportProvVR.isActive__c = 'False';
		SBQQ__Quote__c quote = [
			SELECT Id, L1_L2_Support_Partner__c
			FROM SBQQ__Quote__c
			WHERE SBQQ__Primary__c = TRUE
			LIMIT 1
		];

		Test.startTest();
		String testException = '';
		User dealDesk = getDealDeskUser();
		try {
			System.runAs(dealDesk) {
				quote.L1_L2_Support_Partner__c = null;
				update quote;
			}
		} catch (Exception ex) {
			testException = ex.getMessage();
		}
		Test.stopTest();

		System.assert(
			testException != '',
			'Mid Market Quote is not validating support partner as expected.'
		);
	}

	@IsTest
	static void testPartnerValidation_whenSupportPartnerEmptiedOnNONPrimaryQuote_returnNoException() {
		TriggerHandler.resetRecursionLimits();
		HiddenFeatures__mdt hiddenFeatureL1L2SupportProvVR = Utility.getHiddenFeaturesByDeveloperName(
			'QuoteCPQTriggerUtility_L1L2SupportProvVR'
		);
		hiddenFeatureL1L2SupportProvVR.isActive__c = 'False';
		SBQQ__Quote__c quote = [
			SELECT Id, L1_L2_Support_Partner__c
			FROM SBQQ__Quote__c
			WHERE SBQQ__Primary__c = FALSE
			LIMIT 1
		];

		Test.startTest();
		String testException = '';
		User dealDesk = getDealDeskUser();
		try {
			System.runAs(dealDesk) {
				quote.L1_L2_Support_Partner__c = null;
				update quote;
			}
		} catch (Exception ex) {
			testException = ex.getMessage();
		}
		Test.stopTest();

		System.assert(testException == '', 'No exception thrown.');
	}

	@IsTest
	static void testPartnerValidation_whenDeploymentPartnerEmptiedOnPrimaryQuote_returnException() {
		HiddenFeatures__mdt hiddenFeatureDeploymentVR = Utility.getHiddenFeaturesByDeveloperName(
			'QuoteCPQTriggerUtility_DeploymentVR'
		);
		hiddenFeatureDeploymentVR.isActive__c = 'False';
		TriggerHandler.resetRecursionLimits();
		SBQQ__Quote__c quote = [
			SELECT Id, Deployment_Partner__c, L1_L2_Support_Partner__c
			FROM SBQQ__Quote__c
			WHERE SBQQ__Primary__c = TRUE
			LIMIT 1
		];

		User dealDesk = getDealDeskUser();
		Test.startTest();
		String testException = '';
		try {
			System.runAs(dealDesk) {
				quote.Deployment_Partner__c = null;
				update quote;
			}
		} catch (Exception ex) {
			testException = ex.getMessage();
		}

		Test.stopTest();
		System.assert(
			testException != '',
			'Mid Market Quote is not validating deployment partner as expected.'
		);
	}

	@IsTest
	static void testPartnerValidation_whenDeploymentPartnerEmptiedOnNONPrimaryQuote_returnsNoException() {
		HiddenFeatures__mdt hiddenFeatureDeploymentVR = Utility.getHiddenFeaturesByDeveloperName(
			'QuoteCPQTriggerUtility_DeploymentVR'
		);
		hiddenFeatureDeploymentVR.isActive__c = 'False';
		TriggerHandler.resetRecursionLimits();
		SBQQ__Quote__c quote = [
			SELECT Id, Deployment_Partner__c, L1_L2_Support_Partner__c
			FROM SBQQ__Quote__c
			WHERE SBQQ__Primary__c = FALSE
			LIMIT 1
		];

		User dealDesk = getDealDeskUser();
		Test.startTest();
		String testException = '';
		try {
			System.runAs(dealDesk) {
				quote.Deployment_Partner__c = null;
				update quote;
			}
		} catch (Exception ex) {
			testException = ex.getMessage();
		}

		Test.stopTest();
		System.assert(testException == '', 'No validation error thrown');
	}

	@IsTest
	static void testPartnerValidation_whenStdPartnerEmptiedOnPrimaryQuote_returnException() {
		TriggerHandler.resetRecursionLimits();
		SBQQ__Quote__c quote = [
			SELECT Id, L1_L2_Support_Partner__c
			FROM SBQQ__Quote__c
			WHERE SBQQ__Primary__c = TRUE
			LIMIT 1
		];
		User dealDesk = getDealDeskUser();
		Test.startTest();
		String testException = '';
		try {
			System.runAs(dealDesk) {
				quote.SBQQ__Partner__c = null;
				update quote;
			}
		} catch (Exception ex) {
			testException = ex.getMessage();
		}
		Test.stopTest();
		System.assert(
			testException != '',
			'Mid Market Quote is not validating standard partner as expected.'
		);
	}

	@IsTest
	static void testPartnerValidation_whenStdPartnerEmptiedOnNONPrimaryQuote_returnsNoException() {
		TriggerHandler.resetRecursionLimits();
		SBQQ__Quote__c quote = [
			SELECT Id, L1_L2_Support_Partner__c
			FROM SBQQ__Quote__c
			WHERE SBQQ__Primary__c = FALSE
			LIMIT 1
		];
		User dealDesk = getDealDeskUser();
		Test.startTest();
		String testException = '';
		try {
			System.runAs(dealDesk) {
				quote.SBQQ__Partner__c = null;
				update quote;
			}
		} catch (Exception ex) {
			testException = ex.getMessage();
		}
		Test.stopTest();
		System.assert(testException == '', 'No Validation error thrown.');
	}

	static User getDealDeskUser() {
		List<User> testUsers = [SELECT Id FROM User WHERE LastName = :TestUserFactory.DEAL_DESK_USER];
		if (testUsers.isEmpty()) {
			User dealDeskUser = TestUserFactory.createDealDeskUser();
			TestingUtility.assignPermissionSet(dealDeskUser.Id, 'DisableFlows');
			return dealDeskUser;
		} else {
			return testUsers[0];
		}
	}

	static User getAdminUser() {
		User[] adminUsers = [SELECT Id FROM User WHERE LastName = :TestUserFactory.TANIUM_ADMIN_USER];
		if (adminUsers.isEmpty()) {
			User adminUser = TestUserFactory.createTaniumAdminUser(false);
			adminUser.DisableTaniumCustomTriggers__c = 'AccountTriggerHandler;OpportunityTriggerHandler';
			insert adminUser;
			TestingUtility.assignPermissionSet(adminUser.Id, 'DisableValidationRules');
			TestingUtility.assignPermissionSet(adminUser.Id, 'DisableFlows');
			return adminUser;
		}
		return adminUsers[0];
	}
}