objects/Account_Next_Step__c/Account_Next_Step__c.object-meta.xml
<CustomObject>
    <label>Account Next Step</label>
    <nameField>
        <displayFormat>NS-{00000000}</displayFormat>
        <label>Account Next Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Next Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Next_Step__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Next Steps</relationshipLabel>
    <relationshipName>Account_Next_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Next_Step__c/fields/TAM_Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>TAM_Next_Steps__c</fullName>
    <description>Renamed to Next Steps so this field can be used by CSMs and TAMs and Alliance</description>
    <label>Next Steps</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Account_Next_Step__c/fields/TAM_Owner__c.field-meta.xml
<CustomField>
    <fullName>TAM_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAM Owner (old)</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <value>00132000019soMf</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Account Next Steps</relationshipLabel>
    <relationshipName>Account_Next_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account_Next_Step__c/recordTypes/TAM_Next_Step.recordType-meta.xml
<RecordType>
    <fullName>TAM_Next_Step</fullName>
    <active>true</active>
    <label>TAM Next Step</label>
</RecordType>

objects/TAM_Next_Steps__c/TAM_Next_Steps__c.object-meta.xml
<CustomObject>
    <label>Next Step</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Note ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Next Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TAM_Next_Steps__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>TAM_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/TAM_Next_Steps__c/fields/TAM_Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>TAM_Next_Steps__c</fullName>
    <label>TAM/TSE Next Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/TAM_Next_Steps__c/fields/TAM_Owner__c.field-meta.xml
<CustomField>
    <fullName>TAM_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>11.05.2024 - Deprecated. Jira ticket SS-9539</description>
    <label>DEPRECATED - TAM Owner (old)</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <value>00132000019soMf</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Next Steps</relationshipLabel>
    <relationshipName>Next_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/TAM_Next_Steps__c/recordTypes/TAM_Next_Step.recordType-meta.xml
<RecordType>
    <fullName>TAM_Next_Step</fullName>
    <active>true</active>
    <label>TAM Next Step</label>
</RecordType>

classes/AccountNextStepTriggerHandler.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: AccountNextStep Trigger Handling
 * @Date: 3/2/2016
 * @Author: Cumulus Vision, Tanium Dev Team
 * @Request: ??
 * Modified   ModifiedDate   Description
 * SS-13497   2026-07-07     Remove deprecated fields for project kondo group 2
 */
public class AccountNextStepTriggerHandler extends TriggerHandler {
	public List<Account_Next_Step__c> newAccountNextStepList { get; set; }
	public static final Id ACCOUNT_NEXT_STEP_TAM_RECORDTYPE_ID = Utility.getRecordTypeIdByAPIName(
		'Account_Next_Step__c',
		'TAM_Next_Step'
	);
	public static final Id TAM_NEXT_STEP_TAM_RECORDTYPE_ID = Utility.getRecordTypeIdByAPIName(
		'TAM_Next_Steps__c',
		'TAM_Next_Step'
	);

	public AccountNextStepTriggerHandler() {
		super('AccountNextStepTriggerHandler');
		this.newAccountNextStepList = (List<Account_Next_Step__c>) Trigger.new;
	}

	public override void afterInsert() {
		Map<Id, Account> accountUpdateMap = generateAccountUpdateMap(newAccountNextStepList);
		if (!accountUpdateMap.isEmpty()) {
			List<TAM_Next_Steps__c> newTAMNextStepsList = generateTAMNextStepInsertList(
				newAccountNextStepList,
				accountUpdateMap.keySet()
			);

			if (!newTAMNextStepsList.isEmpty()) {
				insert newTAMNextStepsList;
			}
			update accountUpdateMap.values();
		}
	}

	@TestVisible
	private static Map<Id, Account> generateAccountUpdateMap(
		List<Account_Next_Step__c> accountNextStepList
	) {
		Map<Id, Account> accountUpdateMap = new Map<Id, Account>();

		for (Account_Next_Step__c accountNextStep : accountNextStepList) {
			if (accountNextStep.RecordTypeId == ACCOUNT_NEXT_STEP_TAM_RECORDTYPE_ID) {
				accountUpdateMap.put(
					accountNextStep.Account__c,
					new Account(Id = accountNextStep.Account__c)
				);
			}
		}
		return accountUpdateMap;
	}

	@TestVisible
	private static List<TAM_Next_Steps__c> generateTAMNextStepInsertList(
		List<Account_Next_Step__c> accountNextStepList,
		Set<Id> accountIdSet
	) {
		List<TAM_Next_Steps__c> newTAMNextStepsList = new List<TAM_Next_Steps__c>();
		Map<Id, Id> accountIdOpportunityIdMap = new Map<Id, Id>();

		for (Opportunity opportunity : [
			SELECT Id, AccountId
			FROM Opportunity
			WHERE AccountId IN :accountIdSet AND StageName = :Utility.UNCOMMITTED_RENEWAL
		]) {
			accountIdOpportunityIdMap.put(opportunity.AccountId, opportunity.Id);
		}

		for (Account_Next_Step__c accountNextStep : accountNextStepList) {
			if (accountIdOpportunityIdMap.containsKey(accountNextStep.Account__c)) {
				newTAMNextStepsList.add(
					new TAM_Next_Steps__c(
						RecordTypeId = TAM_NEXT_STEP_TAM_RECORDTYPE_ID,
						TAM_Owner__c = accountNextStep.TAM_Owner__c,
						TAM_Next_Steps__c = accountNextStep.TAM_Next_Steps__c,
						Opportunity__c = accountIdOpportunityIdMap.get(accountNextStep.Account__c)
					)
				);
			}
		}

		return newTAMNextStepsList;
	}
}