objects/X7S_Ideas_Setting__mdt/X7S_Ideas_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Global settings for Ideas</description>
    <label>7S Ideas Setting</label>
    <pluralLabel>7S Ideas Settings</pluralLabel>
</CustomObject>

objects/X7S_Ideas_Setting__mdt/fields/Account_Filter_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Account_Filter_Permission_Set__c</fullName>
    <inlineHelpText>Specify the permission set required to view the account filters</inlineHelpText>
    <label>Account Filter Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Account_Limit_Message__c.field-meta.xml
<CustomField>
    <fullName>Account_Limit_Message__c</fullName>
    <label>Account Limit Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Account_Votes_per_Idea__c.field-meta.xml
<CustomField>
    <fullName>Account_Votes_per_Idea__c</fullName>
    <inlineHelpText>Set the maximum account votes per idea.This can be overridden at the account level.</inlineHelpText>
    <label>Account Votes per Idea</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Allow_Down_Voting__c.field-meta.xml
<CustomField>
    <fullName>Allow_Down_Voting__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allow users to downvote an idea</description>
    <inlineHelpText>Check to enable users to down vote an idea.</inlineHelpText>
    <label>Allow Down Voting</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Auto_subscribe_Idea_Creators__c.field-meta.xml
<CustomField>
    <fullName>Auto_subscribe_Idea_Creators__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this field to auto-subscribe creators to Ideas they have submitted</inlineHelpText>
    <label>Auto-subscribe Idea Creators</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Auto_subscribe_Idea_Requestors__c.field-meta.xml
<CustomField>
    <fullName>Auto_subscribe_Idea_Requestors__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this field to auto-subscribe requestors to Ideas submitted on their behalf.</inlineHelpText>
    <label>Auto-subscribe Idea Requestors</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Chatter_Permission_List__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Permission_List__c</fullName>
    <inlineHelpText>Private Chatter Feed Permissions List - comma-separated permission names that will see the chatter component</inlineHelpText>
    <label>Chatter and Upload Permission Sets</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Chatter_Profile_List__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Profile_List__c</fullName>
    <inlineHelpText>Private Chatter Feed Profile List - comma-separated profile names that will see the chatter component</inlineHelpText>
    <label>Chatter and Upload Profiles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Debug_Mode__c.field-meta.xml
<CustomField>
    <fullName>Debug_Mode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable debug mode for detailed console info</description>
    <inlineHelpText>Enable debug mode for detailed console info</inlineHelpText>
    <label>Debug Mode</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Default_Test_Profile__c.field-meta.xml
<CustomField>
    <fullName>Default_Test_Profile__c</fullName>
    <defaultValue>&quot;System Administrator&quot;</defaultValue>
    <inlineHelpText>Provide the profile name used to create a portal user for unit tests</inlineHelpText>
    <label>Default Test Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Disable_Read_Only_Users__c.field-meta.xml
<CustomField>
    <fullName>Disable_Read_Only_Users__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Disable read only profile users from following, voting and commenting on Ideas</inlineHelpText>
    <label>Restrict Read Only Users</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Enable_Idea_Extension_Functionality__c.field-meta.xml
<CustomField>
    <fullName>Enable_Idea_Extension_Functionality__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Idea Extension Functionality</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Idea_Submission_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Idea_Submission_Email_Template__c</fullName>
    <inlineHelpText>Populate this field with an email template to automatically notify creators and requestors upon submission of an Idea.</inlineHelpText>
    <label>Idea Submission Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Ignore_Vote_Limit_Field__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Vote_Limit_Field__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable this to ignore account voting limits</description>
    <inlineHelpText>If checked, disables account voting restrictions globally.  If unchecked, account-level settings will be used where defined.</inlineHelpText>
    <label>Ignore Vote Limit Field</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/New_Comment_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>New_Comment_Email_Template__c</fullName>
    <inlineHelpText>Idea comment notification email name</inlineHelpText>
    <label>Idea New Comment Email Template</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/OrgWide_Email_Sender__c.field-meta.xml
<CustomField>
    <fullName>OrgWide_Email_Sender__c</fullName>
    <inlineHelpText>Org Wide send email address for notifications</inlineHelpText>
    <label>OrgWide Email Sender</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Status_Change_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Status_Change_Email_Template__c</fullName>
    <inlineHelpText>Idea status change notification email template name</inlineHelpText>
    <label>Idea Status Change Email Template</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/User_Custom_FieldValues__c.field-meta.xml
<CustomField>
    <fullName>User_Custom_FieldValues__c</fullName>
    <description>Enter a list of mandatory User record field value pairs used for unit tests</description>
    <inlineHelpText>Enter a CSV list of required custom User field value pairs for unit tests (Field_API_Name1:value1, field_API_Name2:value2)</inlineHelpText>
    <label>Test User Custom FieldValues</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Vote_Disable_Status__c.field-meta.xml
<CustomField>
    <fullName>Vote_Disable_Status__c</fullName>
    <description>List of statuses (VSC) for which voting will be disabled.</description>
    <inlineHelpText>List of statuses (CSV) for which voting will be disabled for an idea.   When voting is disabled, voting buttons will be disabled and a message will be displayed (custom label).</inlineHelpText>
    <label>Disable Voting Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Ideas_Setting__mdt/fields/Vote_Show_Alternate_Message__c.field-meta.xml
<CustomField>
    <fullName>Vote_Show_Alternate_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enable to display the alternate Idea voted message for a user who has already voted (custom label)</inlineHelpText>
    <label>Show Alternate Voted Message</label>
    <type>Checkbox</type>
</CustomField>

classes/x7sIdeasCommon.cls
/*
 * Licensed Materials - Property of IBM
 * 6949-82Z
 * © Copyright IBM Corp. 2022 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

public without sharing class x7sIdeasCommon {
	// Set the down voting flag in Custom Settings
	// Enabled by default
	@AuraEnabled
	public Boolean lexMode { get; set; }

	@AuraEnabled
	public Boolean debugMode { get; private set; }

	@AuraEnabled
	public String sitePath { get; set; }

	@AuraEnabled
	public Boolean nicknameEnabled { get; set; }

	@AuraEnabled
	public Boolean isAuthenticated { get; set; }

	@AuraEnabled
	public Boolean canCreateNew { get; set; }

	@AuraEnabled
	public String zoneId { get; set; }

	@AuraEnabled
	public String emailIdeaStatusTemplate, emailIdeaCommentTemplate, orgWideFromEmailAddress;

	@AuraEnabled
	public String chatterProfiles, chatterPermissions, accountFilterPermissions;

	// Voting
	@AuraEnabled
	public Boolean allowDownVoting { get; private set; }
	@AuraEnabled
	public Boolean ignoreVoteLimits { get; private set; }
	@AuraEnabled
	public Boolean showAlternateCTA { get; private set; }
	@AuraEnabled
	public String voteDisableStatus { get; private set; }

	@AuraEnabled
	public Boolean disableReadOnlyUsers { get; private set; }

	public final static String IDEAS_SETTINGS = 'X7S_Ideas_Setting__mdt';
	//private final String  SETTINGS_FIELD_SET = 'X7S_Idea_Field_Set__mdt';
	//private final String  SETTINGS_FIELD     = 'X7S_Idea_Custom_Field__mdt';
	private final Integer MAX_CUSTOM_FIELDS = 10;

	public final static String IDEAS_DEVELOPER_NAME = 'Default';
	private final static String IDEAS_UNIT_TEST_NAME = 'x7sIdeasTestSettings';

	public static List<String> commonSettingsFields = new List<String>{
		'id', 'developername',
		'allow_down_voting__c', 'debug_mode__c', 'default_test_profile__c',
		'status_change_email_template__c', 'new_comment_email_template__c', 'orgwide_email_sender__c',
		'Account_limit_message__c', 'Account_Votes_per_Idea__c', 'ignore_vote_limit_field__c',
		'user_custom_fieldvalues__c', 'chatter_profile_list__c', 'vote_disable_status__c', 'chatter_permission_list__c',
		'auto_subscribe_idea_creators__c', 'auto_subscribe_idea_requestors__c',
		'idea_submission_email_template__c', 'enable_idea_extension_functionality__c',
		'account_filter_permission_set__c',
		'vote_show_alternate_message__c',
		'Disable_Read_Only_Users__c '
	};

	public x7sIdeasCommon(String setName) {
		nicknameEnabled = false;
		isAuthenticated = false;
		disableReadOnlyUsers = false;
		zoneId = '';
		voteDisableStatus = '';
		emailIdeaStatusTemplate = '';
		chatterProfiles = '';
		getCustomSettings(setName, false);
	}

	public x7sIdeasCommon(String setName, Boolean loadCustomFields) {
		this(setName);
		getCustomSettings(setName, loadCustomFields);
	}

	private void getCustomSettings(String name, Boolean loadCustomFields) {
		//String developerName = String.isNotBlank(name) ? name : System.Test.isRunningTest() ? IDEAS_UNIT_TEST_NAME : IDEAS_DEVELOPER_NAME;
		String developerName = String.isNotBlank(name) ? String.escapeSingleQuotes(name) : IDEAS_DEVELOPER_NAME;

		//String settingsQuery = x7sIdeasUtility.buildQuery(IDEAS_SETTINGS, '');

		String settingsQuery = 'SELECT ' + String.join(commonSettingsFields, ', ')
			+ ' FROM ' + IDEAS_SETTINGS
			+ ' WHERE DeveloperName = \'' + developerName + '\''
			+ ' LIMIT 1';
		//System.debug('Settings Query: ' + settingsQuery);

		//PMD : False positive, All variables are checked
		X7S_Ideas_Setting__mdt settings = (X7S_Ideas_Setting__mdt) Database.query(settingsQuery); //NOPMD

		if (settings != null) {
			this.debugMode = settings.Debug_Mode__c;
			this.allowDownVoting = settings.Allow_Down_Voting__c;
			this.orgWideFromEmailAddress = settings.OrgWide_Email_Sender__c;
			this.emailIdeaStatusTemplate = settings.Status_Change_Email_Template__c;
			this.emailIdeaCommentTemplate = settings.New_Comment_Email_Template__c;
			this.chatterProfiles = settings.Chatter_Profile_List__c;
			this.chatterPermissions = settings.Chatter_Permission_List__c;
			this.accountFilterPermissions = settings.Account_Filter_Permission_Set__c;
			this.showAlternateCTA = settings.Vote_Show_Alternate_Message__c;
			this.voteDisableStatus = settings.Vote_Disable_Status__c;
			this.disableReadOnlyUsers = settings.Disable_Read_Only_Users__c;
			this.ignoreVoteLimits = settings.Ignore_Vote_Limit_Field__c;

			this.sitePath = System.Site.getPathPrefix();
			this.lexMode = System.Network.getNetworkId() == null;
			this.canCreateNew = x7sIdeasUtility.isIdeaObjectCreateable();
			this.isAuthenticated = !Auth.CommunitiesUtil.isGuestUser();
			this.nicknameEnabled = x7sIdeasUtility.isNicknameDisplayEnabled();

			//dumpSettings(developerName, this);
		}
	}

	public static void dumpSettings(String title, x7sIdeasCommon settings) {
		System.debug('Dump Ideas settings : ' + title);
		System.debug('  debug            : ' + settings.debugMode);
		System.debug('  down voting      : ' + settings.allowDownVoting);
		System.debug('  sender email     : ' + settings.orgWideFromEmailAddress);
		System.debug('  status template  : ' + settings.emailIdeaStatusTemplate);
		System.debug('  comment template : ' + settings.emailIdeaCommentTemplate);
		System.debug('  account perm     : ' + settings.accountFilterPermissions);
		System.debug('  chatter perm     : ' + settings.chatterPermissions);
		System.debug('  chatter profiles : ' + settings.chatterProfiles);
		System.debug('  disable readonly : ' + settings.disableReadOnlyUsers);		
	}
}