objects/Integration_Callout__c/Integration_Callout__c.object-meta.xml
<CustomObject>
    <description>The object stores the result of an outbound callout to third party system for logging purposes</description>
    <label>Integration Callout</label>
    <nameField>
        <label>Integration Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Callout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkBadgeMissionEvent__e/WorkBadgeMissionEvent__e.object-meta.xml
<CustomObject>
    <description>WorkBadgeMissionEvent</description>
    <label>WorkBadgeMissionEvent</label>
    <pluralLabel>WorkBadgeMissionEvents</pluralLabel>
</CustomObject>

objects/WorkBadgeMissionEvent__e/fields/FeedCommentId__c.field-meta.xml
<CustomField>
    <fullName>FeedCommentId__c</fullName>
    <description>FeedCommentId</description>
    <label>FeedCommentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/WorkBadgeMissionEvent__e/fields/FeedItemId__c.field-meta.xml
<CustomField>
    <fullName>FeedItemId__c</fullName>
    <description>FeedItemId</description>
    <label>FeedItemId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/WorkBadgeMissionEvent__e/fields/InsertedById__c.field-meta.xml
<CustomField>
    <fullName>InsertedById__c</fullName>
    <description>InsertedBy User Id</description>
    <label>InsertedById</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/WorkBadgeMissionEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Event</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/FeedCommentTriggerUtility.cls
/*
 * @DATE: 2024-10-16
 * @AUTHOR: Tanium Dev Team
 * @REQUEST:
 * @BUSINESS: Trigger Utility for the FeedCommentTrigger class
 * RequestId  ModifiedDate  Comment
 * SS-9451    2024-11-20    Created the FeedCommentTriggerUtility class
 * SS-8303    2024-12-05    Added method publishWorkBadgeMissionEvent
 */
public with sharing class FeedCommentTriggerUtility {
	public static final Set<String> CLOSED_STATUSES = new Set<String>{
		'Closed',
		'Closed as Duplicate'
	};

	public static void preventFeedCommentsOnClosedCases(List<FeedComment> feedComments) {
		Map<Id, FeedComment> caseIdsFeedCommentMap = new Map<Id, FeedComment>();

		for (FeedComment feedComment : feedComments) {
			if (Utility.isCase(feedComment.ParentId)) {
				caseIdsFeedCommentMap.put(feedComment.ParentId, feedComment);
			}
		}

		for (Case caseRec : [
			SELECT Id, Status
			FROM Case
			WHERE Id IN :caseIdsFeedCommentMap.keySet() AND Status IN :CLOSED_STATUSES
		]) {
			caseIdsFeedCommentMap.get(caseRec.Id)
				.addError('You cannot comment to a closed case. Please open a new case.');
		}
	}

	public static void publishWorkBadgeMissionEvent(List<FeedComment> feedComments) {
		List<Integration_Callout__c> callouts = new List<Integration_Callout__c>();

		List<WorkBadgeMissionEvent__e> workBadgeMissionEvents = new List<WorkBadgeMissionEvent__e>();
		WorkBadgeMissionEvent__e workBadgeMissionEvent;

		for (FeedComment feedComment : feedComments) {
			workBadgeMissionEvent = new WorkBadgeMissionEvent__e();
			workBadgeMissionEvent.InsertedById__c = feedComment.InsertedById;
			workBadgeMissionEvent.FeedItemId__c = feedComment.FeedItemId;
			workBadgeMissionEvent.FeedCommentId__c = feedComment.Id;
			workBadgeMissionEvent.Type__c = feedComment.CommentType;
			workBadgeMissionEvents.add(workBadgeMissionEvent);
		}

		Database.SaveResult[] publishResults = EventBus.publish(workBadgeMissionEvents);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'FeedCommentTriggerUtility.publishWorkBadgeMissionEvent() ERRORS',
				publishResults
			)
			.addTag('apex')
			.addTag('platform-event');
		for (Database.SaveResult publishResult : publishResults) {
			if (publishResult.isSuccess()) {
				callouts.add(
					new Integration_Callout__c(Name = 'WorkBadgeMissionEvent__e - ' + publishResult.getId())
				);
			}
		}
		Database.SaveResult[] insertResults = Database.insert(callouts);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'FeedCommentTriggerUtility.publishWorkBadgeMissionEvent() ERRORS',
				insertResults
			)
			.addTag('apex');
		Logger.saveLog();
	}
}