objects/Integration_Callout__c/Integration_Callout__c.object-meta.xml
<CustomObject>
    <description>The object stores the result of an outbound callout to third party system for logging purposes</description>
    <label>Integration Callout</label>
    <nameField>
        <label>Integration Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Callout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkBadgeMissionEvent__e/WorkBadgeMissionEvent__e.object-meta.xml
<CustomObject>
    <description>WorkBadgeMissionEvent</description>
    <label>WorkBadgeMissionEvent</label>
    <pluralLabel>WorkBadgeMissionEvents</pluralLabel>
</CustomObject>

objects/WorkBadgeMissionEvent__e/fields/IdeaCommentId__c.field-meta.xml
<CustomField>
    <fullName>IdeaCommentId__c</fullName>
    <description>IdeaCommentId</description>
    <label>IdeaCommentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/WorkBadgeMissionEvent__e/fields/IdeaId__c.field-meta.xml
<CustomField>
    <fullName>IdeaId__c</fullName>
    <description>IdeaId</description>
    <label>IdeaId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/WorkBadgeMissionEvent__e/fields/InsertedById__c.field-meta.xml
<CustomField>
    <fullName>InsertedById__c</fullName>
    <description>InsertedBy User Id</description>
    <label>InsertedById</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/WorkBadgeMissionEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Event</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/IdeaCommentTriggerHandler.cls
/*
 * @DATE: 2024-09-06
 * @AUTHOR: Tanium Dev Team
 * @BUSINESS: Trigger Handler on the IdeaComment object.
 * RequestId  ModifiedDate  Comment
 * SS-8303    2025-01-14    Created the class
 */
public with sharing class IdeaCommentTriggerHandler extends TriggerHandler {
	public IdeaComment[] ideaComments { get; set; }
	public Map<Id, Idea> oldMap { get; set; }

	public IdeaCommentTriggerHandler() {
		super('IdeaCommentTriggerHandler');
		this.ideaComments = (IdeaComment[]) Trigger.new;
		this.oldMap = (Map<Id, Idea>) Trigger.oldMap;
	}

	public override void afterInsert() {
		List<IdeaComment> ideaCommentsToPublish = new List<IdeaComment>();

		for (IdeaComment ideaComment : ideaComments) {
			if (ideaComment.CommunityId == Constants.COMMUNITY_PLAYBOOK_IDEAS_ID) {
				ideaCommentsToPublish.add(ideaComment);
			}
		}
		if (!ideaCommentsToPublish.isEmpty()) {
			publishWorkBadgeMissionEvent(ideaCommentsToPublish);
		}
	}

	@TestVisible
	private static void publishWorkBadgeMissionEvent(IdeaComment[] ideaComments) {
		List<Integration_Callout__c> callouts = new List<Integration_Callout__c>();
		List<WorkBadgeMissionEvent__e> workBadgeMissionEvents = new List<WorkBadgeMissionEvent__e>();
		WorkBadgeMissionEvent__e workBadgeMissionEvent;

		for (IdeaComment ideaComment : ideaComments) {
			workBadgeMissionEvent = new WorkBadgeMissionEvent__e();
			workBadgeMissionEvent.InsertedById__c = ideaComment.CreatedById;
			workBadgeMissionEvent.IdeaId__c = ideaComment.IdeaId;
			workBadgeMissionEvent.IdeaCommentId__c = ideaComment.Id;
			workBadgeMissionEvent.Type__c = 'IdeaComment';
			workBadgeMissionEvents.add(workBadgeMissionEvent);
		}

		Database.SaveResult[] publishResults = EventBus.publish(workBadgeMissionEvents);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'IdeaCommentTriggerHandler.publishWorkBadgeMissionEvent() ERRORS',
				publishResults
			)
			.addTag('apex')
			.addTag('platform-event');
		for (Database.SaveResult publishResult : publishResults) {
			if (publishResult.isSuccess()) {
				callouts.add(
					new Integration_Callout__c(Name = 'WorkBadgeMissionEvent__e - ' + publishResult.getId())
				);
			}
		}
		Database.SaveResult[] insertResults = Database.insert(callouts);
		Logger.logDatabaseErrors(
				LoggingLevel.ERROR,
				'IdeaCommentTriggerHandler.publishWorkBadgeMissionEvent() ERRORS',
				insertResults
			)
			.addTag('apex');
		Logger.saveLog();
	}
}