objects/ELV_Order_Event__e/ELV_Order_Event__e.object-meta.xml
<CustomObject>
    <description>Platform Event on Order Object to be consumed by Workato. Clone of Order_Event__e sourcing Quote data from the standard Quote object (NUE) instead of SBQQ__Quote__c, published when an Order is activated.</description>
    <label>ELV Order Event</label>
    <pluralLabel>ELV Order Events</pluralLabel>
</CustomObject>

objects/Integration_Callout__c/Integration_Callout__c.object-meta.xml
<CustomObject>
    <description>The object stores the result of an outbound callout to third party system for logging purposes</description>
    <label>Integration Callout</label>
    <nameField>
        <label>Integration Callout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Callout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order/fields/Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Entity_ID__c</fullName>
    <formula>IF(ISBLANK(Quote.ELV_Partner__c), Account.Netsuite_ID__c, Quote.ELV_Partner__r.Netsuite_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity ID</label>
    <type>Text</type>
</CustomField>

objects/Order/fields/Owner_Department_ID__c.field-meta.xml
<CustomField>
    <fullName>Owner_Department_ID__c</fullName>
    <formula>Opportunity.Owner.Department_Internal_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Department ID</label>
    <type>Text</type>
</CustomField>

objects/Order/fields/Owner_Location_ID__c.field-meta.xml
<CustomField>
    <fullName>Owner_Location_ID__c</fullName>
    <formula>Opportunity.Owner.Location_Internal_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Location ID</label>
    <type>Text</type>
</CustomField>

objects/Order/fields/Owner_NS_ID__c.field-meta.xml
<CustomField>
    <fullName>Owner_NS_ID__c</fullName>
    <description>Do not delete, used in integration</description>
    <formula>Opportunity.Owner.NS_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>NS ID of the Opportunity Owner</inlineHelpText>
    <label>Owner NS ID</label>
    <type>Text</type>
</CustomField>

objects/Order/fields/Reseller_NS__c.field-meta.xml
<CustomField>
    <fullName>Reseller_NS__c</fullName>
    <formula>IF(ISBLANK(Quote.ELV_Partner__c), &quot;1&quot;, &quot;2&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reseller NS</label>
    <type>Text</type>
</CustomField>

objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order/fields/Subsidiary__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary__c</fullName>
    <formula>IF(ISPICKVAL(Opportunity.StageName, &quot;POC&quot;), Account.NS_Subsidiary__c, Quote.ELV_Legal_Entity__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NS Subsidiary</label>
    <type>Text</type>
</CustomField>

objects/Order/fields/Subsidiary_NS__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_NS__c</fullName>
    <formula>IF(ISPICKVAL(Opportunity.StageName, &quot;POC&quot;), Account.NS_Subsidiary_ID__c, Quote.ELV_Legal_Entity__r.NS_Legal_Entity_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NS Subsidiary ID</label>
    <type>Text</type>
</CustomField>

objects/OrderItem/fields/Subsidiary_NS__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_NS__c</fullName>
    <formula>Order.Subsidiary__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NS Subsidiary</label>
    <type>Text</type>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c/fields/First_Billing_Override__c.field-meta.xml
<CustomField>
    <fullName>First_Billing_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Billing Override</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/No_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>No_of_Installments__c</fullName>
    <defaultValue>1</defaultValue>
    <label>No of Installments</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/fields/PaymentTypeNew__c.field-meta.xml
<CustomField>
    <fullName>PaymentTypeNew__c</fullName>
    <defaultValue>&quot;Upfront&quot;</defaultValue>
    <description>Payment Type used to bill the customer</description>
    <inlineHelpText>Payment Type used to bill the customer</inlineHelpText>
    <label>Billing Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentType</valueSetName>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Check as Primary if opportunity NACV should be calculated off of this quote (each opportunity has one primary quote and it should reflect the most likely scenario).</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CEO/Finance Approval</fullName>
            </value>
            <value>
                <fullName>COE Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Lead Approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>RVP Approval</fullName>
            </value>
            <value>
                <fullName>Upper Management Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Length of the deal, in whole months</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/OrderTriggerUtilityTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for OrderTriggerHandler and OrderTriggerUtility
 * @Date: 2023-08-04
 * @Author: Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-7566    2024-03-01    Updated test class
 * SS-7583    2024-03-21    Removing BoomiRestService code references
 * SS-12400   2026-01-22    Removed CAM_Name__c field from test class
 * SS-13646   2026-08-12    Moved OrderTriggerHandlerTest coverage here
 */
@IsTest
private class OrderTriggerUtilityTest {
	@TestSetup
	static void makeData() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'ContactTriggerHandler',
				'OpportunityTriggerHandler',
				'QuoteCPQTriggerHandler'
			}
		);

		Id currentUserId = UserInfo.getUserId();
		System.runAs(TestUserFactory.getAdminUser()) {
			TestFactory.seedRubySettings();

			Pricebook2 globalPriceBook = new Pricebook2(
				Name = 'Global Pricebook',
				Description = 'Global Pricebook description.',
				IsActive = true
			);
			String fieldApiName = 'Ruby__PriceAttributes__c';
			Map<String, Schema.SObjectField> pricebookFields = Schema.SObjectType.Pricebook2.fields.getMap();
			if (pricebookFields.containsKey(fieldApiName)) {
				globalPriceBook.put(fieldApiName, 'Currency;UOM');
			}
			insert globalPriceBook;

			Account acct = TestFactory.buildAccount('Test Account');
			insert acct;
			Opportunity opp = TestFactory.buildOpportunity(
				'Test Opportunity',
				Date.today() + 30,
				'Prospecting',
				acct.Id
			);
			opp.OwnerId = currentUserId;
			insert opp;

			SBQQ__Quote__c quote = new SBQQ__Quote__c(
				SBQQ__StartDate__c = Date.today(),
				SBQQ__EndDate__c = Date.today().addDays(30),
				SBQQ__Opportunity2__c = opp.Id,
				SBQQ__PriceBook__c = globalPriceBook.Id,
				SBQQ__Account__c = acct.Id,
				SBQQ__Status__c = 'Accepted',
				SBQQ__Type__c = 'Quote',
				SBQQ__SubscriptionTerm__c = 30,
				PaymentTypeNew__c = BillingScheduleConfiguratorController.ANNUAL_PAYMENT_TYPE,
				First_Billing_Override__c = false,
				No_of_Installments__c = 2,
				SBQQ__Primary__c = true
			);
			insert quote;

			Quote nueQuote = new Quote(
				Name = 'Test NUE Quote',
				OpportunityId = opp.Id,
				Pricebook2Id = globalPriceBook.Id,
				BillingCity = 'Kirkland'
			);
			insert nueQuote;

			Order sbqqOrder = new Order(
				AccountId = acct.Id,
				OpportunityId = opp.Id,
				SBQQ__Quote__c = quote.Id,
				Pricebook2Id = globalPriceBook.Id,
				EffectiveDate = System.today(),
				Status = 'Draft'
			);
			insert sbqqOrder;

			Order nueOrder = new Order(
				AccountId = acct.Id,
				OpportunityId = opp.Id,
				QuoteId = nueQuote.Id,
				Pricebook2Id = globalPriceBook.Id,
				EffectiveDate = System.today(),
				Status = 'Draft'
			);
			insert nueOrder;

			Product2 product = TestFactory.buildProduct('Test Product', 'TEST-PROD-1');
			insert product;

			PricebookEntry standardPricebookEntry = TestFactory.buildPricebookEntry(
				product.Id,
				10.00,
				TestFactory.STANDARD_PRICEBOOK_ID
			);
			insert standardPricebookEntry;

			PricebookEntry globalPricebookEntry = TestFactory.buildPricebookEntry(
				product.Id,
				10.00,
				globalPriceBook.Id
			);
			insert globalPricebookEntry;

			insert new OrderItem(
				OrderId = nueOrder.Id,
				PricebookEntryId = globalPricebookEntry.Id,
				Quantity = 1,
				UnitPrice = 10.00
			);
		}
	}

	@IsTest
	static void testPublishOrders_Always_PublishOrders() {
		List<Order> orders = [
			SELECT
				Id,
				CreatedDate,
				AccountId,
				Entity_ID__c,
				OpportunityId,
				SBQQ__Quote__c,
				OrderNumber,
				Owner_Department_ID__c,
				Owner_Location_ID__c,
				Owner_NS_ID__c,
				Reseller_NS__c,
				Subsidiary__c,
				Subsidiary_NS__c,
				TotalAmount
			FROM Order
		];
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			OrderTriggerUtility.publishOrders(orders);
			Test.stopTest();
		}
		List<Integration_Callout__c> callouts = [SELECT Id FROM Integration_Callout__c];
		Assert.isFalse(callouts.isEmpty());
	}

	@IsTest
	static void testPublishNueOrderEvents_OrderNewlyActivated_PublishOrders() {
		List<Order> orders = [
			SELECT
				Id,
				CreatedDate,
				AccountId,
				Entity_ID__c,
				OpportunityId,
				QuoteId,
				OrderNumber,
				Owner_Department_ID__c,
				Owner_Location_ID__c,
				Owner_NS_ID__c,
				Reseller_NS__c,
				Status,
				Subsidiary__c,
				Subsidiary_NS__c,
				TotalAmount
			FROM Order
			WHERE QuoteId != null
		];
		Map<Id, Order> oldOrderMap = new Map<Id, Order>(orders.deepClone(true, true, true));
		for (Order order : orders) {
			order.Status = 'Activated';
		}

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			OrderTriggerUtility.publishNueOrderEvents(orders, oldOrderMap);
			Test.stopTest();
		}
		List<Integration_Callout__c> callouts = [
			SELECT Id
			FROM Integration_Callout__c
			WHERE Name LIKE 'ELV_Order_Event__e%'
		];
		Assert.isFalse(callouts.isEmpty());
	}

	@IsTest
	static void testAfterUpdate_OrderActivatedViaDml_PublishesNueOrderEvent() {
		List<Order> orders = [SELECT Id, Status FROM Order WHERE QuoteId != null];
		for (Order order : orders) {
			order.Status = 'Activated';
		}

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			update orders;
			Test.stopTest();
		}

		List<Integration_Callout__c> callouts = [
			SELECT Id
			FROM Integration_Callout__c
			WHERE Name LIKE 'ELV_Order_Event__e%'
		];
		Assert.isFalse(callouts.isEmpty());
	}
}