objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <description>Object that will store the data pertaining to Product Modules. This data should match the Module list that is used by the Provisioner team to entitle customers to Tanium Modules.</description>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POC_Request__c/POC_Request__c.object-meta.xml
<CustomObject>
    <description>Custom Object to request and trigger POC process</description>
    <label>POC Request</label>
    <nameField>
        <label>POC Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POC_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner: On-Prem, Partner: Tanium Cloud</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer: On-Prem, HFPOC, Customer: Tanium Cloud</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POC Requests</relationshipLabel>
    <relationshipName>POC_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/POC_Request__c/fields/Approval_Stage__c.field-meta.xml
<CustomField>
    <fullName>Approval_Stage__c</fullName>
    <label>Approval Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request needs to be submitted for approval</fullName>
                <default>true</default>
                <label>Request needs to be submitted for approval</label>
            </value>
            <value>
                <fullName>Awaiting for Approval</fullName>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Fully Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missing Info</fullName>
                <isActive>false</isActive>
                <label>Missing Info</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/POC_Request__c/fields/Deployment_Method__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Method__c</fullName>
    <description>Designates the Deployment Method for this POC Request, based on the Server Deployment. Jira ticket SS-12115</description>
    <formula>IF(ISBLANK(Server_Deployment__c), NULL, IF(CONTAINS(Server_Deployment__r.RecordType.Name, &apos;Cloud&apos;), &apos;Cloud&apos;, &apos;On-Prem&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Designates the Deployment Method for this POC Request, based on the Server Deployment</inlineHelpText>
    <label>Deployment Method</label>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/Selected_Modules__c.field-meta.xml
<CustomField>
    <fullName>Selected_Modules__c</fullName>
    <description>Provides a list of the Solution fields that have been checked on the record. Jira ticket SS-12115</description>
    <formula>IF(Asset_SBOM__c,&apos;Asset_SBOM__c,&apos;, NULL) &amp;
IF(Certificate_Manager__c,&apos;Certificate_Manager__c,&apos;, NULL) &amp;
IF(Comply__c,&apos;Comply__c,&apos;, NULL) &amp;
IF(Core__c,&apos;Core__c,&apos;, NULL) &amp;
IF(Deploy__c,&apos;Deploy__c,&apos;, NULL) &amp;
IF(Discover__c,&apos;Discover__c,&apos;, NULL) &amp;
IF(Enforce__c,&apos;Enforce__c,&apos;, NULL) &amp;
IF(Engage__c,&apos;Engage__c,&apos;, NULL) &amp;
IF(Impact__c,&apos;Impact__c,&apos;, NULL) &amp;
IF(Integrity_Monitor__c,&apos;Integrity_Monitor__c,&apos;, NULL) &amp;
IF(Investigate__c,&apos;Investigate__c,&apos;, NULL) &amp;
IF(Map__c,&apos;Map__c,&apos;, NULL) &amp;
IF(Patch__c,&apos;Patch__c,&apos;, NULL) &amp;
IF(Performance__c,&apos;Performance__c,&apos;, NULL) &amp;
IF(Provision__c,&apos;Provision__c,&apos;, NULL) &amp;
IF(Reveal__c,&apos;Reveal__c,&apos;, NULL) &amp;
IF(Risk__c,&apos;Risk__c,&apos;, NULL) &amp;
IF(Threat_Response__c,&apos;Threat_Response__c&apos;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Provides a list of the Solution fields that have been checked on the record</inlineHelpText>
    <label>Selected Modules</label>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/Selected_Solutions__c.field-meta.xml
<CustomField>
    <fullName>Selected_Solutions__c</fullName>
    <description>Provides a list of the Solution fields that have been checked on the record. Jira ticket SS-12115</description>
    <formula>IF(Core_Plus__c,&apos;Core_Plus__c,&apos;, NULL) &amp;
IF(Core_Standard__c,&apos;Core_Standard__c,&apos;, NULL) &amp;
IF(Endpoint_Management_Plus__c,&apos;Endpoint_Management_Plus__c,&apos;, NULL) &amp;
IF(Endpoint_Management_Standard__c,&apos;Endpoint_Management_Standard__c,&apos;, NULL) &amp;
IF(Incident_Response__c,&apos;Incident_Response__c,&apos;, NULL) &amp;
IF(Risk_Compliance_Plus__c,&apos;Risk_Compliance_Plus__c,&apos;, NULL) &amp;
IF(Risk_Compliance_Standard__c,&apos;Risk_Compliance_Standard__c&apos;, NULL)</formula>
    <inlineHelpText>Provides a list of the Solution fields that have been checked on the record</inlineHelpText>
    <label>Selected Solutions</label>
    <type>Text</type>
</CustomField>

objects/POC_Request__c/fields/Server_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Server_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Server Deployment object (records)</description>
    <inlineHelpText>Lookup field to the Server Deployment object (records).</inlineHelpText>
    <label>Server Deployment</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Server Deployment selected does not meet filter criteria. The Server Deployment must be active, be on the same Account as this POC and can not be in POC/Pilot</errorMessage>
        <filterItems>
            <field>Server_Deployment__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Server_Deployment__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Server_Deployment__c.Type__c</field>
            <operation>notEqual</operation>
            <value>POC/Pilot</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Server_Deployment__c</referenceTo>
    <relationshipLabel>POC Requests</relationshipLabel>
    <relationshipName>POC_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/POC_Request_Solution_and_Module_Map__c/POC_Request_Solution_and_Module_Map__c.object-meta.xml
<CustomObject>
    <description>Contains a cross reference from fields on the POC Request to their corresponding Products and/or Modules</description>
    <label>POC Request Solution and Module Map</label>
    <nameField>
        <label>POC Request Solution and Module Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POC Request Solution and Module Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POC_Request_Solution_and_Module_Map__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Module record. Jira ticket SS-12115</description>
    <inlineHelpText>Lookup to the Module record</inlineHelpText>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>POC Request Solution and Module Map</relationshipLabel>
    <relationshipName>POC_Request_Solution_and_Module_Map</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/POC_Request_Solution_and_Module_Map__c/fields/POC_Field_Label__c.field-meta.xml
<CustomField>
    <fullName>POC_Field_Label__c</fullName>
    <description>The API name of the field on the POC Request form. This will be used for lookup in Apex</description>
    <inlineHelpText>The API name of the field on the POC Request form. This will be used for lookup in Apex</inlineHelpText>
    <label>POC Field Label</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/POC_Request_Solution_and_Module_Map__c/fields/Product_Cloud__c.field-meta.xml
<CustomField>
    <fullName>Product_Cloud__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Cloud product record. Jira ticket SS-12115</description>
    <inlineHelpText>Lookup to the Cloud product record</inlineHelpText>
    <label>Product - Cloud</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>POC Request Solution and Module Map</relationshipLabel>
    <relationshipName>POC_Request_Solution_and_Module_Map</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/POC_Request_Solution_and_Module_Map__c/fields/Product_On_Prem__c.field-meta.xml
<CustomField>
    <fullName>Product_On_Prem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the On-Prem product record. Jira ticket SS-12115</description>
    <inlineHelpText>Lookup to the On-Prem product record</inlineHelpText>
    <label>Product - On-Prem</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>POC Request Solution and Module Map (Product - On-Prem)</relationshipLabel>
    <relationshipName>POC_Request_Solution_and_Module_Map1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Server_Deployment__c/Server_Deployment__c.object-meta.xml
<CustomObject>
    <description>The Server Deployment Object tracks important technical characteristics about a Production, Test, QA, or Evaluation deployment to provide the support team background information when responding to requests for assistance as well as to gather metrics for Product Management to understand typical configuration and usage.  The object includes two additional Objects--the Client and Zone Server.

2014 | JR</description>
    <label>Server Deployment</label>
    <nameField>
        <label>Instance/Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Server_Deployment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Server Deployments</relationshipLabel>
    <relationshipName>Server_Deployments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

classes/POCRequestTriggerUtility.cls
/**
 * Copyright (c) 2025 Tanium
 *
 * @Business: POCRequest Trigger Utility, part of Trigger Framework
 * @Date: 2025-11-13
 * @Author: Tanium Dev Team
 * RequestId    ModifiedDate    Description
 * SS-12077     2025-11-13      Initial development
 */
public class POCRequestTriggerUtility {
	public static void handleApprovedPOCRequests(
		List<POC_Request__c> pocRequests,
		Map<Id, POC_Request__c> oldMap
	) {
		List<POC_Request__c> approvedPOCRequestsSolutions = new List<POC_Request__c>();
		List<POC_Request__c> approvedPOCRequestsModules = new List<POC_Request__c>();
		Map<Id, Server_Deployment__c> accountIdToServerDeployment = new Map<Id, Server_Deployment__c>();
		Set<Id> accountIds = new Set<Id>();

		for (POC_Request__c pocRequest : pocRequests) {
			if (
				pocRequest.Approval_Stage__c != oldMap.get(pocRequest.Id).Approval_Stage__c &&
				pocRequest.Approval_Stage__c == 'Fully Approved' &&
				String.isNotBlank(pocRequest.Deployment_Method__c)
			) {
				if (String.isNotBlank(pocRequest.Selected_Modules__c)) {
					approvedPOCRequestsModules.add(pocRequest);
					accountIds.add(pocRequest.Account__c);
				}
				if (String.isNotBlank(pocRequest.Selected_Solutions__c)) {
					approvedPOCRequestsSolutions.add(pocRequest);
					accountIds.add(pocRequest.Account__c);
				}
			}
		}

		for (Server_Deployment__c serverDeployment : [
			SELECT Id, Account__c
			FROM Server_Deployment__c
			WHERE Account__c IN :accountIds
		]) {
			accountIdToServerDeployment.put(serverDeployment.Account__c, serverDeployment);
		}

		if (!approvedPOCRequestsModules.isEmpty()) {
			handleApprovedPOCRequestModules(approvedPOCRequestsModules, accountIdToServerDeployment);
		}

		if (!approvedPOCRequestsSolutions.isEmpty()) {
			handleApprovedPOCRequestSolutions(
				approvedPOCRequestsSolutions,
				accountIdToServerDeployment
			);
		}
	}

	private static void handleApprovedPOCRequestModules(
		List<POC_Request__c> approvedPOCRequestModules,
		Map<Id, Server_Deployment__c> accountIdToServerDeployment
	) {
		Map<Id, POC_Request__c> pocRequestMap = new Map<Id, POC_Request__c>();
		Map<Id, List<Id>> pocRequestIdToModuleIds = new Map<Id, List<Id>>();

		for (POC_Request__c pocRequest : approvedPOCRequestModules) {
			pocRequestMap.put(pocRequest.Id, pocRequest);
			pocRequestIdToModuleIds.put(pocRequest.Id, buildModuleIds(pocRequest));
		}

		if (!pocRequestIdToModuleIds.isEmpty()) {
			AccountEntitlementTriggerUtility.createAccountEntitlementsPOCRequestModules(
				pocRequestMap,
				pocRequestIdToModuleIds,
				accountIdToServerDeployment
			);
		}
	}

	private static void handleApprovedPOCRequestSolutions(
		List<POC_Request__c> approvedPOCRequestsSolutions,
		Map<Id, Server_Deployment__c> accountIdToServerDeployment
	) {
		Map<Id, POC_Request__c> productIdToPOCRequest = new Map<Id, POC_Request__c>();

		for (POC_Request__c pocRequest : approvedPOCRequestsSolutions) {
			productIdToPOCRequest.putAll(buildProductIdToPOCRequestMap(pocRequest));
		}

		if (!productIdToPOCRequest.isEmpty()) {
			AccountEntitlementTriggerUtility.createAccountEntitlementsPOCRequestSolutions(
				productIdToPOCRequest,
				accountIdToServerDeployment
			);
		}
	}

	private static List<Id> buildModuleIds(POC_Request__c pocRequest) {
		List<Id> moduleIds = new List<Id>();
		List<String> selectedModules = pocRequest.Selected_Modules__c.split(',');

		for (POC_Request_Solution_and_Module_Map__c pocRequestSolutionAndModuleMap : [
			SELECT Id, POC_Field_Label__c, Module__c
			FROM POC_Request_Solution_and_Module_Map__c
			WHERE Module__c != NULL AND POC_Field_Label__c IN :selectedModules
		]) {
			moduleIds.add(pocRequestSolutionAndModuleMap.Module__c);
		}

		return moduleIds;
	}

	private static Map<Id, POC_Request__c> buildProductIdToPOCRequestMap(POC_Request__c pocRequest) {
		Map<Id, POC_Request__c> productIdToPOCRequest = new Map<Id, POC_Request__c>();
		List<String> selectedSolutions = pocRequest.Selected_Solutions__c.split(',');

		for (POC_Request_Solution_and_Module_Map__c pocRequestSolutionAndModuleMap : [
			SELECT Id, POC_Field_Label__c, Product_Cloud__c, Product_On_Prem__c
			FROM POC_Request_Solution_and_Module_Map__c
			WHERE POC_Field_Label__c IN :selectedSolutions
		]) {
			if (pocRequest.Deployment_Method__c == 'Cloud') {
				productIdToPOCRequest.put(pocRequestSolutionAndModuleMap.Product_Cloud__c, pocRequest);
			} else if (pocRequest.Deployment_Method__c == 'On-Prem') {
				productIdToPOCRequest.put(
					pocRequestSolutionAndModuleMap.Product_On_Prem__c,
					pocRequest
				);
			}
		}

		return productIdToPOCRequest;
	}
}