objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>The quote where the order is created from.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>If(ISBLANK( SBQQ__EndDate__c),If(ISBLANK(SBQQ__Quote__r.SBQQ__EndDate__c) , End_Date_Formula__c -1,SBQQ__Quote__r.SBQQ__EndDate__c),SBQQ__EndDate__c)</description>
    <formula>IF( SBQQ__Product__r.Do_Not_Show_End_Date__c = TRUE, NULL,If(ISBLANK( SBQQ__EndDate__c),If(ISBLANK(SBQQ__Quote__r.SBQQ__EndDate__c) , End_Date_Formula__c -1,SBQQ__Quote__r.SBQQ__EndDate__c),SBQQ__EndDate__c))</formula>
    <inlineHelpText>Computed End Date based on Start Date &amp; Term</inlineHelpText>
    <label>End Date Comp</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Prod_Max_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Prod_Max_End_Date__c</fullName>
    <label>Prod Max End Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Prod_Min_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Prod_Min_Start_Date__c</fullName>
    <label>Prod Min Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appliance</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Authoring</fullName>
            </value>
            <value>
                <fullName>Connect</fullName>
            </value>
            <value>
                <fullName>Trends</fullName>
            </value>
            <value>
                <fullName>Platform</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>Trace</fullName>
            </value>
            <value>
                <fullName>Patch</fullName>
            </value>
            <value>
                <fullName>IOC Detect</fullName>
            </value>
            <value>
                <fullName>Comply</fullName>
            </value>
            <value>
                <fullName>Protect</fullName>
            </value>
            <value>
                <fullName>FIM</fullName>
            </value>
            <value>
                <fullName>Security Suite</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>ELA</fullName>
            </value>
            <value>
                <fullName>Premium Support</fullName>
            </value>
            <value>
                <fullName>Interact</fullName>
            </value>
            <value>
                <fullName>Core-LTD</fullName>
            </value>
            <value>
                <fullName>Core-UPG</fullName>
            </value>
            <value>
                <fullName>IR</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>IC</fullName>
            </value>
            <value>
                <fullName>IOC Funnel</fullName>
            </value>
            <value>
                <fullName>Server</fullName>
            </value>
            <value>
                <fullName>VMWare</fullName>
            </value>
            <value>
                <fullName>Tanium Threat Response</fullName>
            </value>
            <value>
                <fullName>Converge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/TRAC_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TRAC_StartDate__c</fullName>
    <description>Used to copy data across to the OppLine record using Twin field functionality</description>
    <formula>SBQQ__StartDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TRAC_StartDate</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Required field per case 59475</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Upsell</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>POC/Trial</fullName>
            </value>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Ramp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/CalculateARRQuote.cls
/**
 * @Business: Do ARR calcuation on Quote (SBQQ__Quote__c & SBQQ__QuoteLine__c)
 * @Date: 2018-11-23
 * @Author: Cumulus Vision
 * @Request: TAN-710
 * Modified  ModifiedDate   Description
 * TAN-710   2018-11-23     Initial Development
 */

global class CalculateARRQuote {
	@AuraEnabled
	webService static String recalculateARR(String quoteId) {
		List<SBQQ__QuoteLine__c> quoteLineList = [
			SELECT
				Id,
				SBQQ__Product__c,
				End_Date__c,
				TRAC_StartDate__c,
				Prod_Max_End_Date__c,
				Prod_Min_Start_Date__c,
				Transaction_Type__c,
				Product_Line__c
			FROM SBQQ__QuoteLine__c
			WHERE SBQQ__Quote__c = :quoteId AND Transaction_Type__c != NULL AND Product_Line__c != NULL
			ORDER BY SBQQ__Product__c
		];

		quoteLineList = doARRCalculations(quoteLineList);
		update quoteLineList;

		return 'done';
	}

	public static List<SBQQ__QuoteLine__c> doARRCalculations(List<SBQQ__QuoteLine__c> quoteLineList) {
		Map<String, Date> startDatesMap = new Map<String, Date>();
		Map<String, Date> endDatesMap = new Map<string, Date>();

		for (SBQQ__QuoteLine__c quoteLine : quoteLineList) {
			if (startDatesMap.get(quoteLine.Product_Line__c + quoteLine.Transaction_Type__c) == null) {
				startDatesMap.put(
					quoteLine.Product_Line__c + quoteLine.Transaction_Type__c,
					quoteLine.TRAC_StartDate__c
				);
			} else {
				Date lastStartDate = startDatesMap.get(
					quoteLine.Product_Line__c + quoteLine.Transaction_Type__c
				);
				if (quoteLine.TRAC_StartDate__c < lastStartDate) {
					startDatesMap.put(
						quoteLine.Product_Line__c + quoteLine.Transaction_Type__c,
						quoteLine.TRAC_StartDate__c
					);
				}
			}

			if (endDatesMap.get(quoteLine.Product_Line__c + quoteLine.Transaction_Type__c) == null) {
				endDatesMap.put(
					quoteLine.Product_Line__c + quoteLine.Transaction_Type__c,
					quoteLine.End_Date__c
				);
			} else {
				Date lastEndDate = endDatesMap.get(
					quoteLine.Product_Line__c + quoteLine.Transaction_Type__c
				);
				if (quoteLine.End_Date__c > lastEndDate) {
					endDatesMap.put(
						quoteLine.Product_Line__c + quoteLine.Transaction_Type__c,
						quoteLine.End_Date__c
					);
				}
			}
		}

		for (SBQQ__QuoteLine__c quoteLine : quoteLineList) {
			if (startDatesMap.get(quoteLine.Product_Line__c + quoteLine.Transaction_Type__c) != null) {
				quoteLine.Prod_Min_Start_Date__c = startDatesMap.get(
					quoteLine.Product_Line__c + quoteLine.Transaction_Type__c
				);
			}

			if (endDatesMap.get(quoteLine.Product_Line__c + quoteLine.Transaction_Type__c) != null) {
				quoteLine.Prod_Max_End_Date__c = endDatesMap.get(
					quoteLine.Product_Line__c + quoteLine.Transaction_Type__c
				);
			}
		}

		return quoteLineList;
	}
}