objects/X7S_Event__c/X7S_Event__c.object-meta.xml
<CustomObject>
    <description>Object to support Events records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X7S_Event__c/fields/Event_Format__c.field-meta.xml
<CustomField>
    <fullName>Event_Format__c</fullName>
    <label>Event Format</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_Integration_Setting__mdt/X7S_Event_Integration_Setting__mdt.object-meta.xml
<CustomObject>
    <label>7S Event Integration Setting</label>
    <pluralLabel>7S Event Integration Settings</pluralLabel>
</CustomObject>

objects/X7S_Event_Integration_Setting__mdt/fields/Virtual_Platform__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Platform__c</fullName>
    <label>Virtual Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Zoom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/x7sEventsExternalMeetingFactory.cls
/*
 * Licensed Materials - Property of IBM
 * 6949-82P
 * © Copyright IBM Corp. 2022 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

public with sharing class x7sEventsExternalMeetingFactory {
	public static x7sEventsIExternalMeeting getExternalMeeting(X7S_Event__c event) {
		x7sEventsIExternalMeeting externalMeeting = null;

		X7S_Event_Integration_Setting__mdt integrationSetting = X7S_Event_Integration_Setting__mdt.getInstance(
			event.Event_Format__c
		);

		if (
			integrationSetting != null &&
			integrationSetting.Virtual_Platform__c == x7sEventsExternalMeetingConstants.ZOOM
		) {
			externalMeeting = new x7sEventsExternalMeetingZoom();
		} else {
			System.debug('Defaulting to Default External Meeting Interface.');
			externalMeeting = new x7sEventsExternalMeetingDefault();
		}

		return externalMeeting;
	}
}