objects/X7S_Event__c/X7S_Event__c.object-meta.xml
<CustomObject>
    <description>Object to support Events records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X7S_Event__c/fields/Event_Format__c.field-meta.xml
<CustomField>
    <fullName>Event_Format__c</fullName>
    <label>Event Format</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event__c/fields/Host_Email__c.field-meta.xml
<CustomField>
    <fullName>Host_Email__c</fullName>
    <description>Email address of the meeting host</description>
    <label>Host Email</label>
    <type>Email</type>
</CustomField>

objects/X7S_Event__c/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meeting</fullName>
                <default>true</default>
                <label>Meeting</label>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/X7S_Event__c/fields/MeetingId__c.field-meta.xml
<CustomField>
    <fullName>MeetingId__c</fullName>
    <defaultValue>null</defaultValue>
    <description>Unique identifier of the meeting</description>
    <label>MeetingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event__c/fields/NetworkId__c.field-meta.xml
<CustomField>
    <fullName>NetworkId__c</fullName>
    <label>NetworkId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event__c/fields/Number_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attendees__c</fullName>
    <label>Number of Attendees</label>
    <summaryFilterItems>
        <field>X7S_Event_RSVP__c.Response__c</field>
        <operation>equals</operation>
        <value>Attending</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>X7S_Event_RSVP__c.Registration_Status__c</field>
        <operation>notEqual</operation>
        <value>pending</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>X7S_Event_RSVP__c.Registration_Status__c</field>
        <operation>notEqual</operation>
        <value>denied</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>X7S_Event_RSVP__c.Response__c</field>
        <operation>notEqual</operation>
        <value>Waitlist</value>
    </summaryFilterItems>
    <summaryForeignKey>X7S_Event_RSVP__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/X7S_Event__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None Required</fullName>
                <default>true</default>
                <label>None Required</label>
            </value>
            <value>
                <fullName>Auto Approval</fullName>
            </value>
            <value>
                <fullName>Manual Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/X7S_Event__c/fields/Registration_Url__c.field-meta.xml
<CustomField>
    <fullName>Registration_Url__c</fullName>
    <description>Url to use for external meeting registration</description>
    <label>Registration Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of meeting.</description>
    <label>Type</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/X7S_Event_Reg_Field__mdt/X7S_Event_Reg_Field__mdt.object-meta.xml
<CustomObject>
    <description>7S Event Registration Field</description>
    <label>7S Event Reg Field</label>
    <pluralLabel>7S Event Reg Fields</pluralLabel>
</CustomObject>

objects/X7S_Event_Reg_Field__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>Field API Name</description>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/X7S_Event_Reg_Field__mdt/fields/Tooltip_Text__c.field-meta.xml
<CustomField>
    <fullName>Tooltip_Text__c</fullName>
    <description>Text to display as tooltip.</description>
    <label>Tooltip Text</label>
    <type>TextArea</type>
</CustomField>

objects/X7S_Event_Reg_Field__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/X7S_Event_Reg_Field_Set__mdt/X7S_Event_Reg_Field_Set__mdt.object-meta.xml
<CustomObject>
    <description>7S Event Registration Field Set</description>
    <label>7S Event Reg Field Set</label>
    <pluralLabel>7S Event Reg Field Sets</pluralLabel>
</CustomObject>

objects/X7S_Event_Reg_Field_Set__mdt/fields/All_Fields_Required__c.field-meta.xml
<CustomField>
    <fullName>All_Fields_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Optional - way to make all fields required.</description>
    <inlineHelpText>Optional - way to make all fields required.</inlineHelpText>
    <label>All Fields Required</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Event_Reg_Field_Set_Assignment__mdt/X7S_Event_Reg_Field_Set_Assignment__mdt.object-meta.xml
<CustomObject>
    <description>7S Event Registration Field Set Assignment</description>
    <label>7S Event Reg Field Set Assignment</label>
    <pluralLabel>7S Event Reg Field Set Assignments</pluralLabel>
</CustomObject>

objects/X7S_Event_Reg_Field_Set_Assignment__mdt/fields/Field_Label_Override__c.field-meta.xml
<CustomField>
    <fullName>Field_Label_Override__c</fullName>
    <description>Override existing field name</description>
    <label>Field Label Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_Reg_Field_Set_Assignment__mdt/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Mark a field as required.</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Event_Reg_Field_Set_Assignment__mdt/fields/X7S_Event_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>X7S_Event_Field_Name__c</fullName>
    <label>7S Event Field Name</label>
    <referenceTo>X7S_Event_Reg_Field__mdt</referenceTo>
    <relationshipLabel>7S Event Reg Field Set Assignments</relationshipLabel>
    <relationshipName>X7S_Event_Reg_Field_Set_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

objects/X7S_Event_Reg_Field_Set_Assignment__mdt/fields/X7S_Event_Field_Set_Name__c.field-meta.xml
<CustomField>
    <fullName>X7S_Event_Field_Set_Name__c</fullName>
    <label>7S Event Field Set Name</label>
    <referenceTo>X7S_Event_Reg_Field_Set__mdt</referenceTo>
    <relationshipLabel>7S Event Reg Field Set Assignments</relationshipLabel>
    <relationshipName>X7S_Event_Reg_Field_Set_Assignments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

objects/X7S_Event_Reg_Setting__mdt/X7S_Event_Reg_Setting__mdt.object-meta.xml
<CustomObject>
    <description>7S Event Registration Setting</description>
    <label>7S Event Reg Setting</label>
    <pluralLabel>7S Event Reg Settings</pluralLabel>
</CustomObject>

objects/X7S_Event_Reg_Setting__mdt/fields/X7S_Event_Reg_Field_Set__c.field-meta.xml
<CustomField>
    <fullName>X7S_Event_Reg_Field_Set__c</fullName>
    <description>Associated Field Set</description>
    <label>7S Event Reg Field Set</label>
    <referenceTo>X7S_Event_Reg_Field_Set__mdt</referenceTo>
    <relationshipLabel>7S Event Reg Settings</relationshipLabel>
    <relationshipName>X7S_Event_Registration_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

objects/X7S_Event_RSVP__c/X7S_Event_RSVP__c.object-meta.xml
<CustomObject>
    <description>Object to support Event RSVP records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event RSVP</label>
    <nameField>
        <displayFormat>RSVP-{0000}</displayFormat>
        <label>Event RSVP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>7S Event RSVPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/X7S_Event_RSVP__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>7S Event RSVPs</relationshipLabel>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Will be populated automatically and set to read only if a authenticated user is the owner</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>X7S_Event__c</referenceTo>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Event_Segment__c.field-meta.xml
<CustomField>
    <fullName>Event_Segment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>7S Event Segment</label>
    <referenceTo>X7S_Event_Segment__c</referenceTo>
    <relationshipLabel>7S Event RSVPs</relationshipLabel>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Will be populated automatically and set to read only if a authenticated user is the owner</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Will be populated automatically and set to read only if a authenticated user is the owner</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Registration_Id__c</fullName>
    <description>Populated by external service</description>
    <label>Registration Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration_Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Registration_Url__c.field-meta.xml
<CustomField>
    <fullName>Registration_Url__c</fullName>
    <description>Populated by external service</description>
    <label>Registration Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/X7S_Event_RSVP__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attending</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/X7S_Event_RSVP__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>X7S_Event_RSVPs</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/X7S_Event_Segment__c/X7S_Event_Segment__c.object-meta.xml
<CustomObject>
    <description>Object to support Event Segment records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event Segment</label>
    <nameField>
        <label>7S Event Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Event Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/X7S_Event_Segment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>X7S_Event__c</referenceTo>
    <relationshipLabel>7S Event Segments</relationshipLabel>
    <relationshipName>X7S_Event_Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/X7S_Event_Segment__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-person</fullName>
                <default>true</default>
                <label>In-person</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Overall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/x7sEventsRegistration.cls
/*
 * Licensed Materials - Property of IBM
 * 6949-82P
 * © Copyright IBM Corp. 2022 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

public with sharing class x7sEventsRegistration {
	public class EventsRegistrationException extends Exception {
	}

	static public Map<String, List<SObject>> MetadataCoverageRecordMap = new Map<String, List<SObject>>();

	// Current community ID
	private static Id communityId {
		get {
			return System.Network.getNetworkId();
		}
	}

	private static Id getContactId() {
		return [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() WITH SECURITY_ENFORCED]
		?.ContactId;
	}

	/**
	 * @description Method to fetch the rsvp member status. Whether they are joining or not.
	 * @param eventId Event Id
	 * @return  True if member is joining else false
	 */
	@AuraEnabled
	public static Boolean getMemberAttendance(Id eventId) {
		try {
			if (!X7S_Event_RSVP__c.SObjectType.getDescribe().isAccessible()) {
				System.debug('Error: Cannot access X7S_Event_RSVP__c object.');
				return false;
			}

			Id contactId = getContactId();
			List<X7S_Event_RSVP__c> lstEventRSVP;

			if (contactId == null) {
				lstEventRSVP = new List<X7S_Event_RSVP__c>(
					[
						SELECT Id, Name, Event__c, User__c
						FROM X7S_Event_RSVP__c
						WHERE Event__c = :eventId AND User__c = :UserInfo.getUserId()
					]
				);
			} else {
				lstEventRSVP = new List<X7S_Event_RSVP__c>(
					[
						SELECT Id, Name, Event__c, User__c
						FROM X7S_Event_RSVP__c
						WHERE
							Event__c = :eventId
							AND (User__c = :UserInfo.getUserId()
							OR Contact__c = :contactId)
					]
				);
			}
			System.debug('contact id: ' + contactId);
			System.debug('RSVP List: ' + lstEventRSVP.isEmpty());

			return !lstEventRSVP.isEmpty();
		} catch (Exception e) {
			throw new AurahandledException(e.getMessage());
		}
	}

	/**
	 * @description Method to fetch the rsvp reg url and Status.
	 * @param eventId Event Id
	 * @return Event RSVP Object
	 */
	@AuraEnabled
	public static X7S_Event_RSVP__c getRegUrlAndStatus(Id eventId) {
		try {
			if (!X7S_Event_RSVP__c.SObjectType.getDescribe().isAccessible()) {
				System.debug('Error: Cannot access X7S_Event_RSVP__c object.');
				return null;
			}

			Id contactId = getContactId();
			List<X7S_Event_RSVP__c> lstEventRSVP;

			if (contactId == null) {
				lstEventRSVP = new List<X7S_Event_RSVP__c>(
					[
						SELECT Id, Registration_Url__c, Registration_Status__c, Response__c
						FROM X7S_Event_RSVP__c
						WHERE Event__c = :eventId AND User__c = :UserInfo.getUserId()
					]
				);
			} else {
				lstEventRSVP = new List<X7S_Event_RSVP__c>(
					[
						SELECT Id, Registration_Url__c, Registration_Status__c, Response__c
						FROM X7S_Event_RSVP__c
						WHERE
							Event__c = :eventId
							AND (User__c = :UserInfo.getUserId()
							OR Contact__c = :contactId)
					]
				);
			}

			return lstEventRSVP.isEmpty() ? null : lstEventRSVP[0];
		} catch (Exception e) {
			throw new AurahandledException(e.getMessage());
		}
	}

	/**
	 * @description Method to create X7S_Event_RSVP__c records on clicking yes on the RSVP component.
	 * @param rsvpObj Event RSVP Object
	 * @param eventId Event Id
	 * @param response RSVP Response
	 * @return Newly created RSVP Record
	 */
	@AuraEnabled
	public static X7S_Event_RSVP__c createRegistration(
		X7S_Event_RSVP__c rsvpObj,
		Id eventId,
		String response
	) {
		try {
			if (X7S_Event_RSVP__c.SObjectType.getDescribe().isCreateable()) {
				User user = [
					SELECT Id, ContactId
					FROM User
					WHERE Id = :UserInfo.getUserId()
					WITH SECURITY_ENFORCED
					LIMIT 1
				];
				Id contactId;

				if (user.ContactId != null) {
					contactId = user.ContactId;
				}

				if (
					[
						SELECT COUNT()
						FROM X7S_Event_RSVP__c
						WHERE Event__c = :eventId AND User__c = :UserInfo.getUserId()
					] <= 0
				) {
					String firstName = UserInfo.getFirstName();
					rsvpObj.Event__c = eventId;
					rsvpObj.User__c = UserInfo.getUserId();
					rsvpObj.First_Name__c = String.isBlank(firstName)
						? System.Label.x7sEventsNoFirstName
						: firstName;
					rsvpObj.Last_Name__c = UserInfo.getLastName();
					rsvpObj.Email__c = UserInfo.getUserEmail();
					rsvpObj.Contact__c = contactId;
					rsvpObj.Response__c = response;

					// Add Zoom Registrant.
					X7S_Event__c event = [
						SELECT
							Id,
							Name,
							MeetingId__c,
							Meeting_Type__c,
							Registration__c,
							Event_Format__c,
							Host_Email__c
						FROM X7S_Event__c
						WHERE Id = :eventId
						WITH SECURITY_ENFORCED
					];

					x7sEventsIExternalMeeting externalMeeting = x7sEventsExternalMeetingFactory.getExternalMeeting(
						event
					);

					x7sEventsIExternalMeetingResponse externalMeetingResponse = externalMeeting.addRegistrant(
						event,
						rsvpObj
					);

					if (!externalMeetingResponse.isSuccess()) {
						throw new EventsRegistrationException(externalMeetingResponse.getError());
					}

					insert rsvpObj;
				}
			}
			return null;
		} catch (Exception e) {
			throw new AurahandledException(e.getMessage());
		}
	}

	/**
	 * @description Method to Check that user has registered for Event.
	 * @param eventId Event Id
	 * @return If registered then true else false
	 */
	@AuraEnabled
	public static Boolean checkRegistration(Id eventId) {
		try {
			if (!X7S_Event__c.SObjectType.getDescribe().isAccessible()) {
				System.debug('Error: Cannot access Event__c object.');
				return false;
			}

			Id contactId = getContactId();
			Integer rsvpCount;

			if (contactId == null) {
				rsvpCount = [
					SELECT COUNT()
					FROM X7S_Event_RSVP__c
					WHERE
						Event__c = :eventId
						AND User__c = :UserInfo.getUserId()
						AND Event__r.NetworkId__c = :communityId
						AND Registration_Status__c = :x7sEventsExternalMeetingConstants.REGISTRATION_STATUS_APPROVED
				];
			} else {
				rsvpCount = [
					SELECT COUNT()
					FROM X7S_Event_RSVP__c
					WHERE
						Event__c = :eventId
						AND (User__c = :UserInfo.getUserId()
						OR Contact__c = :contactId)
						AND Event__r.NetworkId__c = :communityId
						AND Registration_Status__c = :x7sEventsExternalMeetingConstants.REGISTRATION_STATUS_APPROVED
				];
			}

			return rsvpCount > 0;
		} catch (Exception e) {
			throw new AurahandledException(e.getMessage());
		}
	}

	/*
	 * MethodName	: getAttendeeCount
	 * param			: EventId
	 * Description	: Method to fetch number of Attendees for the event.
	 */
	@AuraEnabled
	public static Decimal getAttendeeCount(Id eventId) {
		X7S_Event__c[] events = [
			SELECT Id, Number_of_Attendees__c
			FROM X7S_Event__c
			WHERE Id = :eventId
			WITH SECURITY_ENFORCED
		];

		return (events.size() > 0) ? events[0].Number_of_Attendees__c : 0;
	}

	/**
	 * @description Method to delete X7S_Event_RSVP__c records on clicking No on RSVP component.
	 * @param EventId  Event Id
	 * @return Event RSVP Object
	 */
	@AuraEnabled
	public static X7S_Event_RSVP__c deleteRegistration(Id EventId) {
		try {
			if (EventId != null && X7S_Event_RSVP__c.SObjectType.getDescribe().isDeletable()) {
				// Cancel a users registration in a external system.
				// Need to load the objects for the process.
				X7S_Event_RSVP__c eventRSVP = [
					SELECT
						Id,
						Registration_Id__c,
						User__c,
						Email__c,
						Registration_Status__c,
						Event_Segment__c,
						Response__c
					FROM X7S_Event_RSVP__c
					WHERE Event__c = :EventId AND User__c = :UserInfo.getUserId()
				];
				X7S_Event__c event = [
					SELECT Id, Name, MeetingId__c, Meeting_Type__c, Registration__c, Event_Format__c
					FROM X7S_Event__c
					WHERE Id = :EventId
					WITH SECURITY_ENFORCED
				];

				// This will set the action to cancel.
				eventRSVP.Registration_Status__c = x7sEventsExternalMeetingConstants.REGISTRATION_STATUS_CANCEL;

				x7sEventsIExternalMeeting externalMeeting = x7sEventsExternalMeetingFactory.getExternalMeeting(
					event
				);

				x7sEventsIExternalMeetingResponse externalMeetingResponse = externalMeeting.updateRegistrant(
					event,
					eventRSVP
				);

				if (!externalMeetingResponse.isSuccess()) {
					System.debug('Error: ' + externalMeetingResponse.getError());

					throw new EventsRegistrationException(externalMeetingResponse.getError());
				}

				delete [
					SELECT Id
					FROM X7S_Event_RSVP__c
					WHERE User__c = :UserInfo.getUserId() AND Event__c = :EventId
					LIMIT 1
				];
			}

			return null;
		} catch (Exception e) {
			throw new AurahandledException(e.getMessage());
		}
	}

	/**
	 * @description Method to all fields related to CMT setting.
	 * @param cmtName  RSVP CMT Setting name
	 * @return x7sEventsRegList
	 */
	@AuraEnabled
	public static x7sEventsRegList getRegFields(String cmtName) {
		List<x7sEventsRegistrationFieldsModal> regRecords = new List<x7sEventsRegistrationFieldsModal>();
		x7sEventsRegList regList = new x7sEventsRegList();

		Boolean allRequired = false;
		if (String.isNotBlank(cmtName)) {
			try {
				X7S_Event_Reg_Setting__mdt regSet = X7S_Event_Reg_Setting__mdt.getInstance(cmtName);
				String fieldSetName = regSet.X7S_Event_Reg_Field_Set__c;
				if (String.isNotBlank(fieldSetName)) {
					X7S_Event_Reg_Field_Set__mdt reqField = X7S_Event_Reg_Field_Set__mdt.getInstance(
						fieldSetName
					);
					allRequired = reqField.All_Fields_Required__c;

					Map<String, X7S_Event_Reg_Field_Set_Assignment__mdt> mapEd = X7S_Event_Reg_Field_Set_Assignment__mdt.getAll();

					for (String rec : mapEd.keySet()) {
						if (mapEd.get(rec).X7S_Event_Field_Set_Name__c == fieldSetName) {
							String fieldName = mapEd.get(rec).X7S_Event_Field_Name__c;
							if (String.isNotBlank(fieldName)) {
								X7S_Event_Reg_Field__mdt mc = X7S_Event_Reg_Field__mdt.getInstance(fieldName);
								List<String> picklistValues = new List<String>();
								String apiName = mc.Field_API_Name__c;
								String fieldType = mc.Type__c;
								String fieldToolTip = mc.Tooltip_Text__c;
								Boolean fieldRequired = false;
								String label = '';

								if (mc.Type__c == 'Picklist') {
									picklistValues = getPicklistValues(mc.Field_API_Name__c);
								}

								if (String.isNotBlank(mc.Field_API_Name__c)) {
									if (isFieldRequired(mc.Field_API_Name__c)) {
										fieldRequired = true;
									} else if (allRequired == true) {
										fieldRequired = true;
									} else {
										fieldRequired = mapEd.get(rec).Required__c;
									}
								}

								if (String.isNotBlank(mapEd.get(rec).Field_Label_Override__c)) {
									label = mapEd.get(rec).Field_Label_Override__c;
								} else {
									label = getFieldLabel(mc.Field_API_Name__c, mc.Field_Label__c);
								}
								regRecords.add(
									new x7sEventsRegistrationFieldsModal(
										apiName,
										label,
										fieldType,
										fieldToolTip,
										fieldRequired,
										picklistValues
									)
								);
								regList.listItem = regRecords;
							}
						}
					}
				}
				return regList;
			} catch (Exception ex) {
				System.debug('Error Message:' + ex.getMessage() + ', Error Line:' + ex.getLineNumber());
				throw new AurahandledException(ex.getMessage());
			}
		}
		return null;
	}

	private static String getFieldLabel(String fieldAPIName, String fieldLabel) {
		List<Schema.DescribeSObjectResult> describeSobjectsResult = Schema.describeSObjects(
			new List<String>{ 'X7S_Event_RSVP__c' }
		); // this can accept list of strings, we describe only one object here
		Map<String, Schema.SObjectField> allFields = describeSobjectsResult[0].fields.getMap();

		String fLabel = '';
		try {
			if (String.isBlank(fieldLabel)) {
				fLabel = allFields.get(fieldAPIName).getDescribe().getLabel();
			} else {
				fLabel = String.escapeSingleQuotes(fieldLabel);
			}
		} catch (Exception ex) {
			System.debug('Invalid Field - ' + fieldAPIName + '- Error :' + ex.getMessage());
		}
		return fLabel;
	}

	private static List<String> getPicklistValues(String Field_name) {
		String ObjectApi_name = 'X7S_Event_RSVP__c';
		List<String> lstPickvals = new List<String>();
		Schema.SObjectType targetType = Schema.getGlobalDescribe().get(ObjectApi_name);
		SObject Object_name = targetType.newSObject();
		Schema.SObjectType sobject_type = Object_name.getSObjectType();
		Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
		Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
		List<Schema.PicklistEntry> pick_list_values = field_map.get(Field_name)
			.getDescribe()
			.getPicklistValues();
		for (Schema.PicklistEntry a : pick_list_values) {
			lstPickvals.add(a.getValue());
		}
		return lstPickvals;
	}

	private static Boolean isFieldRequired(String fieldAPIName) {
		Boolean isRequired = false;
		try {
			Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
			Schema.DescribeSObjectResult r = gd.get('X7S_Event_RSVP__c').getDescribe();
			Map<String, Schema.SObjectField> FsMap = r.fields.getMap();
			if (FsMap.containsKey(fieldAPIName)) {
				Schema.DescribeFieldResult fieldDetails = FsMap.get(fieldAPIName).getDescribe();
				if (!fieldDetails.isNillable()) {
					isRequired = true;
				}
			}
		} catch (Exception ex) {
			System.debug('Invalid Field - ' + fieldAPIName + '- Error :' + ex.getMessage());
		}
		return isRequired;
	}
	@AuraEnabled
	public static Integer getExperienceCount(String EventId, String segment) {
		Integer totalCount = 0;
		try {
			if (String.isNotBlank(EventId) && String.isNotBlank(segment)) {
				List<AggregateResult> segments = [
					SELECT count(Event_Segment__c) total
					FROM X7S_Event_RSVP__c
					WHERE
						Event__c = :EventId
						AND Event_Segment__r.Segment__c = :segment
						AND Response__c = :x7sEventsRegistrationController.RSVP_RESPONSE_YES
						AND Response__c != :x7sEventsRegistrationController.RSVP_RESPONSE_WAIT_LIST
						AND Registration_Status__c != :x7sEventsRegistrationController.RSVP_REGISTRATION_STATUS_PENDING
						AND Registration_Status__c != :x7sEventsRegistrationController.RSVP_REGISTRATION_STATUS_DENIED
					WITH SECURITY_ENFORCED
				];
				if (!segments.isEmpty()) {
					totalCount = (Integer) segments[0].get('total');
					System.debug('---totalCount---' + totalCount);
					if (totalCount > 0) {
						return totalCount;
					} else {
						return 0;
					}
				}
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return totalCount;
	}
}