objects/X7S_Event__c/X7S_Event__c.object-meta.xml
<CustomObject>
    <description>Object to support Events records as part of the Events accelerator from 7Summits.</description>
    <label>7S Event</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>7S Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X7S_Shr_Custom_Field_Set__mdt/X7S_Shr_Custom_Field_Set__mdt.object-meta.xml
<CustomObject>
    <description>Custom field set</description>
    <label>7S Shr Custom Field Set</label>
    <pluralLabel>7S Shr Custom Field Sets</pluralLabel>
</CustomObject>

objects/X7S_Shr_Custom_Field_Set__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Uncheck to make field set inactive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/X7S_Shr_Custom_Field_Set__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <inlineHelpText>Target object API name</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

classes/x7sEventsCMTPicklist.cls
/*
 * Licensed Materials - Property of IBM
 * 6949-82P
 * © Copyright IBM Corp. 2022 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

/**
 * @description : class for making dynamic picklist for builder property
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global with sharing class x7sEventsCMTPicklist extends VisualEditor.DynamicPickList {
	public static final String EVENT_OBJECT = 'X7S_Event__c';
	private static final String NONE = 'None';
	private static final String DEFAULT_FIELDSET = '7S Event Setting - Default Field Set';

	global override VisualEditor.DataRow getDefaultValue() {
		// set the default value of the picklist
		return new VisualEditor.DataRow(NONE, NONE);
	}

	global override VisualEditor.DynamicPickListRows getValues() {
		// create picklist
		VisualEditor.DynamicPickListRows myValues = new VisualEditor.DynamicPickListRows();

		// add the default picklist value
		VisualEditor.DataRow defaultSetting = new VisualEditor.DataRow(NONE, NONE);
		VisualEditor.DataRow cmtSetting = new VisualEditor.DataRow(DEFAULT_FIELDSET, 'Default');
		myValues.addRow(defaultSetting);
		myValues.addRow(cmtSetting);

		List<X7S_Shr_Custom_Field_Set__mdt> settingsName = X7S_Shr_Custom_Field_Set__mdt.getAll()
			.values();

		// populate picklist
		myValues = populatePickListWithSettings(settingsName, myValues);
		return myValues;
	}

	private static VisualEditor.DynamicPickListRows populatePickListWithSettings(
		List<X7S_Shr_Custom_Field_Set__mdt> settingsName,
		VisualEditor.DynamicPickListRows pickList
	) {
		// iterate all the topics
		for (X7S_Shr_Custom_Field_Set__mdt setting : settingsName) {
			// create data row row and add it to picklist
			if (setting.Active__c == true && setting.Object_API_Name__c == EVENT_OBJECT) {
				VisualEditor.DataRow row = new VisualEditor.DataRow(setting.Label, setting.DeveloperName);
				pickList.addRow(row);
			}
		}
		return pickList;
	}
}