objects/AI_Credit_Tier__c/AI_Credit_Tier__c.object-meta.xml
<CustomObject>
    <label>AI Credit Tier</label>
    <nameField>
        <label>AI Credit Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AI Credit Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AI_Credit_Tier__c/fields/Lower_Band__c.field-meta.xml
<CustomField>
    <fullName>Lower_Band__c</fullName>
    <description>Total Customer Software Spend</description>
    <label>Lower Band</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Marginal_Rate_Percent__c.field-meta.xml
<CustomField>
    <fullName>Marginal_Rate_Percent__c</fullName>
    <label>Marginal Rate Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Tanium_Cost_Per_Credit__c.field-meta.xml
<CustomField>
    <fullName>Tanium_Cost_Per_Credit__c</fullName>
    <label>Tanium Cost Per Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/AI_Credit_Tier__c/fields/Upper_Band__c.field-meta.xml
<CustomField>
    <fullName>Upper_Band__c</fullName>
    <description>Total Customer Software Spend</description>
    <label>Upper Band</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product2/fields/Deployment_Method__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Method__c</fullName>
    <label>Deployment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On-Prem</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Tanium Cloud for US Government</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Include_In_Annualized_Software_Spend__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Annualized_Software_Spend__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Products eligible for in the Annualized Software Spend count.</description>
    <inlineHelpText>Products eligible for in the Annualized Software Spend count.</inlineHelpText>
    <label>Include In Annualized Software Spend</label>
    <type>Checkbox</type>
</CustomField>

objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Twin Field.  Value pushed to quote line field &apos;Product Grouping&apos;</description>
    <label>Partner Discount Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Group</valueSetName>
    </valueSet>
</CustomField>

objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Initial Content</fullName>
            </value>
            <value>
                <fullName>Module Feature</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>SaaS</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>TaaS</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Term</fullName>
            </value>
            <value>
                <fullName>Feature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Quantity_of_Credits__c.field-meta.xml
<CustomField>
    <fullName>Quantity_of_Credits__c</fullName>
    <description>The number of credits sent to Licensing, since this product does not use a standard quantity.</description>
    <inlineHelpText>The number of credits sent to Licensing, since this product does not use a standard quantity.</inlineHelpText>
    <label>Quantity of Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Product2/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
    <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product_Type__c/Product_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Product Types</label>
</CustomObject>

objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c/fields/Deployment_Method__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Method__c</fullName>
    <label>Deployment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OnPrem</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Tanium Cloud for US Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Payment Terms for this Quote. If available, the Partner/Account Payment Terms will automatically populate. Otherwise, this will default to Net 30.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 40</fullName>
            </value>
            <value>
                <fullName>Net 42</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 50</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 70</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 85</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 105</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
            <value>
                <fullName>Net 130</fullName>
            </value>
            <value>
                <fullName>Cash with Order (CWO)</fullName>
            </value>
            <value>
                <fullName>See Additional Terms</fullName>
            </value>
            <value>
                <fullName>See Applicable Marketplace Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Check as Primary if opportunity NACV should be calculated off of this quote (each opportunity has one primary quote and it should reflect the most likely scenario).</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c/fields/Annualized_Software_Spend__c.field-meta.xml
<CustomField>
    <fullName>Annualized_Software_Spend__c</fullName>
    <formula>ARR_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annualized Software Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Deployment_Method__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Method__c</fullName>
    <description>Twin Field from Product. SS-8909.</description>
    <label>Deployment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On-Prem</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Include_In_Annualized_Software_Spend__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Annualized_Software_Spend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include In Annualized Software Spend</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Used in Price Rule.  Twin Field from Product.</description>
    <label>Partner Discount Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Group</valueSetName>
    </valueSet>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>SaaS</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>TaaS</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
    <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
    <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

classes/AccountSetSwSpendAndAiCreditsBatchTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for AccountSetSwSpendAndAiCreditsBatch
 * @Date: 2026-07-27
 * @Author: Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-13641   2026-07-27    Created AccountSetSwSpendAndAiCreditsBatchTest class
 * SS-13815   2026-08-09    Updated method tesclass to include Booked_ARR_Exit__c field
 * SS-13834   2026-08-24    Added Monthly Paid AI Credits tests
 */
@IsTest
private class AccountSetSwSpendAndAiCreditsBatchTest {
    @TestSetup
    static void makeData() {
        SBQQ.TriggerControl.disable();
        TriggerHandler.bypass(
            new List<String>{
                'AccountTriggerHandler',
                'OpportunityTriggerHandler',
                'QuoteCPQTriggerHandler',
                'QuoteLineTriggerHandler',
                'SubscriptionTriggerHandler',
                'UserTriggerHandler'
            }
        );

        System.runAs(TestUserFactory.getAdminUser()) {
            Account account = new Account(Name = 'Test Account');
            insert account;

            Opportunity opp = TestFactory.buildOpportunity(
                'Test Opp',
                Date.today(),
                Utility.PROSPECTING,
                account.Id
            );
            insert opp;

			List<Product2> products = new List<Product2>();
			products.add(
				new Product2(
					Name = 'Core Product',
					ProductCode = 'Core',
					IsActive = true,
					Product_Type__c = 'SaaS',
					Product_Group__c = 'Software',
					Include_In_Annualized_Software_Spend__c = true,
					Deployment_Method__c = 'Cloud',
					Family = 'None'
				)
			);
			products.add(
				new Product2(
					Name = 'Discover Product',
					ProductCode = 'Discover',
					IsActive = true,
					Product_Type__c = 'SaaS',
					Product_Group__c = 'Software',
					Include_In_Annualized_Software_Spend__c = false,
					Deployment_Method__c = 'Cloud',
					Family = 'None'
				)
			);
			insert products;

            List<AI_Credit_Tier__c> aiCreditTiers = new List<AI_Credit_Tier__c>();
            AI_Credit_Tier__c tier1 = new AI_Credit_Tier__c(
                Name = 'Tier 1',
                Lower_Band__c = 0,
                Upper_Band__c = 10000,
                Marginal_Rate_Percent__c = 5,
                Tanium_Cost_Per_Credit__c = 0.05
            );
            aiCreditTiers.add(tier1);

            AI_Credit_Tier__c tier2 = new AI_Credit_Tier__c(
                Name = 'Tier 2',
                Lower_Band__c = 10001,
                Upper_Band__c = 50000,
                Marginal_Rate_Percent__c = 3,
                Tanium_Cost_Per_Credit__c = 0.05
            );
            aiCreditTiers.add(tier2);

            AI_Credit_Tier__c tier3 = new AI_Credit_Tier__c(
                Name = 'Tier 3',
                Lower_Band__c = 50001,
                Upper_Band__c = 10000000,
                Marginal_Rate_Percent__c = 1,
                Tanium_Cost_Per_Credit__c = 0.05
            );
            aiCreditTiers.add(tier3);
            insert aiCreditTiers;

            SBQQ__Quote__c quote = new SBQQ__Quote__c(
                SBQQ__Opportunity2__c = opp.Id,
                SBQQ__Account__c = account.Id,
                SBQQ__Type__c = 'Quote',
                SBQQ__Primary__c = true,
                SBQQ__PaymentTerms__c = 'Net 30',
                Deployment_Method__c = 'Cloud'
            );
            insert quote;

            opp.SBQQ__PrimaryQuote__c = quote.Id;
            update opp;

            account.Latest_Closed_Cloud_or_OnPrem_Opp__c = opp.Id;
            update account;

            List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
            for (Product2 product : products) {
                quoteLines.add(
                    new SBQQ__QuoteLine__c(
                        SBQQ__Product__c = product.Id,
                        SBQQ__Quantity__c = 1000,
                        SBQQ__Quote__c = quote.Id,
                        SBQQ__StartDate__c = Date.today(),
                        SBQQ__EndDate__c = Date.today().addMonths(12),
                        SBQQ__SubscriptionPricing__c = null,
                        SBQQ__NetPrice__c = 1000
                    )
                );
            }
            insert quoteLines;

			List<SBQQ__Subscription__c> subscriptions = new List<SBQQ__Subscription__c>();
			for (Integer i = 0; i < quoteLines.size(); i++) {
				subscriptions.add(
					TestFactory.buildSubscription(
						account.Id,
						quoteLines[i].SBQQ__Product__c,
						1000,
						quoteLines[i].Id
					)
				);
				subscriptions[i].Include_In_Annualized_Software_Spend__c = i == 0 ? true : false;
				subscriptions[i].SBQQ__ProrateMultiplier__c = 1.0;
				subscriptions[i].SBQQ__NetPrice__c = 1000;
				subscriptions[i].Customer_Annualized_Software_Spend__c = 10000;
			}
			insert subscriptions;

			List<Product2> paidAICreditProducts = new List<Product2>();
			paidAICreditProducts.add(
				TestFactory.buildProduct('AI Credits Tanium Cloud', 'TANIUM-AI-CREDITS-CLOUD')
			);
			paidAICreditProducts.add(
				TestFactory.buildProduct(
					'AI Credits Tanium Cloud for US Government',
					'TANIUM-AI-CREDITS-CLOUDGOV-US'
				)
			);
			for (Product2 paidAICreditProduct : paidAICreditProducts) {
				paidAICreditProduct.Product_Type__c = 'SaaS';
				paidAICreditProduct.Product_Group__c = 'Software';
				paidAICreditProduct.Include_In_Annualized_Software_Spend__c = false;
				paidAICreditProduct.Deployment_Method__c = 'Cloud';
				paidAICreditProduct.Quantity_of_Credits__c = 10000;
			}
			insert paidAICreditProducts;

			List<SBQQ__QuoteLine__c> paidAICreditQuoteLines = new List<SBQQ__QuoteLine__c>();
			paidAICreditQuoteLines.add(
				new SBQQ__QuoteLine__c(
					SBQQ__Product__c = paidAICreditProducts[0].Id,
					SBQQ__Quantity__c = 1,
					SBQQ__Quote__c = quote.Id,
					SBQQ__StartDate__c = Date.today(),
					SBQQ__EndDate__c = Date.today().addMonths(12),
					SBQQ__SubscriptionPricing__c = null,
					SBQQ__NetPrice__c = 1000
				)
			);
			paidAICreditQuoteLines.add(
				new SBQQ__QuoteLine__c(
					SBQQ__Product__c = paidAICreditProducts[1].Id,
					SBQQ__Quantity__c = 3,
					SBQQ__Quote__c = quote.Id,
					SBQQ__StartDate__c = Date.today().addMonths(-13),
					SBQQ__EndDate__c = Date.today().addDays(-1),
					SBQQ__SubscriptionPricing__c = null,
					SBQQ__NetPrice__c = 1000
				)
			);
			insert paidAICreditQuoteLines;

			List<SBQQ__Subscription__c> paidAICreditSubscriptions = new List<SBQQ__Subscription__c>();
			paidAICreditSubscriptions.add(
				TestFactory.buildSubscription(
					account.Id,
					paidAICreditProducts[0].Id,
					1,
					paidAICreditQuoteLines[0].Id
				)
			);
			paidAICreditSubscriptions.add(
				TestFactory.buildSubscription(
					account.Id,
					paidAICreditProducts[1].Id,
					3,
					paidAICreditQuoteLines[1].Id
				)
			);
			for (SBQQ__Subscription__c paidAICreditSubscription : paidAICreditSubscriptions) {
				paidAICreditSubscription.Include_In_Annualized_Software_Spend__c = false;
			}
			paidAICreditSubscriptions[1].SBQQ__SubscriptionStartDate__c = Date.today().addMonths(-13);
			paidAICreditSubscriptions[1].SBQQ__SubscriptionEndDate__c = Date.today().addDays(-1);
			insert paidAICreditSubscriptions;
		}
	}

    @IsTest
    static void testBatchExecute_WhenNoAccountIds_ReturnJobId() {
        Id jobId = null;
        System.runAs(TestUserFactory.getAdminUser()) {
            Test.startTest();
            AccountSetSwSpendAndAiCreditsBatch batch = new AccountSetSwSpendAndAiCreditsBatch();
            jobId = Database.executeBatch(batch, 2);
            Test.stopTest();
        }

        Assert.isFalse(jobId == null);
    }

	@IsTest
	static void testBatchExecute_WhenAccountIds_ReturnJobId() {
		Map<Id, Account> accountMap = new Map<Id, Account>(
			[SELECT Id, Annualized_Software_Spend__c, Booked_ARR_Exit__c FROM Account]
		);
		Id jobId = null;
		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			AccountSetSwSpendAndAiCreditsBatch batch = new AccountSetSwSpendAndAiCreditsBatch(
				accountMap.keySet()
			);
			jobId = Database.executeBatch(batch, 2);
			Test.stopTest();
		}

        Assert.isFalse(jobId == null);
    }

	@IsTest
	static void testExecute_WhenEligibleSubscriptions_SetAnnualizedSoftwareSpendAndAICredits() {
		Map<Id, Account> accountMap = new Map<Id, Account>(
			[SELECT Id, Annualized_Software_Spend__c, Booked_ARR_Exit__c, Monthly_Paid_AI_Credits__c FROM Account]
		);

        System.runAs(TestUserFactory.getAdminUser()) {
            Test.startTest();
            AccountSetSwSpendAndAiCreditsBatch batch = new AccountSetSwSpendAndAiCreditsBatch(
                accountMap.keySet()
            );
            batch.execute(null, accountMap.values());
            Test.stopTest();
        }

        List<Account> accounts = [
            SELECT Id
            FROM Account
            WHERE
                Id IN :accountMap.keySet()
                AND Annualized_Software_Spend__c > 0
                AND Monthly_FOC_AI_Credits__c > 0
        ];

		Assert.isFalse(
			accounts.isEmpty(),
			'There should be at least one account with Annualized Software Spend greater than 0 and Monthly FOC AI Credits greater than 0'
		);
	}

	@IsTest
	static void testExecute_WhenActiveAndExpiredAICreditsSubscriptions_SetsMonthlyPaidAICreditsFromActiveOnly() {
		Account account = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
		Map<Id, Account> accountMap = new Map<Id, Account>(
			[
				SELECT Id, Annualized_Software_Spend__c, Monthly_Paid_AI_Credits__c, Booked_ARR_Exit__c
				FROM Account
				WHERE Id = :account.Id
			]
		);

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			AccountSetSwSpendAndAiCreditsBatch batch = new AccountSetSwSpendAndAiCreditsBatch(
				accountMap.keySet()
			);
			batch.execute(null, accountMap.values());
			Test.stopTest();
		}

		Account updatedAccount = [
			SELECT Monthly_Paid_AI_Credits__c
			FROM Account
			WHERE Id = :account.Id
		];

		Assert.areEqual(
			10000,
			updatedAccount.Monthly_Paid_AI_Credits__c,
			'Active qty-1 sub counts, expired qty-3 sub excluded => 10000'
		);
	}

	@IsTest
	static void testBatchExecute_WhenScheduledPath_RecalculatesAccountWithNonSpendFlaggedAICreditsSubscription() {
		Account account = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];

		System.runAs(TestUserFactory.getAdminUser()) {
			Test.startTest();
			Database.executeBatch(new AccountSetSwSpendAndAiCreditsBatch(), 2);
			Test.stopTest();
		}

		Account updatedAccount = [
			SELECT Monthly_Paid_AI_Credits__c
			FROM Account
			WHERE Id = :account.Id
		];

		Assert.areEqual(
			10000,
			updatedAccount.Monthly_Paid_AI_Credits__c,
			'Scheduled path surfaces the account via the new AI Credits query conditions and computes 10000'
		);
	}
}