objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Customer Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c/fields/Case_1_Recommend__c.field-meta.xml
<CustomField>
    <fullName>Case_1_Recommend__c</fullName>
    <label>Transactional NPS Factor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Survey__c/fields/Case_2_Overall_Support__c.field-meta.xml
<CustomField>
    <fullName>Case_2_Overall_Support__c</fullName>
    <label>Overall Satisfaction Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extremely satisfied</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat satisfied</fullName>
            </value>
            <value>
                <fullName>Not so satisfied</fullName>
            </value>
            <value>
                <fullName>Not at all satisfied</fullName>
            </value>
            <value>
                <fullName>非常に満足</fullName>
            </value>
            <value>
                <fullName>やや満足</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
            <value>
                <fullName>やや不満</fullName>
            </value>
            <value>
                <fullName>非常に不満</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_3_Speed_of_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Case_3_Speed_of_Resolution__c</fullName>
    <label>Speed of Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extremely satisfied</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat satisfied</fullName>
            </value>
            <value>
                <fullName>Not so satisfied</fullName>
            </value>
            <value>
                <fullName>Not at all satisfied</fullName>
            </value>
            <value>
                <fullName>非常に満足</fullName>
            </value>
            <value>
                <fullName>やや満足</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
            <value>
                <fullName>やや不満</fullName>
            </value>
            <value>
                <fullName>非常に不満</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_4_Technical_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Case_4_Technical_Knowledge__c</fullName>
    <label>Technical Knowledge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extremely satisfied</fullName>
            </value>
            <value>
                <fullName>Very satisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat satisfied</fullName>
            </value>
            <value>
                <fullName>Not so satisfied</fullName>
            </value>
            <value>
                <fullName>Not at all satisfied</fullName>
            </value>
            <value>
                <fullName>非常に満足</fullName>
            </value>
            <value>
                <fullName>やや満足</fullName>
            </value>
            <value>
                <fullName>普通</fullName>
            </value>
            <value>
                <fullName>やや不満</fullName>
            </value>
            <value>
                <fullName>非常に不満</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_5_Issue_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Case_5_Issue_Resolved__c</fullName>
    <label>Issue Resolved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>はい</fullName>
            </value>
            <value>
                <fullName>いいえ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Survey__c/fields/Case_6_Comment__c.field-meta.xml
<CustomField>
    <fullName>Case_6_Comment__c</fullName>
    <label>CSAT Survey Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Survey__c/fields/SurveyCreateDate__c.field-meta.xml
<CustomField>
    <fullName>SurveyCreateDate__c</fullName>
    <label>Submission Date</label>
    <type>DateTime</type>
</CustomField>

classes/SurveyTriggerHandlerTest.cls
/**
 * Copyright (c) 2026 Tanium
 *
 * @Business: Test class for SurveyTriggerHandler
 * @Date: 2026-04-27
 * @Author: Tanium Dev Team
 * RequestId  ModifiedDate  Description
 * SS-13032   2026-04-27    Modified test class
 **/
@IsTest
private class SurveyTriggerHandlerTest {
	@IsTest
	static void caseSurveyTestOneSurvey() {
		TriggerHandler.bypass(
			new List<String>{ 'AccountTriggerHandler', 'ContactTriggerHandler', 'CaseTriggerHandler' }
		);
		System.runAs(TestUserFactory.getAdminUser()) {
			Account account = TestFactory.buildAccount('Account for survey');
			insert account;

			Contact contact = new Contact(
				Email = 'survey@tanium.com',
				FirstName = 'Test',
				LastName = 'Contact',
				AccountId = account.Id
			);

			Case cs = new Case(
				ContactId = contact.Id,
				Accountid = account.Id,
				Subject = 'ROSCOTESTCASE',
				Severity_Community__c = '3',
				Type = 'Incident',
				Reason = 'New problem',
				Origin = 'Email',
				SuppliedEmail = '99@outlook.com',
				Status = 'On Hold',
				Description = 'Case Description',
				RecordTypeId = Utility.getRecordTypeIdByAPIName('Case', 'Support')
			);
			insert cs;

			Survey__c survey = new Survey__c();
			survey.Name = 'Support Center CSAT';
			survey.Case__c = cs.Id;
			survey.SurveyCreateDate__c = Datetime.now();
			survey.Case_1_Recommend__c = '10';
			survey.Case_2_Overall_Support__c = 'Not so satisfied';
			survey.Case_3_Speed_of_Resolution__c = 'Not so satisfied';
			survey.Case_4_Technical_Knowledge__c = 'Not so satisfied';
			survey.Case_5_Issue_Resolved__c = 'No';
			survey.Case_6_Comment__c = 'comment 123';
			insert survey;
		}
	}
}