objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c/fields/Deal_Desk_Approver__c.field-meta.xml
<CustomField>
    <fullName>Deal_Desk_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>used for approval process and populated by trigger</description>
    <label>Deal Desk Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SBQQ__Quote__c/fields/PaymentTypeNew__c.field-meta.xml
<CustomField>
    <fullName>PaymentTypeNew__c</fullName>
    <defaultValue>&quot;Upfront&quot;</defaultValue>
    <description>Payment Type used to bill the customer</description>
    <inlineHelpText>Payment Type used to bill the customer</inlineHelpText>
    <label>Billing Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentType</valueSetName>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Check as Primary if opportunity NACV should be calculated off of this quote (each opportunity has one primary quote and it should reflect the most likely scenario).</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__StartDate__c</fullName>
    <description>Start date for subscriptions in this quote.</description>
    <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CEO/Finance Approval</fullName>
            </value>
            <value>
                <fullName>COE Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Approval</fullName>
            </value>
            <value>
                <fullName>Deal Desk Lead Approval</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>RVP Approval</fullName>
            </value>
            <value>
                <fullName>Upper Management Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Length of the deal, in whole months</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SubmitForApprovalForFlowTest.cls
/*
 * @BUSINESS: SubmitForApprovalForFlow class
 * @DATE: 2024-07-12
 * @AUTHOR: Tanium Dev Team
 * @REQUEST:
 * RequestId  	ModifiedDate  Comment
 * SS-8407    	2024-07-12    Submit for advanced approval called from flow - "Quote - Required for Approval"
 * SS-9651    	2024-11-12    Class enhancements
 */
@IsTest
private class SubmitForApprovalForFlowTest {
	@TestSetup
	static void makeData() {
		SBQQ.TriggerControl.disable();
		TriggerHandler.bypass(
			new List<String>{
				'AccountTriggerHandler',
				'BillingByQuoteLineTriggerHandler',
				'OpportunityTriggerHandler',
				'OpportunityLineItemTriggerHandler',
				'QuoteCPQTriggerHandler',
				'QuoteLineTriggerHandler'
			}
		);
		System.runAs(getAdvanceApprovalUser()) {
			Account acct = TestFactory.buildAccount('Test Account');
			acct.type = 'Analyst';
			acct.Country_Restrictions__c = 'Business Allowed';
			insert acct;
			Opportunity oppty = TestFactory.buildOpportunity(
				'Test Opportunity',
				Date.today() + 30,
				'Prospecting',
				acct.Id
			);
			oppty.CloseDate = Date.today() + 60;
			//oppty.Deal_Desk_Approver__c = getDealsDeskUser().Id;
			insert oppty;

			SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
				PaymentTypeNew__c = 'Annual Installment',
				SBQQ__StartDate__c = Date.today(),
				SBQQ__EndDate__c = Date.today().addDays(30),
				SBQQ__Opportunity2__c = oppty.Id,
				SBQQ__PriceBook__c = Test.getStandardPricebookId(),
				SBQQ__Account__c = acct.Id,
				SBQQ__Status__c = 'Accepted',
				SBQQ__Type__c = 'Quote',
				SBQQ__SubscriptionTerm__c = 30,
				SBQQ__Primary__c = true
			);
			insert testQuote;
		}
	}

	@IsTest
	static void testSubmit_whenSuccess_returnsSUCCESS() {
		List<SubmitForApprovalForFlow.RequestDataFromFlow> requests = new List<SubmitForApprovalForFlow.RequestDataFromFlow>();
		SubmitForApprovalForFlow.RequestDataFromFlow request = new SubmitForApprovalForFlow.RequestDataFromFlow();
		request.recordId = [SELECT Id FROM SBQQ__Quote__c LIMIT 1].Id;
		requests.add(request);
		List<SubmitForApprovalForFlow.SendDataToFlow> results = new List<SubmitForApprovalForFlow.SendDataToFlow>();
		System.runAs(getAdvanceApprovalUser()) {
			Test.startTest();
			try {
				results = SubmitForApprovalForFlow.submit(requests);
			} catch (Exception e) {
			}
			Test.stopTest();
		}
		System.assertEquals(results[0].msgToUser, 'SUCCESS', 'valid record Id');
	}

	@IsTest
	static void testSubmit_whenException_returnsException() {
		List<SubmitForApprovalForFlow.RequestDataFromFlow> requests = new List<SubmitForApprovalForFlow.RequestDataFromFlow>();
		SubmitForApprovalForFlow.RequestDataFromFlow request = new SubmitForApprovalForFlow.RequestDataFromFlow();
		request.recordId = null;
		requests.add(request);
		List<SubmitForApprovalForFlow.SendDataToFlow> results = new List<SubmitForApprovalForFlow.SendDataToFlow>();

		System.runAs(getAdvanceApprovalUser()) {
			Test.startTest();
			try {
				results = SubmitForApprovalForFlow.submit(requests);
			} catch (Exception e) {
			}
			Test.stopTest();
		}
		System.assertNotEquals(results[0].msgToUser, 'SUCCESS', 'invalid record Id');
		System.assertEquals(
			true,
			[SELECT Id FROM LogEntry__c].size() > 0,
			'exception logged in Nebula'
		);
		for (LogEntry__c eachLogEntry : [SELECT Message__c FROM LogEntry__c]) {
			System.assertEquals(
				true,
				eachLogEntry.Message__c.contains('SubmitForApprovalForFlow.submit'),
				'exception logged in Nebula'
			);
		}
	}

	static User getAdvanceApprovalUser() {
		List<User> testUsers = [
			SELECT Id
			FROM User
			WHERE LastName = :TestUserFactory.ADVANCED_APPROVALS_USER
		];
		if (testUsers.isEmpty()) {
			User advanceApprovalUser = TestUserFactory.createAdvancedApprovalsUser();
			assignAdminPermissions(advanceApprovalUser.Id);
			return advanceApprovalUser;
		} else {
			return testUsers[0];
		}
	}

	static void assignAdminPermissions(Id userId) {
		TestingUtility.assignPermissionSet(userId, 'DisableFlows');
		TestingUtility.assignPermissionSet(userId, 'DisableValidationRules');
	}
}